### ISSUE TITLE
Windows container Supporting multi AD's

### ISSUE THREAD

**Issue by gkaleta** [microsoft/Windows-Containers#100]
Support one container accessing multi AD's.

**Comment by vrapolinario** [comment]
Hi @gkaleta can you please provide more details on this?
I'm curious on what is the scenario on which the same container instance needs to access different AD domains.

**Comment by gkaleta** [comment]
> Hi @gkaleta can you please provide more details on this?
> I'm curious on what is the scenario on which the same container instance needs to access different AD domains.

A large finance app needs to auth against various AD's in order to provide customer(s) data. It's being discussed offline internally with PG.

**Comment by vrapolinario** [comment]
Thanks for the update.
Just wondering what is the architecture of the app outside containers (if that's the case). A VM would be domain-joined to a domain and would query other domains that are accessible?

**Comment by mapalko** [comment]
Supporting multiple ADs from one container is not going to be supported.
