### ISSUE TITLE
Windows image with ContainerD for public clouds

### ISSUE THREAD

**Issue by aravindhp** [microsoft/Windows-Containers#101]
In public clouds like AWS and Azure, there are Windows Server images with container support that come with Docker installed and configured. As a consumer of such images, I would like to see similar images published to AWS, Azure etc, with ContainerD installed and configured to reduce the burden on the end user.

**Comment by weijuans-msft** [comment]
@aravindhp Can you can explain how you plan to use containerd with Windows Server container images on Azure and AWS? What kind of burden? Any example? What Azure services are you using? What images are you using? I am curious.

**Comment by aravindhp** [comment]
>Can you can explain how you plan to use containerd with Windows Server container images on Azure and AWS? 

In OpenShift, we use an [operator](https://github.com/openshift/windows-machine-config-operator) to prepare a Windows VM to join a k8s cluster as a worker node. A pre-requisite for this for the runtime to be pre-installed and configured on the VM. We have been using `datacenter-core-20h2-with-containers-smalldisk` and other `*-with-containers` images and was hoping to get similar images for ContainerD. We don't want to place the burden on customers to prepare an image with ContainerD.

**Comment by weijuans-msft** [comment]
I am curious: 1) Why can't OpenShift infra or the Cloud infra bring in containerd bits vs. the customers? 2) How are you using containerd on Windows today on OpenShift? Is the E2E scenario working?

**Comment by aravindhp** [comment]
>Why can't OpenShift infra or the Cloud infra bring in containerd bits vs. the customers?

Will MSFT provide it as a supported server add-on? If yes, then we can explore that option.

>How are you using containerd on Windows today on OpenShift?

We have not moved to ContainerD yet. We are still using Docker which is pre-installed on Windows images in AWS and Azure. What we are asking for is the same treatment when it comes to ContainerD.

**Comment by weijuans-msft** [comment]
We don't have the plan now. It made sense to have Docker pre-installed on the Windows Server images on Azure because it was the only container run-time when Windows Server started supporting containers a few years back. The ecosystem has evolved a lot. There are a lot more diversified options. We are not seeing the same value or need to pre-install containerd on Windows Server at this time. That can change, and we'll revise our plan as needed.

Thanks for the feedback. If no more questions, I'll close this.
