### ISSUE TITLE
[Question] Usage of MSVC toolchain within images

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/Windows-Containers#102]
There's currently ongoing work on providing an official Rust Windows image in https://github.com/rust-lang/docker-rust/pull/71. As Rust uses the MSVC toolchain as a default for compiling for Windows (https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/msvc-toolchain-support.html), it needs to be included within the image.

The issue of licensing has now come up. E.g. https://devblogs.microsoft.com/cppblog/using-msvc-in-a-docker-container-for-your-c-projects/ says:
> Remember that the VS Build Tools are licensed as a supplement to your existing Visual Studio license. Any images built with these tools should be for your personal use or for use in your organization in accordance with your existing Visual Studio and Windows licenses. Please don’t share these images on a public Docker hub.

Are there any updates to that? Does that mean we can't provide an official Rust Windows image which would both help the Rust and the Windows Container community or is a reference to the VS Build tools license enough?

We were wondering because the official .NET Framework SDK image is also using the VS Build Tools (https://github.com/microsoft/dotnet-framework-docker/blob/3b2ac5bcda7603b94c0b6399355f3d0c0c1eb512/src/sdk/4.8/windowsservercore-1909/Dockerfile#L21-L30) without explicitly stating that you need a Visual Studio License to be allowed to use the official image.

**Comment by vrapolinario** [comment]
Unfortunately MSVC is outside my area of knowledge so please allow us to investigate internally with the appropriate teams.

**Comment by lippertmarkus** [comment]
@vrapolinario any updates on this?

**Comment by vrapolinario** [comment]
Unfortunately I don't have an update yes. 
I did find the team inside Microsoft that are currently investigating this, but no updates yet.
I'll update here once I hear back.

**Comment by vrapolinario** [comment]
Alright, apologies for the delay. Here's the information I got internally: (Please note this is not owned by the Windows Container team)
_______________________________________
A change in the MSVC licensing is not being actively discussed. Redistribution of the VS Build Tools is not permitted, so we should make sure that while we document how .dockerfile should install VS Build Tools for anyone wanting to create private container images, we cannot publish these images on any public container repos. 
_______________________________________

On note that was raised is that GH Actions agents already have VS Build Tools on them, so if this helps with Rust CI requirements, it might be an alternative.
