### ISSUE TITLE
Cmdkey looses credentials

### ISSUE THREAD

**Issue by sitofabi** [microsoft/Windows-Containers#104]
Hi,

I've been using the windowsservercore image for a long time to setup some build machines/container.
One part I've used during the build of a new image was to setup some username/credentials with 

`cmdkey /add:servername /user:username /pass:password`

During the runtime of the image I could then simply use `net use * \\servername\share` to get access to the share and afterwards copy files to it or publish some reports and so on.

This worked well the last year(s) and a  `cmdkey /list` in a running container showed me the stored credentials.

But suddenly this doesn't work any more.
Whenever I start an image based on the latest version of servercore image  cmdkey doesn't have any credentials and prints 

> Currently stored credentials: * NONE *

This also happens when I start an interactive session with the latest image and add some credentials via cmdkey. As long as I'm inside the running container cmdkey knows the credentials. Also if I restart the container the credentials are available. As soon as I commit the container and start the new image the credentials are gone
```
docker version
Client: Mirantis Container Runtime
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        6ee42dc
 Built:             03/11/2021 13:24:56
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       1e08f21e79
  Built:            03/11/2021 13:23:32
  OS/Arch:          windows/amd64
  Experimental:     true

docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 192
  Running: 0
  Paused: 0
  Stopped: 192
 Images: 549
 Server Version: 20.10.0
 Storage Driver: lcow (linux) windowsfilter (windows)
  LCOW:
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.1817)
 OSType: windows
 Architecture: x86_64
 CPUs: 20
 Total Memory: 127.9GiB
 Name: xyz
 ID: PIUB:T22F:LATN:YO6U:5LEZ:SV3M:H5JM:DQ5N:5F7Y:WPPJ:4RHD:P3M7
 Docker Root Dir: M:\docker.content
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
Regards
  Tobias

**Comment by vrapolinario** [comment]
@mapalko is this something you can help us investigate?

**Comment by mapalko** [comment]
Adding @jirenugo

**Comment by ThatWileyGuy** [comment]
Are you adding credentials as a system account or as a local user?

**Comment by sitofabi** [comment]
I'm using the default user inside the container, i.e. the ContainerAdministrator

**Comment by mapalko** [comment]
@vrapolinario ThatWileyGuy and I confirmed that we don't know or own how the ContainerAdministrator account is created or what might happen to its profile during container commit so we can't comment on why this would be happening.

**Comment by vrapolinario** [comment]
I have identified an internal team that is currently investigating this issue.

**Comment by vrapolinario** [comment]
To keep the thread updated: We're still investigating this issue and will provide an update as soon as possible.

**Comment by ghost** [comment]
This issue has been open for 90 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by cwilhit** [comment]
This is a long-running issue but we're still actively investigating it. MSFT internal 288993594 for reference. Will post back here as/when we have an update.

**Comment by ravisalamani** [comment]
Any update here. Facing same issue.

**Comment by fady-azmy-msft** [comment]
We're still investigating the issue @ravisalamani, but don't have any updates yet.

**Comment by riyapatel-ms** [comment]
@sitofabi the fix should've gone out around June 26, sorry for the delayed response. Let me know if you are still experiencing this, otherwise I will close this issue.
