### ISSUE TITLE
2019 Core servers after March updates have a Docker user and service running

### ISSUE THREAD

**Issue by jonnyabu1** [microsoft/Windows-Containers#105]
I don't think this is the right place for this but was told to raise an issue in this repository.  But, we are running 2019 Core ( maybe you call them something else now, I still call them Core - command line only ) servers as VMs in VSphere.  So not containers.  After the March updates, we started seeing failed login attempts from a user "user manager\containermanager" which I traced to a service called cexecsvc, which from what I saw in research those both relate to Docker Windows containers. 

I just found a little bit ago also a Reddit thread about this too so maybe it's now known:  https://www.reddit.com/r/sysadmin/comments/m34844/cexecsvc_on_servers_after_windows_updates/

In any case, I just wanted to see a) what happened here and b) is this planned to be removed in the next monthly patches?  I presume either someone pushed out the wrong updates to Core servers when they meant to push them out to containers.  Or testing is done in containers and they forgot to remove the container user and service when packaging updates and those got installed.  

So to reiterate, our servers are not Dockers containers yet after the March updates they now have a Docker user and service installed.

**Comment by vrapolinario** [comment]
Apologies for the delay. I should have pointed out that we opened an internal bug to investigate. Will update once I hear from the internal team.

**Comment by vrapolinario** [comment]
This has now been fixed with the update that just came out today as part of Patch Tuesday (6B update).
