### ISSUE TITLE
Container config JSONs for Windows images don't match docker format

### ISSUE THREAD

**Issue by rcowsill** [microsoft/Windows-Containers#107]
The container config JSON files for a number of official Windows images don't match the format produced by docker engine. Configs produced by docker engine include the property name "rootfs", but some Windows images use "rootfS" (uppercase "S") instead.

This difference is visible in the config JSON blobs stored in V2 registries. Those files also get copied into the tar files created by `docker save`. `docker inspect` doesn't show the difference because it normalizes case to that used internally by the docker code.

The following repos are affected:

Repo name               | Example Tag | Example JSON (mediaType: application/vnd.docker.container.image.v1+json)
--------------------- | --------------- | ---------------
windows                   | 20H2-amd64                   | [sha256:ffdd836c716ccd152d599cca923f3136d32434a9fe105d77083e9b9ffa789484](https://mcr.microsoft.com/v2/windows/blobs/sha256:ffdd836c716ccd152d599cca923f3136d32434a9fe105d77083e9b9ffa789484)
windows/iotcore       | 10.0.17763.1757-amd64 | [sha256:7e2fcc47e5f45cd070df82c3bb7c40a978b4e186fc29bb7113599852efae465d](https://mcr.microsoft.com/v2/windows/iotcore/blobs/sha256:7e2fcc47e5f45cd070df82c3bb7c40a978b4e186fc29bb7113599852efae465d)
windows/nanoserver | 20H2-amd64                  | [sha256:10f2e1bb70d21a4fd8b39405d66b314b5eb97ccd03304f981f5bc1582e2d5a0e](https://mcr.microsoft.com/v2/windows/nanoserver/blobs/sha256:10f2e1bb70d21a4fd8b39405d66b314b5eb97ccd03304f981f5bc1582e2d5a0e)
windows/servercore  | 20H2-amd64                  | [sha256:6a657d491a8e5234b2fb1801eb7b5c953b538a6c5eaf75d2b5649bdad33e3b78](https://mcr.microsoft.com/v2/windows/servercore/blobs/sha256:6a657d491a8e5234b2fb1801eb7b5c953b538a6c5eaf75d2b5649bdad33e3b78)

In the above repos there are hundreds of configs using the `rootfS` form, whereas none of the other repos on MCR do so. It may be that the team(s) making these specific images are using their own custom tooling.

These images do work fine in docker engine, as it uses golang's JSON parser which ignores case. Unfortunately, relying on that hinders interoperability with other languages. For example, a tool written in TypeScript would need to emulate golang's JSON parser to handle these configs correctly.

It'd be great if the affected repos could be updated to match the format used by the other images on MCR.

**Comment by weijuans-msft** [comment]
@rcowsill Thanks for reporting. What do you mean by "produced by docker engine"? Can you also elaborate on the use case that this is a problem? You did mention this "Unfortunately, relying on that hinders interoperability with other languages. For example, a tool written in TypeScript would need to emulate golang's JSON parser to handle these configs correctly.". It'll be nice to know how you are using Windows containers, is it a local dev case, in your CI/CD pipeline, or production? Is it on Azure/AKS or other clouds, or on-prem?

**Comment by rcowsill** [comment]
> @rcowsill Thanks for reporting. What do you mean by "produced by docker engine"?

By that I just mean an image made by running the CLI command `docker build .` in a folder containing a Dockerfile on a machine running the docker daemon.

From looking at the docker source it appears that it will always use the name "rootfs" (all lowercase) when writing new config JSON files. The relevant line is here, where the tag for the RootFS field contains the format string `json:"rootfs,omitempty"`:
https://github.com/docker/engine/blob/72fef53cecdd0b151ecaa8301b6d26f5d3182e9f/image/image.go#L69

Based on this I assume that config JSONs using `rootfS` must have either been built with another tool entirely, or been post-processed before they got pushed to the registry.

> Can you also elaborate on the use case that this is a problem?

I'd like to update the GitHub Action [satackey/action-docker-layer-caching](https://github.com/satackey/action-docker-layer-caching) to cache docker layers in [a more efficient way](https://github.com/satackey/action-docker-layer-caching/discussions/97). This change requires parsing the config JSON files, which are present in the archives written by `docker save`. The change worked fine for Linux containers from dockerhub, but failed when tested with an image based on windows/nanoserver from MCR.

**Comment by tianon** [comment]
I'd suggest that https://github.com/opencontainers/image-spec/blob/v1.0.1/config.md#properties is also very highly relevant here, given lowercase `rootfs` is part of the OCI image specification. :smile:

(Coming here from https://github.com/microsoft/containerregistry/issues/59 which has a bit more relevant detail too :innocent:)

**Comment by weijuans-msft** [comment]
Thanks for the input everyone. I have brought to the right SMEs internally and will figure out a way to fix this. Will add an internal tracking # later on as well.

**Comment by weijuans-msft** [comment]
For Microsoft folks, I filed this ADO for tracking 33232648.

**Comment by weijuans-msft** [comment]
Quick update: for Microsoft folks, one ADO is not enough:). There is a bug ADO filed 33660269, and the right SME team is on it, aiming to fix it in upcoming months through the monthly patch release. woohoo~~

**Comment by weijuans-msft** [comment]
With input from the community, we are moving ahead making the fix.
https://twitter.com/WeijuanLand/status/1410267959537270785

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by weijuans-msft** [comment]
This fix was released in July 2nd Tuesday updates (aka '7B'), see more here [https://support.microsoft.com/en-us/topic/kb5005128-windows-server-containers-for-july-2021-51dbbd2a-0c6d-4df2-89b0-046da47416be.](https://support.microsoft.com/en-us/topic/kb5005128-windows-server-containers-for-july-2021-51dbbd2a-0c6d-4df2-89b0-046da47416be) @rcowsill please confirm this solves the problem. Thanks.

**Comment by rcowsill** [comment]
I'm still finding configs containing "rootfS". In addition to the repos listed above there's now one more affected (just one config in this case):

Repo name               | Example JSON (mediaType: application/vnd.docker.container.image.v1+json)
--------------------- | ---------------
azuremonitor/containerinsights/cidev | [sha256:152749f71f8fd6004056d15c7fd5791563072703171eb8dbd3e66b2ee67f8287](https://mcr.microsoft.com/v2/azuremonitor/containerinsights/cidev/blobs/sha256:152749f71f8fd6004056d15c7fd5791563072703171eb8dbd3e66b2ee67f8287)

`windows`, `windows/iotcore`, `windows/nanoserver` and `windows/servercore` all still have tags that reference configs with the issue.

Does the fix only apply to tags that have had an update since July 2nd?

**Comment by rcowsill** [comment]
I'm still finding configs containing "rootfS". In addition to the repos listed above there's now one more affected (just one config in this case):

[azuremonitor/containerinsights/cidev:vishwa-test-042121@sha256:152749f71f8fd6004056d15c7fd5791563072703171eb8dbd3e66b2ee67f8287](https://mcr.microsoft.com/v2/azuremonitor/containerinsights/cidev/blobs/sha256:152749f71f8fd6004056d15c7fd5791563072703171eb8dbd3e66b2ee67f8287)

`windows`, `windows/iotcore`, `windows/nanoserver` and `windows/servercore` all still have tags that reference configs with the issue.

@weijuans-msft, does the fix only apply to tags that have had an update since July 2nd?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @judyliu-ms, please provide an update or close this issue.

**Comment by cwilhit** [comment]
> does the fix only apply to tags that have had an update since July 2nd?

Hey @rcowsill, none of the containers from before the bugfix will have that fix retroactively applied to them. I spot checked to be sure, and our current updated containers look correct. I am going to close this as fixed unless you're seeing this with images published after July 2021.
