### ISSUE TITLE
Docker Windows Container: DllNotFoundException: Unable to load DLL 'gdiplus.dll' or one of its dependencies

### ISSUE THREAD

**Issue by eric10220420** [microsoft/Windows-Containers#108]
Hi guys,

I have an issue regarding libgdiplus which on windows containers.
I google a lot here and there but all answers are related Linux.
Anyone have any ideas on how to fix the issue?
Below is my windows container dockerfile.

# Dockerfile Content
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WebAPI/WebAPI.csproj", "WebAPI/"]
RUN dotnet restore "WebAPI/WebAPI.csproj"

COPY . .
WORKDIR "/src/WebAPI"
RUN dotnet build "WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebAPI.csproj" -c Release -o /app/publish

FROM build AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebAPI.dll"]

**Comment by vrapolinario** [comment]
I believe this dll is not present in the image you're using as it is a dotnet core image and that uses Nano Server. I'm not sure it is present in the Server Core image either, but would be the first thing to try out. The image to try would be https://hub.docker.com/_/microsoft-dotnet-framework-aspnet.

If that image doesn't work, you can still try the Windows image: https://hub.docker.com/_/microsoft-windows. However, I don't think there's a dotnet image based on that base image, so if it gets to that, you'll have to build the app on that image by hand.

**Comment by vrapolinario** [comment]
Happy to open this issue once we hear back from the user.

**Comment by Saibamen** [comment]
This same on image `mcr.microsoft.com/dotnet/aspnet:6.0`

**Comment by Saibamen** [comment]
With `mcr.microsoft.com/dotnet/framework/aspnet:4.8` I was unable to start container in Azure (App Service)

With `4.8.1` tag, I could not build Docker image in Azure DevOps:
```
no matching manifest for windows/amd64 10.0.17763
```
