### ISSUE TITLE
Intermittent TCP connection error 10053 between containers

### ISSUE THREAD

**Issue by awakecoding** [microsoft/Windows-Containers#114]
TCP connections between two containers on the same host randomly fail with "An established connection was aborted by the software in your host machine. (os error 10053)", or a variant of the same error, but it is always error code 10053. We've been chasing this bug down for over 6 months already, and have seen it happen at customer sites and in all of our Windows lab environments, with both container port mapping and internal docker networks, but never when using Linux containers on Linux.

We develop a multi-container application composed of multiple Rust microservices, and the connection error manifests itself with no precise failure pattern when making HTTP requests from one container called "den-server" to another container called "den-lucid", both of which are written in Rust. The HTTP client is using [reqwest](https://crates.io/crates/reqwest) and [hyper.rs](https://hyper.rs/), while the HTTP server is using [saphir](https://crates.io/crates/saphir) and [hyper.rs](https://hyper.rs/).

The connection load does not seem to be an important factor, we've already tried creating an artificial flooding of HTTP requests between the two containers without success. Sometimes it can work well for days, and some days it just happens a few times in a row. While trying to find workarounds to the problem, we tried disabling the reqwest HTTP connection pooling to force one-connection-per-request, and all it did was make things worse with a failure once every 2-3 requests. In other words, the connection pooling partially hid the problem by making less connections, and therefore os error 10053 would happen less.

Googling for possible causes of error 10053 returns many mentions of issues related to TCP keep-alives, along with AVs and firewalls blocking the connection. We've tested with the Windows Defender firewall logging enabled, and reproduced the issue multiple times without a corresponding entry in the dropped packets, meaning it is *probably* not Windows Defender. I don't know if the Windows Defender real-time protection could block connections without logging them, but for now we think Windows Defender is not responsible.

One thing that would greatly help debug the connection issues would be to find a way to capture the traffic in Wireshark. We've tried Wireshark and RawCap on *all* interfaces, one at a time, and never managed to capture traffic between containers, even when we did port mappings for all containers on the host and then used the host IP + port between the containers. The container networking appears to go through a completely different route that is never captured and I wasn't able to find a way to enable it. I suspect that the problem still occurs even with port mapping because it's just using the docker "nat" interface. We normally use our own docker network created with "docker network create" and no special options.

I followed instructions from the [advanced container networking page](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced) to create my own transparent docker network attached to a Hyper-V NIC with MAC address spoofing enabled, and managed to launch all my containers on it. I even managed to capture some of the traffic from the Hyper-V host in Wireshark, but it only be the direct traffic between my host and the first container that stands on the "edge" of the docker network (traefik reverse proxy). I have never been able to capture traffic between two containers, and I'm still looking for what kind of setup may allow inter-container traffic packet capturing for debugging. If we could see what happens at the TCP level, it would greatly help.

This should be a pretty good summary of the long list of things we've tried so far, otherwise there's a whole [twitter thread](https://twitter.com/awakecoding/status/1392223183873396736) about it. It's a quite serious issue for us because we can't find a way to stabilize our software on Windows Server, and it is by far the most popular deployment option with our customers. We can't tell them to switch to Linux to run Linux containers even if it is a supported deployment option.

**Comment by awakecoding** [comment]
Quick update: I can now capture inter-container traffic using pktmon:

```
pktmon start --capture --pkt-size 0 -f capture.etl
pktmon stop
pktmon etl2pcap .\capture.etl
```

The HTTP request is sent, and the HTTP response is also sent, but I suspect it may not be fully received before the TCP connection is dropped by the server, causing os error 10053. I am now trying to review how [TCP options work inside containers](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/description-tcp-features).

The packet captures that I have show a very large number of TCP fast retransmissions, and the os error 10053 appears to always correspond [with a series of invalid TCP fragments reported by wireshark](https://twitter.com/awakecoding/status/1392577719926501378), after which we can see a TCP FIN. The TCP analysis warning reported by Wireshark is "Reassembly error, protocol TCP: New fragment overlaps old data (retransmission?)" so it doesn't look benign at all.

I would like to see if the TCP options can be tweaked to reduce the amount of TCP fast retransmissions, and maybe get a cleaner, less chatty capture. Something appears off in the way TCP is handled between the containers.

**Comment by thecloudtaylor** [comment]
A cursory review of saphir and hyper.rs it looks like they are using socket bindings so we can likely rule out HTTP.SYS.

**Comment by awakecoding** [comment]
@thecloudtaylor we found the issue, and it was a bug in our application combined with a race condition: the HTTP client would incorrectly send a body containing the string "null" in HTTP GET requests. I can't fully explain why, but since the HTTP client would send the HTTP request headers first, and then the HTTP body, I believe the timing at which those two packets were received would influence the failure/success outcome of the call, because I could see a lot of requests succeed even with this unexpected body. Here's a more detailed analysis and explanation:

https://twitter.com/awakecoding/status/139284940739407872

We can close this ticket, it is not a fault in Windows container networking. However, it may be a good thing to provide more information on how to diagnose issues between Windows containers, and give pktmon capturing instructions. If I had known how to capture the traffic between the containers a year ago, we wouldn't be here today closing this ticket now :)
