### ISSUE TITLE
Adding hosts for windows containers (extra_hosts) does not work

### ISSUE THREAD

**Issue by ancaantochi** [microsoft/Windows-Containers#115]
Using docker engine API, I created a container with ExtraHosts. I inpected the container and I can see that extrahosts is set, but hosts file doesn't contain the mapping and I can't ping the hostname

from inspect: 
```
"ExtraHosts": [                                                                                                                                                                                       
   "gateway.local:127.0.0.1"                                                                                                                                                                   ]

```

```
docker -H npipe:////./pipe/iotedge_moby_engine exec -it edgeAgent ping gateway.local
Ping request could not find host gateway.local. Please check the name and try again.
```

this issue was reported on azure iot edge, but it is windows containers issue from what I can tell: https://github.com/Azure/iotedge/issues/4939

**Comment by ancaantochi** [comment]
Hi! Any estimates when this bug could be fixed?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Hi, as this is related to Docker/Moby, I think it would be better tracked out of moby/moby#41439 or moby/moby#41165.
