### ISSUE TITLE
Missing gdiplus.dll  (system.drawing.common)  on mcr.microsoft.com/dotnet/aspnet:5.0 base image

### ISSUE THREAD

**Issue by llyons** [microsoft/Windows-Containers#120]
Are we able to use system.drawing.commong (gdiplus.dll) on the   mcr.microsoft.com/dotnet/aspnet:5.0 base image?

We had been using server core base images that did have the library but this image was too large (4-5gb)?

**Comment by vrapolinario** [comment]
Adding @richlander from the .Net team for visibility and input.

**Comment by richlander** [comment]
I believe that the new Windows Server image is required to resolve this. Is that right, Windows Server Team? Which image contains GDI+? I guess the client image would resolve that, too.

That said, we (.NET Team) are only planning on publishing Nano Server and Server Core images. As context, we don't publish Client images today. If you would like to use either the new Server or the Client image, you'll need to build them yourself. The source Dockerfiles we use are all available on GitHub. https://github.com/dotnet/dotnet-docker/tree/main/src

https://techcommunity.microsoft.com/t5/containers/announcing-a-new-windows-server-container-image-preview/ba-p/2304897

@mthalman @MichaelSimons

**Comment by mthalman** [comment]
No, Nano Server doesn't provide this DLL.  But it will work on Windows Server Core as mentioned by @llyons.  There are [tags](https://hub.docker.com/_/microsoft-dotnet-aspnet) available for 5.0 on Windows Server Core that can be used: `5.0-windowsservercore-ltsc2019`.

**Comment by weijuans-msft** [comment]
@llyons I am closing this as Matt confirmed it worked on Server Core images and you can find the right tag for the corresponding .NET 5.0 image. For size, in the upcoming release of Windows Server 2022, we (Windows container and .NET) have worked together and made some optimization. So encourage you to give it try when it's available later this year.
