### ISSUE TITLE
aspnet docker image pfx certificate

### ISSUE THREAD

**Issue by stzach** [microsoft/Windows-Containers#123]
Hello,

I am trying to build an aspnet docker image for identityserver. I am using the default docker file configuration provided from visual studio, but i need to install within the final image a pfx certificate. This certificate is a X509 for identity server (.AddSigningCredential(configuration.GetValue<string>("SigningCertificate"), System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine);).

I cannot find any way to do that because on the final image there is no certutil or powershell. I have also tried to programatically install it on application startup but i get permission errors.

`# escape=
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

#RUN CMD certutil -importpfx -p "123456" "./cert_signed.pfx"
#RUN dotnet dev-certs https -ep "./cert_signed.pfx" -p "123456"
#RUN dotnet dev-certs https --trust
#RUN dotnet dev-certs https -ep ./cert_signed.pfx -p 123456
#RUN dotnet tool install --global dotnet-certificate-tool
#RUN dotnet tool install --tool-path ./ dotnet-certificate-tool
#RUN certificate-tool add --file "./cert_signed.pfx" --password "123456"

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
RUN dotnet nuget add source http://tfs.server.int:81/nuget/Default/ -n MyNuget
COPY ["IdentityServer/IdentityServer.csproj", "IdentityServer/"]
COPY ["IdentityServer.Services/IdentityServer.Services.csproj", "IdentityServer.Services/"]
RUN dotnet restore "IdentityServer/IdentityServer.csproj"
COPY . .
WORKDIR "/src/IdentityServer"
RUN dotnet build "IdentityServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IdentityServer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
#RUN CMD certoc -importpfx -p "123456" "c:\\app\\cert_signed.pfx"
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IdentityServer.dll"]`

Can anyone suggest something? I thought that powershell should be installed on aspnet docker images.

thank you

**Comment by weijuans-msft** [comment]
@richlander Poweshell should be supported on ASPNet images right?

**Comment by stzach** [comment]
Powershell is not available. Problem has been resolved.

The idea is to create the certificate in for local machine and add it as parameter to docker image to load it.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@mapalko, @weijuans-msft, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@mapalko, @weijuans-msft, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Closing as issue appears to have been resolved several months ago.
