### ISSUE TITLE
SQL with gMSA breaks SSL implementation

### ISSUE THREAD

**Issue by joachimcarrein** [microsoft/Windows-Containers#124]
After creating a SQL Docker image, the SSL does no longer work to import certain certificates, or create new self signed certificates.

We tested on different Server 2019 versions updated to the last update:

- 1809: same error
- 1903: works (we have no clue why it does work here)
- 1909: same error
- 2004: same error
- 20H2: same error

The error we received is the following:
```
New-SelfSignedCertificate : CertEnroll::CX509Enrollment::_CreateRequest: The remote procedure call failed. 0x800706be (WIN32: 1726 RPC_S_CALL_FAILED)
At C:\start.ps1:72 char:1
+ New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SelfSignedCertificate], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand
```

We used the [dockerfile from Microsoft](https://github.com/microsoft/mssql-docker/tree/master/windows/mssql-server-windows-express).

We adjusted the start.ps1 to not loop, but instead just run a new-selfsignedcertificate command:
`New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgorithm RSA -DnsName "test.test.com" -Type SSLServerAuthentication -NotAfter (Get-Date).AddYears(40)`

The issue started with Business Central containers which was also reported here on the [navcontainerhelper ](https://github.com/microsoft/navcontainerhelper/issues/1730) github. We worked a bit to more pin down the issue. This is the furthest / cleanest repro point we got.

If you do not enabled gMSA, the issue is not there. However in our scenario we need to use gMSA.

For completeness, I will include the files we used in DevOps for multiple server run. We also did this manually, so it is not a DevOps issue.

[github_report.zip](https://github.com/microsoft/Windows-Containers/files/6648863/github_report.zip)

**Comment by weijuans-msft** [comment]
acknowledging; looking which SMEs in side who can help triage and root cause...

**Comment by joachimcarrein** [comment]
A little update, we just found out it isn't even related to SQL.
We ran the following docker file with the same results as above:

```
FROM %%sourceimage%%

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

COPY start.ps1 /
WORKDIR /

RUN \
  Write-Host 'Trying to create certificate'; \
  New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgorithm RSA -DnsName 'test.test.com' -Type SSLServerAuthentication -NotAfter (Get-Date).AddYears(40);

RUN \
  Write-Host 'Trying to create certificate'; \
  New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgorithm RSA -DnsName 'test.test.com' -Type SSLServerAuthentication -NotAfter (Get-Date).AddYears(40);

CMD powershell -Command .\start.ps1
```

the start.ps1 is as follows:
```
Write-Host "Trying to create certificate (1)"
New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgorithm RSA -DnsName "test.test.com" -Type SSLServerAuthentication -NotAfter (Get-Date).AddYears(40)

Write-Host "Trying to create certificate (2)"
New-SelfSignedCertificate -KeyLength 2048 -SmimeCapabilities -KeyAlgorithm RSA -DnsName "test.test.com" -Type SSLServerAuthentication -NotAfter (Get-Date).AddYears(40)
```
it appears as soon as the build step creates a certificate, the start.ps1 can no longer create certificates.
If we place the 2 tryouts in the dockerfile in comment, the start.ps1 works as expected.

so presumably, SQL Install creates a certificate in the install process which results in the same problem.

**Comment by joachimcarrein** [comment]
Any updates?

**Comment by BartBourgeois** [comment]
We are having the same problem, currently blocking upgrade for our customers.

Kind regards

**Comment by waldo1001** [comment]
We too :(.

@weijuans-msft , would you have any feedback on this?

**Comment by weijuans-msft** [comment]
The SQL container image is not an officially supported image. However I understand this is not SQL specific. We are looking at repro'ing in house and investigate. If there is any other info such as logs etc, please do share.

**Comment by BartBourgeois** [comment]
The most straight forward example for recreating the issue is the example of @joachimcarrein 
=> https://github.com/microsoft/Windows-Containers/issues/124#issuecomment-870525577

It's based on windows core (no sql involved) and can be repro'd very easily.

**Comment by bingbing8** [comment]
@joachimcarrein, can you help me understand the behavior of this issue:
1. is this gMSA v1 or v2? what are the steps for you to enable gMSA?
2. Just curious why you need to create same certs twice? Does the failing application have write access to HKLM\My store? Is a new certificate added each time. Or does it do name matching and overwrite?
3. Do you mean the New-SelfSignedCertificate cmdlet work in docker file but not in start.ps1? 
4. What happens if you remove the lines to create cert in docker file and leave the start.ps1 to create cert?
5. What is the container host os version when your repro it? I assume the above 1809 to 20H2 are container images. It would be good if you could provide both container host and image build version combination on which it repros.
6. Is it process isolated runtime?

**Comment by joachimcarrein** [comment]
Hi @bingbing8 

1. No clue if it is v1 or v2. This is how we create the gmsa with PowerShell:
```
New-ADServiceAccount -Name $GmsaAccount `
                     -DNSHostName $ServerFQDN `
                     -PrincipalsAllowedToRetrieveManagedPassword "Domain Controllers", "domain admins", "CN=Container Hosts,CN=Builtin, DC=domain, DC=local" `
                     -KerberosEncryptionType RC4, AES128, AES256
```
2. We do not need the same certificate twice. This is just a reproduction scenario that is easy to test and gives the exact same error we had. In our scenario, we do customisations on an Microsoft pre built image and do need a self signed certificate. Our suspision is that in the Microsoft pre built image their is already a certificate created (maybe even temporary).
3. No. It doesn't work within docker or start.ps1 as soon as the command was run in the docker file.
4. This is just repro scenario, see point 2, we have no control over the Microsoft pre built image
5. We have explicitly tested on the same host OS as container image version. No differences there
6. We tested both

**Comment by weijuans-msft** [comment]
@joachimcarrein by gMSAv2, we meant "gMSA with non-domain joined host" :), see more here in this blog: https://techcommunity.microsoft.com/t5/containers/announcing-active-directory-identity-improvement-on-aks-on-azure/ba-p/2374198.

I believe you are using the current version of gMSA which requires a domain joined host, sometimes referred as gMSA v1 internally.

**Comment by tommyreinsmsft** [comment]
For Microsoft folks, the internal bug filed is #34951982. @joachimcarrein is this still impacting you?

**Comment by joachimcarrein** [comment]
Hey @tommyreinsmsft We have worked around it and the problem is no longer an issue for us

**Comment by tommyreinsmsft** [comment]
> Hey @tommyreinsmsft We have worked around it and the problem is no longer an issue for us

How did you work around this? Would love to share that knowledge to the community!

**Comment by joachimcarrein** [comment]
As described in the issue, for some reason it did work on 1903. So internally we have rebuild all our platforms to 1903 and migrated all dockers to work around the issue. On other locations where we were currently unable to upgrade the platform, we halted all upgrades and kept everything as it is for continuity.

Very recently we did a build on an 1809 machine, where we noticed that the base image was changed (windows update) and apparently also don't run into the issue anymore.

**Comment by jdebbink** [comment]
@tommyreinsmsft any update on this? This is impacting our ability to upgrade to newer versions of the container. We are running on 2019 LTSC hosts that are domain joined. We cannot remove gMSA.

**Comment by jdebbink** [comment]
For anyone stumbling on this issue, I've found a workaround. You'll want to generate the self signed certificate during your docker build, *not* at runtime. The key here is that the the hostname on the certificate must match the hostname of the container at runtime. I'm running on ECS w/ EC2 so the hostname is set for me to be the name of the gMSA. You can also override hostname in the docker run command as [documented here](https://docs.docker.com/config/containers/container-networking/).

For example, look at the credential spec to get the `MachineAccountName` value:
``` 
{
  "DomainJoinConfig": {
    "Sid": "S-1-234",
    "MachineAccountName": "my-gmsa",
    "Guid": "1234",
    ....
  },
  ...
}
```

Take that and generate the self signed cert at build like so in your Dockerfile:
```
RUN New-SelfSignedCertificate -Subject "my-gmsa" -DnsName "my-gmsa" -CertStoreLocation "Cert:\LocalMachine\My" -NotAfter (Get-Date).AddYears(10)
```
