### ISSUE TITLE
“The system cannot find the file specified” error happens when pd windows driver tried to unmount volume

### ISSUE THREAD

**Issue by lizhuqi** [microsoft/Windows-Containers#125]
Enviroment: GKE
Cluster version: 1.19.9

Operation for "{volumeName:kubernetes.io/gce-pd/[ID]--[ID] podName: nodeName:}" failed. No retries permitted until [TIMESTAMP](durationBeforeRetry 500ms). Error: "UnmountDevice failed for volume \"[ID]\" (UniqueName: \"kubernetes.io/gce-pd/[ID]--[ID]\") on node \"[ID]\" : CreateFile \\var\\lib\\kubelet\\plugins\\kubernetes.io\\gce-pd\\mounts\\[ID]--[ID]: The system cannot find the file specified."

Our customer found this error in their log. Unmount eventually succeeded but the status is not in sync so driver was trying to unmount  no longer exists volume. @jsturtevant mentioned this might be caused by some racing condition.  

@daschott and @jsturtevant  - please take a look. Thanks!

**Comment by lizhuqi** [comment]
According to the log, mount/unmount/remount seems to succeed but however customer sees some IO errors like "The file or directory is corrupted and unreadable." when they tried to read a dir or file:

**Comment by lizhuqi** [comment]
With more investigation, we think the volume corruption is not caused by “The system cannot find the file specified” error but we are still not clear the cause.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by weijuans-msft** [comment]
@lizhuqi Have you tried with GCE support or the community? or Sig-Windows? I can't tell with the info here that is something Windows container can start investigating.

**Comment by lizhuqi** [comment]
Hi Weijuan, I am from GKE. Can you help me understand more about "The system cannot find the file specified." error? It is a very general error from Windows OS. What may trigger it happen? May some stale symlink cause this issue?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
Hey @lizhuqi , are you still having this issue? If so, are you able to provide any more information about the customer scenario and configuration? This would make it easier for us to investigate this.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.
