### ISSUE TITLE
MCR-hosted VS Build Tools base image

### ISSUE THREAD

**Issue by TBBle** [microsoft/Windows-Containers#126]
Following up on https://github.com/microsoft/Windows-Containers/issues/102#issuecomment-827170844.

> Redistribution of the VS Build Tools is not permitted, so we should make sure that while we document how .dockerfile should install VS Build Tools for anyone wanting to create private container images, we cannot publish these images on any public container repos.

Is there any chance we could have a VS Build Tools base image offered from MCR the way Windows container base images are, using foreign layers for the non-redistributable parts?

I would assume an VS Build Tools image would derive from the Server Core base, so it'd be another foreign layer or two on top of those already offered from MCR.

The foreign layers system would mean that people building containers from that base are not then distributing those layers, as all users would fetch them directly from Microsoft's servers, even though the manifest pointing at them might be hosted on Docker Hub or other public repo.

This might be complex because I guess one of the following has to hold:
* The base image contains _all_ of the VS Build Tools, or at least enough to cover the wide variety of uses cases; and is hence much larger than most users need.
* Different, parallel base images are needed covering different Workloads (I guess); and hence maintenance cost for MS is combinational.
* The VS Build Tools are installed in the layer distributed from MCR, and people deriving container images from that are not violating the license by adding more packages and publishing the result; if the license allows that. (I haven't checked)

**Comment by vrapolinario** [comment]
Hi @TBBle, Our team (Windows Containers) don't own MSVC and while we're happy to pass on the suggestion to that team, we have no control over other Microsoft components. I see that their page https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options?view=msvc-160 is on GitHub and open for suggestion as well as present many members of the team so it'd be easier to contact that team directly there. I apologize for the confusion of having this Windows Containers repo as you expect a single point of contact for container related topics with Microsoft, but the reality is that our team has no ownership on MSVC.

Hopefully the link above can help you get in contact with that team. I'll be closing this for now, but please let us know the outcome.

**Comment by TBBle** [comment]
I'm guessing you meant to link to https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019, but it's a good point, I'll raise it with the Visual Studio product team instead.

Edit: For those following along at home, I raised it at https://developercommunity.visualstudio.com/t/Please-publish-an-MCR-hosted-VS-Build-To/1454970

While doing so, realised that the [.NET Framework SDK container image](https://hub.docker.com/_/microsoft-dotnet-framework-sdk/) is an example of the second approach, and as noted in #102, it isn't super-obvious that you can't use it unless you have a VS Build Tools license, which [does _not_ cover VS Code](https://visualstudio.microsoft.com/license-terms/mlt031519/) for example.

[VS Code's C++ docs](https://code.visualstudio.com/docs/cpp/config-msvc) also note this:
> Note: You can use the C++ toolset from Visual Studio Build Tools along with Visual Studio Code to compile, build, and verify any C++ codebase as long as you also have a valid Visual Studio license (either Community, Pro, or Enterprise) that you are actively using to develop that C++ codebase.

So this aspect of the issue isn't container-specific, anyway, so I think redistribution is the main concern to be addressed.
