### ISSUE TITLE
service and multi-stage

### ISSUE THREAD

**Issue by Andrysky** [microsoft/Windows-Containers#128]
hi help please, i installed the program in windows/servercore now i want to transfer to windows/nanoserver
I copied the files, but when the container starts, the services do not start (and they are not in the list - `sc queryex type = service state = all`), I tried to copy the registry (C:\windows\System32\config\) but the results are not gave (((

**Comment by vrapolinario** [comment]
Hi @Andrysky can you please provide more details on what you're building and the issue you're seeing? Can you provide details on your dockerfile, the error message if any, etc?

**Comment by weijuans-msft** [comment]
@Andrysky reminder, please share more details.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.
