### ISSUE TITLE
Bugcheck  on afunix.sys causes node reboot

### ISSUE THREAD

**Issue by porrascarlos802018** [microsoft/Windows-Containers#129]
Bugcheck: 139, please provide updates here.

**Comment by vrapolinario** [comment]
This is under investigation and we're working on a fix. Will provide updates as they come.

**Comment by vrapolinario** [comment]
I just got a note that the fix for this issue is going to be out on the 9C update for Windows Server 2019.

**Comment by rma666** [comment]
Hi, 
We are suffering heavily from this, is there a KB or private fix that we can refer to with product support?
