### ISSUE TITLE
[Windows Swarm] windowsfilter directory isn't cleaned up - unreferenced layers are used by another process

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/Windows-Containers#130]
We already brought up the issue here: https://github.com/moby/moby/issues/42521 

As there wasn't much feedback, we also would like to ask the Windows Containers platform team here if you see another way around this issue apart from regularly redeploying the cluster nodes?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by brasmith-ms** [comment]
Hey @lippertmarkus, unfortunately since we have moved most of our support services to containerd we have not seen this issue. I don't really see a way around this besides redeploying cluster nodes.
