### ISSUE TITLE
Documentation for New-SmbGlobalMapping

### ISSUE THREAD

**Issue by perithompson** [microsoft/Windows-Containers#131]
The Kubernetes SMB CSI driver uses New-SmbGlobalMapping but there doesn't seem to be any docs explaining the command and the various switches such as RequirePrivacy, please can this be documented alongside https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbmapping?view=windowsserver2019-ps so that we can understand what is going on.

**Comment by perithompson** [comment]
@immuzz this was mentioned on SIG Windows last night

**Comment by perithompson** [comment]
hI @immuzz any update on this?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Hey @perithompson sorry for the radio silence. I do see this is documented now here: 

https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbglobalmapping?view=windowsserver2022-ps&viewFallbackFrom=windowsserver2019-ps

In which case we're good to resolve the issue.
