### ISSUE TITLE
DNS queries fail for small time window after Windows Container start in Dockershim

### ISSUE THREAD

**Issue by daschott** [microsoft/Windows-Containers#132]
There is a known issue in dockershim such that DNS server regKeys will not be set on container startup in dockershim on Kubernetes. This can cause DNS resolution errors for a small time interval upon startup. 

To workaround this issue, you can use lifecycle hooks to wait for the DNS server to be plumbed: 
https://github.com/kubernetes/community/blob/master/sig-windows/CONTRIBUTING.md#troubleshooting

This issue is resolved with containerD and any CNI plugins that leverage HNS v2 APIs with namespace objects (sdnbridge, sdnoverlay).

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by NandoTheessen** [comment]
hi @daschott 👋🏻 
We're facing an issue that is very similar to what you're describing here (intermittent DNS issue on startup of windows server 2019 containers that we can fix by pinging the containers standard gateway).
Is there a way we could confirm that it is actually the issue you're describing here, so we can convince management that the work involved in a new CRI and CNI plugin is necessary?

**Comment by zhiweiv** [comment]
We observed this issue in Containerd pod today, we have dns ensure logic at the application start.

C:\Users\zwliu>kubectl logs recocanary-job-srn20211130033437080363
2021-11-30 03:34:54 EnsureDns result: No such host is known.
2021-11-30 03:35:07 EnsureDns result: No such host is known.
2021-11-30 03:35:20 EnsureDns result: No such host is known.
2021-11-30 03:35:33 EnsureDns result: No such host is known.
2021-11-30 03:35:46 EnsureDns result: No such host is known.
2021-11-30 03:36:00 EnsureDns result: No such host is known.
2021-11-30 03:36:13 EnsureDns result: No such host is known.
2021-11-30 03:36:26 EnsureDns result: No such host is known.
2021-11-30 03:36:39 EnsureDns result: No such host is known.
2021-11-30 03:36:40 EnsureDns done.

AKS 1.12.1
Windows Server 2019 Datacenter   10.0.17763.2300    
containerd://1.4.8+unknown

The code
```
	public static void EnsureDns()
        {
            while (true)
            {
                try
                {
                    Dns.GetHostEntry("www.google.com");
                    break;
                }
                catch (Exception e)
                {
                    Logger.Log("EnsureDns result: {0}.", e.Message);
                }
                Thread.Sleep(TimeSpan.FromSeconds(1));
            }
            Logger.Log("EnsureDns done.");
        }
```

**Comment by daschott** [comment]
@zhiweiv Thank you for trying out containerD! 
This issue you are describing appears to be different since you are seeing intermittent connectivity for a longer time span. Can you file a new issue where this can be tracked?

**Comment by zhiweiv** [comment]
Thanks for the information, I will add log to verify if dns server configured when dns resolve error. Will do more investigate before file new issue.

**Comment by cwilhit** [comment]
Closing this issue since containerd has GA'ed in AKS. For users who are impacted by this issue and not running in AKS, please consider moving to containerd runtime.
