### ISSUE TITLE
Running custom script extension to change the locale on VM Scale Set does not change I18N formatting 

### ISSUE THREAD

**Issue by ovidiubuligan** [microsoft/Windows-Containers#137]
We are trying to set the locale  on a AKS VM Scale Set via Custom Script Extension that is run at startup , this is not Ideal ,any other better way would help . The script extension that we run is : 

```powershell
if($(Get-WinSystemLocale).Name -ne "nb-NO"){
	Write-Host " not norwegian locale"
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name sThousand -Value "."
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name sDecimal -Value ","
    Set-WinSystemLocale nb-NO
    Set-WinUserLanguageList -LanguageList nb-NO -Force
    Set-Culture -CultureInfo nb-NO
    Set-WinHomeLocation -GeoId 177
    Restart-Computer
} 
```

The problem is now that calling `Get-WinSystemLocale` return correct `nb-NO` after restart , But the currently format and date format is not honored. For example :
```powershell
>>>"{0:C}" -f 9999999999999
$9,999,999,999,999.00
```

How can we fix this ?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.

**Comment by immuzz** [comment]
Host Process Containers for K8s is in v1.22. That would be the best way to do this. It will be available in AKS in a couple of months. https://kubernetes.io/blog/2021/08/16/windows-hostprocess-containers/
