### ISSUE TITLE
When will base image for nano server stop being available?

### ISSUE THREAD

**Issue by metaljo5001** [microsoft/Windows-Containers#138]
Hello,

I am trying to find out when specific base image will stop being available for use for docker. I found https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle for the end of support date, but it is not the information I was looking for. Essentially, when will link like mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-1903 stop working?

**Comment by TBBle** [comment]
That image (`mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-1903`) belongs to https://github.com/dotnet/dotnet-docker so you might want to ask there. Based on https://github.com/dotnet/dotnet-docker/issues/2445, I suspect they won't actually be removed, but they'll also never be updated again.

**Comment by thecloudtaylor** [comment]
Presently we do not remove old images, though this is an active topic of discussion. However please be aware that once images are outside of support (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle) they are not patched and I would strongly recommend moving to a supported/patched version.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@thecloudtaylor, @weijuans-msft, please provide an update or close this issue.
