### ISSUE TITLE
Windows servercore containers: Not possible to delete files/folders that start with $

### ISSUE THREAD

**Issue by PNe-ins** [microsoft/Windows-Containers#142]
In windows servercore containers it is not possible to delete all files/folders that start with $.

If there is a folder containing folders/files that start with $, that is added via Dockerfile then the first file/folder (in alphabetical order) cannot be removed properly. There is no error message, but the file/folder is still listed in the folder. If you try to open the file / enter the folder, you receive an error message, that the file/folder does not exist.

To recreate the issue:

1.  Create an Folder "context with the follwoing structure:context
    |-- $abc
    |-- $def
    |-- $ghi
    |-- files
    |    |-- $abc.txt
    |    |-- $def.txt
    |    |-- $ghi.txt
2. Use this folder as context to build the following dockerfile
    `FROM mcr.microsoft.com/windows/servercore:20H2`
    `ADD . context`
3. Start an interactive container of this image and try to delete $abc, resp. $abc.txt

It doesn't matter if you use cmd or powershell, rmdir or remove-item, the file/folder will be listed after beeing removed.
This leads additionally to the fact that it is not possible to delete the folders 'files' or 'context' recursively, because windows detects a subfolder/file that it tries to delete, but cannot be deleted because it doesn't exist.

I tried this with mounted folders as well, but there is no error. The file/folder gets deleted like expected.

Are there any suggestions regarding this behavior. I would also appreciate a workaround.
Thank you

**Comment by cwilhit** [comment]
Hi @PNe-ins I tried to set up a repro environment. Rather than use 20H2-version images I opted for WS2022-versioned images. I was not able to repro this--I could delete both files and folders prefixed with a '$'. See below commands, is that what you tried?

![image](https://user-images.githubusercontent.com/5685031/157296104-4213cf7a-850f-4fc7-a247-dc136b73d6f2.png)

**Comment by PNe-ins** [comment]
Hi @cwilhit 
Yeah that's pretty much the szenario. Tried the same command on a 20H2 image an got the same result as described at first: 
![grafik](https://user-images.githubusercontent.com/58724452/157472306-da3e8e11-8eaa-4247-aeb2-d4421c1235dd.png)

Unfortunally, as we are using Windows Server 2019 Hosts, I cannot simply use 2022 Images.
Tried it with 2022 images anyway and it worked with 'remove-Item' in powershell, as well as with 'rmdir' resp. 'del' in cmd. Seems to be fixed in server 2022. Now i know at least, that it will work as soon as we use server 2022.

Thank you 👍

**Comment by cwilhit** [comment]
You're welcome. I am going to mark this issue closed with recommendation for other users who might visit this issue to please roll forward to WS2022 if this is impacting them.
