### ISSUE TITLE
It's impossible to do something as basic as configuring an application without workarounds

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/Windows-Containers#143]
Let's try configuring my application using environment variables, just like in Linux:

```
docker run -e MyApplicationSettingsSection__someField=okay --isolation process some/image
```

Do I see the environment variable? No, because of something weird with shell versus exec syntax in Dockerfile entrypoints versus commands (https://stackoverflow.com/a/43051690/1757994).

Okay, let's try bind mounting my configuration file.

```
docker run -v "./myconfig.json:C:\\App\\config.json" --isolation process some/image
```

No, I can't do that, because for some reason I can't bind files in Windows containers (https://github.com/moby/moby/issues/30555)

Okay, let's try getting configuration from a host. Seems logical I can serve it from an http address from the host, a common pattern:

```
// inside my exe
Get("http://host.docker.internal:5555/configuration.json");

// my shell
docker run --isolation process some/image
```

No, that doesn't work, because Windows docker containers do not have the DNS host names for the local gateway by default, you have to use some random guy's script to get this to work (https://github.com/docker/for-win/issues/1976#issuecomment-585423014)

All of this would come up in Kubernetes. You mount `ConfigMap` files and set environment variables and all this stuff all the time, it's so standard, and none of it works.

**Comment by vrapolinario** [comment]
I assigned this to Weijuan as she can find someone to investigate these scenarios. Wanted to point out a few things:
- On your first case, it seems that there is a solution to use Entrypoint. Linux and Windows containers behave differently and it might be the case that you need to adjust your dockerfile to a Windows environment.
- On the second case, I'm not sure we can mount a file directly (might have to do with permissions), but is it possible to mount a folder that then gives the container access to the file?

**Comment by doctorpangloss** [comment]
> it seems that there is a solution to use Entrypoint

Yes. This issue comes up because entrypoints are how Windows containers do stuff like copy drivers from the host drivers directory - and really, what else are people using Windows containers for, if not for things that require DirectX and other high-quality windows features? It ain't MSSQL.

An example entrypoint that correctly does startup tasks like copying files and also correctly passes environment variables to the delegate would be ideal.

Something I have not investigated - does nssm read the environment variables? According to printing each environment variable in a process, sometimes the process gets the environment specified in Docker, and sometimes it doesn't, which is really really surprising.

> is it possible to mount a folder that then gives the container access to the file?

Yes, that is what I'm doing. I'm advocating for a known workflow, like the ConfigMap workflow, which expects to be able to mount files, as opposed to a workaround.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Your first item is explained in the dockerfile run [reference](https://docs.docker.com/engine/reference/builder/#cmd). Regarding your second item for single file mapping, that  has since been delivered in the platform (see #31), provided you're on Windows Server 2019 or later and provided you're using containerd or another container runtime that uses HCSv2 schema. So Kubernetes can do this. To my knowledge, Docker on Windows is not on this yet. 

To your third item, that is a feature request we could look at implementing but would be better tracked in a separate, dedicated issue. If that is of interest, let's open a separate issue. I am closing this one out.
