### ISSUE TITLE
vEthernet Initial RTO timeouts

### ISSUE THREAD

**Issue by warrenspe** [microsoft/Windows-Containers#144]
Good day!

Please let me know if I've posted this to the wrong support channel

My team is using windows containers on a windows server 2019 physical machine, leveraging the default NAT network and are noticing an intermittent delay when connecting to TCP sockets either from:
* container to a server on its host
* a container to a server in another container on the same host
* the host to a server running in a container (on that same host)
But not:
* container to itself
* host to itself

For example, using this script on the host:
```
$endpoint = New-Object System.Net.IPEndPoint ([System.Net.IPAddress]::Any, 81)
$listener = New-Object System.Net.Sockets.TcpListener $endpoint
$listener.Start()
do {
    $client = $listener.AcceptTcpClient() # will block here until connection
    echo $client
    $client.Dispose()
} while ($true)
```

and this script running inside of the container:
```
function Test-TCPPort{
    Param(
        $HostAddress = 'HOST_IP_HERE',
        $HostPort = 81
    )
    $socket = New-Object Net.Sockets.TcpClient
    Try{
        $socket.Connect($HostAddress, $HostPort)
        Write-Host "Connected"
    }
    Catch{
        Write-Host $_
    }
    Finally{
        $socket.Close()
        $socket.Dispose()
    }
}
(measure-command { Test-TCPPort  }).TotalSeconds
```

We are seeing results such as the following (note the 2nd last result; tests below run from container client -> server on host):
```
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
0.0011696
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
0.0011756
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
0.0011102
PS C:\>
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
0.0011874
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
3.0023414
PS C:\> (measure-command { Test-TCPPort  }).TotalSeconds
Connected
0.0012115
```

The latency is very intermittent, it can happen twice in a row, or it can be many runs apart, but on average it occurs roughly once in every 5-50 connections.  We have noticed, however, that the delay (3s as noted above) does reflect the "Initial RTO" timeout configured at:
```
>netsh interface tcp show global
Querying active state...

TCP Global Parameters
----------------------------------------------
…
Initial RTO                         : 3000
…
```
In other words, if we change the Initial RTO, the latency we observe changes accordingly.

We have also looked at some netsh capture logs captured at the time the issue occurred and noticed the following:
```
TCPIP: Transport (Protocol TCP, AddressFamily = IPV4) dropped 1 packet(s) with Local = HOST_IP_HERE:81, Remote = HOST_IP_HERE:50223.
Reason = Listener dropped SYN because SO_PAUSE_ACCEPT was set.
```

However, we're not able to find much, if any, documentation about the SO_PAUSE_ACCEPT flag online, so hit a wall there.

We would be quite interested to know if anyone else is able to reproduce this on their machines, or if it is something specific to our own setup, and/or if anyone has any ideas what might be causing the packets to be dropped, and what might be done to remedy the problem!

Some environment details below:

Docker version:
```
> docker version
Client: Mirantis Container Runtime
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        b3766ff
 Built:             06/29/2021 17:14:16
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       a3dc69e6b9
  Built:            06/29/2021 17:12:49
  OS/Arch:          windows/amd64
  Experimental:     false
```

OS Version:
```
Windows Server 2019
> (Get-CimInstance Win32_OperatingSystem).version
10.0.17763
```

Container Image (issue replicated on a base servercore image):
```
REPOSITORY                                              TAG          IMAGE ID           CREATED
mcr.microsoft.com/windows/servercore   ltsc2019   86eddd4761f5   12 months ago
```

**Comment by warrenspe** [comment]
Just hoping to follow up with this - I'm still able to reliably reproduce the issue; if anyone has any debugging tips they'd like me to try I'm all ears!

**Comment by daschott** [comment]
I am following up with some teams at Microsoft for more guidance and recommended steps.

**Comment by daschott** [comment]
Some feedback from experts:
SO_PAUSE_ACCEPT is set when a listening socket’s backlog fills up (i.e. when the application calls accept() or whatever .NET wrapper API too slow to keep up with the rate of inbound connections). So this is most likely an issue with the server application.

You can get more details by running the following ETW trace:
`netsh trace start provider=Microsoft-Windows-Winsock-AFD keywords=0xffffffff level=5`

Look for “TlBacklogCount”, “Current Backlog”, “Backlog Count” from the converted trace. This will get a more clear idea of what’s the maximum backlog (to be accepted connection) supported and how it gets filled up, as well as when the pause/unpause happen.

My impression is this might be more of a question/issue for .NET API owners, rather than an issue with containers stack. Have you considered raising an issue with .NET API owners as well for help?

**Comment by warrenspe** [comment]
Thank you kindly for the response @daschott !  I am away for a week but will try your suggestions upon my return.  As for whether or not it's a .NET issue, I had not yet considered that - I must admit I'm not fully familiar with where or how .NET is integrated into the container stack/vEthernet drivers.

It's probably worth noting that while my reproduction examples above are PowerShell scripts (.NET, likely?) I am able to reproduce the issue identically using a Python client/server setup, which I wouldn't expect to be impacted by any .NET APIs.

Also, I'm not sure if I mentioned it, but just as a bit of backstory the reason I'm chasing this bug is because I initially noticed this latency when proxying HTTP requests from one container to another via two Apache servers (which to my knowledge don't use .NET either).

Anyways, thanks for the suggestion and I will get back to you after I've had a chance to give it a whirl!

Warren

**Comment by warrenspe** [comment]
Hello again @daschott,

Sorry for the delay; small update on my end - I set up the trace as instructed above and recreated the issue.

I'm no expert at reading the logs, though I did go through each of the different subsections looking for any rows with any mention of "Backlog" in them.  I found many records with one of the various wordings of Backlog you mentioned above, however, notably, I didn't see a single entry with any of the backlogs > 0.

I did notice that right before the latency occurred there was a request from one of my IT department's monitoring software, Nagios something; the delay on my end is that I've been trying to schedule a time with them to disable that on the off chance that their software might be causing the issue.

I hope to be able to do that in the next week or two; I'll let you know whether it remedies the issue or not!

**Comment by warrenspe** [comment]
Good morning @daschott,

Another follow up - I have tested the server with a member of my IT team, testing the docker containers without IT's management software or antivirus running - unfortunately the latency was still present, so it seems that they were not causing it.

Which brings me back close to square one:
* Is there perhaps another way for SO_PAUSE_ACCEPT to get set? Looking at the logs I didn't see a single record with any backlog values > 0 which seems peculiar given the description of it above
* Regarding your .NET suggestion above; was that specific to the powershell server I gave in my initial post?  (As I can reproduce with python and Apache server; sans .NET) Or were you referring to another .NET piece somewhere that I am ignorant of
* Would it be of any assistance if I were to send the logs to someone for inspection?  (I'm not sure I'd be comfortable posting them straight to Github)
  * Alternatively, if it's necessary I might be able to see about getting my organization to create some sort of a Microsoft support ticket; (we have a ton of microsoft servers being a Gov organization), I'm sure they have some sort of support setup figured out.

**Comment by wagnerscastle** [comment]
We gave up on process isolation because of this and related issues.  Disabling RSC "fixed it" for 2019 and 2022.  [Issue 145](https://github.com/microsoft/Windows-Containers/issues/145).

**Comment by warrenspe** [comment]
Thanks for the suggestion @wagnerscastle,

I have tried disabling RSC support on the network adapter as indicated in #145 ; however it does not seem to have any impact on this issue.

Thanks again for the suggestion though!

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by daschott** [comment]
Hi @warrenspe sorry for the long overdue response. I reached out to the team and was informed that WinNAT is a networking mode intended for development purposes in which unfortunately perf issues like this are expected. Instead, we are recommending l2bridge networking which does not exhibit performance issues: 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies#networking-modesdocker-drivers

Could you switch to l2bridge networking mode instead? If there are any performance issues here we would definitely want to know and help out. 
https://aka.ms/winl2bridge

**Comment by warrenspe** [comment]
Hello @daschott,

Thanks for the reply!  I do recall attempting to use l2bridge back when I was initially trying to debug this, but I didn't have any luck; not because I ran into the same performance issues, but because my containers seemed to become unreachable.  Probably just some sort of a configuration issue on my end.

Anyways, I recently found out that the there are issues trying to build docker containers on the virtual machines that my organization is switching to, so it looks like my attempts at incorporating Docker into my company's workflow might be killed for a different reason anyways.

Thanks for your assistance with debugging this nonetheless!

**Comment by cwilhit** [comment]
> I recently found out that the there are issues trying to build docker containers on the virtual machines that my organization is switching to

Not to rathole this issue thread on something unrelated, but I'm curious on this point -- any more info you can share on what the build issues are that you're seeing?

**Comment by warrenspe** [comment]
Hello @cwilhit,

It was a few months ago that I ran into it; I uninstalled Docker from that VM after googling the issue and finding no results (which is about as far as my debugging goes when it comes to Docker issues).  I will take a look at re-installing Docker on that machine and giving it another go to get you some specifics (might be a week before I can get around to it, though).

In the meantime, based off of my search history it seems I was running into this when creating a new image:
    CreateComputeSystem The group or resource is not in the correct state to perform the requested operation

and I recall it occurring right at the top of my Dockerfile, on the 3rd command of:
```
ARG from_image
FROM $from_image

RUN mkdir C:\temp C:\mnt
```

where from_image is: mcr.microsoft.com/windows/servercore:ltsc2019

**Comment by warrenspe** [comment]
Sorry; things are getting a bit hectic over here - might not be able to get to this for a while

**Comment by cwilhit** [comment]
Ok, thanks for the update.
