### ISSUE TITLE
You cannot rename files and folders in mounted directories, another problem that has persisted for 4 years

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/Windows-Containers#147]
A directory bind mounted into the container errors with error with `DirectoryNotFound` or `FileNotFound` when the user or an application renames a filename or directory inside the bind mounted directory.

https://github.com/docker/for-win/issues/1058

https://github.com/docker/for-win/issues/2089

https://github.com/moby/moby/issues/38256

This reproduces today on 20H2.

**Comment by doctorpangloss** [comment]
I just bought another SSD to mount a D:/ drive in order to work around this problem, according to https://github.com/moby/moby/issues/38256#issuecomment-614626439

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by cwilhit** [comment]
@doctorpangloss I tried to repro this on WS2022 and was not able to. I tried one of the repro steps listed in the linked issue and tried another one of my own. Both worked as expected. Are you still experiencing issues here, and if you are, have you found anything to reliably repro it?

**Comment by doctorpangloss** [comment]
I have no idea, it wasn't working around Aug 13, 2021, so by now I've abandoned Windows containers.

This was definitely not one of those, "a bug so old it couldn't possibly be a real problem" issues. This was a "hit the homekey and never try again" issue. I filed 3 critical / blocking Windows containers bugs and just didn't hear back from an engineer, still, for months, so what else was I going to do.

The best response you could give would be a link to the automated test verifying the issue is fixed. For something like infrastructure I'm sure it's reasonable that there's an automated test instead of two randos on the Internet going by each other's word on it.

**Comment by cwilhit** [comment]
I am sorry some did not respond to your issue until now (waiting for seven months is laughable, I agree). 

We've had Microsoft engineers look at this in the past and have been unable to repro this. I am closing this issue as you've since moved on and we don't have a point of engagement to help pinpoint further what the culprit could be. If someone else is hitting this issue, please let us know and we will reopen and work on getting to the bottom of this.

**Comment by doctorpangloss** [comment]
> We've had Microsoft engineers look at this in the past and have been unable to repro this. I am closing this issue as you've since moved on and we don't have a point of engagement to help pinpoint further what the culprit could be. 

It's the Windows containers team's prerogative whether or not it wants to write automated tests.

**Comment by jheaff1** [comment]
I observed this issue today and have a simple repro:

```bat
docker run --rm -it -v my-named-volume:C:\my-named-volume --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022@sha256:7c07bd85c69a70b536ff05c59f49c1e308bf704906e59825d1a30e0cee86a84a
```

Then inside the container run:
```bat
cd my-named-volume
mkdir test
move test test2
```

The last command fails.

This is preventing me from using Windows containers as a developer environment. I could use hyper-v but my builds slow down by a factor of 3

**Comment by velbur** [comment]
Looks like a solution has been found for me! It's just necessary to grant permissions to the folder or disk that you are mounting into the container for the group from which Docker is launched. For example, it is the docker-user for me.

**Comment by robertoandrade** [comment]
Interesting how nobody was able to repro this. I just launched a WS2022 container and bumped into this issue. Trying to rename/move a folder/file inside a folder that was mounted from the host within the container errors out with the "The system cannot find the path specified". Seems like a pretty basic and simple problem to repro?

**Comment by robertoandrade** [comment]
I wonder why @fady-azmy-msft closed this after having reopened it 6-7 months before without any new pointers or work being done. The issue persists!

**Comment by Amaranterre** [comment]
I ran into similar problem on my Windows Container. We reproduce it in 
[this issue](https://github.com/oceanbase/docker-images/issues/56)

**Comment by lygstate** [comment]
issue still present with `docker run --isolation=process`
with `docker run --isolation=hyperv`, issue not present.
