### ISSUE TITLE
Containers Running on Windows Server 2019 Run Faster In HyperV Isolation

### ISSUE THREAD

**Issue by Eddy555** [microsoft/Windows-Containers#149]
**Expected behavior**
Docker container runs at the same speed between Windows 10 and Windows Server 2019 when copying files to\from a container or compiling source code

**Actual behavior**
Docker container is signficantly slower to copy files or run the compiler in a container when running in process isolation mode. Switching to HyperV isolation on Windows Server allows them to work faster

**Information**
Hi

We are running a set of servers with Docker and have found that our servers with Windows Server 2019 with Mirantis Container Runtime run the same Docker container slower than those running Windows 10 with Docker Desktop, unless we run the container with HyperV isolation on Windows Server where it approaches the same speed.

The job is triggered by Jenkins and carries out the following key steps:
- copies source code from a bind mount to inside the container
- then runs a compiler on the source code on the files in the container
- then copies the build results from the container to the bind mount again.

The file copy takes
- ~ 4 minutes on Windows Server 2019 with standard process isolation
- 60 s on Windows Server 2019 with HyperV isolation
- 40 s on Windows 10

The compiler takes
- 55 s on Windows Server 2019 with standard process isolation
- 37 s on Windows Server 2019 with HyperV isolation
- 40 s on Windows 10

I’ve also tried swapping the Docker install on each server as below
- Mirantis Container Runtime on Windows 10
- Docker Desktop on Server 2019

and the results are the same.
Windows 10 is significantly faster to copy the files and run the compiler container than Windows Server 2019.
Both servers are running on VMs on the same VM server.
Does anyone have an idea for why this would be?

Details of the servers below:
**Windows Server 2019**
- 10.0.17763.2114
- Intel Xeon Gold 5281R @ 2.10 GHz 2 sockets, 16 cores
- 16GB RAM

_Mirantis Container Runtime_
Client:
Context: default
Debug Mode: false
Plugins:
app: Docker Application (Docker Inc., v0.8.0)
cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
Containers: 2
Running: 0
Paused: 0
Stopped: 2
Images: 3
Server Version: 20.10.6
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics internal l2bridge l2tunnel nat null overlay private transparent
Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.2114)
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 16GiB
Name: DEAEC-EE-DODev2
ID: VLTY:FNY4:K4LG:62D2:UNIU:AR6W:CKSD:VIDG:DU35:XMX4:QRP5:NQ2X
Docker Root Dir: C:\ProgramData\docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Windows 10**
- 10.0.19043.1165
- Intel Xeon Gold 5281R @ 2.10 GHz 1 sockets, 4 cores
- 16GB RAM

_Docker Desktop_
Client:
Context: default
Debug Mode: false
Plugins:
buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
scan: Docker Scan (Docker Inc., v0.8.0)

Server:
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 1
Server Version: 20.10.7
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics internal l2bridge l2tunnel nat null overlay private transparent
Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
Operating System: Windows 10 Pro Version 2009 (OS Build 19043.1165)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: AEC-EE-DODev3
ID: MW3G:CEMR:FODF:RQ23:3GS2:ZVAJ:TBZX:757D:IDUW:ISRX:BJCP:7DAZ
Docker Root Dir: C:\ProgramData\docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by cwilhit** [comment]
@Eddy555 thank you for opening this issue. Does either environment have Windows Defender running? Opening MSFT internal #38520928 to track.

**Comment by Eddy555** [comment]
I don't have access to the server right now, but once I do I'll check. Generally we run Trend ApexOne, but Defender may still be running on them.

**Comment by cwilhit** [comment]
Is it feasible for you to try and repro with a test environment, except leave Trend ApexOne off, to see if that is the culprit? There are container-related optimizations [that we've documented](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers) for 3rd party antivirus vendors, and while I do not if Trend ApexOne has implemented these recommendations in their product, this seems like a good first place to investigate.

**Comment by Howard-Haiyang-Hao** [comment]
@Eddy555 Thank you for reporting the issue. I have put your repro configuration in a table, please let me know if I missed anything:
![reproconfig](https://user-images.githubusercontent.com/30302321/174683088-26ffbc16-6163-466e-acff-c99addfc745d.png)

I am trying to repro the issue in our lab. But before the repro, I would like to clarify few things.

1. I assume the repro machines were physical machines, not VMs. Am I right?
2. I would like to know the container images that you used to repro the issue.
3. The source files that you used as for copy operations

Really appreciate your helps!

**Comment by Eddy555** [comment]
Hi, sorry I've not had chance to do more testing on this due to other urgent work I've had.
In answer to your questions
1. These were on VMs
2. The container images are custom ones that we have built container some compiler programs. These are based on mcr.microsoft.com/windows/servercore:ltsc2019
3. The source files are our own internal code, consisting of around 4671 files and 828 MB.

So I guess you could replicate this with the base servercore image and copy a similar set of files to the container with the different settings.

**Comment by Howard-Haiyang-Hao** [comment]
Hi @Eddy555, 

I have taken the steps and measured on my machine, here are the results:

<img width="206" alt="image" src="https://user-images.githubusercontent.com/30302321/175241968-5ee90944-bc95-4254-a741-181f7e2a362c.png">

As I understand, that you have an anti-virus software running on your container host, that may explain why the process isolated container case is slower, because the file operations are visible to the container host OS, the anti-virus software may have scanned all these file operations. That will significantly slow down the file copy operations.  As we can see from the traces that I have collected from the container host, the process isolated container write operations were visible to the host:

![image](https://user-images.githubusercontent.com/30302321/175242940-b4e93d12-fce1-43c6-be7e-bf427aae5893.png)

I believe the compile operations slowness on the process isolated containers were also caused by the FileIO, since the anti-virus monitored all the file open operations. Plus it also consumes the CPU time for file scanning. 

Here are the details from my measurements:
![image](https://user-images.githubusercontent.com/30302321/175243810-29eb3814-9cb8-4f2f-b6b8-bb200038eaf9.png)

Please let me know if you have any questions.

Regards,
Howard.

**Comment by Howard-Haiyang-Hao** [comment]
@Eddy555, please let me know if I have answered your question. If you still have your repro machine, you can disable or add exclusion of the directory from the anti-virus scanning.  If the problem persists, please collect the perf traces and I can take a look to figure out what is causing the slower performance.

Regards,
Howard.

**Comment by Howard-Haiyang-Hao** [comment]
@Eddy555, I consider this issue is resolved. Please let me know if you are still experiencing performance issues even after disabling anti-virus scanning.

**Comment by Eddy555** [comment]
Hi, sorry for the slow response. What do you use to take measurements for the file operations?

**Comment by Howard-Haiyang-Hao** [comment]
![image](https://user-images.githubusercontent.com/30302321/176258945-2b7021ba-68e3-4ad0-8fe2-07d45352ce9b.png)

timecmd.cmd is from the following post:

https://stackoverflow.com/questions/673523/how-do-i-measure-execution-time-of-a-command-on-the-windows-command-line


@echo off
@setlocal

set start=%time%

:: Runs your command
cmd /c %*

set end=%time%
set options="tokens=1-4 delims=:.,"
for /f %options% %%a in ("%start%") do set start_h=%%a&set /a start_m=100%%b %% 100&set /a start_s=100%%c %% 100&set /a start_ms=100%%d %% 100
for /f %options% %%a in ("%end%") do set end_h=%%a&set /a end_m=100%%b %% 100&set /a end_s=100%%c %% 100&set /a end_ms=100%%d %% 100

set /a hours=%end_h%-%start_h%
set /a mins=%end_m%-%start_m%
set /a secs=%end_s%-%start_s%
set /a ms=%end_ms%-%start_ms%
if %ms% lss 0 set /a secs = %secs% - 1 & set /a ms = 100%ms%
if %secs% lss 0 set /a mins = %mins% - 1 & set /a secs = 60%secs%
if %mins% lss 0 set /a hours = %hours% - 1 & set /a mins = 60%mins%
if %hours% lss 0 set /a hours = 24%hours%
if 1%ms% lss 100 set ms=0%ms%

:: Mission accomplished
set /a totalsecs = %hours%*3600 + %mins%*60 + %secs%
echo command took %hours%:%mins%:%secs%.%ms% (%totalsecs%.%ms%s total)

**Comment by Eddy555** [comment]
Thanks, I'll give that a go when I get chance. I guess as this will take me some time to get around to doing, we can close this for now as we appear to have an understanding of the issue. Thanks again for your support and investigation.

**Comment by Howard-Haiyang-Hao** [comment]
@Eddy555, thank you for reporting the issue. Please ping this thread again if the issue persists.
