### ISSUE TITLE
Publish the windows container image for windows server 2022 (ltsc2022)

### ISSUE THREAD

**Issue by rgl** [microsoft/Windows-Containers#150]
The `windows` container image `mcr.microsoft.com/windows:ltsc2022` for Windows Server 2022 (aka ltsc2022 aka 21H1 aka 10.0.20348.169) is missing from https://mcr.microsoft.com/v2/windows/tags/list.

Why wasn't it published like `mcr.microsoft.com/windows/nanoserver:ltsc2022` and `mcr.microsoft.com/windows/servercore:ltsc2022`?

Can it be published?

**Comment by vrapolinario** [comment]
We announced back in April that moving forward the new Server image: https://techcommunity.microsoft.com/t5/containers/announcing-a-new-windows-server-container-image-preview/ba-p/2304897

**Comment by rgl** [comment]
Oh I did not notice that. Thank you for pointing it out!
