### ISSUE TITLE
Run Node js application in windows container 

### ISSUE THREAD

**Issue by arjaiswa** [microsoft/Windows-Containers#151]
Could you please provide me a windows base image for creating a docker image for the Node js application. I have tried multiple options :
mcr.microsoft.com/windows/servercore:ltsc2022
mcr.microsoft.com/windows/servercore/insider:10.0.18362.1
mcr.microsoft.com/windows/nanoserver/insider:10.0.20348.1
mcr.microsoft.com/windows/servercore:1803

I am getting below error:
 no match for platform in manifest sha256:8f756a7fd4fe963cc7dd2c3ad1597327535da8e8f55a7d1932780934efa87e04: not found

**Comment by vrapolinario** [comment]
It seems that the version of the image you're trying to pull is newer than the container host you're running. Can you please check confirm the version of the host you're running the pull?
For more information, please check: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-20H2%2Cwindows-10-20H2

**Comment by vrapolinario** [comment]
Closing this issue. Will re-open if we hear back that the issue persists.
