### ISSUE TITLE
Container fails to start if storage-opts is set to a large value with hyperv isolation

### ISSUE THREAD

**Issue by snorrk** [microsoft/Windows-Containers#152]
If Docker storage-opts is set to a value greater than 20GB, starting Windows containers on Windows Server 2022 fails with "The virtual machine or container exited unexpectedly. (0xc0370106)".

- Windows version: 10.0.20348.169
- Docker version: 20.10.6
- Container: mcr.microsoft.com/windows/servercore/iis:nanoserver:1909
- Hyper-V enabled: yes

Repro steps:

Setup
- Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
- Install-Package -Name docker -ProviderName DockerMsftProvider
- Add-WindowsFeature Hyper-V
- Restart-Computer
- (Wait for restart)

Docker steps
- docker run -it --isolation hyperv mcr.microsoft.com/windows/servercore/iis:nanoserver:1909
  - Note that the container starts without issue
- Stop-Service docker
- '{ "storage-opts" : [ "size=30G" ] }' | Out-File -Encoding ASCII -FilePath C:\ProgramData\Docker\config\daemon.json
- Start-Service docker
- docker run -it --isolation hyperv mcr.microsoft.com/windows/servercore/iis:nanoserver:1909

**Expected result:**
Container is started

**Actual result:**
docker: Error response from daemon: container 4d5ccad533be46ee607f989474a80adf35ca19560ddb68ad35a3f6d9f7612974 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by cwilhit** [comment]
@snorrk I tried to repro this and was able to do so on 1909-tagged nanoserver image. However, it does not repro for me on ltsc2022-tagged images, for neither server core or nanoserver. 1909-tagged images reached end of life several months back--are you still seeing this issue on the newest image versions?

**Comment by cwilhit** [comment]
I am going to close this issue as no repro. If we are able to get a beat on this on one of the images currently in support, we'd be happy to reopen this.
