### ISSUE TITLE
How to run a Windows container in a Windows VM on a Linux host?

### ISSUE THREAD

**Issue by thejohnfreeman** [microsoft/Windows-Containers#153]
[I'm trying to run a Windows container in a Windows VM on a Linux host with a Ryzen CPU](https://www.reddit.com/r/vmware/comments/pep2gj/how_to_run_a_windows_container_in_a_windows_vm_on/). I have tried VMs running:

- Windows 10 Pro, 20H2
- Windows 10 Pro, 21H1, build 19043.928
- Windows 11 Pro, 21H2, build 22000.168

That last one is the only [Windows Insider ISO](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso) I could find with build >= 19636 (which I think I need because that was when [nested virtualization was enabled for AMD CPUs](https://techcommunity.microsoft.com/t5/virtualization/amd-nested-virtualization-support/ba-p/1434841)).

I'm under the impression that if I can find a container image exactly matching the build number of my VM, then I can run it in Docker with "process isolation" instead of Hyper-V and avoid any difficulties associated with Hyper-V virtualization. **Please correct me if that is wrong.** Sadly, I have not been able to find such images for [`windows/nanoserver/insider`](https://mcr.microsoft.com/v2/windows/nanoserver/insider/tags/list) or [`windows/servercore/insider`](https://mcr.microsoft.com/v2/windows/servercore/insider/tags/list) or [`windows/insider`](https://mcr.microsoft.com/v2/windows/insider/tags/list).

At this point, I'm able to:

- Enable the Hyper-V and Containers Windows features in the VM
- Install Docker Desktop for Windows and get the engine running for Windows containers
- Pull a container image (e.g. `mcr.microsoft.com/windows/nanoserver:20H2-amd64`)

When I try to run the image with `docker run -it $image cmd.exe` in a Powershell running as an administrator, it eventually times out with this error:

```
docker: Error response from daemon: hcsshim::CreateComputeSystem <hex>: hcsshim: timeout waiting for notification.
```

Searching for that leads me to [this issue](https://github.com/Microsoft/hcsshim/issues/152) which is unresolved. In fact, as of this writing, the final comment says "I discovered through some trial an error that the issue only manifests itself when running Windows 10 as a virtual machine and attempting to use Windows containers", which is exactly my problem. Is this use case unsupported?

I've been searching for a single success story for what I'm trying to accomplish and haven't found any. Is what I want to do even possible?

**Comment by vrapolinario** [comment]
I'm not sure this is a supported scenario. @brasmith-ms should be able to provide clarity.

**Comment by thejohnfreeman** [comment]
I have found a solution and am writing it up now. I'll report back when it is published.

**Comment by thejohnfreeman** [comment]
The [trick](https://jfreeman.dev/blog/2021/09/01/how-to-run-a-windows-container-from-a-windows-10-virtual-machine/) is to specify process isolation in the `docker run` command (in the past I had relied on this being the default isolation mode), and to specify those arguments _before_ the image tag (putting them after results in an unhelpful error message that led me on a wild goose chase; I didn't catch my real error until I looked at the command column in `docker container ls --all`).

**Comment by vrapolinario** [comment]
Thanks for the note. I still want to make sure this is a supported scenario from @brasmith-ms
