### ISSUE TITLE
Will there be a free Win10 Container Runtime?

### ISSUE THREAD

**Issue by grochoge** [microsoft/Windows-Containers#154]
With the recent announcement that Docker Desktop will cost at least $5/month, are there any plans to make a free replacement available for development on Windows 10?

**Comment by vrapolinario** [comment]
To clarify from Docker's announcement: Docker Desktop remains free for small businesses (fewer than 250 employees AND less than $10 million in annual revenue), personal use, education, and non-commercial open source projects.

I'll let Taylor and Siddique chime in, but in my view, there are options for customers who don't want to pay for Docker Desktop, such as Moby, right?

**Comment by MarkIannucci** [comment]
There are [two](https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1140) [issues ](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1639)in the virtualization documentation repo trying to determine the answer to this question as well.

**Comment by naikrovek** [comment]
from this page (https://docs.docker.com/engine/install/binaries/) I found a link to a very vanilla Windows Docker engine download.  It does not contain `docker-compose` but otherwise it should suffice for folks that use Windows containers on Windows.

https://download.docker.com/win/static/stable/x86_64/

Note that this is *not* a link to Docker Desktop.  This is a link to the Docker Engine for Windows.  This remains free.  This gives you 4 plain `.exe` command-line tools: `docker.exe`, `dockerd.exe`, `docker-app.exe`, and `docker-buildx.exe`.  

Like with Linux, everything you do must be done at the command-line.  There is no GUI interface for these tools.

**Comment by MarkIannucci** [comment]
@naikrovek, thank you for the link to the windows binaries.  

I removed Docker Desktop from my laptop and downloaded the latest version at the link you provided.  After doing that, I was able to step through pulling and running a container after I started `dockerd.exe`.  I know the Docker Desktop installer does a bunch of windows configuring when you run through the install.

Does anyone know if simply downloading the binaries will work on a machine that hasn't previously had Docker Desktop installed on it will work?

**Comment by naikrovek** [comment]
@MarkIannucci the binaries you just tried should work fine on a "virgin" machine.  The magic that Docker Desktop provides is all Linux and GUI stuff.

**Comment by lippertmarkus** [comment]
Thanks @naikrovek! I quickly wrote it down here for anyone needing a simple guide: https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/

**Comment by slonopotamus** [comment]
I'd like to announce [Stevedore](https://github.com/slonopotamus/stevedore) project. It aims to provide a free and convenient way to use Docker on Windows (both client and server). Currently, it only supports Windows containers. Stevedore is distributed as an MSI installer.

Installation
* Download [MSI installer](https://github.com/slonopotamus/stevedore/releases/latest)
* Double-click on it
* Next-next-next
* Reboot your computer
* Profit! `docker` command is now available on your PATH and `dockerd` daemon is already running.

Update: installation via Chocolatey is now also available: https://community.chocolatey.org/packages/stevedore

**Comment by cwilhit** [comment]
Closing. For further discussion please see MicrosoftDocs/Virtualization-Documentation#186
