### ISSUE TITLE
Exception in thread "AWT-Windows"

### ISSUE THREAD

**Issue by MisterK91** [microsoft/Windows-Containers#156]
Hello together, 
I trie to containerise my Java application build on Vaadin framework using following base image:

> openjdk:11-nanoserver

For some reason I always receive following strange exception I could not really categorize, the Vaadin support told me it is probably because there are missing dependencies  in Nano Server? 

`Exception in thread "AWT-Windows" java.lang.InternalError: unsupported screen depth
        at java.desktop/sun.awt.windows.WToolkit.init(Native Method)
        at java.desktop/sun.awt.windows.WToolkit.run(WToolkit.java:293)
        at java.base/java.lang.Thread.run(Thread.java:829)`

My full docker file looks like following:

`# Set escape char for Windows build systems
# escape=`
# Windows distribution
FROM openjdk:11-nanoserver
WORKDIR /
ADD target/*.jar app.jar
EXPOSE 8080
CMD java -jar app.jar`

Would welcome your support.
Thanks

**Comment by vrapolinario** [comment]
Most likely this is not supported because (as you mentioned) the necessary components are not present in the Nano Server, given that this requires some GUI components. My recommendation is to try the Server Core or even Server images (if you're using WS2022)

**Comment by judyliu-ms** [comment]
Hi @kliebhart - checking in on this thread, were you able to make this work with Server Core or Server? If so, I will close out this issue.

**Comment by judyliu-ms** [comment]
Closing this issue under the assumption that Server Core/Server image solved the issue.
