### ISSUE TITLE
Pods fails to terminate on Windows nodes

### ISSUE THREAD

**Issue by andbess** [microsoft/Windows-Containers#157]
Hi All!
We experience the same issue in our AKS cluster as was reported in Windows-Container #106 , except we're not using fluentbit or fluentd logging agents (we only use Azure Monitor with combination of Grafana). Sporadically some the pods are not automatically terminated and we have to manually run "kubectl delete --force" to force terminate the pods. 

The error message is always the same:
`Message:      unable to remove filesystem for 5bbd9142e090352ac34b5c118a69f0b76efd1f79c35e50bb264aad0c3731664f: CreateFile C:\ProgramData\docker\containers\5bbd9142e090352ac34b5c118a69f0b76efd1f79c35e50bb264aad0c3731664f\5bbd9142e090352ac34b5c118a69f0b76efd1f79c35e50bb264aad0c3731664f-json.log: Access is denied.`

Information about AKS cluster:
Kernel version: 10.0.17763.2114
OS Image:  Windows Server 2019 Datacenter
Container runtime version: docker://20.10.6
Kubernetes version: 1.21.2

It would be greatly appreciated if anyone has  any suggestion in order to prevent this problem.

**Comment by andbess** [comment]
Update:
Could it be that Microsoft Monitoring Agent also sometime holds the container log and that's the reason that it cannot be removed?

The version of Microsoft Monitoring Agent we're using on our Windows Node:
IdentifyingNumber : {88EE688B-31C6-4B90-90DF-FBB345223F94}
Name              : Microsoft Monitoring Agent
Vendor            : Microsoft Corporation
Version           : 10.20.18053.0
Caption           : Microsoft Monitoring Agent

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.
