### ISSUE TITLE
Window Server Image for Using it in Windows Server 2019 Data center Node

### ISSUE THREAD

**Issue by arjaiswa** [microsoft/Windows-Containers#160]
Hi Team,
I am leveraging Kubernetes Windows node (Host for my container )and this provides the below version of windows.
![image](https://user-images.githubusercontent.com/76682247/134375181-c0529a33-0786-4176-9407-9de40ce1fa3c.png)

Could you please help me to use the correct window/server base image for my container as there is no supported version with the host machine (10.0.17763.2114)?

I have used Nano and server core but they have some missing dependencies. Due to this, I can not use it.

**Comment by cwilhit** [comment]
@arjaiswa there is a version of the base images that is available matching that build number. You would do:

`docker pull mcr.microsoft.com/windows/servercore:10.0.17763.2114
`

to get this image. Are you saying you were able to pull the base image successfully, but the app you wanted to put into the container does not work in these containers?

**Comment by cwilhit** [comment]
Closing due to staleness.
