### ISSUE TITLE
Running dockers as `--isolation=process` on Win10 21H1

### ISSUE THREAD

**Issue by roozbehid** [microsoft/Windows-Containers#163]
I cannot find any version of windows image to be able to run on Windows 10.0.19043.x (21H1) with "--isolation=process"

This page says you should be able to run 20H2 (?) on 21H1.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1#windows-client-host-os-compatibility

Am I missing something here?

**Comment by roozbehid** [comment]
Also to be more confused (at least on my side) what would be the case for Windows 10 21H2, is it similar to Windows 11 21H2 and can run Windows Server 2022?

**Comment by roozbehid** [comment]
Talking to myself :D it seems answer is no as build number on Windows 10 stays same so Windows 10 21H2 like Windows 10 21H! wont support inprocess.
https://github.com/microsoft/Windows-Containers/issues/117

**Comment by QuAzI** [comment]
Nothing works with W10 21H2 which is marked as LTSC

**Comment by slonopotamus** [comment]
> This page says you should be able to run 20H2 (?) on 21H1

That page lies.

**Comment by vrapolinario** [comment]
Microsoft did not release a 21H1 container image as you can see here: https://hub.docker.com/_/microsoft-windows-servercore. (This one is Server Core, but other images follow this) The latest one is ltsc2022 which is ahead of Win10. You can run LTSC2022 on Win11 with process isolation. We clarified some of this on this blog post: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487

I assigned the folks that are working on this to this thread so they can provide the latest on this.

**Comment by vrapolinario** [comment]
And as for the docs page, I will follow up with the Docs team to fix the error on the page.

**Comment by QuAzI** [comment]
@vrapolinario 
Will we have a chance to have containers for W10 21H2? We need it because downgrade to 20H2 impossible

**Comment by slonopotamus** [comment]
@QuAzI forget about that. All Windows 10 after 20H2 are a no-go WRT process-isolated containers.

**Comment by vrapolinario** [comment]
The main thing here is that while Win10 is updated, it continues to have a lower version compared to new images, but higher compared to pre-ltsc2022 images. So, AFAIK you can run earlier images (20H2, for instance) with hyper-v isolation and use the temp images I mentioned on the blog post with hyper-v isolation as well.

**Comment by vrapolinario** [comment]
The other option you have is to run a VM to host your image-specific needs. For example, run a VM with Windows Server, version 20H2 to run a 20H2 container image with process isolation.

**Comment by QuAzI** [comment]
@slonopotamus I can't. Because it is strange situation when new version have less functions. And looks like other versions will EOL soon https://docs.microsoft.com/en-us/lifecycle/products/windows-server
EOL 2004 - Dec 14, 2021
EOL 20H2 - Aug 11, 2022
So we don't have stable version for work anymore

**Comment by QuAzI** [comment]
@vrapolinario hyper-v isolation too slow. I regularly have situation when MSVS and then Docker Desktop getting stuck.

32GB RAM, i7-10510U, NVMe SSD. And it still getting stuck

![image](https://user-images.githubusercontent.com/1897605/145264009-1f6bb637-b9cc-4568-84b2-6febf78d5262.png)

**Comment by idontsov** [comment]
Same issue here.
Windows 10 version 21H2 build 19044.1466.
Unable to run a container in the "process" isolation mode: "The container operating system does not match the host operating system".
Hyper-v isolation is not an option.

**Comment by roozbehid** [comment]
Kind of sad how bad situation is managed. 
Windows 10 has a supported feature that does not run on supported Windows 10 version!

**Comment by idontsov** [comment]
Can we have an update here? Is there any estimation on when the issue will be resolved?

**Comment by slonopotamus** [comment]
This issue will never be resolved. As Microsoft said in https://github.com/microsoft/Windows-Containers/issues/117, there will be no newer container images for Windows 10.

**Comment by QuAzI** [comment]
Broken containers, broken L2TP, broken RDP, broken old Epson printers... and same story with .NET - almost removed reloading before release, broken Xamarin.Forms (MAUI now) for Linux...
meh... we must write another one OS to run .NET Core apps properly

**Comment by idontsov** [comment]
> This issue will never be resolved. As Microsoft said in #117, there will be no newer container images for Windows 10.

I missed that thread. Thank you for the hint!

**Comment by peterwishart** [comment]
I ran into this problem while checking I could switch docker desktop for nerdctl on Windows 10.
Rolling back feature updates 21H2 and 21H1 seems to be the only fix if you can't upgrade to Windows 11.

This issue isn't called out in [Windows Client host OS compatibility](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1#windows-client-host-os-compatibility), 21H2 isn't mentioned there at all.

**Comment by danzaharescu** [comment]
Hi All, I am evaluating a 21H2 build, I know it looks counter-intuitive, but on my machine, the 2004 (mcr.microsoft.com/windows/servercore:2004) looks to be working with process isolation. Hope this helps someone.
I am wondering, if I am the only to be so lucky...

**Comment by QuAzI** [comment]
@danzaharescu it is "bug" and doesn't work properly. Please check https://github.com/dotnet/dotnet-docker/issues/3324#issuecomment-989085674

**Comment by danzaharescu** [comment]
@QuAzI Looks like you are right... but what I believe, is that this invented restriction should have never been in place, which is now being proved - the container that shouldn't have worked, works.  The format of the executable, paths, registry, etc is not changed from 20H2 to 21H2 for example (logic can be extended as far as 1803 or lower maybe). My executable from the container loads the dll from the container, I do not understand.... probably there might be some corner cases or subtle problems, but I am almost sure those might have been addressable with reasonable efforts.

**Comment by cwilhit** [comment]
We're working on publishing some additional documentation on aka.ms/containers to provide guidance related to this thread. Please stay tuned, we will ping back when the docs get published.

**Comment by slonopotamus** [comment]
I want to note that there's an open https://github.com/microsoft/Windows-Containers/issues/197 about process isolation not working properly on Windows 11. Given that 20H2 is almost EOL and neither 21H1/21H2 are able to use process isolation at all, the only option for development currently is Windows 2019 LTSC, which cannot be easily bought by individual persons.

**Comment by brasmith-ms** [comment]
Hi folks, I have updated our [documentation ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) to address the concerns mentioned here.

@slonopotamus yes thank you for the note. This is an issue that we're actively investigating and working to solve. As I mentioned in the docs, cross-version compatibility in Windows is an incredibly hard problem to solve, especially when trying to maintain our promise for security. We're working hard to enable this feature for folks, and we greatly appreciate your patience so far.

Please don't hesitate to reach out to me with any additional concerns. I'm available in the K8s slack channel "Brandon Smith (MS)"
