### ISSUE TITLE
Switching user within a container

### ISSUE THREAD

**Issue by dave07y** [microsoft/Windows-Containers#166]
My requirement is to protect a directory and its contents from being accessed by any programs/scripts other than allowed ones within a Windows container. This means that the directory contents should be protected against read, write, and execute operations.

I tried to implement this by Process restriction. This includes using policies to “Run only specified Windows applications”, “Don’t run specified Windows applications”, “Prevent access to command prompt”. But I was not able to achieve the desired results.

So, I tried applying user based restrictions to the directory and its contents. This means that permissions would be given only to a specific user say “Worker” user. The default user when a container is spun up would be a “Dummy” user. From “Dummy” user, I would like to trigger a specific process as “Worker” user. I have tried the following:

From cmd: **runas** /user:_Worker_ "program"
From powershell: **Start-Process** "program" -Credential  $_credential_  where _credential_ contains “Worker” user credential.

I had tried to use the above with batch files, powershell scripts and AutoIt executables. 
I had also enabled FastUserSwitching in the containers.
I had also tried both RUN_LOGON_NOPROFILE and RUN_LOGON_PROFILE options of Autoit **runas** function.

I could not successfully trigger the process or see the output of the triggered process. Im not sure where the failure occurs.

I had tried with the below docker images:

mcr.microsoft.com/windows/servercore/insider: 10.0.19035.1
mcr.microsoft.com/windows:20H2
mcr.microsoft.com/windows:1809
mcr.microsoft.com/windows/servercore:ltsc2019

I would like to know if there is support for User Switching in any of the available version of docker images.
If not, is there a plan to support this feature in an upcoming version ?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
Hey @dave07y apologies for the wait. Is this still an issue you're facing?
