### ISSUE TITLE
Let's Encrypt root (DST Root CA X3) isn't in the base image

### ISSUE THREAD

**Issue by scottdcarson** [microsoft/Windows-Containers#169]
This specifically refers to mcr.microsoft.com/windows/servercore:ltsc2019, although it also applies to nanoserver images.

Like many, we were bit two weeks ago by the expiration of the Let's Encrypt root certificate.  We worked around it at the time using certoc to install the root certificate manually in (all) our Dockerfiles.  But on further investigation, there's more information.

Question/Issue 1: are we to expect that root certificates are kept up to date in the Windows base images?  They appear to be for (what was once) more "mainstream" certificates from Entrust, Digicert, etc., but Let's Encrypt didn't make that cut.  Is this is an issue/process to fix?

Question/Bug/Issue 2: we use an outbound proxy, and the system proxy is configured accordingly.  Wiresharking the container, we see everything go through the proxy normally *except* the http requests to ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab and  apps.identrust.com/roots/dstrootcax3.p7c from the Microsoft-CryptoAPI, which would have been where it updated the Let's Encrypt root.  That attempted a direct connection, which clearly failed.

Realizing that Issue 2 is more of a Windows issue than a docker image issue, wouldn't that make it more compelling to settle Issue 1 by keeping the image CAs up to date?   Otherwise every Dockerfile writer will have to repeat the same process of certoc'ing the root CAs as they expire in the future.

**Comment by scottdcarson** [comment]
As one further piece of information - the wininet stack itself doesn't seem to be in the nanoserver base image; thus, AFAICT it's not even possible to configure the CryptoAPI to update certificates in nanoserver.  So while this problem is solvable (albeit with a certain resorting to undocumented trickery) in windowsservercore, it's simply not solvable at all with nanoserver behind a proxy as nanoserver stands today.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by SSvilen** [comment]
@scottdcarson 

Regarding the second question - take a look at [this article](https://docs.microsoft.com/en-us/troubleshoot/developer/browsers/connectivity-navigation/no-internet-connectivity-internet-explorer-not-started). 
We solved the problem by exporting that key from a working server and importing it in our Docker images. 
Not a clean solution, but  ¯\\_(ツ)_/¯.

**Comment by fady-azmy-msft** [comment]
Hey @scottdcarson re: your first question, what are you referring to by up to date? And can you share what are you trying to accomplish by having access to the Let's Encrypt root certificate?
