### ISSUE TITLE
No available tag for mcr.microsoft.com/windows:21H1

### ISSUE THREAD

**Issue by emericcolombe** [microsoft/Windows-Containers#172]
When running a container host on windows 10 21H1 (not server), there is no available image to run containers with a matching version.
The only available previews are for server, nanoserver and servercore

**Comment by vrapolinario** [comment]
Hi, We discussed this issue on this blog post: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487 The images for WS2022 are still available for pull. You can also pull earlier images and spin up containers with hyper-v isolation.
