### ISSUE TITLE
 Base Filtering Engine (BFE)

### ISSUE THREAD

**Issue by rrgadeev** [microsoft/Windows-Containers#173]
The bfe service is disabled by default, how do I enable it in docker?
This is necessary for testing.

**Comment by judyliu-ms** [comment]
Hi @rgadeevm, to help our team understand your issue, would you be able to provide more details on your use case: 
1. You mentioned you are using the BFE service for testing, can you expand on how this service will be used for testing? 
2. Which version of Windows Server are you running on your host? What version are you running for your image?  
3. What environment are you running in? (standalone, AKS etc.)

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@judyliu-ms, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Closing due to staleness. @rgadeev if you can provide the details requested by Judy we can open this back up.

**Comment by rrmistry** [comment]
Our use case is: we have a legacy 3rd party vendor software that runs on Windows. We are attempting to modernize this application using Windows Containers.

The problem is this vendor software has a hardcoded check on startup for Windows Firewall Rules that it attempts to check and open for its use if closed. Since the `BFE` service is disabled by default in Windows Containers, the firewall rule check fails, and the vendor software comes to a stop.

This is the error as of the image: `mcr.microsoft.com/windows:10.0.17763.973`

```ps
PS C:\> Get-Service -Name "BFE" | Start-Service
Start-Service : Service 'Base Filtering Engine (BFE)' cannot be started due to the following error: Cannot start service BFE on computer '.'. 
At line:1 char:27
+ Get-Service -Name "BFE" | Start-Service
+                           ~~~~~~~~~~~~~ 
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\>  
```

This is a huge show stopper for us so any advise to unblock would be greatly appreciated!

**Comment by rrmistry** [comment]
Hi @Judyliu-ms, @cwilhit,

Is it possible to discuss this further in a formal capacity?

We want to assess the Windows Container product team's long-term vision for these services, the underlying reason for these services being disabled, and if there are any suggested options or workarounds for customers within Windows Container ecosystem.

Any insight, advise, or understanding would be greatly appreciated! 🙏🙏🙏

Thank you for your ongoing efforts to make Windows Containers better! 

CC: @msuthar09

**Comment by wizpresso-steve-cy-fan** [comment]
@vrapolinario We also met the same issue @rrmistry mentioned, is it good to re-open this?

**Comment by rrmistry** [comment]
@wizpresso-steve-cy-fan , let me know if you are interested in collaborating to brainstorm ideas.

For our use case, 1 year down the line, we had to abandon Windows Containers altogether. But solving this is still very much needed.
