### ISSUE TITLE
Memory leak on svchost.exe

### ISSUE THREAD

**Issue by zhiweiv** [microsoft/Windows-Containers#176]
We observed obvious memory consumption after upgrade AKS Windows node pools. The memory was used by svchost.exe in containers. I deployed this yaml to test
```
apiVersion: v1
kind: Pod
metadata:
  name: memtest
spec:
  containers:
  - name: test
    image:  mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["PowerShell", "while($true) { sleep 999 }"]
  nodeSelector:
    agentpool: memtst
```
Output from **kubectl exec memtest -- tasklist | findstr svchost**, you can see memory of every svchost.exe are increasing.
```
Day 1
svchost.exe                   8996 Services                  33     10,068 K
svchost.exe                   3520 Services                  33      8,216 K
svchost.exe                   3492 Services                  33     23,972 K
svchost.exe                   8216 Services                  33      9,088 K
svchost.exe                   8668 Services                  33     14,560 K
svchost.exe                   1920 Services                  33     18,780 K
svchost.exe                   6640 Services                  33      5,772 K
svchost.exe                   5132 Services                  33     22,556 K
svchost.exe                   4016 Services                  33      6,488 K

Day 2
svchost.exe                   8996 Services                  33     18,928 K
svchost.exe                   3520 Services                  33     16,016 K
svchost.exe                   3492 Services                  33     65,016 K
svchost.exe                   8216 Services                  33     16,844 K
svchost.exe                   8668 Services                  33     21,720 K
svchost.exe                   1920 Services                  33     44,668 K
svchost.exe                   6640 Services                  33     11,680 K
svchost.exe                   5132 Services                  33     49,596 K
svchost.exe                   4016 Services                  33     13,532 K

Day 3
svchost.exe                   8996 Services                  33     19,088 K
svchost.exe                   3520 Services                  33     16,132 K
svchost.exe                   3492 Services                  33     66,976 K
svchost.exe                   8216 Services                  33     16,844 K
svchost.exe                   8668 Services                  33     21,880 K
svchost.exe                   1920 Services                  33     44,800 K
svchost.exe                   6640 Services                  33     11,680 K
svchost.exe                   5132 Services                  33     49,512 K
svchost.exe                   4016 Services                  33     13,596 K

Day 4
svchost.exe                   8996 Services                  33     19,360 K
svchost.exe                   3520 Services                  33     16,360 K
svchost.exe                   3492 Services                  33     65,672 K
svchost.exe                   8216 Services                  33     16,856 K
svchost.exe                   8668 Services                  33     21,852 K
svchost.exe                   1920 Services                  33     44,980 K
svchost.exe                   6640 Services                  33     11,692 K
svchost.exe                   5132 Services                  33     51,428 K
svchost.exe                   4016 Services                  33     13,640 K
```

Output of a pod after running 23 days
```
svchost.exe                  44488 Services                  78     10,572 K
svchost.exe                  44512 Services                  78     44,052 K
svchost.exe                  44584 Services                  78     41,668 K
svchost.exe                  44708 Services                  78      7,608 K
svchost.exe                  44804 Services                  78     12,372 K
svchost.exe                  44956 Services                  78     21,728 K
svchost.exe                  44040 Services                  78      6,136 K
svchost.exe                  44192 Services                  78     81,028 K
svchost.exe                  44364 Services                  78      3,020 K
```

We are using AKS 1.21.1, Windows version: **AKSWindows-2019-17763.2213.210922**

**Comment by zhiweiv** [comment]
@AbelHu @mainred

**Comment by AbelHu** [comment]
cc @kevpar

**Comment by kevpar** [comment]
Can you confirm if this is running Docker or containerd as the runtime?

**Comment by zhiweiv** [comment]
It occurs in both Docker and Containerd. I tested with latest AKSWindows-2019-17763.2237.211014, it still occur.

A fresh new Windows node with 30 pods(two containers per pod), after 24 hours there are 650 svchost processes take total 10GB memory.

**Comment by yuzsun** [comment]
Day 1
svchost.exe                  10496 Services                  15      8,112 K
svchost.exe                   7888 Services                  15      9,928 K
svchost.exe                   1320 Services                  15     25,576 K
svchost.exe                   9992 Services                  15      8,968 K
svchost.exe                   6424 Services                  15     14,524 K
svchost.exe                   8772 Services                  15     18,464 K
svchost.exe                  10076 Services                  15      5,740 K
svchost.exe                  11684 Services                  15     23,476 K
svchost.exe                   4208 Services                  15      6,428 K

Day 2
svchost.exe                  10496 Services                  15     18,168 K
svchost.exe                   7888 Services                  15     20,700 K
svchost.exe                   1320 Services                  15     67,884 K
svchost.exe                   9992 Services                  15     18,804 K
svchost.exe                   6424 Services                  15     24,012 K
svchost.exe                   8772 Services                  15     46,656 K
svchost.exe                  10076 Services                  15     13,940 K
svchost.exe                  11684 Services                  15     52,836 K
svchost.exe                   4208 Services                  15     15,792 K

Day 3
svchost.exe                  10496 Services                  15     18,548 K
svchost.exe                   7888 Services                  15     20,892 K
svchost.exe                   1320 Services                  15     68,824 K
svchost.exe                   9992 Services                  15     18,816 K
svchost.exe                   6424 Services                  15     24,028 K
svchost.exe                   8772 Services                  15     46,784 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     53,572 K
svchost.exe                   4208 Services                  15     15,836 K

Day 4
svchost.exe                  10496 Services                  15     18,768 K
svchost.exe                   7888 Services                  15     21,072 K
svchost.exe                   1320 Services                  15     67,796 K
svchost.exe                   9992 Services                  15     18,772 K
svchost.exe                   6424 Services                  15     24,280 K
svchost.exe                   8772 Services                  15     47,056 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     55,616 K
svchost.exe                   4208 Services                  15     15,856 K

Day 5
svchost.exe                  10496 Services                  15     19,172 K
svchost.exe                   7888 Services                  15     21,248 K
svchost.exe                   1320 Services                  15     68,928 K
svchost.exe                   9992 Services                  15     18,772 K
svchost.exe                   6424 Services                  15     23,856 K
svchost.exe                   8772 Services                  15     47,236 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     54,392 K
svchost.exe                   4208 Services                  15     15,856 K

Day 8
svchost.exe                  10496 Services                  15     22,932 K
svchost.exe                   7888 Services                  15     21,852 K
svchost.exe                   1320 Services                  15     69,128 K
svchost.exe                   9992 Services                  15     18,900 K
svchost.exe                   6424 Services                  15     24,440 K
svchost.exe                   8772 Services                  15     47,160 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     57,332 K
svchost.exe                   4208 Services                  15     15,856 K

Day 9
svchost.exe                  10496 Services                  15     26,152 K
svchost.exe                   7888 Services                  15     22,092 K
svchost.exe                   1320 Services                  15     67,696 K
svchost.exe                   9992 Services                  15     18,796 K
svchost.exe                   6424 Services                  15     24,292 K
svchost.exe                   8772 Services                  15     47,268 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     57,484 K
svchost.exe                   4208 Services                  15     15,856 K

Day 11
svchost.exe                  10496 Services                  15     28,388 K
svchost.exe                   7888 Services                  15     22,228 K
svchost.exe                   1320 Services                  15     69,388 K
svchost.exe                   9992 Services                  15     18,832 K
svchost.exe                   6424 Services                  15     25,436 K
svchost.exe                   8772 Services                  15     47,340 K
svchost.exe                  10076 Services                  15     13,928 K
svchost.exe                  11684 Services                  15     57,940 K
svchost.exe                   4208 Services                  15     15,856 K

**Comment by zhiweiv** [comment]
We decide to increase Windows node memory as solution.

**Comment by andyzhangx** [comment]
> We decide to increase Windows node memory as solution.

@zhiweiv you mean use a larger Windows vm size? what's the new vm size?

**Comment by zhiweiv** [comment]
We switched to E4_V4 from E2_V4 in dev/test cluster. It is only affect our dev/test because it has much bigger pod density than prod env.

You can find more detail in SR #2111170060000728.

**Comment by zhiweiv** [comment]
It seems get worse, a dumb pod without any activity after 23 days, svchost takes 438MB total.
```
svchost.exe 21740 162,008 K RpcEptMapper, RpcSs
svchost.exe 75400  25,600 K
svchost.exe 80280  71,548 K gpsvc, iphlpsvc, ProfSvc, Schedule, SENS, UserManager, UsoSvc, Winmgmt
svchost.exe 83680  19,156 K
svchost.exe 73088  25,132 K
svchost.exe 54052  49,328 K CryptSvc, Dnscache, LanmanWorkstation, WinR
svchost.exe 85128  13,980 K
svchost.exe 85144  77,156 K DiagTrack
svchost.exe 85216  16,280 K
```
