### ISSUE TITLE
Outgoing network connection not working for Windows Server 2022, process isolation

### ISSUE THREAD

**Issue by tfenster** [microsoft/Windows-Containers#181]
When I create a container for the servercore:ltsc2022 image and try to download something from GitHub (just as an example), it only works for hyperv isolation

## Repro steps:
1. Create an Azure VM (Windows Server 2022 Datacenter Server Core - Gen1, Size Standard_D4s_v5)
2. Run the following script to get the prereqs, the latest Docker version and restart the computer
```
$ProgressPreference = 'SilentlyContinue'  
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V, Containers -All -NoRestart
Invoke-WebRequest -UseBasicParsing -Uri https://download.docker.com/win/static/stable/x86_64/docker-20.10.11.zip -OutFile docker-20.10.11.zip
Expand-Archive .\docker-20.10.11.zip -DestinationPath $env:ProgramFiles
$path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
[Environment]::SetEnvironmentVariable("Path", "$path;$env:ProgramFiles\docker", "Machine")
& 'C:\Program Files\docker\dockerd.exe' --register-service
Restart-Computer -Force
```
3. Add defender exceptions to make sure it isn't interfering and get the needed image
```
Add-MpPreference -ExclusionPath 'C:\Program Files\docker\'
Add-MpPreference -ExclusionPath 'C:\ProgramData\docker\'
docker pull mcr.microsoft.com/windows/servercore:ltsc2022
```
4. Run the container with process isolation and try to download something from GitHub --> **doesn't work**
```
docker run -ti mcr.microsoft.com/windows/servercore:ltsc2022 powershell
PS C:\> curl.exe -o traefik.zip -LO https://github.com/traefik/traefik/releases/download/v2.5.4/traefik_v2.5.4_windows_amd64.zip -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 140.82.121.4...
* TCP_NODELAY set
* Connected to github.com (140.82.121.4) port 443 (#0)
* schannel: SSL/TLS connection with github.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 155 bytes...
* schannel: sent initial handshake data: sent 155 bytes
* schannel: SSL/TLS connection with github.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
```
5. Run the exact same thing in hyperv isolation --> **works**
```
docker run -ti --isolation hyperv mcr.microsoft.com/windows/servercore:ltsc2022 powershell
PS C:\> curl.exe -o traefik.zip -LO https://github.com/traefik/traefik/releases/download/v2.5.4/traefik_v2.5.4_windows_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0    638      0  0:00:01 --:--:--  0:00:01  1945
100 25.2M  100 25.2M    0     0  25.2M      0  0:00:01  0:00:01 --:--:-- 49.7M
```

I also tried installing through the `DockerMsftProvider` as follows, which gives me Docker 20.10.7, but with the same result:
```
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider
```

## Version infos
`docker info` when installed through direct download
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 20.10.11
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Datacenter Version 2009 (OS Build 20348.350)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: bug-repro7
 ID: OLQP:L24P:NV2P:WVDI:IS2D:TJSZ:AB5F:JZL3:VSIK:WGNV:M3N6:J2RA
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

`docker info` when installed through the `DockerMsftProvider`
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Datacenter Version 2009 (OS Build 20348.350)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: bug-repro7
 ID: OLQP:L24P:NV2P:WVDI:IS2D:TJSZ:AB5F:JZL3:VSIK:WGNV:M3N6:J2RA
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Windows Server version info:
```
(Get-WMIObject win32_operatingsystem).Version
10.0.20348
```

**Comment by wagnerscastle** [comment]
You may want to try this [workaround](https://github.com/microsoft/Windows-Containers/issues/145).  Disabling RSC fixed this issue for our on-premise server 2022.

**Comment by daschott** [comment]
Did you notice any other issues with the process-isolated containers? 
For example:
1. Can 2 process-isolated containers connect to each other? 
2. Can you connect to the Internet and view the content of webpage like bing.com from process-isolated container? It seems you are downloading a larger file (~25.2 MB) - is all Internet access broken or large file download only?
3. Have you tried the workaround suggested in the comments to disable RSC?

**Comment by tfenster** [comment]
> Did you notice any other issues with the process-isolated containers? For example:
> 
> 1. Can 2 process-isolated containers connect to each other?

Yes, that works. I have tried ping and http, both work

> 2. Can you connect to the Internet and view the content of webpage like bing.com from process-isolated container? It seems you are downloading a larger file (~25.2 MB) - is all Internet access broken or large file download only?

`Invoke-WebRequest -UseBasicParsing -Uri https://www.bing.com` --> works
`Invoke-WebRequest -UseBasicParsing -Uri https://www.github.com` --> doesn't work
`Invoke-WebRequest -UseBasicParsing -Uri https://www.microsoft.com` --> works
`Invoke-WebRequest -UseBasicParsing -Uri https://www.google.com` --> doesn't work

> 3. Have you tried the workaround suggested in the comments to disable RSC?

Thanks for the reminder. I tried and can confirm that it works. Both larger files and the failed Invoke-WebRequests work after disabling RSC. IMHO this is still a bug, so I would keep this open?

**Comment by doctorpangloss** [comment]
Another one bites the dust due to https://github.com/microsoft/Windows-Containers/issues/145

Not sure why nobody at Microsoft is interested in fixing this issue.

**Comment by daschott** [comment]
@tfenster Yes, keep the issue open. There have been multiple fixes made in Server 2022 that we hoped would resolve the container performance issues you are facing, but unfortunately it's clear this is still active and needs to be investigated further. I am raising this issue with the owners of relevant areas for comment...

**Comment by cwilhit** [comment]
Hi @tfenster, I tried to repro this in an Azure VM just now (granted, this is on the March, 2022 image - 10.0.20348.587) and it did not repro for me. I could download the file just fine for both isolation modes. We tried to repro this on a lab machine and were not successful either. Have you still been seeing this behavior?

**Comment by tfenster** [comment]
@cwilhit confirmed, now it works for me! Thanks 😊
