### ISSUE TITLE
Support for NTFS/ReFS Deduplication

### ISSUE THREAD

**Issue by BorMor** [microsoft/Windows-Containers#185]
I want to mount the deduplicated volume to the container but the container can't read deduplicated data.
Is it even possible or maybe you have plans for implementing deduplication support?

I installed Windows Server 2022 with docker

```
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider
docker pull mcr.microsoft.com/windows/server:ltsc2022
```
Then enable deduplication feature
I made drive O: with deduplication and put a 2Mb text file on it.
```
Start-DedupJob -Volume "O:" -Type Optimization -Wait
```
I have checked the text file, I able to open it with Notepad

Then I run the container in process isolation mode
```
docker run -it --rm -v O:\:C:\o mcr.microsoft.com/windows/server:ltsc2022 powershell
Get-Content C:\o\sample-2mb-text-file.txt
```
and get error
```
Get-Content: The file or directory is corrupted and unreadable.
At line:1 char:1
+ Get-Content sample-2mb-text-file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\o\sample-2mb-text-file.txt:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by BorMor** [comment]
any updates?

**Comment by cwilhit** [comment]
Hi @BorMor, I'm  assigning this issue to myself and following up with my dev team internally. I'll get back to you once I have an answer.

**Comment by cwilhit** [comment]
Preliminary thinking is this should work for process-isolated containers correctly--but it's not--so tagging as a bug and we will have to investigate further. MSFT-internal 38264011 opened for reference.

**Comment by cwilhit** [comment]
After a little more digging, it turns out dedup not being supported is a known gap (albeit not documented till now) that we haven't implemented support for in the OS. We will need to prioritize the work to go plug the set of APIs to bring up support for this feature. @BorMor can you provide more context about what scenario you're trying to achieve? Is the goal to map in a general purpose file share into these containers?

**Comment by BorMor** [comment]
@cwilhit I just want to use data from deduplicated directory inside container, also will be nice to use deduplication for container volumes

**Comment by ghost** [comment]
This issue has been open for 90 days with no updates.
@cwilhit, please provide an update or close this issue.

**Comment by mllab-nl** [comment]
Any update on the issue ?

**Comment by fady-azmy-msft** [comment]
I'm taking this issue over, and got some insight on this. This a known feature gap, not a bug - deduplication is not supported on container volumes.

**Comment by fady-azmy-msft** [comment]
To make sure we consider this in the future, can you share how important this feature is for you? I'll highlight this to the right teams.
