### ISSUE TITLE
Request: Easy way to install containerd on Windows nodes (similar to DockerMsftProvider)

### ISSUE THREAD

**Issue by marosset** [microsoft/Windows-Containers#186]
We should have a straight-forward way to install containerd on Windows machines.

Some possible options include:
- OneGet provider (similar to DockerMsftProvider)
- Create a winget target (requires a .exe or .msi installer)

**Comment by jsturtevant** [comment]
related to https://github.com/microsoft/Windows-Containers/issues/101#issue-830412007

/cc @aravindhp @brasmith-ms

**Comment by aravindhp** [comment]
Thank you @marosset @jsturtevant 

/cc @selansen @anandnatraj

**Comment by TBBle** [comment]
[`DockerMsftProvider` is going away in September 2022](https://www.mirantis.com/blog/windows-server-container-users-mirantis-is-here-to-support-you/), so we might also need this for Docker Engine too. And probably next year, Docker Engine will depend on containerd on Windows as well.

Although whatever packaging is done for Docker Engine on Windows Server would possibly bundle a local containerd.

**Comment by lippertmarkus** [comment]
I created https://github.com/lippertmarkus/containerd-installer and hope that may help you with creating a winget target

**Comment by brasmith-ms** [comment]
@TBBle since Mirantis has the rights & ownership of Docker Engine Enterprise (Mirantis container runtime), they will have their own installation script for the runtime - hence why we are deprecating the API. [Install MCR on Windows Servers](https://docs.mirantis.com/mcr/20.10/install/mcr-windows.html). 

That being said, we're considering options for doing something similar with Moby / Docker Engine like you mention.

@lippertmarkus That is fantastic, and incredibly helpful! Thank you! I will definitely try this out.

**Comment by TBBle** [comment]
It's slightly tangential, but there's a project to install Moby and a few related tools at https://github.com/slonopotamus/stevedore. This is only for Windows containers, so doesn't do any of the Hyper-V or WSL2 setup used by Docker Desktop to support Linux Containers, but it's equivalent to `DockerMsftProvider` if you don't require support from Mirantis or any Docker Engine Enterprise-specific features.

It's an MSI, so a winget target would be quite feasible.

**Comment by brasmith-ms** [comment]
Thanks for the additional info @TBBle, I'll look into that and see what we can target for winget

**Comment by slonopotamus** [comment]
> It's slightly tangential, but there's a project to install Moby and a few related tools at https://github.com/slonopotamus/stevedore. This is only for Windows containers, so doesn't do any of the Hyper-V or WSL2 setup used by Docker Desktop to support Linux Containers, but it's equivalent to DockerMsftProvider if you don't require support from Mirantis or any Docker Engine Enterprise-specific features.
> 
> It's an MSI, so a winget target would be quite feasible.

Things have changed a bit since then.

1. Stevedore now can be installed via WinGet by simple `winget install stevedore`
2. Stevedore added support for Linux containers via WSL2 (for obvious reasons, this is not supported on Windows Server due to lack of WSL2)

**Comment by brasmith-ms** [comment]
Just updating this thread, I think most of the folks involved here already know about this, but here is the documentation we have for installing containerd on Windows server with some links to useful projects: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=containerd#windows-server-1

There are more discussions ongoing to improve this, but for now I will close this issue until we have something more concrete.

**Comment by codefox42** [comment]
The documentation link has slightly changed: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=containerd#windows-server-2
