### ISSUE TITLE
Printers don't work inside container

### ISSUE THREAD

**Issue by arst** [microsoft/Windows-Containers#187]
Windows version: 10.0.19044 Build 19044
Docker version: 20.10.8
Container: mcr.microsoft.com/windows:1809, mcr.microsoft.com/windows:1903, mcr.microsoft.com/windows:20H2
Hyper-V enabled: yes
Repro steps:
Run simple printing script:
$sourcetxtfile = 'c:\1.txt'
$destPDFfile = 'c:\1.pdf'
Add-Type -AssemblyName System.Drawing
$txtToPDF = New-Object System.Drawing.Printing.PrintDocument
$txtToPDF.DocumentName = $sourcetxtfile
$txtToPDF.PrinterSettings = New-Object System.Drawing.Printing.PrinterSettings
$txtToPDF.PrinterSettings.PrinterName = 'Microsoft Print to PDF'
$txtToPDF.PrinterSettings.PrintToFile = $true
$txtToPDF.PrinterSettings.PrintFileName = $destPDFfile
$txtToPDF.Print()

Setup

Create file 1.txt on C:\
docker run -it -v c:\\:c:\ mcr.microsoft.com/windows:1809 powershell
run script
Get-WinEvent -FilterHashTable @{ LogName = "Microsoft-Windows-PrintService/Admin"; }

Actual result:
Exception calling "Print" with "0" argument(s): "Settings to access printer 'Microsoft Print to PDF' are not valid."

There are also some events:
  370 Error            The print spooler failed to regenerate the printer driver information for driver Microsoft enhanced Point and Print compatibility driver for environment Windows x64. Win32 system error code 87 (0x57). This can occur after an operating system upgrade or because of data loss on the hard drive.
12/17/2021 1:59:48 PM          215 Error            Installing printer driver Microsoft enhanced Point and Print compatibility driver failed, error code 0x490, HRESULT 0x80070057. See the event user data for context information.

**Comment by judyliu-ms** [comment]
@arst Have you tried the following steps: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/print-spooler 

Let me know if this works for you!

**Comment by arst** [comment]
@judyliu-ms Yes, I've tried top stop/start host spooler, reboot host machine, unfortunately, nothing helped. 
I think that this is the same problem that was described here: https://github.com/moby/moby/issues/37124.

**Comment by cwilhit** [comment]
transferring to @msjingli who has been looking into print-related support for Windows containers.

**Comment by msjingli** [comment]
@arst It looks like when the host is patched with an earlier CU than the binaries within the container base image. Can you please double check if your host has the latest patch? Thanks.

**Comment by msjingli** [comment]
@arst I am going to close this issue for now. Please feel free to activate it if you see it again. Thanks!

**Comment by yuan-shih-seagull-com** [comment]
Hello, 
The issue still exists in the latest of windows 2019 and 2022 ltsc server images (with Process Isolation).
"Microsoft Print to PDF" printer appears in the result of Get-Printer cmdlet, but System.Drawing.Printing.PrinterSettings.Valid is false.

According to the code, it queries DeviceCapabilities of the printer.
https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Printing/PrinterSettings.cs,303

Also, in our test, the Win32 API OpenPrinter and GetPrinter succeeded but DocumentProperties and DeviceCapabilities failed.
Thanks.
