### ISSUE TITLE
Microsoft is not a verified publisher on Docker Hub

### ISSUE THREAD

**Issue by cowlinator** [microsoft/Windows-Containers#188]
Microsoft is not a verified publisher on Docker Hub.

Please verify yourselves.

**Comment by cwilhit** [comment]
Thanks for bringing this to our attention. We're actively working with the folks at Docker Hub on getting this resolved. I'll leave this issue open until we have the Windows base image repos confirmed as verified publisher.

**Comment by cwilhit** [comment]
Update: we're still working on resolving this issue. There was a backend change in Docker Hub that impacted us and it's taking a few weeks to resolve.

**Comment by juss-wes** [comment]
Any updates?  I was very surprised to see Microsoft as not verified.  My company would like to lock down all but verified packages for use in the Docker Hub configuration, but that would block the use of Microsoft base images.

**Comment by davidbarrowsatasos** [comment]
Hi, any update on when this issue may be resolved?  We have training materials for Docker, which use Microsoft images, and which refer to MS being a verified publisher.  Thanks

**Comment by SteveLasker** [comment]
Adding @justincormack from Docker on the changes.

**Comment by SteveLasker** [comment]
@davidbarrowsatasos, as much as we'd like to see the Docker Hub issues get resolved, and we continue to work with Docker, Microsoft now offers a browsing experience for the [Microsoft Artifact Registry](https://mcr.microsoft.com/), with more info here: [General availability: New portal experience for Microsoft Artifact Registry](https://azure.microsoft.com/updates/general-availability-new-portal-experience-for-microsoft-artifact-registry/)

@juss-wes, as you might have noticed, while we provide the catalog list on Docker Hub, all the `pull` urls are actually from microsoft.com, so you could configure your rules to limit to verified vendors, using the domains.

Ultimately, you should likely lock down your source images to those signed by the vendors you trust. We've started signing artifacts in MAR with [Notary v2](https://github.com/notaryproject/notaryproject). We're not quite ready to mass announce MAR signing, just yet. To get a sense of the signing experience: [Verifying From Microsoft Artifact Registry](https://github.com/SteveLasker/Presentations/blob/master/demo-scripts/notaryv2/notation-verify-mcr.md)


Here's two posts I'd suggest:

- [OCI Blog Post: Consuming Public Content](https://opencontainers.org/posts/blog/2020-10-30-consuming-public-content/)
- [Cryptographic Signing for Containers](https://aws.amazon.com/blogs/containers/cryptographic-signing-for-containers/) - yes, it's an AWS post, and credit due for great content. AWS are co-maintainers of Notary v2

**Comment by davidbarrowsatasos** [comment]
> 

@SteveLasker thanks for your reply, I'll update our training materials with a link to this info.

**Comment by fady-azmy-msft** [comment]
Closing this issue for now, as we continue to work with Docker to get this resolved.

**Comment by slonopotamus** [comment]
I thought issues work differently. They are closed when they are resolved.
