### ISSUE TITLE
Networking - Enable DSR mode in RS5 LTSC builds

### ISSUE THREAD

**Issue by mkostersitz** [microsoft/Windows-Containers#19]
Servicing is in progress.

**Comment by immuzz** [comment]
cc: @daschott

**Comment by daschott** [comment]
Assuming there are no unexpected showstoppers (regressions, etc.) in the cumulative update that ships, this is tentatively scheduled to be included in the August 8C cumulative update. 

That being said, for K8s scenarios, there are version checks in kube-proxy to disable this feature on RS5 which still need to be addressed.

This has already been done in hcsshim: https://github.com/microsoft/hcsshim/pull/848, last step is reflecting this in kube-proxy

**Comment by daschott** [comment]
The kube-proxy changes can be tracked here: https://github.com/kubernetes/kubernetes/pull/93080#pullrequestreview-449420461

**Comment by mkostersitz** [comment]
DSR is now available in Windows Server 2019 with the 8B update installed. Note we have discovered and fixed a regression which can cause HNS policies not re-hydrate correctly upon restarting the service. The fix for that will be available in the 11B update in November
