### ISSUE TITLE
Is there a way to expose ports from process isolated containers?

### ISSUE THREAD

**Issue by L1ghtman2k** [microsoft/Windows-Containers#190]
I am planning to run a web app. The requirement is to have process isolated containers. Is there a way to publish ports for `--isolation=process?`, so it is accessible outside of the docker host?
Simply running `docker run -p 8000:8000 --isolation process` does not expose it to the outside world

**Comment by cwilhit** [comment]
Hi, that's something you'd need to configure in your host's firewall. That's not a command you issue through docker, rather have a look at [this example](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps) (example 7 on that page) for how to do the next step.

**Comment by L1ghtman2k** [comment]
Thanks, this worked. I wish it was documented more, I can't seem to find it anywhere, especially given that ports don't show up on tools like TCP view, this becomes very hard to debug. 

Tested on windows datacenter 2022.

If you are trying this, you must make sure that:
- You are exposing ports with `-p` command
- Windows firewall IS ENABLED and has the edge-traversal rule ON (the same one as in example 7).

Ex 7:
```
New-NetFirewallRule -DisplayName "Allow TCP 12345 and 5000-5020 over Teredo" -Direction Inbound -Action Allow -EdgeTraversalPolicy Allow -Protocol TCP -LocalPort 12345,5000-5020 -Program "C:\Program Files (x86)\TestIPv6App.exe"
```
