### ISSUE TITLE
Unable to run procmon on windows-containers in hyperv isolation mode

### ISSUE THREAD

**Issue by L1ghtman2k** [microsoft/Windows-Containers#191]
I have an app that works completely fine in the `--isolation process`, but does not work in `--isolation hyperv`. I am not sure what could be the reason. I have checked dependencies, and DLLs on both are identical. My last resort for debugging was to use procmon, however it does not work inside containers. (and since it is hyperv isolation, I can not just run procmon on the host).

This issue is also documented here: https://github.com/StefanScherer/dockerfiles-windows/tree/main/procmon, which intern links to a few more forums about the issue

docker hosts: windows11 pro, and windows server 2022
docker images: mcr.microsoft.com/windows:20H2, mcr.microsoft.com/windows/server:ltsc2022

**Comment by cwilhit** [comment]
To the subject title question concerning procmon in Windows containers running with Hyper-V isolation, that feedback would be good to direct to the [Sysinternals community](https://docs.microsoft.com/en-us/answers/topics/windows-sysinternals-procmon.html).

To the bigger issue, which is that your app does not work when the isolation mode changes, can you share more details about what is happening? Does the container fail to start entirely?

**Comment by L1ghtman2k** [comment]
Hey, I figured out the issue. Hyper-V isolation mode has a default cap on CPU, and RAM, that I didn't account for. After expanding those with --cpus, and --memory, the application worked
