### ISSUE TITLE
Can we leverage File Server Resource Manager Feature inside container?

### ISSUE THREAD

**Issue by thxCode** [microsoft/Windows-Containers#193]
hey, as the topic said, is that possible to use FSRM inside a container? btw, can someone tidy up a list of what features can or cannot enable inside a Windows container? appreciate so much :).

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Hi, can you share more about the scenario you're trying to accomplish and how running FSRM in a Windows container would help you meet your needs?
