### ISSUE TITLE
nanoserver images are not multi-arch ones

### ISSUE THREAD

**Issue by mainred** [microsoft/Windows-Containers#195]
The doc in https://hub.docker.com/_/microsoft-windows-nanoserver shows that we have multi-arch images for a range of nano images of different os versions, but after inspecting these images, I found we support only amd64 for those ones labeled with multi-arch like nano:1809

```
➜  ~ docker manifest inspect mcr.microsoft.com/windows/nanoserver:1809
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 574,
         "digest": "sha256:fb17f0ecdf2fc3c06d5b3b8a661f9832580f1c381de0578960cf8abc4a4e605a",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.2366"
         }
      }
   ]
}
```

**Comment by mainred** [comment]
The same happens to windows-servercore https://hub.docker.com/_/microsoft-windows-servercore

**Comment by TBBle** [comment]
I think amd64 _is_ the only architecture supported by Windows Server for customers. So 'multiarch' here is being somewhat misused, they really mean 'manifest list', and then there's only one possible manifest to include in the list.

Maybe they're being forward-looking, and reducing friction for if-and-when they ship their ARM64 server build to the public.

It doesn't seem super-valuable to offer this for these repos, it makes more sense for things like [.NET runtime](https://hub.docker.com/_/microsoft-dotnet-runtime) where their manifest lists, e.g. `6.0`, are _much_ more extensive (although they don't use the term multiarch there, or even highlight that it's a manifest list).

**Comment by cwilhit** [comment]
That's right, we only publish amd64-architecture Windows base images.
