### ISSUE TITLE
Unable to get custom Container Credentials Guard plugin to be invoked 

### ISSUE THREAD

**Issue by macsux** [microsoft/Windows-Containers#196]
We have been attempting unsuccessfully to build a custom CCG plugin as documented here:

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts

https://docs.microsoft.com/en-us/windows/win32/api/ccgplugins/nf-ccgplugins-iccgdomainauthcredentials-getpasswordcredentials

The plugin was built in C# conforming to interface spec with COM interop and registered. It was confirmed that it is visible to COM and can be activated by its ID. However, when referenced in container spec json it never gets activated. 

A full description of workflow we attempted along with the code tried is found here:

https://github.com/macsux/kerberos-buildpack/tree/main/src/CcgPlugin

Additionally, Microsoft support ticket (2112140040007266) has been opened and they recommended a GitHub issue be created against this repo.

**Comment by mjj209** [comment]
I wanted to check in on this issue, this is blocking a major feature development for VMware. There are many eyes on this, is someone available to provide guidance on this?

**Comment by selzoc** [comment]
To add a few more details, we were able to use [these troubleshooting steps](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting#non-domain-joined-container-hosts-use-event-logs-to-identify-configuration-issues) to find that the CCG doesn't seem to think the plugin is registered:
```
ProviderName : Microsoft-Windows-Containers-CCG
Id           : 4
Message      : Container Credential Guard failed to instantiate the plugin: {DEFFF03C-3245-465F-8391-CC586A2D1F32}.
               Error: Class not registered
```

The [docs](https://docs.microsoft.com/en-us/windows/win32/api/ccgplugins/nf-ccgplugins-iccgdomainauthcredentials-getpasswordcredentials) specify
```
The implementer must add a key under “HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\CCG\COMClasses” for their COM CLSID. Write access to “CCG\COMClasses” is restricted to SYSTEM and Administrator accounts.
```
which we have done:
```
> reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CCG\COMClasses" /s

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CCG\COMClasses
    (Default)    REG_SZ

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CCG\COMClasses\{DEFFF03C-3245-465F-8391-CC586A2D1F32}
    (Default)    REG_SZ
```

**Comment by macsux** [comment]
This indicates that you haven't properly registered the COM object. Please run `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe CcgPlugin.dll /tlb /codebase` from same folder where `CcgPlugin.dll` is (probably `bin\Debug`).

Having said this, this is what I'm getting on my machine when the object is properly COM registered:

```
get-winevent -logname Microsoft-Windows-Containers-CCG/Admin | format-list


TimeCreated  : 1/25/2022 1:19:21 PM
ProviderName : Microsoft-Windows-Containers-CCG
Id           : 4
Message      : Container Credential Guard failed to instantiate the plugin: {DEFFF03C-3245-465F-8391-CC586A2D1F32}. Error: Object was not found in registry
```

**Comment by selzoc** [comment]
@jsturtevant @vrapolinario 👋  Tagging y'all here since you announced gMSA support for AKS in #28 - can you help us figure out how to register our plugin?  We know the one on AKS works 😄

**Comment by selzoc** [comment]
Related: [docs pr](https://github.com/MicrosoftDocs/sdk-api/pull/1040) for the correct registry path

**Comment by macsux** [comment]
When comparing registration of the plugin on an AKS node, seems like the correct path should be `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CCG\COMClasses`. I now get the same error @selzoc mentioned. This seems to be an error in docs as the path mentioned [here ](https://docs.microsoft.com/en-us/windows/win32/api/ccgplugins/nf-ccgplugins-iccgdomainauthcredentials-getpasswordcredentials)

**Comment by selzoc** [comment]
For anyone else following along, we were able to get this to work yesterday:
- Building the [latest version](https://github.com/macsux/kerberos-buildpack/tree/f23f1479b5a70fa7e71b210979c995b682ac0891/src/CcgPlugin) of our .Net plugin (in our case, with hardcoded creds to check that the rest of the flow works)
- Registering it with `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regsvcs /fc CcgPlugin.dll`
- Adding the `CLSID` to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CCG\COMClasses` (`{DEFFF03C-3245-465F-8391-CC586A2D1F32}` in the case of that specific plugin) **Note** - we had to use [these instructions](https://www.msftnext.com/take-ownership-registry-key/) to take control of the `COMClasses` key to add the `CLSID`.
- Creating a `credspec.json` following [this format](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting#check-the-credential-spec-file) (section 2.b, using the same `CLSID` as above), and placing it in `C:\ProgramData\docker\credentialspecs`
- Building a docker image called `iisfun`using the [example script here](https://docs.microsoft.com/en-us/azure/aks/use-group-managed-service-accounts#verify-gmsa-is-installed-and-working) with the following `Dockerfile`
    ```
    FROM mcr.microsoft.com/windows/servercore/iis
    COPY run.ps1 c:
    ENTRYPOINT powershell C:\run.ps1
   ```
- Running with `docker run --security-opt "credentialspec=file://credspec.json" --rm iisfun`
- Finding the container's IP address with `docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" <container-name>`
- Opening a browser to the container's IP address and logging in with domain credentials 🎉

**Comment by cwilhit** [comment]
Hi @macsux did @selzoc's guidance above work for you too? If so, it sounds like there's room for improvement to provide better docs for this whole process, so adding 'documentation' tag and leaving open until a PR gets submitted to Microsoft docs addressing this.

**Comment by macsux** [comment]
Well I figured it out, @selzoc just reposted them here for everyone to see.
Docs have a lot of room for improvement and providing a sample app in c#
would probably make it much more approachable to the masses then c++
snippet they currently give. We're still trying to find a few key hurdles
in terms of which features and versions of windows are needed to get it
working as it doesn't work on every setup.

**Comment by cwilhit** [comment]
We have created a new open-source repository housing our Azure Key Vault Plugin used for Group Managed Service Accounts (gMSA) for Windows Containers. This plugin helps connect the Container Credential Guard (CCG) component on the node with Azure Key Vault to facilitate domain-joining nodes. Folks can now leverage this odebase as a reference to develop your own plugins to connect to Azure Key Vault as part of their gMSA solution. Additionally, our [Container Credential Guard (CCG) API](https://docs.microsoft.com/en-us/windows/win32/api/ccgplugins/nf-ccgplugins-iccgdomainauthcredentials-getpasswordcredentials) is also available for customers to use in their solutions.

Learn about our new GitHub repository and contribute here: https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA

I am going to close this issue because I think this satisfies the documentation request.
