### ISSUE TITLE
Processes fail with -2147023829 exit code under process isolation on Windows 11 on AMD CPUs

### ISSUE THREAD

**Issue by slonopotamus** [microsoft/Windows-Containers#197]
This was reproduced on VirtualBox 6.1.28 running on top of Ryzen 3700X.

1. Install Windows 11. SHA256 of `Win11_English_x64v1.iso` I used: 4bc6c7e7c61af4b5d1b086c5d279947357cff45c2f82021bb58628c2503eb64e. Installing all available Windows updates (as of 2022-01-07) doesn't fix anything
2. Install Docker engine for Windows containers (either via Docker Desktop or whatever way you prefer)
3. Reboot
4. Create directory somewhere
5. Create `Dockerfile` in that directory with the following contents:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2022
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
ENV CHOCO_URL=https://chocolatey.org/install.ps1
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
 [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'; \
 iex ((New-Object System.Net.WebClient).DownloadString("$env:CHOCO_URL"));
RUN choco install -y vcredist-all
```
6. `docker build --isolation=process .` in that directory. Expected: it succeeds. Actual: lots of stuff fails with `Exit code was '-2147023829'`

Note that there is an independent report (https://github.com/adamrehn/ue4-docker/issues/216) from @TomSmithGR who reproes the same issue running Windows 11 on a bare AMD Ryzen 9 5900X (i.e. VirtualBox is not involved).

We do not reproduce this issue with Hyper-V isolation.
We do not reproduce this issue on Windows Server 2022.
We do not reproduce this issue on Intel CPUs.

**Comment by michbern-ms** [comment]
Microsoft is seeing issues with Windows 11 hosts and Server 2022 guests when running TLS scenarios.  We are investigating these currently.   We are running a preview of cross version support (as described here (https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487)) but that preview has turned up an issue.   I don't have an ETA for a fix yet.   For a development scenario, you can use --isolation=hyperv.  For a production scenario, please use matching versions for host and guest.  (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1)

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by slonopotamus** [comment]
@msftbot this issue got no meaningful updates since February! That's _a bit_ more than 30 days.

**Comment by hach-que** [comment]
I can confirm that process isolation for LTSC2022 on Windows 11 on a Ryzen CPU appears to be fixed, as I successfully ran containers on my Windows 11 machine yesterday using that method.

**Comment by slonopotamus** [comment]
@fady-azmy-msft we have [evidence](https://github.com/adamrehn/ue4-docker/issues/343#issuecomment-1881969880) that this issue was **not** fixed. Can you provide a link to exact KB where you believe the fix was?
