### ISSUE TITLE
App service windows container start error

### ISSUE THREAD

**Issue by pevgeniev** [microsoft/Windows-Containers#199]
I've an asp.net core app that I want to run as windows container inside app service.
The app is built as self contained and uses docker file as (snippets):

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS base
....
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
.. -c Release -o /app/publish --self-contained --runtime win-x64
...
and then
FROM base AS final
ENTRYPOINT ["App.exe"]

The docker file is used to correctly build and push to ACR from azure devops pipeline, but when running the image in App Service it says:
Unable to start container. Error message: Index was outside the bounds of the array

I've also tried couple of other base images:
FROM mcr.microsoft.com/dotnet/aspnet:6.0-windowsservercore-ltsc2019 AS base
and 
FROM mcr.microsoft.com/dotnet/runtime:5.0-windowsservercore-ltsc2019 AS bas
and they give same error. 
What windows images does app service support?

**Comment by cwilhit** [comment]
@apwestgarth have you seen this issue before? Another user who [hit a similar issue](https://docs.microsoft.com/en-us/answers/questions/463587/windows-containers-unable-to-start-container-error.html) apears to have resolved the issue by changing the base image target

**Comment by apwestgarth** [comment]
Thanks for adding me @cwilhit 

As per our documentation - https://docs.microsoft.com/azure/app-service/configure-custom-container?pivots=container-windows - we have the following images cached locally on our workers to help with startup time - https://docs.microsoft.com/azure/app-service/configure-custom-container?pivots=container-windows#supported-parent-images

mcr.microsoft.com/windows/servercore:20H2
mcr.microsoft.com/windows/servercore:ltsc2019
mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-20H2
mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
mcr.microsoft.com/dotnet/runtime:5.0-nanoserver-20H2
mcr.microsoft.com/dotnet/runtime:5.0-nanoserver-1809
mcr.microsoft.com/dotnet/aspnet:5.0-nanoserver-20H2
mcr.microsoft.com/dotnet/aspnet:5.0-nanoserver-1809
mcr.microsoft.com/dotnet/runtime:3.1-nanoserver-20H2
mcr.microsoft.com/dotnet/runtime:3.1-nanoserver-1809
mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-20H2
mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-1809

As such any Windows Container based on LTSC2019 to 20H2 should be fine.

This is an example dockerfile from a sample app I created this afternoon:


```
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:6.0-windowsservercore-ltsc2019 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019 AS build
WORKDIR /src
COPY ["NetCoreWindowsCoreContainerSample/NetCoreWindowsCoreContainerSample.csproj", "NetCoreWindowsCoreContainerSample/"]
RUN dotnet restore "NetCoreWindowsCoreContainerSample/NetCoreWindowsCoreContainerSample.csproj"
COPY . .
WORKDIR "/src/NetCoreWindowsCoreContainerSample"
RUN dotnet build "NetCoreWindowsCoreContainerSample.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NetCoreWindowsCoreContainerSample.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NetCoreWindowsCoreContainerSample.dll"]
```

Our support engineers can take a look at the specific issue you are hitting, if you open a support case in the Azure Portal.

**Comment by cwilhit** [comment]
@pevgeniev have you taken a look at the above links and did it resolve your issue? I think this issue is solidly not a Windows containers platform issue (rather App Service, if anything) so I am going to mark this as closed.
