### ISSUE TITLE
Networking - Enable Session Affinity in Kubeproxy for Windows

### ISSUE THREAD

**Issue by mkostersitz** [microsoft/Windows-Containers#20]

**Comment by daschott** [comment]
See https://github.com/kubernetes/kubernetes/pull/91701

See 1.19 docs: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#load-balancing-and-services

**Comment by mkostersitz** [comment]
This is available now in Kubernetes 1.19
