### ISSUE TITLE
Windows Defender slow

### ISSUE THREAD

**Issue by Hvid** [microsoft/Windows-Containers#201]
Windows Defender is using and incredible amount of CPU on a server with lots of containers. When 100 containers are running, defender usually accounts for 20-25% of the CPU usage on the server.

Can Microsoft provide some guidance on what can safely be excluded?

Are there any other tweaks to be made regarding Defender?

**Comment by Hvid** [comment]
When a server is rebooted and thus, containers restarted. Startup of all containers can take several minutes due to realtime monitoring of defender.

**Comment by michbern-ms** [comment]
Microsoft has some guidance on tuning anti-malware tools for Containers here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers

In general, Windows Defender is going to do work proportional to the amount of I/O happening, since it needs to monitor that I/O.   The Windows Defender team has worked to tune Defender's CPU usage, but when all those containers are starting, there is just a lot of scanning that needs to be done to ensure that malware is caught if it infiltrates the containers.

**Comment by cwilhit** [comment]
Removing `triage` tag and adding `documentation` tag. It'd be great to see the main container docs have easy/quick reference to the existing Microsoft docs on tuning anti-malware tooling, so leaving this open until we get a change merged.

**Comment by Hvid** [comment]
Thanks. This looks more like a reference for AV vendors to use. I was looking for best practices/guidance for sysadmins.

**Comment by michbern-ms** [comment]
@Hvid - I was asking around and one of our Defender experts shared this link:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus?view=o365-worldwide

It is not a tuning guide, but it may help you gather some data about what Defender is scanning and provide some ideas about how you might adjust it.

**Comment by cwilhit** [comment]
@Hvid I am not sure if you are running these containers with containerd, but if you are, the Windows Defender team recently made some updates to their definitions to exclude containerd and related processes (see [this comment ](https://github.com/microsoft/Windows-Containers/issues/92#issuecomment-1083591322 ) on another issue). Are you using Docker or containerd?

**Comment by Hvid** [comment]
I'm using docker. I'm unsure how much excluding dockerd.exe will affect the security of the host.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
Hey @Hvid, were you able to see this when using containerd? As Craig mentioned Windows Defender team recently made some updates to their definitions to exclude containerd and related processes (see https://github.com/microsoft/Windows-Containers/issues/92#issuecomment-1083591322on another issue).

**Comment by Hvid** [comment]
Hi, 
I haven't tried it, as i have not been able to find any good documentation from Microsoft on how to transition from docker to containerd.

**Comment by brasmith-ms** [comment]
Please see the context in this thread for a workaround while the issue is being resolved https://github.com/microsoft/Windows-Containers/issues/345#issuecomment-1569197716
