### ISSUE TITLE
Windows Server 2022 failed on NodePort test for Kubernetes upstream test

### ISSUE THREAD

**Issue by msjingli** [microsoft/Windows-Containers#204]
The issue was discovered by Kubernetes upstream test with WS2022 Issue was understood and it's from OS level. We're in the progress to validate the fix and backport to WS2022

**Comment by jsturtevant** [comment]
failing tests are 

```
Kubernetes e2e suite.[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
Kubernetes e2e suite.[sig-network] Services should be able to create a functioning NodePort service [Conformance]
```

example error message:

```
Feb  2 00:00:36.920: INFO: Service reachability failing with error: error running /usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig --namespace=services-8918 exec execpodqzj49 -- /bin/sh -x -c echo hostName | nc -v -t -w 2 10.1.0.5 30165:
Command stdout:

stderr:
+ echo hostName
+ nc -v -t -w 2 10.1.0.5 30165
capz-conf-phg2v.internal.cloudapp.net [10.1.0.5] 30165 (?): TIMEDOUT      
command terminated with exit code 1
```

**Comment by marosset** [comment]
@msjingli is this issue meant to track the NodePort issues we see on Windows Server 2022 with overlay networking?
I believe there is another issue around L2Bridge networking when DSR is enabled. Is that a separate issue or are does this issue track that as well?

**Comment by msjingli** [comment]
@marosset we can use this issue to track both issues. On WS2022 nodeport test failed on below scenarios:
1. With Overlay: It's an OS issue. Bug is understood and working on backport to WS2022. 
2. With L2bridge: the bug only occurs when WinDSR is enabled. Investigating in progress.

**Comment by marosset** [comment]
Thanks @msjingli!

**Comment by marosset** [comment]
I believe this issue has been addressed with Windows Server 2022 OS patches.

**Comment by daschott** [comment]
This has been resolved with Windows Server 2022 cumulative updates.

**Comment by daschott** [comment]
This was fixed in KB5012637 released April 2022.
