### ISSUE TITLE
Is there Windows Image for running SSIS projects in containers?

### ISSUE THREAD

**Issue by shanthini385** [microsoft/Windows-Containers#205]

**Comment by cwilhit** [comment]
Hello, by SSIS do you mean [SQL Server Integration Services](https://docs.microsoft.com/en-us/sql/integration-services/sql-server-integration-services?view=sql-server-ver15)? We do not currently publish an image for running SQL server in Windows containers. That does not mean you cannot install SQL on your own on top of one of the [Windows container base images](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images) we do provide. Can you share more about your scenario related to this running in containers?

**Comment by cwilhit** [comment]
Closing due to staleness. Will reopen if additional info can be provided.
