### ISSUE TITLE
Docker/containerd support for Container Image integrity hashes?

### ISSUE THREAD

**Issue by jterry75** [microsoft/Windows-Containers#209]
Docker and Containerd by default when downloading Windows Base Images spend an enormous amount of time validating the images when apply/unpacking them to the file system. To work around this it seems to be that a customer must set an exception on the docker/containerd layer folders to exclude them from Windows Defender. The problem with this approach is that any layers above the Windows Base Images should be scanned.

If memory serves, in the past Docker had a way to use a code integrity hash associated with the Windows Base Image that Defender could use to verify that a given set of images and their files were already checked and signed and thus did not require scanning at pull time. This behavior now seems to be broken? Has it been removed?

Note: The difference in time pulling with / without the exclusion on our instances for just the size of the base image is 3 minutes versus 12 minutes. (4x slower with Defender)

@kevpar - FYI

Thanks,
Justin

**Comment by jterry75** [comment]
Part one of this has been fixed in #92 reference above. I have verified that Defender now no longer takes the additional time even without the exclusion. 

For part two, is there any support for integrity for customer image layers to avoid scans we could pull alongside from a registry etc?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
, please provide an update or close this issue.

**Comment by brasmith-ms** [comment]
Hi @jterry75, by your second question do you mean support for image / layer signatures? We are working on supporting this with MCR to package signatures for the Windows base images.

**Comment by jterry75** [comment]
Oh neat, is there any documentation for such a feature to make sure runtimes can support this from any registry?

**Comment by brasmith-ms** [comment]
Hey @jterry75, we have a blog post on this topic here: https://techcommunity.microsoft.com/t5/containers/announcing-image-signing-for-windows-containers/ba-p/3792097
