### ISSUE TITLE
Increase default scratch space on windows containers

### ISSUE THREAD

**Issue by khatrig** [microsoft/Windows-Containers#211]
**Is your feature request related to a problem? Please describe.**
Windows K8s + ContainerD doesn't support increasing windows container scratch space size. Related issue - https://github.com/containerd/containerd/issues/6694

**Describe the solution you'd like**
Increase default size of container scratch space to a large number(say 200Gi). It'd be great if this can be done for ltsc2019, 20H2, ltsc2022

**Describe alternatives you've considered**
[This solution](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#example) works only with docker but docker runtime k8s support is deprecated

**Additional context**
K8S + ContainerD support for increasing windows container scratch space seems to be at least some quarters away - https://github.com/kubernetes/kubernetes/pull/108894

**Comment by cwilhit** [comment]
Hello! This is a platform capability that already exists (e.g. Docker can do this today) and the feature gap you're asking about is solidly in cri/containerd projects. Having a separate issue on this repo is redundant. Let's close this issue and keep tracking from the containerd issue you linked above (I see Microsoft engineers are already engaged there anyhow).
