### ISSUE TITLE
Intermittent DNS issues with Windows containers

### ISSUE THREAD

**Issue by haiduc32** [microsoft/Windows-Containers#217]
This will be a long explanation of the issue and the investigations that were performed, so best grab a coffee first. Also this issue was initially reported at https://github.com/docker/for-win/issues/12638 but suggested to report it here.

  - [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features

### Actual behavior
Running this powershell in a Windows container, results in 1-3 timed out responses: for ($i=0;$i -lt 100;$i++) {nslookup google.com}

### Expected behavior
No DNS requests should fail.

### Information
The issue original issue is that our applications (.net core in windows containers in a kubernetes cluster) intermittently fail with the error: "No such host is known" when communicating with various resources (other services, database, etc).

We managed to reproduce the issue on a dev machine by running the powershell script in a windows container: for ($i=0;$i -lt 100;$i++) {nslookup google.com}

To exclude any issues with our work environment, I took this to a beefy vanilla machine (my personal gaming pc), with no prior docker installed. Installed Docker, activated Hyper-V, ran the container and the script, and same issue. In depth details bellow. 

  - Windows version: 20H2 10.0.19042.1586 (reproduces on different versions of windows)
  - Docker version: 20.10.13 (on earlier versions as well)
  - Docker image: mcr.microsoft.com/windows/servercore:10.0.19042.1586
  - Hyper-V (AFAIK)

### Steps to reproduce the behavior

  1. Run the docker command to start the container and enter interactive mode

```
docker run -it mcr.microsoft.com/windows/servercore:10.0.19042.1586 cmd
```
After starting the container, run `powershell` to switch to powershell. 

2. First thing I ran the following powershell scripts inside the container, on my setup, to set Google DNS servers, as the default DNS server wasn't working. In our work setup we also inject custom DNS servers, but it should not be related as I'll explain below :

```
get-netadapter "Ethernet" | Set-DnsClientServerAddress -ResetServerAddresses

$network = (get-netadapter).name | Select-Object -Last 1
Set-DnsClientServerAddress -InterfaceAlias $netwowrk -ServerAdresses ("8.8.8.8","8.8.4.4")
```
3. Next, after confirming with `ipconfig /all` that only the Google DNS servers are used, I run the following powershell script:
```
for ($i=0;$i -lt 100;$i++) {nslookup google.com}
```
On my setup, almost all the time, the script pauses 3 times, for 2 seconds each time, and in that case I see **DNS request timed out.**. On the work setup, it's about once in two runs. 

4. To confirm that it's not a Google DNS issue, I run the same script `for ($i=0;$i -lt 100;$i++) {nslookup google.com}` from the host machine, with no timeouts. (repeated the test multiple times with no timeouts).

5. After lots of head scratching, time to pull out the big boys tools, namely Wireshark. First, investigate the packets for the **Ethernet adapter vEthernet (nat)** (I'll share the capture if it's deemed useful, but for the sake of already long issue, I'm skipping it). To best of my knowledge, this is the adapter that the container communicates with. Here we see DNS UDP packets that are sent, but don't have a reply packet. 

> Sidenote: It's not necessarily just the DNS UDP that don't get a reply, I suspect there might be some other packets that don't get a reply in time, and blocks nslookup; but ATM I can not confirm.

6. Now that we know there are packets lost, let's check if those packets reach our physical network interface. I run Wireshark on my physical network interface, and filter only DNS A type packets `dns.qry.name == "google.com" && dns.qry.type == 1`. Run the script again in the container. I can see 198 packets filtered (request/reply). So only 99 out of 100 DNS requests reached physical interface (I did check that all requests have a response). 

**Notice** that I mentioned earlier that there are usually 3 timeouts but in this Wireshark I usually see just 1 missing request/response because of the Wireshark filter. So far that's the one type of packet I identified for sure as missing in action, but there are more types that I can't put my finger on.

### Conclusions

Based on that research I draw the conclusion that some DNS (and maybe not only DNS) UDP packets get lost between the vEthernet NAT interface and the physical ethernet interface. 

### Questions

Can I investigate something further? I'm not a network guy, and best I can do is reading Wireshark logs, but how the routing behind is done or what is involved is all black-box to me.

**Comment by cwilhit** [comment]
Hey! Thanks for posting this detailed writeup. Have you had a look at #216?

**Comment by cwilhit** [comment]
Opening MSFT internal 38848137 to track.

**Comment by haiduc32** [comment]
Hi @cwilhit, I took a quick look now, but it doesn't seem to be the same issue. As mentioned, I could not reproduce the issue outside the container.  Also the message from the nslookup when it times out is:
```
DNS request timed out.
    timeout was 2 seconds.
Name:    google.com
Address:  2a00:1450:400d:80d::200e

Server:  dns.google
Address:  8.8.8.8
```

**Comment by dineshgovindasamy** [comment]
@haiduc32 : Can you please try Resolve-DNSName instead of nslookup? Let me know if u see the same issue.

**Comment by levimatheri** [comment]
Any update on this? I'm having a similar issue running IIS containers on Azure VMSS hosted in Service Fabric with Windows Server 2019 with Containers. Sometimes especially after high load, the outbound connections from the containers will intermittently time out for whatever reason. Restarting the containers doesn't fix it. Only thing that fixes it is restarting the host VM. @haiduc32 were you able to figure this one out?

**Comment by AbelHu** [comment]
If you hit the issue in Azure VM/VMSS, please reference the mitigation in https://github.com/Azure/AKS/issues/2988

**Comment by fady-azmy-msft** [comment]
> @haiduc32 : Can you please try Resolve-DNSName instead of nslookup? Let me know if u see the same issue.

@haiduc32 were you able to see the same issue after trying Resolve-DNSName? 

> If you hit the issue in Azure VM/VMSS, please reference the mitigation in [Azure/AKS#2988](https://github.com/Azure/AKS/issues/2988)

Abel also referenced a mitigation if you see this issue in Azure VM/VMSS.

**Comment by fkorotkov** [comment]
Fixed it for our use case by setting `--dns` flag explicitly when a container is getting run e.g. `docker run --dns 8.8.8.8`.

**Comment by AbelHu** [comment]
> Fixed it for our use case by setting `--dns` flag explicitly when a container is getting run e.g. `docker run --dns 8.8.8.8`.

I guess that the dns issue occurs when policies for dns are being updated (deleted and added) so adding a static dns  could fix this issue.

**Comment by ericoporto** [comment]
@cwilhit any updates here?
