### ISSUE TITLE
Virtual switch makes network speed extreamly slow when external Wi-Fi adapter is used

### ISSUE THREAD

**Issue by Zensey** [microsoft/Windows-Containers#218]
**Describe the bug**
When I share Wi-Fi adapter with virtual switch (bridged mode) it works, but network connection speed becomes extreamly slow and unstable: both for host and guest systems. 

With Ethernet everything works as expected.
Tried to reproduce it on various machines with different Wi-Fi adapters, but for me this bug is stable.

**To Reproduce**
* Create a VM using Hyper-V manager
* Create a virtual switch with external Wi-Fi adapter and have "Allow management operation system share.." checked.
* Measure network speed: it becomes low and with timeouts.
You even don't need to start VM.
![image](https://user-images.githubusercontent.com/769152/161844991-da0b6bce-6d5f-4c13-b0b5-62e6fe81a6f0.png)

**Configuration:**
Windows 10 (version 21H2), Hyper-V

**Additional context**
It looks like this bug is known for a few years already, but there's stil no solution.

**Comment by cwilhit** [comment]
It looks like this issue is related to Hyper-V networking, whereas this repo is for Windows containers; I'd recommend filing a feedback via the Windows Feedback Hub app instead.
