### ISSUE TITLE
source for Windows base images?

### ISSUE THREAD

**Issue by trevor-webster** [microsoft/Windows-Containers#222]
How can one get the source for any of the Windows base images*? 

(*as listed at https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images)

**Comment by brasmith-ms** [comment]
Sorry, can you clarify? You should be able to run the command: 

`docker pull mcr.microsoft.com/windows/servercore:ltsc2022`

**Comment by ohault** [comment]
On the one hand, there is a huge lack of documentation on features, the files of every official Windows containers base image, and on the other hand, there is also no documentation, nor any tools provided to generate custom **base** images for Windows Containers.

**Comment by weijuans-msft** [comment]
@trevor-webster  Assuming you are asking the dockerfile of those base images, the answer is no, today there is no source file for those Windows base images. All Windows flavor container images will be built from one of the base images.

@ohault Can you help me understand what you are exactly looking for? Are you developing new apps on Windows containers or moving existing apps in Windows containers? 

I understand Linux allows you to create images from scratch.  Currently for Windows, we are *not* supporting generating any customer base images. We are definitely seeing customers asking this, especially from the angle of being able to have smaller image size. We acknowledge this is a pain. We are looking at different options.

**Comment by weijuans-msft** [comment]
@ohault Does this blog help? I am trying to understand what documentation that's most useful for you?

https://techcommunity.microsoft.com/t5/containers/nano-server-x-server-core-x-server-which-base-image-is-the-right/ba-p/2835785.

**Comment by ohault** [comment]
@weijuans-msft Unfortunately not at all, the question here is not to understand what image to use, but a regulatory/compliance question about what each Windows Container based images is composed of. Currently, it's a black box. Microsoft should provide a complete documentation and the full toolchain tools to build Windows Containers base images with full traceability.

**Comment by akarshm** [comment]
Is the ask to publish SBOM for Windows containers?

**Comment by ohault** [comment]
> Is the ask to publish SBOM for Windows containers?

Indeed, this include the list of artefacts used, the scripts and tools used to build each flavour of Windows Container base images.

**Comment by akarshm** [comment]
Thanks for the confirmation. This is on our roadmap, but we don't have a timeline to share.

**Comment by ohault** [comment]
hi @akarshm , great but does it possible to even keep a [Windows Container Roadmap] published online ? [Windows Container Roadmap](https://github.com/microsoft/Windows-Containers/projects/1) would be closed.
