### ISSUE TITLE
Improve the error message when pulling images on incompatible Windows OS version

### ISSUE THREAD

**Issue by ShiqianTao** [microsoft/Windows-Containers#223]
**Is your feature request related to a problem? Please describe.**
When pulling a Windows Server 2022 image in Windows Server 2019 nodes, check the pod events:
```
Warning Failed 11s kubelet Failed to pull image "mcr.microsoft.com/windows/servercore:ltsc2022": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/windows/servercore:ltsc2022": no match for platform in manifest: not found
```
Users are confused about it.

**Describe the solution you'd like**
Users want to see a clearer message showing what happens and how to do it.
E.g., the current windows server 2019 node cannot support the ltsc2022 image. Recommend using the ltsc2019 image.
Besides Windows Server 2019/2022, Microsoft will support more and more Windows OS versions to host containers. Users are happy to see a clearer message about this guidance when upgrading/changing their Windows OS version.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by brasmith-ms** [comment]
Containerd is the one producing this error, if it can't find an entry in the manifest matching the hosts build number then it throws this error. It uses RtlGetVersion to do this. Moved it here https://github.com/containerd/containerd/issues/6989
