### ISSUE TITLE
Custom image based on the "mcr.microsoft.com/windows/nanoserver:1809" and "mcr.microsoft.com/windows/nanoserver:ltsc2022" based on "servercore" instead of "nanoserver"

### ISSUE THREAD

**Issue by sc-olenanosenko** [microsoft/Windows-Containers#225]
**Describe the bug**
Custom image based on the "mcr.microsoft.com/windows/nanoserver:1809" and "mcr.microsoft.com/windows/nanoserver:ltsc2022" based on "servercore" instead of "nanoserver"

**To Reproduce**
When I am trying to use "mcr.microsoft.com/windows/nanoserver:1809" images as a base image for building custom images after viewing the image manifest of my custom image I see that is based on "servercore" instead of "nanoserver".

When I am using the previous version "mcr.microsoft.com/windows/nanoserver:10.0.17763.2803" image as a base image for custom - is OK.
The same for the ltsc2022 - using "mcr.microsoft.com/windows/nanoserver:10.0.20348.643" images is OK.

When I am using this one "mcr.microsoft.com/windows/nanoserver:10.0.17763.2928" or this "mcr.microsoft.com/windows/nanoserver:10.0.20348.707" - not work (servercore instead of nanoserver).

**Expected behavior**
Custom images based on "mcr.microsoft.com/windows/nanoserver:1809" or "mcr.microsoft.com/windows/nanoserver:ltsc2022" image should base on "nanoserver"

**Comment by brasmith-ms** [comment]
Hi @sc-olenanosenko, I haven't been able to repro this. Can you provide the dockerfile you're using alongside the commands you're using to check the manifest?

**Comment by sc-olenanosenko** [comment]
Hi @brasmith-ms, here placed our Dockerfile - https://github.com/Sitecore/docker-tools/blob/main/image/src/Dockerfile, where BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:1809 and BUILD_IMAGE=mcr.microsoft.com/windows/servercore:ltsc2019

**Comment by brasmith-ms** [comment]
Can you specify how you're checking that it is servercore? I don't see any reason to believe it is returning servercore. The servercore image is much larger and has more utilities installed, including powershell. 

For nanoserver 1809:
```
C:\>REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    [..]
    BuildLab    REG_SZ    17763.rs5_release.180914-1434
    BuildLabEx    REG_SZ    17763.1.amd64fre.rs5_release.180914-1434
    CompositionEditionID    REG_SZ    ServerDatacenterNano
    CurrentBuild    REG_SZ    17763
    [...]
    EditionID    REG_SZ    NanoServer
    [...]
    InstallationType    REG_SZ    Nano Server
    [...]
    ReleaseId    REG_SZ    1809
    [...]
```

And for nanoserver ltsc2022:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    [...]
    BuildLab    REG_SZ    20348.fe_release.210507-1500
    BuildLabEx    REG_SZ    20348.1.amd64fre.fe_release.210507-1500
    CompositionEditionID    REG_SZ    ServerDatacenterNano
    [...]
    EditionID    REG_SZ    NanoServer
    [...]
    InstallationType    REG_SZ    Nano Server
    [...]
```

And on servercore ltsc2019:
```
PS C:\> Get-WindowsEdition -online


Edition : ServerDatacenterCor
```

**Comment by sc-olenanosenko** [comment]
**Steps to reproduce:**
1) you can modify the docker-compose file by the URL https://github.com/Sitecore/docker-tools/blob/main/image/src/docker-compose.yml to change the image name for example, image: acrRegistryURL/namespace/sitecore-docker-tools-assets:0.0.0-test
2) run command: 
docker-compose build --build-arg BASE_IMAGE="mcr.microsoft.com/windows/nanoserver:1809" --build-arg BUILD_IMAGE="mcr.microsoft.com/windows/servercore:ltsc2019" --force-rm
3) then I push generated image (acrRegistryURL/namespace/sitecore-docker-tools-assets:0.0.0-test) to the ACR
docker push acrRegistryURL/namespace/sitecore-docker-tools-assets:0.0.0-test
4) then I have checked the manifest in the Azure Repository for this image

![image](https://user-images.githubusercontent.com/87434783/170497054-a168be39-90e1-48be-a6bc-1eaeeca3a883.png)
5) when I run this command:
docker-compose build --build-arg BASE_IMAGE="mcr.microsoft.com/windows/nanoserver:10.0.17763.2803" --build-arg BUILD_IMAGE="mcr.microsoft.com/windows/servercore:ltsc2019"
I see that my custom image (acrRegistryURL/namespace/sitecore-docker-tools-assets:0.0.0-test) based on the "nanoserver" instead of "servercore"

**Comment by brasmith-ms** [comment]
@sc-olenanosenko for what reason are you using nanoserver for the BASE_IMAGE argument? That is almost certainly the image you are pushing to the repository. I'm not sure what the BASE_IMAGE and BUILD_IMAGE arguments are supposed to do as those seem to be specific to the sitecore/docker-tools repository. Docker compose is designed for multi-container environments so it's likely you're running both, or docker is attempting to merge the custom layers of the build image onto the nanoserver base image.
