### ISSUE TITLE
mcr.microsoft.com/windows/servercore:ltsc2022 and ltsc2019 5/10/2022 update changed the base layer not just delta

### ISSUE THREAD

**Issue by jterry75** [microsoft/Windows-Containers#226]
**Describe the bug**
Every month on Patch Tuesday Microsoft updates the ltsc2022 and ltsc2019 images. (Along with many others). On 5/10/2022 update, for the first time that we have noticed, Microsoft updated the base layer and not just the delta layer. Why did this happen? It has large storage impact over the MoM Delta Layer strategy. Below you will see that for at least the last 13 months of releases this has never happened. Please advise what the update strategy for these images will be moving forward and if this is expected to happen again. This breaks our automation which verifies the identity chain of the base images. Thank you.

**To Reproduce**
```PowerShell
mcr.microsoft.com/windows/servercore:ltsc2019
sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93
sha256:8b534d64a7c337eb8a23b425e4f598cd3e7407ddf8c7b2f714d1e7f7ed6a04be

mcr.microsoft.com/windows/servercore:10.0.17763.2928
sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93
sha256:8b534d64a7c337eb8a23b425e4f598cd3e7407ddf8c7b2f714d1e7f7ed6a04be

mcr.microsoft.com/windows/servercore:10.0.17763.2803
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:ba8181afd4264392fbbf8df14fb4cddc55fbe085ab000e986b789678bc2bb171

mcr.microsoft.com/windows/servercore:10.0.17763.2686
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:0a6173b79e25f2ebc0ed51b0ac32a6f65ca5a3bbfcbeab8b74a6c24324121dea

mcr.microsoft.com/windows/servercore:10.0.17763.2565
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:1bd78008c728d8f9e56dc2093e6eb55f0f0b1aa96e5d0c7ccc830c5f60876cdf

mcr.microsoft.com/windows/servercore:10.0.17763.2458
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:567fd00846e9a9f44eea5925b497356dda00fe89b8335d2a3b2a8b9d84b0bb69

mcr.microsoft.com/windows/servercore:10.0.17763.2452
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:635f15ebd5b486e8a00bf217a0574a29550e5bbf08c1d021e1e308100b2e49b5

mcr.microsoft.com/windows/servercore:10.0.17763.2366
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:5ee7a7ea9cf22f75886179907a41810a992e21f3d0c57cc10d2147ce9237701c

mcr.microsoft.com/windows/servercore:10.0.17763.2300
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:c1f4c7287c99b95fce227924349d1d139aceb37d97b555144bd5808935b6eab0

mcr.microsoft.com/windows/servercore:10.0.17763.2237
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:c0698cf91ebd6bcfb319be6a50421b356d6a3dbbd213d9b2b9dca0f837d7a999

mcr.microsoft.com/windows/servercore:10.0.17763.2183
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:a0ddf88812f10c7d6edc858aa9784ff5ca9de4a7bb631909c090090343abd059

mcr.microsoft.com/windows/servercore:10.0.17763.2114
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:c67ded6868b61d392a0c096f911563fd6bc0bc3ed4fe401d077b3718a1b0cdaf

mcr.microsoft.com/windows/servercore:10.0.17763.2061
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:f143c6fed32d477c35b660b2e108ea62e3593c03e44bd9ced208ce52b26b0841

mcr.microsoft.com/windows/servercore:10.0.17763.2029
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:8d5139ce8e391161879a01d93f3cedd815a56486d43851e002819daea95cbbda

mcr.microsoft.com/windows/servercore:10.0.17763.1999
sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f
sha256:639bb6bb2beb4cfdcacb9f0844344448fe26494665d5fe78a494419f86fbb18f
```

**Expected behavior**
The 5/10/2022 delta update should have been based on `sha256:4612f6d0b889cad0ed0292fae3a0b0c8a9e49aff6dea8eb049b2386d9b07986f` to maintain compatibility.

**Comment by akarshm** [comment]
Thanks, Justin, for raising this issue. What you mentioned is expected and was done as part of our re-baseline effort leading to the change in the base layer. We are investing in different approaches to reduce the Windows container base image size, and more updates will be shared as we learn more on this journey.

**Comment by jterry75** [comment]
Can you please provide information that we can monitor to better understand this process? IMO this was a breaking change to the process with no prior warning or heads up about a change to how this was being done. Where was this communicated that we could haven noticed to be aware of the change that was coming?

**Comment by akarshm** [comment]
​Hey Justin, note that as the Windows updates are cumulative, the delta layer keeps increasing, leading to longer pull times for our customers. Re-baselining allows us to reset this increase by merging the base and delta layer to create the new base layer and then letting the servicing layer contain further updates as released. As a result, you had to pull both the base and delta layer this time.

We appreciate your feedback and shall have the re-baselining mentioned in our release notes when we do it the next time.

**Comment by jterry75** [comment]
Thank you that would be helpful.
