### ISSUE TITLE
Intermittent slow outbound network in containers

### ISSUE THREAD

**Issue by levimatheri** [microsoft/Windows-Containers#229]
**Describe the bug**
I'm running some Windows IIS containers on Azure VM scale set. For the most part, it seems to run fine. However, occasionally, especially after a high load, outbound connections become slow and even timeout. Restarting the container doesn't fix it, only restarting the host VM seems to resolve it. I cannot rely on this workaround of course. Connections to localhost inside the container work fine. And outbound connections on the host VM work fine too.

**To Reproduce**
I haven't been able to consistently reproduce, but one way would be to load test the container by sending many requests to it. I'm running an IIS container on Windows Server 2019 with Containers. 

**Expected behavior**
The container outbound network should work consistently, and not fail intermittently. I'd expect the issue to resolve once a container is restarted. 

**Configuration:**
 - Edition: Windows Server 2019
- Base Image being used: Windows IIS ltsc 2019
 - Container engine:  docker
 - Container Engine version docker version 20.10.9 Mirantis Container Runtime

**Comment by levimatheri** [comment]
This might be caused by this? https://github.com/moby/moby/issues/30822

**Comment by dcantah** [comment]
@sbangari @kestratt @daschott

**Comment by levimatheri** [comment]
Possibly could also be caused by this RSC issue? https://github.com/microsoft/Windows-Containers/issues/145

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
, please provide an update or close this issue.

**Comment by levimatheri** [comment]
Our issue turned out to be caused by port exhaustion. We increased the port range from 16k to 32k which fixed the issue.

**Comment by fady-azmy-msft** [comment]
Thank you for letting us know @levimatheri
