### ISSUE TITLE
ipv6 windows server 2022 this request is not supported by null ipam driver

### ISSUE THREAD

**Issue by thealtor** [microsoft/Windows-Containers#230]
**Hello**

I have a  windows server 2022 on which I have installed docker (version=20.10.9)

Based on official documentation ipv6 should be supported   with l2bridge network on windows server 2022 , but this still not working

The command I execute: docker network create -d l2bridge --ipv6 test
Response: Error response from daemon: This request is not supported by null ipam driver

Can you please guide me ?

**Comment by brasmith-ms** [comment]
Hi @thealtor, docker itself does not support ipv6 on Windows server 2022, but containerd does via the sdnbridge and Azure CNI plugins. I do agree that the docs you mention need to be updated to provide guidance around containerd, as we are now focused on supporting containerd.

**Comment by thealtor** [comment]
@brasmith-ms thanks a lot
