### ISSUE TITLE
hcsshim::ImportLayer Error

### ISSUE THREAD

**Issue by warrenspe** [microsoft/Windows-Containers#231]
**Describe the bug**
Docker build does not work

**To Reproduce**
Dockerfile:
```
# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN mkdir C:\temp
```
```
docker build -t debugimage .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> 86eddd4761f5
Step 2/2 : RUN mkdir C:\temp
 ---> Running in 237a8d94102a
re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)
```

**Expected behavior**
An image to be created with a C:\temp directory

**Configuration:**
 - Edition: Windows 10.0.19043
- Base Image being used:  Windows Server Core ltsc2019
 - Container engine: docker
 - Container Engine version 4.9.0

Virtualization is enabled; this is on a brand new laptop with docker installed

**Additional context**
Not sure if any more detailed logging would be produced that might be of assistance in debugging this; if there's a way to get more information out of docker please let me know!

**Comment by pbozzay** [comment]
I tried to reproduce this issue last week with no success. Just to confirm, are you able to start a normal docker container (and it's only building an image locally that fails)?

**Comment by warrenspe** [comment]
Hello @pbozzay,

Yes, it appears to be able to run containers as expected, just not build new images

```
PS C:\docker\applications\debug> docker build -t debugimage .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> 86eddd4761f5
Step 2/2 : RUN mkdir C:\temp
 ---> Running in 43c984b807e8
re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)

PS C:\docker\applications\debug> docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 cmd.exe
Microsoft Windows [Version 10.0.17763.1397]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>exit
PS C:\docker\applications\debug>
```

**Comment by warrenspe** [comment]
Well, figured it out - I was getting burned by this:

https://social.technet.microsoft.com/Forums/en-US/01db4c1d-547c-460e-bbbb-32626436b881/sysmon-preventing-docker-build?forum=windowstroubleshooting

I guess my organization pushes sysmon to our machines automatically.

Not sure why this is an issue, but it might be something worth making a ticket for
