### ISSUE TITLE
I cant do basics with windows containers

### ISSUE THREAD

**Issue by rifaterdemsahin** [microsoft/Windows-Containers#232]
**Describe the bug**
I need to run a dockerfile on windows containers i cant do basics
It gets stuck at the running state

**To Reproduce**
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
RUN ["powershell" ,"New-Item","c:\\test"]
```
[Steps to reproduce the behavior Shown in a Loom Video:](https://www.loom.com/share/ffc19243be064f2ba3b8c39749e6dd54)

**Expected behavior**
Builds the machine

**Configuration:**
PS C:\dockerwindows> docker version
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:07 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.0 (80466)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 08:44:17 2022
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\dockerwindows>

**Additional context**
I suspect i am missing a basic part here...
Also asked to Azure support as I need to deploy it to ACI
Support request ID | 2206200050001592
https://portal.azure.com/#view/Microsoft_Azure_Support/SupportRequestDetails.ReactView/id/%2Fsubscriptions%2F90caadfe-6a7d-4b5c-89f9-6141cf26362b%2Fproviders%2Fmicrosoft.support%2Fsupporttickets%2F2206200050001592

**Comment by rifaterdemsahin** [comment]
@onuralp here it is

**Comment by pbozzay** [comment]
I just tried to repro the issue and was unsuccessful - it built just fine with the RUN command included. Powershell does take a while to spin up though, and I initially wondered if it was hung because the command took ~30s to complete. Can you confirm you gave it a significant grace period to finish?
