### ISSUE TITLE
Powershell Helper Module for Host Compute Service (HCS)

### ISSUE THREAD

**Issue by ohault** [microsoft/Windows-Containers#233]
**Is your feature request related to a problem? Please describe.**
Meanwhile, there is a Powershell Helper Module Host Networking Service (HNS), it is not the case for Host Compute Service (HCS) - see https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

**Describe the solution you'd like**
All Windows Host Networking Service (HNS) and Host Compute Service (HCS) services (API features) should be available through Powershell and for all flavors of Containers on Windows (novel gases)

**Describe alternatives you've considered**
Using Docker, but Docker should no longer needed at all for running Windows Containers on Windows.

**Comment by fady-azmy-msft** [comment]
Hey @ohault, could you share more about what you want to accomplish with exposing HNS and HCS (for all container types) through Powershell?

**Comment by ohault** [comment]
Hey @fady-azmy-msft, yes for sure.

1) for Windows Admin Center, it will provide a way to create an extension for HNS/HNC
2) Hyper-V Manager and all other current tools are only showing a very limited part of the whole Virtualisation/Container architecture on Windows (one exception https://github.com/ShaunLawrie/HnsExplorer)  
3) hidden VM, containers .... is a real problem in terms of compliancy
4) using hnsdiag,exe and hcsdiag.exe is too limitative
5) it locks innovation
6) It's a big spending of times and resources for all solutions that need to rely on HNC/HNC (see BUILD 2022 sessions about IoT, Edge and AKS) 
7) it's a very obscure and untrustworthy approach to try to hide such thing as well as all the associated documentation.
8) ....

I can continue, I already confirm that it should be done for both HNS and HCS coherently.

I hope this help.

**Comment by fady-azmy-msft** [comment]
Thank you for sharing this @ohault. I spoke with my team about this FR and it's certainly something we'll consider in the future but it's not a priority at the moment. I'm going to leave the enhancement tag on but close this issue to keep track of this FR moving forward.

**Comment by ohault** [comment]
Hi @fady-azmy-msft , can you please add this in the [roadmap](https://github.com/microsoft/Windows-Containers/projects/1) before closing this feature request ?
