### ISSUE TITLE
Installing Language Packs for Windows in containers

### ISSUE THREAD

**Issue by DmitrySenin** [microsoft/Windows-Containers#234]
**What is your question?**
I'm currently developing a tool which is based on Windows + LibreOffice, and this tool doesn't work well with Japanese - LibreOffice outputs boxes after processing a document. Locally, it all works just fine
I came to a conclusion that my base Windows image lacks a language pack for Japanese and I'm looking for a way to install it with no luck for now

Can you suggest anything?

**Notes**
My base image is mcr.microsoft.com/dotnet/framework/runtime:4.7.2-20210209-windowsservercore-ltsc2019

**Comment by weijuans-msft** [comment]
@DmitrySenin Windows containers no longer supported language packs. We did when initially released with Windows Server 2016. Later on in the effort of reducing image size, we have removed those.

**Comment by Jasonlhy** [comment]
@weijuans-msft I understand language pack is no longer shifted with windows container, but is there any easy way to install the language pack with PowerShell?

**Comment by adiroiban** [comment]
Same issue here.

I am ok not to have language pack images published by MS.

Can we get some help/instructions on how to create an image with a language pack? Thanks!

I am looking into language pack as a way to help with the i18n automated tests of our product.
