### ISSUE TITLE
Docker image for Windows 10 IoT Enterprise LTSC 2021

### ISSUE THREAD

**Issue by tyb-dev** [microsoft/Windows-Containers#235]
I need to run unit and integration tests for my application on _Windows 10 IoT Enterprise LTSC 2021_ in a containerized pipeline. I was expecting to find a `mcr.microsoft.com/windows:21H2` Docker image but the [tag list](https://mcr.microsoft.com/v2/windows/tags/list) ends with 20H2. 

Where can I find it?

**Comment by weijuans-msft** [comment]
We have stopped shipping SAC releases after 20H2. You can find more details in this blog post: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487. 

What is your use case for using that Windows image on the IoT host?

**Comment by ohault** [comment]
+1
@weijuans-msft to contribute this ticket, I can think about a use case, for the Automotive industry and mission critical system (nuclear power plant, aircrafts, ....) using Edge devices. On these critical Edge devices, system/customer safety cannot be an option, it's part of the design requirements. Virtualisation and Containers technologies play a very important role here (see e.g. http://xhypervisor.org/) and if Windows IoT would like to be part of it, Microsoft should at least provide a base image for Windows IoT.

The whole problem in the current architecture of Windows Container is that currently we have to answer such use case questions for each request. This underlines a deeper problem related to the two following issues :
1) For compliancy : all Windows Container base images should be fully documented and reproductible (build for source) 
2) For all application needs : ISV/OEM/ODM/Developer/ITpro should be able to build the exact custom base image from their specific application needs  and no more (minimum risk exposure principle)

The current posture is currently indefensible/unpardonable especially knowing that Windows Container base images is already imposed as the only solution on Windows for Windows Containers using currently available technologies.

**Comment by tyb-dev** [comment]
> what is your use case for using that Windows image on the IoT host?

In my case our host is a Windows Server, not an IoT one. I want to run unit and integration tests in a CI/CD pipeline within a container, without having to set up and maintain a collection of VMs.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
@tyb-dev can you explain what's blocking you from running integration tests in a CI/CD pipeline within a container? 

CC @viniciusl-msft

**Comment by tyb-dev** [comment]
> @tyb-dev can you explain what's blocking you from running integration tests in a CI/CD pipeline within a container?
> 
> CC @viniciusl-msft

I needed to test an application against a specific version of Windows, but there was no Docker image available for that version of Windows.

**Comment by TerryWarwick** [comment]
@tyb-dev, could you run a different container version in Hyper-V isolation mode on top of Windows 10 IoT Enterprise LTSC 2021?

**Comment by tyb-dev** [comment]
No longer relevant

**Comment by gregg-cbs** [comment]
Window Tiny10 uses this IOT version... just realised Docker wont install on it and now im screwed.
