### ISSUE TITLE
Can a custom ICcgDomainAuthCredentials be used to provide a non gMSA account for a pod?

### ISSUE THREAD

**Issue by arontsang** [microsoft/Windows-Containers#236]
My company infrastructure team currently does not support gMSA for dynamically provisioned servers.

Therefore I would like to run containers under AD service accounts managed by a 3rd party credential store.

My question is, can k8s be configured to run a pod under a cred that it gets from a custom ICcgDomainAuthCredentials. As opposed to getting a credential to then query AD for the gMSA creds.

The node is also going to be a non AD windows node.

**Comment by fady-azmy-msft** [comment]
Looping in @jsturtevant as this seems to be a K8s question.

**Comment by jsturtevant** [comment]
If you build your own ccg plugin you can configure the pod with the `hostAccountConfig` value that uses the GUID of that plugin: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#additional-credential-spec-configuration-for-non-domain-joined-container-host-use-case.  

The latest gmsa webhook release has support for this field as well: https://github.com/kubernetes-sigs/windows-gmsa/pull/47

For building your own ccg plugin you can use https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA as a reference

**Comment by arontsang** [comment]
@jsturtevant

I think you've misunderstood me.

I am unable to use mGSA at all. I was hoping to inject an unmanaged (from the perspective of Microsoft AD) AD service account to run my pod/container.

**Comment by jsturtevant** [comment]
regardless of if the pod is in kubernetes or running locally the only way to interact with the domain from a Windows container perspective is to use the gMSA: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts. I believe this is due to the way that passwords are managed with containers.

**Comment by jsturtevant** [comment]
@arontsang did that answer you question?  can we close this issue or do you have further questions?
