### ISSUE TITLE
No Manifest linux/amd64 or linuxaarch64 

### ISSUE THREAD

**Issue by sojab0on** [microsoft/Windows-Containers#238]
**What is your question?**
when pulling the windows:20H2 or 10.0.19042.1766 tagged it gives an manifest linux/amd64 on my linux docker host based on amd64 architecture also when i try to do this om my OCI arm instance with docker it gives linux/aarch64 not found 

What can i do to pull the images

**Comment by fady-azmy-msft** [comment]
Hey @sojab0on , can you share a bit more information on what you're trying to do?

**Comment by sojab0on** [comment]
OCI is an oracle arm based vm running ubuntu linux 

When i try to pull the windows images trough docker pull command it gives that error 
Same if i try it on my ubuntu based X86_64 server same error

**Comment by lippertmarkus** [comment]
Windows images don't work on Linux.
