### ISSUE TITLE
Support of COPY flag --from=<name> in Dockerfile for Windows Containers

### ISSUE THREAD

**Issue by ohault** [microsoft/Windows-Containers#239]
**Is your feature request related to a problem? Please describe.**
Currently for Windows Containers, COPY flag --from=<name> is not supported in Dockerfile.

**Describe the solution you'd like**
Implement the required support for this --from flag for the COPY instruction - ref : https://docs.docker.com/engine/reference/builder/

**Describe alternatives you've considered**
Unkown

**Comment by slonopotamus** [comment]
I believe this is a wrong project to report such issue and instead it should go to https://github.com/moby/moby

**Comment by mthalman** [comment]
@ohault - Why do you say this is not supported? Can you give an example of what's not working for you? You can see that we make use of the `--from` flag in our Windows Dockerfiles for .NET. See https://github.com/dotnet/dotnet-docker/blob/8e6da7a9fcde3a28b31faa7ef70d0fc3bcaf13d0/src/runtime/6.0/nanoserver-ltsc2022/amd64/Dockerfile#L40

**Comment by ohault** [comment]
@mthalman - I was trying either to rebase an existing Windows container image or to create a new smaller Windows Container base image by uninstalling/removing unwanted stuff from one of the existing Windows Container base images provided by Microsoft.

It was probably in relationship with a "FROM scratch" 

FROM scratch
COPY --from=....

In the while, I have found https://github.com/StefanScherer/rebase-docker-image

**Comment by brasmith-ms** [comment]
Hi @ohault, to our knowledge this command is supported. Furthermore, if there is a bug with this please file it in the Moby project.
