### ISSUE TITLE
Support of Docker commit for Windows Containers

### ISSUE THREAD

**Issue by ohault** [microsoft/Windows-Containers#240]
**Is your feature request related to a problem? Please describe.**
Currently, Windows Containers would not support Docker commit command.

**Describe the solution you'd like**
Implement a support of Docker commit command for Windows Containers. Ref: https://docs.docker.com/engine/reference/commandline/commit/

**Describe alternatives you've considered**
Unkown

**Comment by slonopotamus** [comment]
I believe this is a wrong project to report such issue and instead it should go to https://github.com/moby/moby

**Comment by ohault** [comment]
I'm referencing here the underlying (snapshot) support required in Windows Container to provide a way to implement the commit command.

**Comment by adamrehn** [comment]
@ohault `docker commit` does actually work for Windows containers, [just not while they're running](https://github.com/moby/moby/blob/v20.10.18/daemon/commit.go#L126). They need to be stopped first, either by closing the entrypoint process or by using `docker stop`. From what I can tell, this actually worked [as far back as January 2017](https://www.ntweekly.com/2017/01/16/part-7-save-windows-container-a-docker-image/).

**Comment by ohault** [comment]
@adamrehn indeed, this ticket need to be clarified to avoid unwritten assumption. In the title and the description, I propose to rename "for Windows Containers" in "for running Windows Containers", or do you want to suggest something else ?

**Comment by 07110711** [comment]
Пн, 24 апр. 2023 г. в 14:41, microsoft-github-policy-service[bot] <
***@***.***>:

**Comment by brasmith-ms** [comment]
Hi @ohault, like was mentioned docker commit will work for Windows containers when the container is stopped. I appreciate the suggestion, but there is no room for work to support commit while running on our roadmap at the moment.
