### ISSUE TITLE
Windows Server 2019 no internet access

### ISSUE THREAD

**Issue by stonesbg** [microsoft/Windows-Containers#241]
**Describe the bug**

We are currently deploying GCP Windows Server 2019 (specifically this image `windows-2019-for-containers`).  We hit a rather weird issue where when creating a new vm instances sometimes the containers that run on the machine don't have internet access.  The base image that we are using for our containers are `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019`.

As part of GCP we are using Managed Instance Groups which allow us to recreate if there is an issue and recreation doesn't solve this issue.

I have tried to create a new custom nat and this behaves the exact same.  Looking at the interface shows the right Ethernet adapter has the higher priority.

The work around is to create a transparent network using `docker network create -d transparent test_net` and then removing it.  Whatever this does (I am guessing to the external  nic) fixes the issue.  As part of the creation, we don't connect any containers to it.

This network is created while the other containers are running and are connected to the default nat.

Why would create a temporary transparent network fix the nat connectivity to the internet?

**To Reproduce**

Not reproducible in all instances.  Only happened on 3 of the 30 machines.

1. Create a Managed Instance Group using base image  windows-2019-for-containers
2. Create 2 VM Instances
3. Using docker-compose to pull and run the docker containers.
4. using docker exec <container_name> powershell ping 8.8.8.8

**Expected behavior**

Default container nat allows for connecting to the internet.

**Configuration:**

 - Edition: Windows Server 2019 Datacenter
 - Base Image being used: aspnet:4.8-windowsservercore-ltsc2019
 - Container engine: docker
 - Container Engine version 19.03.19

**Additional context**

When trying to diagnose:

- Unable to ping 8.8.8.8
- Unable to resolve google.com
- You are able to ping Host IP
- You are unable to other MIG VM instances
- HNS Service is Started
- HNS information Get-HNSNetwork and Get-HNSEndpoint looked fine (as far as I could tell)
- Windows Server 2019 doesn't appear to have a way to look at the virtual switch
- Internal network information has the correct default gateway, also the host DNS server entries to communication with NIC was setup
- Ran debug-container-host.ps1 but nothing stood out other than it couldn't find Get-VMSwitch as a cmdlet

**Comment by stonesbg** [comment]
Issue still exists, waiting for communication

**Comment by fady-azmy-msft** [comment]
Hey @stonesbg , can you try to repro this using containerd as the container runtime? This will help eliminate the NIC being the issue as containerd doesn't hot add it.

**Comment by stonesbg** [comment]
I am going to close this issue for right now.  So far, I have not been able to find/reproduce the issue since moving to bigger instances size e2-meduim to n2-standard-2.

**Comment by stonesbg** [comment]
@fady-azmy-msft I was able to get a system that has experienced the issue.  I installed containerd (specifically `containerd github.com/containerd/containerd v1.6.0-rc.1 ad771115b82a70cfd8018d72ae489c707e63de16.m`).

As a test I am creating a base image rather than one that I created to rule out it is something to do with the container that I am creating. `ctr run --cni --rm -t mcr.microsoft.com/windows/nanoserver:1809 test`

The containerd was using the same default nat and when running `ping 8.8.8.8` it couldn't process it.  Only after running the below does things come to life both the docker engine containers and containerd.

```powershell
$transparent_net = -join (((48..57) + (65..90) + (97..122)) * 80 | Get-Random -Count 12 | % { [char]$_ })
docker network create -d transparent ${transparent_net}_net | Out-Null
docker network rm ${transparent_net}_net | Out-Null
```

Let me know if you need more info.  My assumption something either gets changed in the vethernet or the nat when the transparent network gets created.

Docker Version: Docker version 19.03.19, build 5b7ee53
