### ISSUE TITLE
How to block GPU from the host system? 

### ISSUE THREAD

**Issue by LiuChangFreeman** [microsoft/Windows-Containers#242]
I'm packaging a program into Windows Container.   
It works well in hyper-v mode but when I try `--isolation=process` it always exits with failure.   
I tested it on every machine of mine and it turns out that when the host system doesn't have a physical GPU(such as Virtual Machines) the process isolation can also be OK.    
So I'm wondering how to `block` the container from trying to use the physical GPU. 
Is there a CLI usage example?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by brasmith-ms** [comment]
Hi @LiuChangFreeman, GPU access is disabled by default when running a Windows server container. Please see this page for more information on what is supported https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration
