### ISSUE TITLE
MSDTC failed in AWS EKS environment when Windows Pod with GMSA configured connect to AWS RDS MSSQL instance

### ISSUE THREAD

**Issue by chemi0213** [microsoft/Windows-Containers#247]
Anyone buildup MSDTC successful in AWS EKS environment? I tried two case on AWS:
Case1: 
APP side: EC2 Windows 2019 server with container support, setup container image with docker run mcr.microsoft.com/windows/servercore:ltsc2019
DB side: AWS RDS MSSQL with MSDTC configured, refer to AWS blog post https://aws.amazon.com/blogs/database/enabling-distributed-transaction-support-for-domain-joined-amazon-rds-for-sql-server-instances/

Test result: MSDTC test successful

Case2:
APP side: AWS EKS cluster to run Windows Pod with same image: servercore:ltsc2019, refer to AWS blog post https://aws.amazon.com/blogs/containers/windows-authentication-on-amazon-eks-windows-pods/
DB side: AWS RDS MSSQL with MSDTC configured, refer to AWS blog post https://aws.amazon.com/blogs/database/enabling-distributed-transaction-support-for-domain-joined-amazon-rds-for-sql-server-instances/

Test result: MSDTC test failed

I've tried to capture via Wireshark at RDS side (since I choose custom RDS, it's normally an windows server I can login with it). Looks like Case2 have permission denied issue when DB inverse connect to PODs
![image](https://user-images.githubusercontent.com/13843245/179480882-d52f9d78-ccd4-4f8e-b3b4-601199d36b17.png)

Case1 for reference: (no permission denied issue)
![image](https://user-images.githubusercontent.com/13843245/179481099-4574b1ae-f965-41e1-89d6-2dd5f9b18f73.png)

I can now confirmed basic requirement below are good:

- DB and POD can ping each other via NETBIOS name
- POD can get accurate kerberos ticket from AWS managed Microsoft AD
- No firewall/Security group issues
- MSDTC well configured by
`Set-DtcNetworkSetting -Confirm:$false -DtcName "Local" -AuthenticationLevel NoAuth -InboundTransactionsEnabled $true -OutboundTransactionsEnabled $true -RemoteClientAccessEnabled $true -RemoteAdministrationAccessEnabled $true -XATransactionsEnabled $true -LUTransactionsEnabled $true`

Any suggestion for solving this issue? Thanks

**Comment by weijuans-msft** [comment]
Today MSDTC is supported only on limited scenarios. You can find more at our doc [here:](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/lift-shift-to-containers#applications-not-supported-by-containers). We haven't done any MSDTC validation on K8s platform either.

What is your app? Is it .NET Framework based? What version?

**Comment by chemi0213** [comment]
@weijuans-msft We use .NET 4.7.03190

`PS C:\> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full
    version    REG_SZ    4.7.03190`

We already knew MSDTC is supported only on limited scenarios, and we should fulfill the requirement you're listed:

- container name must match the gMSA name
- NETBIOS to solve/ping to each other
- Unique UUID for MSDTC

**Comment by chemi0213** [comment]
@weijuans-msft May I have an update for this issue?

**Comment by fady-azmy-msft** [comment]
Hello @chemi0213, are you still facing this issue?

**Comment by chemi0213** [comment]
Hi @fady-azmy-msft 
We're going to get rid of MSDTC when containerize our application. So we may no longer need the fix. However this issue still exists not only on AKS, but also affects other K8S platforms.

**Comment by fady-azmy-msft** [comment]
ACK. Closing because you'll no longer need the fix, but feel free to comment again so we can prioritize accordingly
