### ISSUE TITLE
Support for Edge on Windows Containers for automated UI testing

### ISSUE THREAD

**Issue by vrapolinario** [microsoft/Windows-Containers#25]
Request from User Voice: https://windowsserver.uservoice.com/forums/304624-containers/suggestions/34081195-edge

Need Edge in a container for automated UI testing

**Comment by vrapolinario** [comment]
Sorry for not making any comments on this.
This is still in our backlog so we'll close the issue for now. We're open to requests in case customers want to see this implemented.

**Comment by yoanchin** [comment]
as aoto tester,I want to see this implemented.
I want to create many type of  windows test envionment as docker images.
