### ISSUE TITLE
Can not run nanoserver docker container

### ISSUE THREAD

**Issue by rohitdalvi** [microsoft/Windows-Containers#252]
I have a windows2019 Datacenter server without GUI. The version of OS is 10.0.17763 N/A Build 17763.
I tried to run multiple tags from the list (https://mcr.microsoft.com/v2/windows/nanoserver/tags/list) including 10.0.17763*.
But I get this error,
`Error: failed to start container "windows": Error response from daemon: container windows encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)`

How can I find the right tag which is suitable and can run in my OS ?
Thanks.

**Comment by rohitdalvi** [comment]
I could not find the dockerfile for this image, it would  be  good to know what is the  command that container uses to start, as I am using this and probably thats  the reason it is not starting,
`- name: windows
            image: mcr.microsoft.com/windows/nanoserver:1809
            imagePullPolicy: IfNotPresent
            command:
            - powershell
            args:
            - Start-Sleep
            - 999999`

**Comment by lippertmarkus** [comment]
Nanoserver doesn't include PowerShell but you can use `cmd` instead

**Comment by mthalman** [comment]
If you want PowerShell, you can use `mcr.microsoft.com/powershell:nanoserver-1809` (see https://hub.docker.com/_/microsoft-powershell)

**Comment by fady-azmy-msft** [comment]
Thanks @mthalman for answering @rohitdalvi's question.

**Comment by mloskot** [comment]
@lipp
> Nanoserver doesn't include PowerShell but you can use `cmd` instead

There is no `TASKLIST` on NanoServer
