### ISSUE TITLE
Windows Server 2022 Container on Windows Server 2019 Host?

### ISSUE THREAD

**Issue by oZakari** [microsoft/Windows-Containers#253]
Is it possible to run a Windows Server 2022 container image on a Windows Server 2019 host? Looking at this [document](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-11-21H2) it looks like it's not supported by Microsoft. However, the documentation states that they it still may be "possible, but not guaranteed" if there is a mismatch between the host and container.

**Comment by michbern-ms** [comment]
I think that document is our best statement of understanding: running a Server 2022 container image on a Server 2019 host is not supported.

**Comment by olljanat** [comment]
With Hyper-V isolation is might be possible but I highly recommend not to use it but instead of deploying Win 2022 hosts to be able to run containers in process isolation mode.

**Comment by oZakari** [comment]
Thank you both, appreciate it!
