### ISSUE TITLE
Cannot run Tasklist or Taskkill in Nanoserver 2022 in Docker

### ISSUE THREAD

**Issue by Sudoite** [microsoft/Windows-Containers#254]
Newbie question here. I'd like to debug a process running in a Nanoserver Docker container (I'm running nanoserver:ltsc2022). But to do that I need to know the process ID to attach to and Tasklist.exe is not available. Other than copying Tasklist.exe and any necessary DLLs in from outside, are there any native options? Similarly, if I'd like to kill a task with Taskkill, what can I do? I noticed [here ](https://github.com/microsoft/Windows-Containers/issues/252#issuecomment-1191466977) that I there's a Nanoserver 1809 instance with PowerShell, is that my best option? Are there any others? I'm hoping I've overlooked some useful CMD command. Already tried netstat -aon, but my process isn't listening on a port. Thanks!

**Comment by fady-azmy-msft** [comment]
Hey @Sudoite. I'm going to assume you're running a process isolated container, and you're trying to get the process id of the process so the debugger can connect to it.

The easiest option would be to run the debugger from the host. You can: 
1. launch taskmgr
2. go to the details tab
3. right click on of the column headers to select a new column to be displayed (the session id column)
4. Then I sort by session id. 

If you only have one container running, you can find the session your container is running in by looking for the CExecSvc.exe process. Whatever session ID it is in, the process should be in the same session. Now you can find the process id for the process, and launch the debugger on the host and connect to the process.

**Comment by Sudoite** [comment]
Hi @fady-azmy-msft , thanks so much! Yes you are right, and I got that to work for me. I can also infer from your response that I can similarly kill the process from outside the Docker container if needed. And indeed that is true. Awesome! I'm a happy camper. I can also infer that I should be able to use Powershell from the host to automate the process of killing troublesome processes in the Docker container. I'll post another question if I can't figure it out. Super helpful answer, thank you.
