### ISSUE TITLE
Data execution prevention settings in windows server container image

### ISSUE THREAD

**Issue by sriluxman** [microsoft/Windows-Containers#255]
**How to change the data execution prevention support policy of the container?**

Inside my mcr.microsoft.com/windows/servercore:1809 container I want to set the DEP level to 0.

I ran: 
wmic OS Get DataExecutionPrevention_SupportPolicy

result:
DataExecutionPrevention_SupportPolicy
2

To set it to off when I run:

bcdedit.exe /set nx AlwaysOff

I encounter an error message:
The boot configuration data store could not be opened.
The requested system device cannot be found.

How is it possible to turn of the DEP?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@akarshm, please provide an update or close this issue.

**Comment by plooploops** [comment]
@sriluxman 
Out of curiosity, what are you trying to achieve by setting the data execution prevention level to 0 in this scenario?

We don't provide a way to control this setting within the container.  Rather Windows Server Containers will inherit the DEP settings from the host, so if you'd like to change these settings in the container, you would need to run your desired `bcdedit.exe` commands on the host, restart the host, and then run your container.

**Comment by fady-azmy-msft** [comment]
Closing because issue is going stale.

**Comment by fady-azmy-msft** [comment]
Providing more context on this for those interested on this use case. We don't provide a way to control this setting within the container. Rather Windows Server Containers will inherit the DEP settings from the host, so if you'd like to change these settings in the container, you would need to run your desired bcdedit.exe commands on the host, restart the host, and then run your container.
