### ISSUE TITLE
Python program running in windows container reboots the host (windows 10 host)

### ISSUE THREAD

**Issue by nchandra-seg** [microsoft/Windows-Containers#259]
**Describe the bug**
Windows container allocated 8GB, 4 core cpu. python program calculating size of 500GB dir, reboots VM itself. (VM is running on VMware host)

**To Reproduce**
Windows 10 host. Running  * Docker version 20.10.6, build 370c289 *. Windows host has 16GB RAM, 2 CPU, 8 cores.
Create Docker container from the image
mcr.microsoft.com/windows/servercore:ltsc2019.
with options :  -m 8g --cpus="4" 

python get_size.py:
============
```
import os
import time

def get_size(start_path = '.'):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(start_path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            # skip if it is symbolic link
            print(f)
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)

    return total_size

print(get_size(start_path="//network/huge_dir"), 'bytes')
```

//network/huge_dir is 525GB.
Running this python program in windows container reboots host itself. Please note I can run this program directly on the host without any problem.

```
From the container:
PS C:\> systeminfo | select-string 'Total Physical Memory'

Total Physical Memory:     8,703 MB


PS C:\> systeminfo | select-string 'Processor'

OS Build Type:             Multiprocessor Free
Processor(s):              1 Processor(s) Installed.


PS C:\> Get-WmiObject -class Win32_processor | Format-Table Name,NumberOfCores,NumberOfLogicalProcessors

Name                                      NumberOfCores NumberOfLogicalProcessors
----                                      ------------- -------------------------
Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz             4                         4

PS C:\> hostname
d0db4c58d66d
``` 
**Expected behavior**
Since we are capping the memory and cpu, this should not reboot the system. Docker should have killed the program if memory and cpu is very high.  I have ran similar program on linux. Kernel kills docker container(it's a process in linux), if CPU and memory is 100% for few mins.

**Configuration:**
Windows 10, Docker Desktop: Docker version : * Docker version 20.10.6, build 370c289 *. Windows host has 16GB RAM, 2 CPU, 8 cores.
Docker container : mcr.microsoft.com/windows/servercore:ltsc2019.

**Additional context**

**Comment by fady-azmy-msft** [comment]
I've opened an internal bug (ADO #: 40981735), someone from the team will look into this shortly.

**Comment by nchandra-seg** [comment]
Thanks @fady-azmy-msft

**Comment by thecloudtaylor** [comment]
@nchandra-seg - one point of clarification/awareness. With resource limits applied ( -m 8g --cpus="4") we won't kill the container, but it should be limited to 8GB of memory and affinized to 4 CPUs.  

Regardless the host should not reboot or crash so we're definitely going to be looking into that - thank you for opening the issue!

**Comment by nchandra-seg** [comment]
Thanks @thecloudtaylor. That would be great.
We are not able to use Windows Container due to this. Let me know if you need anything else from the system.

**Comment by nchandra-seg** [comment]
@thecloudtaylor : Can you please provide an update on this.

**Comment by fjs4** [comment]
@nchandra-seg: I took a stab at reproducing this but was unable to.  Perhaps my environment wasn't quite the same.  However, if the host is rebooting, I suspect it is bugchecking.  Can you check to see if a memory.dmp file is being created in the c:\windows directory?

**Comment by nchandra-seg** [comment]
@fjs4 : Yes it is being created. What can I check in that?

**Comment by fjs4** [comment]
@nchandra-seg - Thanks for confirming.  Could you send the memory.dmp to Microsoft via this email address: WindowsContainerGitHubIssues@service.microsoft.com.  Then we can examine it to try to find the cause for the crash.  If your dump is too large to attach, then you might need to change the type of crash dump created to a kernel (or mini) dump to reduce the size.

**Comment by thecloudtaylor** [comment]
We can also create a OneDrive drop box for the dump if you send mail to that address, one of the team can reply with a link.

**Comment by fady-azmy-msft** [comment]
Closing this thread due to inactivity.

**Comment by nchandra-seg** [comment]
Can I please get back next week. I am travelling.
