### ISSUE TITLE
Provide support for Office for Windows Containers

### ISSUE THREAD

**Issue by vrapolinario** [microsoft/Windows-Containers#26]
Request from User Voice: https://windowsserver.uservoice.com/forums/304624-containers/suggestions/19686220-provide-office-support-for-containers

Many Business Application are dependent on Office to edit files or import/export of ppt or word formats. So adding office support for Containers would be a good idea.

**Comment by zhiweiv** [comment]
Any plan or progress?

**Comment by vrapolinario** [comment]
Hi @zhiweiv, this item is still under our backlog. We'd love to better understand the scenarios on which this would be needed so if you have more details on this ask, we'd love to hear it.
Thanks.

**Comment by zhiweiv** [comment]
We use Outlook MAPI to manipulate pst files, in existing architecture we install office 2013 to Azure VM, then run our application in Azure VM.

We are on the way to containerize our applications, office is blocker for this type of workload.

**Comment by vrapolinario** [comment]
Thanks for the details @zhiweiv. Just to confirm, you need Outlook support on containers to run the referenced application, not the whole Office package, correct? Also, can you share more details on the manipulation of PST files? Just trying to understand the goal of your application so we can provide the best alternative or take this internally for analysis.
Thanks!

**Comment by zhiweiv** [comment]
We use Redemption(http://dimastr.com/redemption/home.htm) to add mail/folder/contact etc to pst files. Redemption has dependency on Outlook.

The application we are about to containerize is a legacy service, it is unlikely to make big changes to use other solution.

**Comment by vrapolinario** [comment]
Thanks for the additional details @zhiweiv. We'll take this internally and check what we can do from the container platform. For now this item will continue on our backlog, but we'll update once have any news.
Regards.

**Comment by vrapolinario** [comment]
Apologies for the delay in providing a response here. We're still investigating with the Office team on this issue, but not update or timeline at this moment. I'll change the tag to In progress, to reflect the state of our investigation.

**Comment by zhiweiv** [comment]
We replaced Redemption by Aspose, Outlook is no longer needed.

**Comment by vrapolinario** [comment]
I have checked with the Office team internally. The current statement is that Office products are not supported on Windows Containers not a scenario they are looking into. They do, however, encourage folks to provide feedback on their UserVoice channel: https://office365.uservoice.com/

I'll be closing this issue as a solution for this would have to come from the Office team.

**Comment by weijuans-msft** [comment]
@zhiweiv I am late in this "party" :). I noticed you no longer needed Outlook hence Office support as you moved to use Aspose. I am curious: which Windows container image do you use today? Is it Server Core or the Windows one?

**Comment by zhiweiv** [comment]
We use .NET Framework on Windows Server Core.
