### ISSUE TITLE
Cannot install KB5015733 in windows/server:ltsc2022

### ISSUE THREAD

**Issue by sphr2k** [microsoft/Windows-Containers#261]
**Describe the bug**
I'm trying to create a Windows Server 2022 (mcr.microsoft.com/windows/server:ltsc2022) (i.e. full edition) image w/ .NET Framework 3.5.

Installation of the 2022-08 Cumulative Update for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 ([KB5015733](https://www.catalog.update.microsoft.com/Search.aspx?q=5015733)) fails, apparently due to a reboot being required. 

I based my Dockerfile on the one from the official MS .NET Docker repo: [https://github.com/microsoft/dotnet-framework-docker/blob/main/src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile](https://github.com/microsoft/dotnet-framework-docker/blob/main/src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile).

I guess the issue is that a reboot is requested by DISM, which, of course, is not possible when building a container. I tried wrapping the DISM command like this

```batch
@if not defined _echo echo off
setlocal enabledelayedexpansion

call %*
if "%ERRORLEVEL%"=="3010" ( exit /b 0 )
```

to deal with the non-zero exit code, but no matter what I do, the Hotfix is not installed in the final image.

Installation of the base CAB (`microsoft-windows-netfx3-ondemand-package~31bf3856ad364e35~amd64~~.cab`) works fine.

This is what the list of hotfixes looks like in the final image:

```
$ Get-HotFix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
ED8F5C4EF702  Update           KB5013630                          8/14/2022 12:00:00 AM
ED8F5C4EF702  Security Update  KB5016627                          8/6/2022 12:00:00 AM
ED8F5C4EF702  Update           KB5015897                          8/6/2022 12:00:00 AM
```

**Configuration:**
 - Edition: Windows Server 2022
- Base Image being used: mcr.microsoft.com/windows/server:ltsc2022
 - Container engine: Docker
 - Container Engine version: 20.10.9

**Comment by sphr2k** [comment]
@mthalman Maybe you have an idea how to deal with this? Any feedback would be appreciated :)

**Comment by sphr2k** [comment]
Here's the [dism.log](https://github.com/microsoft/Windows-Containers/files/9333675/dism.log)

**Comment by mthalman** [comment]
@sphr2k - I'm not seeing the same thing you are. I took the Dockerfile at https://github.com/microsoft/dotnet-framework-docker/blob/main/src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile, replaced `servercore` with `server` in the base image tag, and it built fine. Make sure you've pulled the latest `server` base image.

**Comment by sphr2k** [comment]
@mthalman Sorry, you're right. I might have made a mistake along the way somehow.
