### ISSUE TITLE
Process mode not work on Windows10 (2004).

### ISSUE THREAD

**Issue by CheaterScript** [microsoft/Windows-Containers#262]
Hi.
I use process mode on Windows10 version 2004, but it's not work.
Somebody can help me?

`C:\Users\Zan>docker run -it --isolation=process mcr.microsoft.com/windows:2004`
`docker: Error response from daemon: container f1ad66ad7573c52a861865ada2d7f44625641f6ae2f57682044d44c46f7419fe encountered an error during hcsshim::System::Start: context deadline exceeded.`

**Comment by mthalman** [comment]
Be aware that Windows 10, version 2004 has been [out of support](https://docs.microsoft.com/lifecycle/announcements/windows-10-version-2004-end-of-servicing) since Dec 2021.

**Comment by fady-azmy-msft** [comment]
Hey @dcantah, have you seen this before?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@dcantah, please provide an update or close this issue.

**Comment by riyapatel-ms** [comment]
@CheaterScript are you experiencing this issue with other versions of Windows 10 as well? Could you provide me with more specifications of the Docker version you are using in your environment? 

_edit:_ https://github.com/microsoft/hcsshim/issues/801 does this seem like it could be related to your issue as well?

**Comment by riyapatel-ms** [comment]
@CheaterScript I would also take a look at https://github.com/microsoft/Windows-Containers/issues/163, which should give you some additional clarity on your issue. 

Closing, feel free to reach out if you have any other concerns.
