### ISSUE TITLE
DaemonSet with HostProcess initContainer and non-HostProcess Main Container

### ISSUE THREAD

**Issue by gianniskt** [microsoft/Windows-Containers#264]
Hello,

I am trying to apply a **DaemonSet** on an AKS Cluster, which I need to execute a PS Script on all AKS Windows Nodes via **HostProcess** Container technique -> https://docs.microsoft.com/en-us/azure/aks/use-windows-hpc

[daemonset.txt](https://github.com/microsoft/Windows-Containers/files/9394432/daemonset.txt)

The configuration has an **initContainer**, that should run a **Powershell Script on all Windows Nodes**, and a **main Container**, that I use it as **"sleep" container.**

What I am trying to do, is to apply **different SecurityContext for initContainer** (which I need it to be **HostProcess**, as it should run on the AKS Windows Hosts once), and **different SecurityContext for the main Container** (which I want to be **non-HostProcess**, as I don't want to have Privileged Containers running in my Cluster).

After troubleshooting, I receive the error below:

![image](https://user-images.githubusercontent.com/38279583/185926133-e6504b56-f748-4d87-bdf0-960b10558cc5.png)

If I remove the last lines of the configuration, which I am trying to disable HostProcess for the main Container, the DaemonSet is running successfully, the initContainer does it's job, and then the main container is running.

As you may understand, there is a big security issue, because there is a **Privileged Pod running in the cluster!**

Has anyone faced a similar issue? Is there any workaround for this problem? Any ideas are welcome!

**Comment by lippertmarkus** [comment]
Like the error and the docs (https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/#limitations) state, that's a current limitation of the Windows platform.

**Comment by gianniskt** [comment]
@lippertmarkus Ok I understand the limitation. 
Is there any other idea how can I achieve these actions?
Running a PS Script on all Windows AKS Nodes, and not having any Privileged Pods (or similar security gap) alive in the cluster, after script execution.

**Comment by lippertmarkus** [comment]
There's no built-in way, but you could use external controllers like https://openkruise.io/docs/user-manuals/broadcastjob that provide "Daemon Jobs", so running Jobs on all nodes without having a "pause" container.

**Comment by brasmith-ms** [comment]
Hi @gianniskt, like Markus mentioned you cannot mix HostProcess and regular WS containers in a single pod, but you can run multiple pod types on the same node. You can use the HostProcess container to set up a long-running job / daemon on the host and then exit - after which no privileged container should be left running. A non-privileged pod can be run on the same node with the normal security restrictions in place. You should not be running business logic in a privileged pod to minimize the security risk.
