### ISSUE TITLE
Signtool within a windowsservercore-ltsc2019 container failing when using /fd SHA256

### ISSUE THREAD

**Issue by zosocanuck** [microsoft/Windows-Containers#265]
**Describe the bug**

We have a system which Authenticode signs files such as .DLL, .EXE, etc. We use SA256 hashing when adding the certificate with signtool with the following command line:

signtool.exe sign /debug /fd SHA256 /sm /sha1 .

Putting this into a Windows container, using windowsservercore-ltsc2019 running on a Windows Server 2019 node, signtool fails with 0xC0000225.

Error code 0xC0000225, as far as I can see, is to do with not being able to find a system file.

If we use signtool.exe sign /debug /fd SHA1 /sm /sha1 this works and successfully signs, however, we don't want to use a SHA1 hash.

Has anyone else encountered this issue, or is aware of a patch to the Microsoft image windowsservercore-ltsc2019 that we can apply to fix this issue?

**To Reproduce**
Use mcr.microsoft.com/windows/servercore:ltsc2019 with Windows SDK (signtool)

**Expected behavior**
Expected to work with SHA256 digest

**Configuration:**
- servercore:ltsc2019
- Docker engine community 1.42

**Comment by fady-azmy-msft** [comment]
Hey @zosocanuck, someone will be looking into this shortly! I've created an internal ticket (#41056707) to track this :)

**Comment by fjs4** [comment]
Hi @zosocanuck, I tried to repro this.  I tried a slightly different command then line then you.  I did the following:

signtool sign /f mycert.pfx /fd SHA256 foo.exe

That worked fine for me.  I tried this on Windows Server 2019.  Can you check if signing in this way works for you?
