### ISSUE TITLE
How to run "netsh trace start" and "netsh trace stop" in Windows Server Core 2019 Container?

### ISSUE THREAD

**Issue by alex031029** [microsoft/Windows-Containers#270]
I wish to use netsh trace to capture network trace within server core container. It returned an error 
`The inbox capture driver could not be started (error=0x800106d9)`. After searching it in the Internet, I could not find any solid answer. So I am wondering if there is a solution to run `netsh trace start` in server core container. Thanks.

![image](https://user-images.githubusercontent.com/2452221/188537823-fba63951-fd24-4e93-88b1-fafebc07b40a.png)

**Comment by fady-azmy-msft** [comment]
Hey @alex031029 , I've reached out to the team to get you an answer to this and will get back to you shortly (internal ticket #41246995).

**Comment by jsturtevant** [comment]
What are you trying to accomplish?

If you are using process isolated containers, you can do this from the host and capture the events and container traffic.  I am not sure If it should work in Hyper-v containers.

**Comment by alex031029** [comment]
> Hey @alex031029 , I've reached out to the team to get you an answer to this and will get back to you shortly (internal ticket #41246995).

Thanks @fady-azmy-msft  for your help. Looking forward to your response.

**Comment by alex031029** [comment]
> What are you trying to accomplish?
> 
> If you are using process isolated containers, you can do this from the host and capture the events and container traffic. I am not sure If it should work in Hyper-v containers.

I wish to capture the network trace within the container. But just as you said, capture from the host is also feasible. Still, I am curious why "netsh trace start" command cannot work within the container.

**Comment by fady-azmy-msft** [comment]
Hey @alex031029 , I spoke with my engineering team and "running netsh trace start/stop" isn't currently supported in containers. Moving forward we'll look into adding support in the future.

**Comment by mainred** [comment]
@fady-azmy-msft  May I ask do we have a plan for this enhancement?

**Comment by mike-estes-fl** [comment]
Would be nice to have.  Trying to troubleshoot a network issue with GHA using our AKS runners in Azure but we get the same failure.  This is on Windows Server Datacenter 2022 Core.

Tried using pktmon instead of netsh trace, thinking that perhaps the newer way of doing captures would work, but it fails as well.
