### ISSUE TITLE
Docker CE warning TLS1.2

### ISSUE THREAD

**Issue by yrest** [microsoft/Windows-Containers#274]
Have installed Docker using install-docker-ce.ps1 on Windows Server 2022 Datacenter

Receiving the following warning, please advise?

Microsoft container registries will switch to TLS v1.2 very soon and your version of Docker does not support this. You should install a new version of docker asap (version 18.03.0 or later)

**Comment by brasmith-ms** [comment]
Hi @yrest, please use the latest version of the script with the latest version of docker (as of right now 24.xx)
