### ISSUE TITLE
com registration not working in a windows container

### ISSUE THREAD

**Issue by bnagajagadeesh** [microsoft/Windows-Containers#275]
I've a requirement to register a third party COM DLL in a windows container which will be used by .Net framework application. 

I've used below base image.
mcr.microsoft.com/dotnet/framework/runtime:4.8

and then used below command to register a DLL
COPY ./TestCom.dll ./
RUN regsvr32 ./TestCom.dll /s

When I run container, I'm getting below error.
Retrieving the COM class factory for component with CLSID {CE92C3B9-9A93-40E1-85AB-6A49170AEF7F} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

Can you please let me know what is the issue here?

**Comment by mthalman** [comment]
I'm no COM expert but could this perhaps be related to the container being x64? Is this DLL 32-bit at all?

cc @richlander

**Comment by bnagajagadeesh** [comment]
Thanks for your response. I've checked com DLL and found that it is 64 bit. Anyone having a solution to this issue?

**Comment by fady-azmy-msft** [comment]
Hey @bnagajagadeesh , thank you for raising this issue. What OS are you using and is this a custom DLL?

**Comment by bnagajagadeesh** [comment]
@fady-azmy-msft, Sorry I missed your comment. Yes, it a custom DLL and OS is Windows

**Comment by bnagajagadeesh** [comment]
I was able to resolve the issue using registration free COM Interop.
https://learn.microsoft.com/en-us/dotnet/framework/interop/registration-free-com-interop
