### ISSUE TITLE
How to run and display graphic programs

### ISSUE THREAD

**Issue by Liuccysdgg** [microsoft/Windows-Containers#279]
Can I do this by starting Remote Desktop? However, I failed to start Remote Desktop. If there are relevant documents or cases, Please provide it, thank you.

**Comment by fady-azmy-msft** [comment]
Hey @Liuccysdgg , can you clarify what you mean by graphic programs and why did Remote Desktop fail to start?

**Comment by fady-azmy-msft** [comment]
@Liuccysdgg Windows Containers don't support GUIs, you can instead change it to a silent install. Here's a blog that discusses this in more detail - https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/lift-shift-to-containers#what-cant-be-moved-to-windows-containers

**Comment by Liuccysdgg** [comment]
thank you for your answer. I don't have the source code of GUI program. It seems that it can't run in Docker, and the container scheme can't be a candidate.
@fady-azmy-msft
