### ISSUE TITLE
[Feature] gMSA support in AKS 

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#28]
Support of gMSA so that Windows applications using gMSA can run as Windows Containers on AKS.

**Comment by immuzz** [comment]
We are making significant progress here. Stay tuned for good news.

**Comment by schlbra** [comment]
Any good news to report back?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.

**Comment by vrapolinario** [comment]
The work for this is in progress and we expect to have something to announce soon.

**Comment by vrapolinario** [comment]
Just to keep this issue updated: We continue to make progress on this and expect to have something to announce externally soon.

**Comment by rjayapra** [comment]
@vrapolinario Any timeline for this feature availability ?

**Comment by vrapolinario** [comment]
We don't have a timeline that we can provide publicly at this point. For customers interested in gMSA on AKS, please reach out to me privately at viniap@microsoft.com or to your account team.

**Comment by jsturtevant** [comment]
This is preview now: https://docs.microsoft.com/en-us/azure/aks/use-group-managed-service-accounts

**Comment by vrapolinario** [comment]
This has now moved to Public Preview, so I'll be closing the issue. Please let us know with new issues if you see any bugs or has any feedback.
