### ISSUE TITLE
Windows python image is break after recent image release

### ISSUE THREAD

**Issue by xia-xiao** [microsoft/Windows-Containers#280]
**Describe the bug**
Windows python image is break

**To Reproduce**
docker pull mcr.microsoft.com/windows-cssc/python3.7.2nanoserver:ltsc2019

ltsc2019: Pulling from windows-cssc/python3.7.2nanoserver
invalid rootfs in image configuration

**Expected behavior**
It should pull the image success.

**Configuration:**
 - Edition: Windows Server 2022
- Base Image being used: Windows Nano Core
 - Container engine: docker
 - Container Engine version 20.10.17

**Additional context**

**Comment by plooploops** [comment]
Hi @xia-xiao, thank you for reporting this, the latest images should be published.

Can you please retry with `docker pull mcr.microsoft.com/windows-cssc/python3.7.2nanoserver:ltsc2019`?

**Comment by plooploops** [comment]
With the re-publish, you can re-pull the images now:

`docker pull mcr.microsoft.com/windows-cssc/python3.7.2nanoserver:ltsc2019`

@xia-xiao Can you confirm this works for you? If it does, you can close this issue?

**Comment by xia-xiao** [comment]
This is work for me.

**Comment by plooploops** [comment]
Thank you for the verification!
