### ISSUE TITLE
Windows Server Core with Desktop Experience

### ISSUE THREAD

**Issue by baendron** [microsoft/Windows-Containers#284]
Good day,

I am currently trying to convert an existing ASP.NET framework project to use Docker. In the process of doing so, I've run into an issue where my project requires Desktop Experience to run properly. This issue is related to missing ACM codecs for playing WAV files using NAudio. Searching for solutions to this issue have indicated that this is because the Desktop Experience features are missing from the installation of Windows Server Core. 

As such, I have been trying to search for base images for Windows Server Core with this feature enabled but I am struggling to find anything related to this.

I am currently using `mcr.microsoft.com/windows/servercore:ltsc2019` but this does not seem to have Desktop Experience enabled. Is anyone able to provide any help on how to enable Desktop Experience with this image or provide a link to an image that has that feature enabled?

I have checked with the Windows Server Core team and was told to ask the same question here.

**Comment by vrapolinario** [comment]
To clarify: Windows containers don't support applications that require GUI, so the Desktop experience is not present - neither on Server Core or Nano Server. However, what seems to be the case for you is that you need some specific APIs, not the GUI itself. For that case, I'd recommend either the Server image (which requires Windows Server 2022) or the Windows image (which works on Windows Server 2019, but is now out of support)

Here is a blog post about this topic: https://techcommunity.microsoft.com/t5/containers/nano-server-x-server-core-x-server-which-base-image-is-the-right/ba-p/2835785

Here are the images:
Server: `docker pull mcr.microsoft.com/windows/server:ltsc2022`
Windows: `docker pull mcr.microsoft.com/windows:20H2` (NOTE: This is now out of support)

**Comment by baendron** [comment]
Hi vrapolinario,

thanks for the image link! this seems to work for me.
