### ISSUE TITLE
Is logrotation supported by the kubelet on windows nodes?  

### ISSUE THREAD

**Issue by aleberkn** [microsoft/Windows-Containers#286]
**What is your question?**
A clear and concise description of what your question is. If you have bug/blocker, please open a 'Bug Report' issue instead.

**Comment by AbelHu** [comment]
There is a known issue in k8s https://github.com/containerd/containerd/issues/7075

**Comment by fady-azmy-msft** [comment]
I'm going to resolve this issue as there's another issue tracking the same thing on a more related repo.

**Comment by mosabami** [comment]
heres the issue hes refering to: https://github.com/containerd/containerd/issues/7075
