### ISSUE TITLE
Microsoft Artifact Registry down?

### ISSUE THREAD

**Issue by alishawong-credera** [microsoft/Windows-Containers#289]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**

I can't pull images from the artifact registry.

https://mcr.microsoft.com/ is down.

Specifically I am trying to use the nanoserver image (mcr.microsoft.com/windows/nanoserver:ltsc2022) in Azure App Services but i'm getting an error. This was working just a couple hours ago. 

`docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022` locally doesn't work either.

**To Reproduce** 

`docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022`

**Expected behavior**
Image to be pulled out without error.

**Configuration:**
- Base Image being used: Windows Nano Server
 - Container engine: Docker

**Comment by fady-azmy-msft** [comment]
Hey @alishawong-credera , can you share the error you're seeing?

**Comment by alishawong-credera** [comment]
If I go to mcr.microsoft.com I get:
![image](https://user-images.githubusercontent.com/103436989/200900184-4723589e-7c16-4e6e-914e-dd0cc1fd0694.png)

I've been deploying an application in Azure using Terraform and have been using the `mcr.microsoft.com/windows/nanoserver:ltsc2022 ` image fine up until lunchtime today UK time.

![image](https://user-images.githubusercontent.com/103436989/200900563-7900ca28-cee5-42e4-9f31-69a2ec1cc503.png)

The `DOCKER_REGISTRY_SERVER_URL` is a bit of a red herring. it's showing this because it can't connect to the registry.

**Comment by alishawong-credera** [comment]
This was working this morning (9am UK time) and now the service is down again. I can't find any information online about this.
![image](https://user-images.githubusercontent.com/103436989/201116371-f4e1c72a-a63f-4aa1-8ef3-ebae96dc8304.png)

I can't even create a windows web app with a quickstart image - 
![image](https://user-images.githubusercontent.com/103436989/201117171-c34be3a9-a106-4546-b65a-0bbe4dc9dea5.png)
![image](https://user-images.githubusercontent.com/103436989/201117208-46df0a88-374d-4ddd-b5a1-854aefe88a5a.png)

**Comment by jsturtevant** [comment]
this was an issue with the MCR website which has been resolved now.
/close

**Comment by unmultimedio** [comment]
We've been having issues today as well with similar error messages while downloading images from mcr. Is there a status page we can check for the uptime of the service?
