### ISSUE TITLE
[Feature] Calico Network Policy Support for Windows Containers on AKS

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#29]
Calico Network policy support for Windows Containers on AKS

**Comment by immuzz** [comment]
cc: @mkostersitz

**Comment by mkostersitz** [comment]
The work for this is in progress. We are expecting this to become available end of the year/early next year.

**Comment by mkostersitz** [comment]
The work for this is in progress. We are expecting this to become available end of the year/early next year

**Comment by jsturtevant** [comment]
Calico Windows on AKS is in preview: https://azure.microsoft.com/en-us/updates/public-preview-calico-windows-support-in-aks/
