### ISSUE TITLE
Run 20H2 containers on a server 2022 host?

### ISSUE THREAD

**Issue by edwardvandevorst-philips** [microsoft/Windows-Containers#294]
**What is your question?**
Is it possible to run 20H2 containers on a server 2022 host?

**Comment by judyliu-ms** [comment]
Hi @edwardvandevorst-philips, no it is not. Windows Server host and container image must match versions. The only exception to this rule is you can run WS2022 containers on Windows 11 hosts. 

Another thing to note is Windows Server 20H2 reached the end of servicing on Aug 9, 2022.
