### ISSUE TITLE
Not able to build Windows Server core image ltsc2022

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/Windows-Containers#295]
Hi Team, 
I am trying to build my application base image which depends upon the Windows Server core as you see below. 

![image](https://user-images.githubusercontent.com/17148381/205899171-a46b4043-b73a-4b0b-b620-cbb363595e36.png)

For the faster building of the image, I have already pulled the image on my local, but when I try to build my application image, I get the below manifest not found error. 
![image](https://user-images.githubusercontent.com/17148381/205899480-456d62a1-1fa1-4653-b930-a354dcf7b3f9.png)

Before following the above I have already switched my docker to Windows containers. 

Below is my system info. 

![image](https://user-images.githubusercontent.com/17148381/205899800-382f49e4-5f5d-4294-be14-db532fbc7ef1.png)

**Comment by derek-williams-hcl** [comment]
I am running in to the same error.  How do you switch the docker to Windows containers?   I am also on a Mac, and I am not sure if I can even build these on the Mac.

**Comment by ShreyasJejurkar** [comment]
Yes, I have switched to windows docker containers, but getting the same error. 

I don't think you can build Windows container images on a host which is not Windows. You need to be on windows, to build windows container images.

**Comment by ShreyasJejurkar** [comment]
Thanks to @brasmith-ms for the solution (via internal chat). 
We need to append `windows` before the image name. 
So instead of pulling like this `mcr.microsoft.com/servercore:ltsc2022`, we need to pull it like this `mcr.microsoft.com/windows/servercore:ltsc2022`

See the below screenshot for more reference. Notice the image name
![image](https://user-images.githubusercontent.com/17148381/207304876-cc8e7851-5bdd-4101-a703-75aac8ea4fb0.png)
