### ISSUE TITLE
Is Docker-in-Docker ( DinD ) possible with Windows containers ?

### ISSUE THREAD

**Issue by kaidokert** [microsoft/Windows-Containers#296]
Linux containers support DinD, which streamlines a lot of build pipelines. Is this feasible or planned with Windows containers ?

**Comment by jankap** [comment]
You can use the host's docker engine. With that, you build on your host (with all its disadvantages), but from inside the guest, if the CLI is installed there.

**Comment by kaidokert** [comment]
This sounds promising - is there any available example as how to do that ? I'm most specifically interested in how to do this within Github Actions pipeline, but a simple standalone demo would be great to see, if one exists.

**Comment by Juarezhm** [comment]
Hi, thanks for reaching out and for your patience! Currently, docker-in-docker is not supported for Windows containers. However, we have noted this feature request for our long-term roadmap. Since this is currently not supported, I will be closing out this issue.
