### ISSUE TITLE
Issue while running Moby engine on windows VM

### ISSUE THREAD

**Issue by Sathwik8** [microsoft/Windows-Containers#297]
Build and test Moby on Windows - https://github.com/moby/moby/blob/master/docs/contributing/software-req-win.md 

**Describe the bug**
I have created a Windows VM and installed Docker CE 
I built Moby engine following document
While running Moby engine its getting struck at "API listen on //./pipe/docker_engine" as shown in below screenshot

![image](https://user-images.githubusercontent.com/55187652/206737268-2d9e6c3b-feee-4309-8f6e-e986b7473fdb.png)

**To Reproduce** 
Follow document - https://github.com/moby/moby/blob/master/docs/contributing/software-req-win.md 

**Configuration** 
Edition: Windows Server 2019

**Comment by fady-azmy-msft** [comment]
@Juarezhm any thoughts on this?

**Comment by corhere** [comment]
That looks like a perfectly normal startup of dockerd.exe when launched from a shell. The "API listen on" log message means it has successfully started up and is listening for API requests from the `docker` CLI and other clients. @Sathwik8 try running `docker info` from another terminal window and see if the engine is responsive.

**Comment by Sathwik8** [comment]
@corhere  I see engine is responsive and am able to view docker info

**Comment by Sathwik8** [comment]
We would like to run Moby engine as a Windows service, when we tried it running as service, we got below error

<img width="247" alt="image" src="https://user-images.githubusercontent.com/55187652/208730531-a961415e-16fa-4231-8461-485ca9feacee.png">

**Comment by corhere** [comment]
@Sathwik8 are you passing the `--run-service` flag to dockerd.exe?

**Comment by Sathwik8** [comment]
yes, issue has been resolved after running it as service

New-Service -Name "MobySvc" -BinaryPathName "C:\dockerd.exe --run-service"
