### ISSUE TITLE
Does Microsoft allow to copy fonts "Segoe UI" into Server Core image for production environment?

### ISSUE THREAD

**Issue by xinfli** [microsoft/Windows-Containers#298]
We are using SQL Server Reporting Service in our production, font "Segoe UI" is used for many of our reports.

Now we need deploy our product into cloud, we selected [Windows Server Core image](https://hub.docker.com/_/microsoft-windows-servercore) as base image for our product.

The problem there is no TrueType font in Windows Server Core image, this caused our reports use lucon.ttf as fallback font for "Segoe UI", the style of reports is not so good.

I'm wondering if we can copy Segoe UI fonts from [Windows image](https://hub.docker.com/_/microsoft-windows) into our product image, is that allowed by Microsoft? or do we need a license to do so?

Thanks!

**Comment by zhiweiv** [comment]
There is guide from MS to install fonts to container, link is https://techcommunity.microsoft.com/t5/itops-talk-blog/adding-optional-font-packages-to-windows-containers/ba-p/3559761. Does this help?

**Comment by xinfli** [comment]
@zhiweiv Thanks

I tried it on my local computer, but unfortunately I failed to do so, it always failed to access the network path.

But does it mean Microsoft officially allowed to copy font files from a Windows product to a Windows Server Core image?

Technically I can copy the font files from a **Windows image** into our product image based on **Windows Server Core image**, I'm worried about the license.

**Comment by fady-azmy-msft** [comment]
@akarshm any thoughts on this?

**Comment by xinfli** [comment]
Or if it's OK to copy the fonts from windows server image to windows server core image? thanks!
```
FROM mcr.microsoft.com/windows:ltsc2019 as file-source
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019

COPY --from=file-source ["/Windows/Fonts/segoe*.ttf", "/Windows/Fonts/"]

# ...
```

**Comment by vrapolinario** [comment]
Can you please let us know what is the issue with accessing the networking path? is there an error you see or is it a different networking setup? Accessing the network path should be simple as this is local access.

**Comment by xinfli** [comment]
Sorry to reply you late, I tried again, it returned such error:
```
C:\install>for /F "tokens=3 delims=: " %g in ('netsh interface ip show address | findstr /c:"Default Gateway"') do set GATEWAY=%g

C:\install>set GATEWAY=172.27.144.1

C:\install>net use o: \\172.27.144.1\WinSxS /user:ShareUser Abc_Abc.123
System error 53 has occurred.

The network path was not found.
```

This is the .ps1 file I created to build such image:
```powershell
$pwd4Share = 'Abc_Abc.123'

Write-Host "Create share user"
& net user ShareUser "$pwd4Share" /ADD

Write-Host "Create shared folder"
& net share WinSxS="$($env:windir)\WinSxS" /grant:"ShareUser,READ"

Write-Host "Build docker image"
docker build -t win2019corewithfont:latest --build-arg SHARE_PW="$pwd4Share" .

& net share WinSxS /delete
& net user ShareUser /delete
```

**Comment by sebok** [comment]
Any update on this?
Is it **legal** to copy fonts from an mcr.microsoft.com/windows image to an image based on a windowsservercore image?

If not then is it legal to temporary copy the WinSxS folder, enable font features, and then remove the temporary WinSxS folder?

**Comment by fady-azmy-msft** [comment]
Unfortunately, I personally can't comment on the legality of what is okay and what isn't. Please have a look [at our licensing terms](https://mcr.microsoft.com/en-us/product/windows/server/about#license).
