### ISSUE TITLE
I'm unable to run process-isolated WS2022 containers on Windows 11

### ISSUE THREAD

**Issue by Badsworth** [microsoft/Windows-Containers#302]
In theory I should be able to run WS2022 containers on my Windows 11 pro operating system (Microsoft Windows [Version 10.0.22621.963]) in process isolation mode according to this link: [Container Version Compatibly link](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?source=recommendations&tabs=windows-server-2022%2Cwindows-11)

Unfortunately, I'm getting incompatibility docker errors when I execute:
docker run --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022

I've installed the latest version of docker desktop. Interestingly when I run docker info, it believes the host op system is " Windows 10 Pro Version 2009 (OS Build 22621.963)"

Question: Is the reason why WS2022 images fail to run on Windows 11 in process isolation mode down to docker thinking that I'm running Windows 10 or am I focusing in the wrong area?

**Comment by Badsworth** [comment]
Figured it out. The docker command should be:-
`docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 cmd --isolation=process` << This works (--isolation=process needs to be at the end).

This is the original docker command that fails:-
`docker run -it --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022 cmd`

**Comment by vrapolinario** [comment]
Can you please provide the actual error that you see? that will help narrow down the issue.

**Comment by dk-ebeisecker** [comment]
I'm also having the same problem when trying to run a process isolated Windows server 2022 container on Windows 11.

```
docker run --rm -it mcr.microsoft.com/windows/servercore:ltsc2022 --isolation=process
docker: Error response from daemon: container 164c82ee344087afab240e79fd2278aac5de592cde4c404a4ae6199cdd83ae0c encountered an error during hcs::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF63804EC2D: (caller: 00007FF637FF4AE7) Exception(2) tid(3d4) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000].
```

OS Info
```
OsVersion  OsBuildNumber WindowsEditionId WindowsInstallationType
---------  ------------- ---------------- -----------------------
10.0.22621 22621         Professional     Client
```

Docker info

```
docker system info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 23.0.3
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22621 (22621.1.amd64fre.ni_release.220506-1250)
 Operating System: Microsoft Windows Version 22H2 (OS Build 22621.1555)
 OSType: windows
 Architecture: x86_64
 CPUs: 24
 Total Memory: 63.79GiB
 Name: Desktop
 ID: cdd9214e-b13d-4333-ad7e-38d3b8810720
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by dk-ebeisecker** [comment]
Fun fact, my problem was that I had `--isolation=process` after the Image name. If I run `docker run --rm -it --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022` it works fine....

**Comment by vrapolinario** [comment]
Thanks for catching that @dk-ebeisecker. The syntax of the command does make a difference.

@Badsworth this is a very weird scenario. If you're running on a Windows 11 host, Docker should be able to see that. Also, it does seem more like an issue with the Docker daemon than Windows. Have you tried opening a question on the Docker Forum? 

You also might want to try a few things:
- Have you confirmed you switched the context from Linux to Windows containers on Docker Desktop?
- Can you try adding a few things to your docker run command? like: `docker run -d --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022`

**Comment by vrapolinario** [comment]
I just checked on my system and noticed it also shows a Windows 10, although I'm running on Windows 11. I'll go ahead and open a ticket with Docker/Moby to try and fix this. I think the main reason is that the kernel version did not change from Windows 10 and 11, it shows a major version of 10, but Docker should know based on the build number that you should be able to run a Windows Server 2022 image with process isolation.

Also, I tried running the image as you did, and I got an interesting output:
```
PS C:\GitHub\> docker run --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022
Microsoft Windows [Version 10.0.22621.1006]
(c) Microsoft Corporation. All rights reserved.

C:\>
```
After the above, it immediately exited the container and went back to the context on my PowerShell session. This is by design, but it might be interpreted as an error. This happens because the Server Core image has no EntryPoint in its dockerfile. The result is that Docker thinks the image has completed it lifecycle and exits the container. To avoid this, you have two options:
- You can create your own dockerfile with an EntryPoint - which is the preferred option for you to run your own application.
- You can open an interactive session with the Server Core image by using: `docker run -it --process-isolartion mcr.microsoft.com/windows/servercore:ltsc2022 powershell`

@Badsworth  can you please confirm the above?

**Comment by fady-azmy-msft** [comment]
Closing because issue is now stale.
