### ISSUE TITLE
Modifying the registry does not take effect

### ISSUE THREAD

**Issue by ferghs** [microsoft/Windows-Containers#303]
What is your question?
When I'm inside the mcr.microsoft.com/windows/servercore:ltsc2019 container
Add a parameter TcpTimedWaitDelay to the registry. Although it can be found that it has been added, it does not take effect. When I stop and start the container, the situation is still the same. So I want to know how to make it take effect after modifying the registry?
Here are my steps:
docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 cmd.exe

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" /v "TcpTimedWaitDelay" /t REG_DWORD /d "30" /f

docker stop 7dc9e940a6d5

docker start 7dc9e940a6d5

docker exec -it 7dc9e940a6d5 cmd.exe

reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"

**Comment by ferghs** [comment]
After modifying the registry, the TIME_WAIT time is still the default 2 minutes instead of 30 seconds

**Comment by vrapolinario** [comment]
Just to confirm, are you executing this on a running containers? The recommendation is to always change the configuration on the dockerfile to persist the config across all containers created from that image.
