### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified. 

### ISSUE THREAD

**Issue by vanessadev** [microsoft/Windows-Containers#304]
I have installed docker on my windows machine. I can run linux images. When I select "Switch to Windows containers," and run the docker pull mcr.microsoft.com/windows/server:ltsc2022 command from powershell I get the error:

Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified. Not sure what I am doing wrong.

**Comment by neersighted** [comment]
This is an issue for https://github.com/docker/for-win as it is with the Docker Desktop product, and not with the Windows Containers platform itself.

**Comment by vanessadev** [comment]
Thank you for the info! I uninstalled Docker Desktop 4.15 and installed 4.13.1. That fixed it.
