### ISSUE TITLE
Microsoft Edge Updates trigger in background, causing containers to fail to shutdown

### ISSUE THREAD

**Issue by bcooksley** [microsoft/Windows-Containers#305]
When using or building Docker Images based off of mcr.microsoft.com/windows/server:ltsc2022 it is possible that Microsoft Edge will be triggered to initiate an update in the background. 

While fairly harmless on a normal Windows system, this is very harmful in a container context as it can lead the container to fail to shutdown when the currently running command in the container finishes. 

This will result in a fairly cryptic error message from Docker itself:
```
<command> returned a non-zero code: 4294967295: failed to shutdown container: container 58e3041dc1bef332471187cc2d76004f08b1f80015d8676b351a31c7765cf548 encountered an error during hcsshim::ComputeSystem::Wait: hcsshim: timeout waiting for notification
```

In our situation the background update of Microsoft Edge is triggered by the installation of Visual Studio Build Tools (2019 - VS Channel 16). 

At this time my workaround for this is to:
a) run "docker top <containerid>"
b) hunt down the offending processes in Task Manager running as Administrator on the host system once the build command finishes and kill them

The process described in (b) required killing msiexec.exe, TiWorker.exe and other processes related to Windows Update / MSEdge background updates - and it is a racy condition as a human has to move fast enough to kill the processes in the timeout window that hcsshim allows.

The following Dockerfile should allow reproduction of this.
```
#escape=`
FROM mcr.microsoft.com/windows/server:ltsc2022

# Visual Studio is a bit delicate, ensure it is running under cmd.exe for maximum compatibility
SHELL ["cmd.exe", "/S", "/C"]

# Based on https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
# Install Build Tools with the vc++ workload, excluding workloads and components with known issues.
RUN `
    # Download the latest Build Tools bootstrapper
    # You cannot use the correct version for VS 2019 as that will fail after installing very little with no errors
    # This likely has something to do with it installing the latest VS installer
    curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe  `
    `
    # Install Visual Studio with the components we need, excluding workloads and components with known issues.
    # We instruct it to not update the installer as that just causes too many issues
    # We have to use channeluri/installchanneluri as we are abusing the MSVC 2022 installer to bring in 2019 (see above notes)
    && (start /w vs_buildtools.exe --quiet --wait --norestart --nocache --noUpdateInstaller `
        --channeluri https://aka.ms/vs/16/release/channel `
        --installchanneluri https://aka.ms/vs/16/release/channel `
        --add Microsoft.VisualStudio.Component.VC.ATL `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        --add Microsoft.VisualStudio.Component.VC.CoreBuildTools `
        --add Microsoft.VisualStudio.Component.VC.CLI.Support `
        --add Microsoft.VisualStudio.Component.Windows10SDK `
        --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
        --remove Microsoft.VisualStudio.Component.Windows81SDK `
        || IF "%ERRORLEVEL%"=="3010" EXIT 0) `
    `
    # Cleanup
    && del /q vs_buildtools.exe `
    && powershell -Command "Remove-Item @( 'C:\Windows\Temp\*', 'C:\Windows\Prefetch\*', 'C:\Documents and Settings\*\Local Settings\temp\*', 'C:\Users\*\Appdata\Local\Temp\*' ) -Force -Recurse -Verbose"
```

Contents of "docker info" as follows:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 24
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Datacenter Version 2009 (OS Build 20348.1366)
 OSType: windows
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24GiB
 Name: WIN-OKIODCBGNG6
 ID: NU7D:YF2Z:XVBA:QA42:73GL:ZOLO:QYCU:TAJK:4PUR:XB6I:UIQ6:5P4K
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: [removed]
 Registry: [removed]
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by akarshm** [comment]
Hi Ben, could you please clarify if you're seeing Edge update itself in the container, or is it your theoretical question? I'd be very surprised if this is the former.

**Comment by bcooksley** [comment]
I am seeing Microsoft Edge updates triggering within the container itself which cause the build of Docker images to fail.

It may very well be that the Visual Studio installation processes awakens other update processes which the Edge updater is tied in with.

**Comment by plooploops** [comment]
Out of curiosity, how are you stopping the container?  Are you using a `docker stop` command?

**Comment by bcooksley** [comment]
The stopping of the container is being done automatically by Docker itself as part of the "docker build" command.

It expects the container to exit/stop normally following the completion of the build command that it ran within the container as documented within the Dockerfile above.

**Comment by plooploops** [comment]
I attempted to use the Dockerfile mentioned in the top of the thread, and while I did notice the Microsoft Edge updates triggering, I did not see the docker build fail.

Instead of failing, the docker build took a while to actually complete the build step.

**Comment by bcooksley** [comment]
Can you confirm the version of Docker Engine you are making use of @plooploops?

**Comment by plooploops** [comment]
I'm using v20.10.23.

**Comment by bcooksley** [comment]
We've got 20.10.7 as noted above - is this behaviour which could possibly have been fixed between .7 and .23 perhaps @akarshm?

**Comment by plooploops** [comment]
Just a heads up, it looks like the VS Installer [requires WebView2 to be installed](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/troubleshoot-installation-issues?view=vs-2022#problems-installing-webview2).

Given that you're seeing Edge updates **after** starting the VS Installer, then it looks like the VS Installer is using the [evergreen distribution mode](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#the-evergreen-runtime-distribution-mode) to update the WebView2 runtime and the Edge binaries.

**Comment by bcooksley** [comment]
Interesting. Given we are using windows/server:ltsc2022 as our base image, I imagine Edge and WebView2 may very well be included within this image - so this behaviour would only be seen in the time between Edge pushing an update and the Docker image being rebuilt.

Is it possible to get a command we can run in the container to force a Edge update, and which will only exit once that update is completed?

**Comment by fady-azmy-msft** [comment]
Adding this for reference (internal tracking #43968465).

**Comment by akarshm** [comment]
We announced on May 9, 2023 ([here](https://techcommunity.microsoft.com/t5/containers/continuing-improvement-to-windows-server-containers-and-the/ba-p/3816701)) that Microsoft Edge will become an optional component soon.

**Comment by plooploops** [comment]
Per @akarshm, there's a [follow up](https://techcommunity.microsoft.com/t5/containers/announcing-changes-to-windows-containers-image-composition-to/ba-p/3846615) that Microsoft Edge is now an optional component.

@bcooksley would you be able to retry with the following steps?

1. Pull in the latest [server](https://mcr.microsoft.com/en-us/product/windows/server/about) image
    `docker pull mcr.microsoft.com/windows/server:ltsc2022`
1. Use the below modified repro Dockerfile to build and run your image
    1. I modified your repro Dockerfile by commenting out the section cleaning up `'C:\Windows\Temp\*'`, and was able to see that the vs build tools bootstrapper completed

```dockerfile
#escape=`
FROM mcr.microsoft.com/windows/server:ltsc2022

# Visual Studio is a bit delicate, ensure it is running under cmd.exe for maximum compatibility
SHELL ["cmd.exe", "/S", "/C"]

# Based on https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
# Install Build Tools with the vc++ workload, excluding workloads and components with known issues.
RUN `
    # Download the latest Build Tools bootstrapper
    # You cannot use the correct version for VS 2019 as that will fail after installing very little with no errors
    # This likely has something to do with it installing the latest VS installer
    curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe  `
    `
    # Install Visual Studio with the components we need, excluding workloads and components with known issues.
    # We instruct it to not update the installer as that just causes too many issues
    # We have to use channeluri/installchanneluri as we are abusing the MSVC 2022 installer to bring in 2019 (see above notes)
    && (start /w vs_buildtools.exe --quiet --wait --norestart --nocache --noUpdateInstaller `
        --channeluri https://aka.ms/vs/16/release/channel `
        --installchanneluri https://aka.ms/vs/16/release/channel `
        --add Microsoft.VisualStudio.Component.VC.ATL `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        --add Microsoft.VisualStudio.Component.VC.CoreBuildTools `
        --add Microsoft.VisualStudio.Component.VC.CLI.Support `
        --add Microsoft.VisualStudio.Component.Windows10SDK `
        --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
        --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
        --remove Microsoft.VisualStudio.Component.Windows81SDK `
        || IF "%ERRORLEVEL%"=="3010" EXIT 0) `
    `
    # Cleanup
    && del /q vs_buildtools.exe `
    && powershell -Command "Remove-Item @( 'C:\Windows\Prefetch\*', 'C:\Documents and Settings\*\Local Settings\temp\*', 'C:\Users\*\Appdata\Local\Temp\*' ) -Force -Recurse -Verbose"
    # This line is cleaned up as there can be conflicts with C:\Windows\Temp\
    # && powershell -Command "Remove-Item @( 'C:\Windows\Temp\*', 'C:\Windows\Prefetch\*', 'C:\Documents and Settings\*\Local Settings\temp\*', 'C:\Users\*\Appdata\Local\Temp\*' ) -Force -Recurse -Verbose"
```

**Comment by bcooksley** [comment]
I'm happy to report that the image is now able to build within our pipelines successfully, and without issue.
(Build log visible at https://invent.kde.org/sysadmin/ci-images/-/jobs/1001996)

Thanks for working on getting this fixed!

**Comment by plooploops** [comment]
Wonderful news @bcooksley!  Glad it's working and let's close this one out then!
