### ISSUE TITLE
Getting error when trying to access office installed in Windows server core container via C# code

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/Windows-Containers#307]
We are trying to dockerize the .NET core application which uses Microsoft Visio for generating diagrams. We are generating diagrams by using the interop library for Visio via C# code. 

Our app works great if we are using a Windows client machine docker image, but when we try to use a Windows Server Core container image, we are getting the below error 

`Retrieving the COM class factory for component with CLSID {00021A20-0000-0000-C000-000000000046} failed due to the following error: 800706d9 There are no more endpoints available from the endpoint mapper. (0x800706D9)`

May I know what could be the issue!? Do I need to enable any windows service to get it working!?

**Comment by vrapolinario** [comment]
This is because the API surface on the Server Core and Nano Server images are smaller than the Windows or Server images. Most likely, the component your app is trying to use is not present on those images.

The other thing is that Microsoft Office components are not supported on Windows containers, although they might work.

**Comment by ShreyasJejurkar** [comment]
Hi @vrapolinario , Thanks for the reply. I understand that the API surface on the server core image is limited compared to others. 
Based on the above error, can we find the missing module and install it as part of the docker on top of the Windows server core image? 
We really want to avoid using full-blown windows client machine as it's too big, that's why we are checking with windows server core image!

**Comment by ShreyasJejurkar** [comment]
Any updates on this!?

**Comment by dt-brahim-bouaboud** [comment]
it may be out of context but did you try using aks edge ?
https://learn.microsoft.com/en-US/azure/aks/hybrid/aks-edge-overview
