### ISSUE TITLE
Windows containers do not have entries in the hosts file (Single File Mapping)

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#31]
File Mounting support bug reported in K8s SIG-Windows : https://github.com/kubernetes/kubernetes/issues/70189

**Comment by immuzz** [comment]
Expected to land in Windows OS for September 2020 (For 2004, 1909, 1903 and 2019)

**Comment by marosset** [comment]
@immuzz do you know yet if this will be in the Sept 2020 updates for Windows Server 2019?

**Comment by marosset** [comment]
@immuzz Did these updates land in 9B updates for Windows Server 2019?

**Comment by immuzz** [comment]
Yes these are part of 9C release
