### ISSUE TITLE
Support for containerized Active Directory Domain Services (ADDS and maybe more server roles)

### ISSUE THREAD

**Issue by Sporesirius** [microsoft/Windows-Containers#313]
### Discussed in https://github.com/microsoft/Windows-Containers/discussions/312

<div type='discussions-op-text'>

<sup>Originally posted by **Sporesirius** February  2, 2023</sup>
Hello,
I know that it's currently not supported because of how the architecture of ADDS is built. I think supporting ADDS (and maybe more server roles) in containers would be a huge benefit for a stable infrastructure. For example, it would be possible to use ADDS in Kubernetes and use the tooling of K8s (IaC, Terraform) in that environment. It would also minimise the code that runs on each service for security benefits (if we are talking about separating e.g. ADDS, the ADDS DB and DNS to their own microservices).

I would like to ask if this is already planned for the future or being considered?

More server roles would make the Windows Containers project more attractive, as these are services that are unique to the Windows ecosystem (e.g. I can also host .NET 6 apps in Linux and have the benefits of K8s + Tools).

Best regards</div>

**Comment by fady-azmy-msft** [comment]
Thank you for sharing this feedback, let me find the right owners to look at this.

**Comment by fady-azmy-msft** [comment]
Assigning this to @akarshm.

**Comment by Sporesirius** [comment]
Is there a status?

**Comment by akarshm** [comment]
Thanks for submitting the feature request. We will consider this in the future, but we don't have a timeline to share at this time.
