### ISSUE TITLE
Support for running and building containers on mismatched container and host Windows versions

### ISSUE THREAD

**Issue by Sporesirius** [microsoft/Windows-Containers#314]
**Is your feature request related to a problem? Please describe.**
Less flexible. Updates are more tricky.

**Describe the solution you'd like**
Support for running and building containers on mismatched container and host Windows versions

**Comment by lippertmarkus** [comment]
Starting with Server 2022 there is downward compatbility: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487

**Comment by fady-azmy-msft** [comment]
Additionally, you can also run containers with Hyper-V isolation, which means you can have different OS versions in the container host and image.

https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-11#hyper-v-isolation-for-containers

**Comment by Sporesirius** [comment]
Thanks for the feedback. I would close the issue.
