### ISSUE TITLE
What's the difference between multiarch and amd64 images? Which one to use?

### ISSUE THREAD

**Issue by travnick** [microsoft/Windows-Containers#315]
**What's the difference between multiarch and amd64 images? Which one to use?**
I'm confused about docker images, e.g. here: https://hub.docker.com/_/microsoft-windows

Should I use `multiarch` or `amd64`? What are the differences? When use, particular image type?

**Comment by fady-azmy-msft** [comment]
Hey @travnick, multiarch images are images that you can use the same docker pull command on different platforms (such as Linux and Windows) and the container runtime will find the right one.

For example, if you pull a .NET image, you can use the one for Linux or Windows, but you can use the same pull command (docker pull x) and the runtime will figure out the right one.

If you're unsure, I suggest you go with default command: docker pull mcr.microsoft.com/windows:ltsc2019

**Comment by travnick** [comment]
Ok, so multiarch is about the host, not the guest, right?

Then can you please explain, what does the multiarch exactly mean here: https://hub.docker.com/_/microsoft-windows ?
Since the only variants I can see there are `amd64` and `multiarch`, then I wonder what are other options except for `amd64`

**Comment by akarshm** [comment]
Both `amd64` and `multiarch` would download the same bits since we are only shipping `amd64` for now. Hope this clarifies.

**Comment by travnick** [comment]
Ok, that's clear here. So until I see anything more than amd64, then multiarch is simply an alias for a single architecture.
