### ISSUE TITLE
Windows containers missing from Dockerhub

### ISSUE THREAD

**Issue by leopck** [microsoft/Windows-Containers#319]
Windows containers are removed from Dockerhub, was this removed by mistake?

https://hub.docker.com/_/microsoft-windows-servercore
https://hub.docker.com/_/microsoft-windows-nanoserver
https://hub.docker.com/_/microsoft-windows
https://hub.docker.com/_/microsoft-windows-server/

![image](https://user-images.githubusercontent.com/4161783/220730588-484786b6-dc6f-4bc8-9e76-738c06d7ef29.png)
![image](https://user-images.githubusercontent.com/4161783/220731237-49ae1414-7929-4475-9571-f5813b143b62.png)
![image](https://user-images.githubusercontent.com/4161783/220731262-6713640e-7ba4-47fc-acfc-51bc39678873.png)
![image](https://user-images.githubusercontent.com/4161783/220731279-2bcbdb86-fbe6-4c2c-a9db-024a11876017.png)

**Comment by mloskot** [comment]
AFAICT, It's all good now.

**Comment by leopck** [comment]
Thank you!
