### ISSUE TITLE
Unable to run VC2013 vcredist_x86.exe on  mcr.microsoft.com/windows/server:ltsc2022

### ISSUE THREAD

**Issue by ArthwitRail** [microsoft/Windows-Containers#323]
**Describe the bug**
I am trying to dockerise a windows application by running its installer silently. The installer does not start and simply instantly returns to the powershell prompt of my container. I believe this to be related to missing dependent libraries in the image.

I explored this further and also found that i am unable to run the visual c/c++ 2013 redistributable (either 32 or 64 bit) when the container starts, it behaves in the same way as my application installer. Interestingly the VS17 redistributable does run and will install silently.

**To Reproduce** 

Using Dockerfile 

```
FROM mcr.microsoft.com/windows/server:ltsc2022 

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Download for VS17 redist
#RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;  Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe";  Start-Process -filepath C:\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process;

# Download VS 2013 redist
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;  Invoke-WebRequest "https://aka.ms/highdpimfc2013x86enu" -OutFile "vcredist_x86.exe"

# Run vc redist install silently 
#RUN Start-Process -filepath C:\vcredist_x86.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process;

```

build using

docker build . -t testexample

run 

docker run -it testexample powershell.exe

at the command prompt of the running container attempt to run **vcredist_x86.exe /install /passive /norestart** and it will drop back tot he powershell prompt of the comtainer

**Expected behavior**

Expect vc redist installer to run.

**Configuration:**
 - Windows 11 Pro (22H2), OS build 22621.1343
 - Base image - Windows/server:ltsc2022 
-  Docker Desktop 4.16.3 (96739) with Docker Engine v20.10.22

**Comment by fady-azmy-msft** [comment]
We weren't able to reproduce this issue with the same configurations and docker file @ArthwitRail. 

Can you share what you observed that made you suspect the issue is with the installer?

**Comment by fady-azmy-msft** [comment]
Closing issue due to no response.
