### ISSUE TITLE
Cannot run wpr / perfview inside docker container

### ISSUE THREAD

**Issue by dindo-dindo** [microsoft/Windows-Containers#324]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
Performance tools like WPR and Perfview are unable to start inside microsoft container
(mcr.microsoft.com/windows/servercore:ltsc2022)

**To Reproduce** 
Run the following commands:
(from host)
docker pull mcr.microsoft.com/windows/servercore:ltsc2022
docker run -dit mcr.microsoft.com/windows/servercore:ltsc2022
docker exec --user ContainerAdministrator -it <container id> cmd

(from container)
wpr.exe -start CPU

**Expected behavior**
Performance tool starts collecting metrics

**Configuration:**
 - Edition: Windows 10.0.20348 Microsoft Windows Server 2022 Datacenter
- Base Image being used: mcr.microsoft.com/windows/servercore:ltsc2022
 - Container engine: docker
 - Container Engine version 22.06.0

**Additional context**
error message received:
  A required privilege is not held by the client.
  Profile Id: CPU.Verbose.Memory
  Error code: 0x80070522

**Comment by fady-azmy-msft** [comment]
Looking into this (internal ticket #43968476)

**Comment by ntrappe-msft** [comment]
Hi! It looks like we cannot start a trace for the **`CPU`** profile in a container at the moment. I'm trying to confirm that this is true. If we can in fact get CPU data in a container using WPR then I'll provide you with those steps.

**Comment by ntrappe-msft** [comment]
@dindo-dindo 
While we continue to work on providing more support for WPR in containers, there are other ways to gather CPU data in a container. You can use a command-line tool called **`logman`** that's already available in Windows Server Core 2022. 

I don't know exactly what CPU data you'd like to measure but here's an example of how to capture the percentage of CPU time used by all processes on the system every 5 seconds.

### Instructions
1. Start up your container in interactive mode (_exactly how you did in your repro steps_).
```powershell
docker run -dit mcr.microsoft.com/windows/servercore:ltsc2022
docker exec --user ContainerAdministrator -it cmd
```
2. Inside the container, create a new counter log named "CPU Usage". 
```ruby
logman create counter -n "CPU Usage" -c "\Processor(*)\% Processor Time" -si 5 -f csv -o C:\logs\cpu_usage.csv
```
3. To check that you successfully created a counter log you can run `logman query` and you should see:
```powershell
Data Collector Set              Type                  Status
----------------------------------------------------------------------
CPU Usage                       Counter               Stopped
```
4. Now we can start to collect data. You can confirm it is running by using `logman query` again.
```ruby
logman start "CPU Usage"
```
5. When you're done collecting data:
```ruby
logman stop "CPU Usage"
```
6. To see the output of the data, navigate to the folder `C:\logs\` and you should see a new csv file. You can read the contents using a command like:
```powershell
more cpu_usage.csv
```

### More Details
  - `-n` defines the name of the counter as "CPU Usage"
  - `-c` specifies the counter path to the monitor which is _all_ processes here
  - `si` specifies the interval of capture as 5 seconds
  - `-f` defines the log file format as CSV
  - `-o` is the output file location as `C:\logs\` and file name `cpu_usage.csv`
 
### Resources
1. [Logman documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/logman)
2. [Collecting Performance Data into a CSV File Using Logman](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/collecting-performance-data-into-a-csv-file-using-logman)
3. [Logman Forum](https://social.technet.microsoft.com/Forums/windows/en-US/home?forum=wptk_v4)

**Comment by l-o-l** [comment]
Has this been fixed in some way? I am hitting the same issue trying to profile inside a windows container. Originally trying to use:
PS C:\Program Files\Microsoft Visual Studio 17.0\Team Tools\DiagnosticsHub\Collector> .\VSDiagnostics.exe start 1 /attach:6672 /loadConfig:AgentConfigs\CPUUsageLow.json

However, which also hits permission issues. Profiling inside a windows docker container appears to be impossible?
