### ISSUE TITLE
Support for Azure AD Connect cloud sync agents

### ISSUE THREAD

**Issue by Sporesirius** [microsoft/Windows-Containers#330]
**Is your feature request related to a problem? Please describe.**
The ability to move to cloud-native workflows and scale solutions with "classic" Microsoft Windows Server products.

**Describe the solution you'd like**
Scaling solutions for hybrid AD environments.

As the "old" Azure AD Connect on-premises application has no way to use multiple active agents for high availability (https://learn.microsoft.com/en-us/azure/active-directory/hybrid/whatis-azure-ad-connect).
The ability and first-party support for containers with Azure AD Connect cloud sync agents (https://learn.microsoft.com/en-us/azure/active-directory/cloud-sync/what-is-cloud-sync) would be I think the way to go.

Kind regards

**Comment by vrapolinario** [comment]
This is an interesting scenario. However, a quick glance at the documentation and it seems like this is product built with an UI, not CLI. This would make the product virtually unsupported on Windows containers. My recommendation would be to contact the AAD Connect Cloud sync team and pose the request to that team so they know you have a scenario that they should consider.

**Comment by Sporesirius** [comment]
Hi @vrapolinario,

thanks for the reply. I looked into [this](https://learn.microsoft.com/en-us/azure/active-directory/cloud-sync/how-to-install-pshell) and it works with PowerShell cmdlets and gMSA are also supported.
I'll test it to see if it works, but it would be nice to have official container images for Microsoft software like this. I believe that Windows Admin Center (WAC), for example, has official container images.
Also of course one of the best features would be support for Windows Server roles like ADDS etc. See #313 

One problem I've noticed is giving feedback to the MS developers and possibly going directly into an exchange e.g via github issues to give feature reqeusts etc. I see this only with two products where it works ok, Windows Containers with the github repo and WAC with the forum (although I think a github repo would be better).

Best regards

**Comment by vrapolinario** [comment]
Thanks for the info @Sporesirius. I'm confused as to if this doc you just sent works the same as for the AAD Connect Cloud sync. It seems there are different version of the product with different names, and the Connect Cloud sync one is the latest and what I believe you referenced earlier. As you pointed out, the first step is to actually try everything on a PowerShell environment outside of a container, to then check if it works inside a container. 

As for ADDS, this is something we heard many times but would be a massive undertaking. Just point this out to @thecloudtaylor and @michbern-ms so they are aware of yet another request on this.

Thanks for the feedback on the other teams. GitHub has been a good tool for feedback, but not all teams have adopted it. My suggestion is to provide feedback on the documentation page, which tends to arrive at someone involved with the project.

**Comment by lucillex** [comment]
Thank you for the feature request. This is currently being tracked internally under item 44685306, however, we do not have a timeline to share for this at this time.

**Comment by lucillex** [comment]
Closing this issue for now. We will consider this in the future, but we don't have a timeline to share at this time.

**Comment by ntrappe-msft** [comment]
@ritikaguptams WAC features FYI
