### ISSUE TITLE
Documentation Bug in https://hub.docker.com/_/microsoft-windows-servercore

### ISSUE THREAD

**Issue by oaltawil** [microsoft/Windows-Containers#332]
In the "How to Use this Image" section, there are two missing parameters in the docker command that are required for interactively running cmd.exe (the default entry point) and keeping it running on all the Microsoft base images:

docker run mcr.microsoft.com/windows/servercore:ltsc2022

The missing parameters are "-i" and "-t". Without these parameters, cmd.exe exits immediately. To have cmd.exe run interactively and stay running the "-i" and "-t" parameters are required, e.g.

docker run -i -t mcr.microsoft.com/windows/servercore:ltsc2022

According to the Docker Documentation
https://docs.docker.com/engine/reference/commandline/run/

--interactive , -i Keep STDIN open even if not attached
--tty , -t Allocate a pseudo-TTY
 
That’s it!

**Comment by vrapolinario** [comment]
This is by design on the Windows Base Container images. These images have no process to run, unless you build an application to run on it - which in this case should be the Entrypoint.
As an alternative, you can use the Log Monitor tool, which has its documentation to set the Entrypoint.
