### ISSUE TITLE
windows/server, windows/servercore container manifest broken: no matching manifest for windows/amd64

### ISSUE THREAD

**Issue by JunaidChaudry** [microsoft/Windows-Containers#334]
the windows/server https://hub.docker.com/_/microsoft-windows-server docker image's manifest is broken: get error `no matching manifest for windows/amd64` on docker running on windows-server. 

**Describe the bug**
The dockerhub page lists that the image tags ltsc2022 are multiarch. However when I try to `pull` the image using `docker-ce` installed on my windows server, I get the error saying `no matching manifest for windows/amd64 10.0.17763 in the manifest list entries`. 
I have installed docker following Windows Server instructions for Docker CE / Moby available at https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1  to install docker on my windows server, which is running Windows Server 2019 Datacenter.

**To Reproduce** 
1. Install Docker on a Windows Server 2019 using the Docker CE / Moby instructions available at https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1
2. try pulling any `windows/server` or `windows/servercore` docker images. e.g. ` docker pull mcr.microsoft.com/windows/server:ltsc2022`
 

**Expected behavior**
The docker image is successfully pulled

**Configuration:**
 - Edition: Windows Server 2019 Datacenter
- Base Image being used: windows server 
 - Container engine: docker
 - Container Engine version: Server Version: master-dockerproject-2022-03-26
 
**Additional context**
Please see the screenshot showing the error, as well as the `docker info`. 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/49313431/225685470-ed43eb14-4793-49ec-91ba-269352092ca2.png">

**Comment by TBBle** [comment]
You're trying to run a Windows Server LTSC 2022 container on Windows Server LTSC 2019, [that's not supported](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-11#windows-server-host-os-compatibility).

The full error is telling you that: "no matching manifest for windows/amd64 **10.0.17763** in the manifest list entries", i.e. docker is looking for a Windows Server LTSC 2019-compatible AMD64 image, and not finding one.

Try pulling `mcr.microsoft.com/windows/servercore:ltsc2019`, that should work.

There's no `mcr.microsoft.com/windows/server:ltsc2019` image, as `mcr.microsoft.com/windows/server` was new with Windows Server LTSC 2022, replacing `mcr.microsoft.com/windows`.
