### ISSUE TITLE
Encoding inside container

### ISSUE THREAD

**Issue by horzone** [microsoft/Windows-Containers#336]
Hello! how do i change the encoding inside the servercore container? I need 1251, when using the image mcr.microsoft.com/windows/servercore:10.0.14393.5786-ru-ru [System.Text.Encoding]::Default gives 1252, chcp - 65001. When trying to change the encoding inside the chcp container, it gives an error that 1251 - Invalid code page. pls help :)

**Comment by fady-azmy-msft** [comment]
Hello! To change the encoding inside the servercore container, you can use the activeCodePage manifest element. Please see this document for what is supported:
https://devblogs.microsoft.com/oldnewthing/20220531-00/?p=106697

**Comment by vrapolinario** [comment]
Closing this issue based on the StackOverflow thread: https://stackoverflow.com/questions/75917614/encode-in-windows-container
