### ISSUE TITLE
docker hub readme: build number for ltsc2022 wrong

### ISSUE THREAD

**Issue by mweibel** [microsoft/Windows-Containers#340]
**Describe the bug**
Build numbers for ltsc2022 tagged images are wrong on docker hub. See e.g. https://hub.docker.com/_/microsoft-windows-nanoserver for an example. 

ltsc 2022 has `10.0.20348.x` as build number while on the README (full tag listing) it's written as `10.0.14393.x` which is [windows server 2016](https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info).

**Comment by akarshm** [comment]
Thanks, Michael. This is fixed, but note that the Microsoft Artifact Registry portal ([Nano Server](https://mcr.microsoft.com/en-us/product/windows/nanoserver/about), [Server Core](https://mcr.microsoft.com/en-us/product/windows/servercore/about), [Server](https://mcr.microsoft.com/en-us/product/windows/server/about), and [Windows](https://mcr.microsoft.com/en-us/product/windows/about)) is the central page for updates related to Windows container images.

**Comment by mweibel** [comment]
thanks for fixing and pointing me to the links - I wasn't aware there is an MCR portal :)
