### ISSUE TITLE
NtQueryVolumeInformationFile returns wrong FILE_FS_ATTRIBUTE_INFORMATION for bind mounted directory

### ISSUE THREAD

**Issue by YO4** [microsoft/Windows-Containers#341]
**Describe the bug**
Getting FILE_FS_ATTRIBUTE_INFORMATION structure vis invoking NtQueryVolumeInformationFile with FileFsAttributeInformation FsInformationClass, it's FileSystemAttributes contains wrong FILE_SUPPORTS_POSIX_UNLINK_RENAME / FILE_SUPPORTS_OPEN_BY_FILE_ID flag for bind mounted directory in windows container.

FileSystemAttributes differences summary
| image | isolation | mounted? | FileSystemAttributes | | | | | |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| ltsc2016 | hyper-v  | normal | 0x1c700df | | +OPEN_BYID | 
| ltsc2019 | hyper-v  | normal | 0x1c706df | | +OPEN_BYID | +POSIX | +CLEANUP | 
| ltsc2022 | hyper-v  | normal | 0x1c706df | | +OPEN_BYID | +POSIX | +CLEANUP | 
| ltsc2022 | process  | normal | 0x1c706df | | +OPEN_BYID | +POSIX | +CLEANUP | 
| ltsc2016 | hyper-v  | binded | 0x2c706ff | +USN_J |  |           **+POSIX** | +CLEANUP | +QUOTA | 
| ltsc2019 | hyper-v  | binded | 0x2c706ff | +USN_J |  |           **+POSIX** | +CLEANUP | +QUOTA | 
| ltsc2022 | hyper-v  | binded | 0x2c706ff | +USN_J |  |           **+POSIX** | +CLEANUP | +QUOTA | 
| ltsc2022 | process  | binded | 0x3e706ff | +USN_J | **+OPEN_BYID** | +POSIX | +CLEANUP | +QUOTA | 

OpenByFileId and POSIX_UNLINK_RENAME test result
| image | isolation | mounted? | OpenByFileId | POSIX_UNLINK_RENAME |
| --- | --- | --- | --- | --- |
| ltsc2016 | hyper-v |  normal |  success | fail?(windows version) |
| ltsc2019 | hyper-v |  normal |  success | success |
| ltsc2022 | hyper-v |  normal |  success | success |
| ltsc2022 | process |  normal |  success | success |
| ltsc2016 | hyper-v |  binded |  fail | interesting but not tested |
| ltsc2022 | hyper-v |  binded |  fail | **fail** |
| ltsc2019 | hyper-v |  binded |  fail | **fail** |
| ltsc2022 | process |  binded |  **fail** | success |

| description above | meanings |
| --- | --- |
| hyper-v | --isolation=hyperv |
| process | --isolation=process |
| normal | normal directory in container |
| binded | bind mounted directory in container |
| USN_J | FILE_SUPPORTS_USN_JOURNAL |
| OPEN_BYID | FILE_SUPPORTS_OPEN_BY_FILE_ID |
| POSIX | FILE_SUPPORTS_POSIX_UNLINK_RENAME |
| CLEANUP | FILE_RETURNS_CLEANUP_RESULT_INFO |
| QUOTA | FILE_VOLUME_QUOTAS |

**To Reproduce** 
run windows container with bind mount, like
``` docker run -it --rm --isolation=process -v c:\host_dir:c:\bind_dir mcr.microsoft.com/windows/servercore:ltsc2022```
then, get FileSystemAttributes using ```fsutil fsinfo volumeinfo``` or getVolInfo.exe in cygwin's csih package. 

For OpenByFileId, I used OpenByFileId.c at https://gist.github.com/YO4/47b31ac8ca01388936471b1783dd6bea
To check POSIX_UNLINK_RENAME support, I used msys2's rm.exe / mv.exe

**Expected behavior**
In bind mounted directory,
For process isolated ltsc2022 container, FILE_SUPPORTS_OPEN_BY_FILE_ID must be false.
For hyper-v isolated ltsc2022 container, POSIX unlink / rename function should work.(#338)
For hyper-v isolated ltsc2019 container, POSIX unlink / rename function should work.(#338)
For hyper-v isolated ltsc2016 container, it looks like host-side file system FileSystemAttributes are leaking out.

**Configuration:**
- Edition: Windows Server [Version 10.0.20348.1547]

**Additional context**
I was researching #338 and found this.
Characteristics except FILE_SUPPORTS_POSIX_UNLINK_RENAME and FILE_SUPPORTS_OPEN_BY_FILE_ID have not been tested.

**Comment by fady-azmy-msft** [comment]
Looking into this

**Comment by ntrappe-msft** [comment]
Issue has gone stale. Closing for now.

**Comment by sskras** [comment]
Have Microsoft ran out of the supporting personnel ?
Developers are suffering due to this issue.
