### ISSUE TITLE
Using Windows base images on Windows 11

### ISSUE THREAD

**Issue by jminnie** [microsoft/Windows-Containers#348]
**What is your question?**
At this URL, one can get a Windows docker image:

https://hub.docker.com/_/microsoft-windows-base-os-images?tab=description

At the same URL, the license only mentions Windows 10 when indicating the hosts on which the base images can be used.

Can the license be updated to clearly state how the Windows docker images can be used on Windows 11?

If there is a reason why the Windows base images may not be used on Windows 11, it will be nice if the license can call out the exclusion.

**Comment by fady-azmy-msft** [comment]
Looping @vrapolinario for this

**Comment by vrapolinario** [comment]
Thanks for bringing this to our attention. I noticed the MCR page, which is the official one, also mentions Windows 10 only. https://mcr.microsoft.com/en-us/product/windows/about

@akarshm can you please help us with this?

**Comment by akarshm** [comment]
Done. Changes are live on both Docker [Hub](https://hub.docker.com/_/microsoft-windows-base-os-images?tab=description) and [MAR](https://mcr.microsoft.com/en-us/product/windows/about) portal.
