### ISSUE TITLE
Memory leak on Windows nodes, svchost.exe consumed a lot of memory

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#35]
Reported by AKS users : https://github.com/Azure/AKS/issues/1397

**Comment by immuzz** [comment]
We are looking into this issue.

**Comment by immuzz** [comment]
Question from Developer : We just need to know the name of the service hosted by Svchost.exe in this case. The process dump will also help.

**Comment by zhiweiv** [comment]
@immuzz 
Do you konw how to get the name of the service hosted by svchost.exe?
I can't find it in Task Manager. Here is the dump of svchost.exe(16504): https://rcoltest.blob.core.windows.net/public/svchost.zip

![svchost](https://user-images.githubusercontent.com/22001089/86228103-90762c00-bbc0-11ea-94b4-2298b3c6bd65.PNG)

**Comment by jsturtevant** [comment]
you can get it by running the following in the cmd:

```
tasklist /svc /fi "IMAGENAME eq svchost.exe"
```

**Comment by zhiweiv** [comment]
```
C:\Users\apcs>tasklist /svc /fi "IMAGENAME eq svchost.exe" | findstr 16504
svchost.exe                  16504 N/A
```
The memory used of 16504 was 218532k yesterday, it is 221200k now.

**Comment by jsturtevant** [comment]
The reported repo steps are here: https://github.com/Azure/AKS/issues/1397#issuecomment-650860266

**Comment by mikkelhegn** [comment]
@zhiweiv - it might be a process inside one of your containers. Can you check the session ID for the process? `Get-CimInstance Win32_Process -Filter "ProcessID = 16504" | select SessionId`, If it's not `0` it's highly likely in a container. Can you also check if the memory increase correlates with container memory usage?

**Comment by zhiweiv** [comment]
```
PS C:\Users\apcs> Get-CimInstance Win32_Process -Filter "ProcessID = 16504" | select SessionId

SessionId
---------
       30
```

It is the process in Windows Server Core container. These outputs were ran in one container which is already up for 33 days .

```
C:\approot>tasklist /fi "IMAGENAME eq svchost.exe"
tasklist /fi "IMAGENAME eq svchost.exe"

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
svchost.exe                  28488 Services                  12    103,124 K
svchost.exe                  30880 Services                  12     49,260 K
svchost.exe                  26392 Services                  12    224,496 K
```

```
C:\approot>tasklist /svc /fi "IMAGENAME eq svchost.exe"
tasklist /svc /fi "IMAGENAME eq svchost.exe"

Image Name                     PID Services
========================= ======== ============================================
svchost.exe                  28488 gpsvc, iphlpsvc, ProfSvc, Schedule, SENS,
                                   UserManager, UsoSvc, Winmgmt
svchost.exe                  30880 CryptSvc, Dnscache, LanmanWorkstation, WinR
svchost.exe                  26392 DiagTrack
```

**Comment by zhiweiv** [comment]
A conclusion from my observation: The memory of  svchost.exe(s) keep increasing slowly(5MB ~ 10MB per container per day) in Windows Server Core containers(.net framework app). It is a big problem for long running pods, for example there are 20 pods in one host, it will eat 3GB ~ 5GB per month, we have to restart these pods regularly to release memory.

**Comment by mthalman** [comment]
Which Windows version are the containers running?

**Comment by zhiweiv** [comment]
Host OS and Container OS are all 10.0.17763.1158, however it reproduced in previous older Windows version too.

**Comment by zhiweiv** [comment]
Any update?

**Comment by zhiweiv** [comment]
The memory usage of svchost.exe looks good with following OS version, it is not beyond 30MB after a few days with the previous setting.

Publisher: microsoft-aks  
Offer: aks-windows  
SKU: 2019-datacenter-core-smalldisk-2008  
Version: 17763.1397.200820

**Comment by immuzz** [comment]
This is good news. Closing it out as we have investigated and made some improvements there. Please let us know if you see the issue again.
