### ISSUE TITLE
[BUG] Running many pods on a Windows node at the same will lead to failures of container

### ISSUE THREAD

**Issue by ShiqianTao** [microsoft/Windows-Containers#351]
**According to https://github.com/Azure/AKS/issues/3612, the first issue should belong to Windows Containers runtime.**

**Describe the bug**
Running many pods on a Windows node at the same will lead to failures of the container.
- Windows containerd created container but exited with failure repeatedly. E.g., 
```
time="2023-04-07T07:19:37.961009200Z" level=info msg=Span duration="575.2µs" endTime="2023-04-07 07:19:37.9615844 +0000 GMT m=+52.729818501" event="&TaskExit{ContainerID:dab1f8e69908b82004b7588053bb2e8b534d7f670ba47e4afebf95893b39d23e,ID:dab1f8e69908b82004b7588053bb2e8b534d7f670ba47e4afebf95893b39d23e,Pid:12876,ExitStatus:2147500037,ExitedAt:2023-04-07 07:19:25.9646369 +0000 GMT m=+40.733090601,XXX_unrecognized:[],}" name=publishEvent parentSpanID=1efed0bbef22d2cf spanID=f85b785afe091c68 startTime="2023-04-07 07:19:37.9610092 +0000 GMT m=+52.729243301" topic=/tasks/exit traceID=c472cfea53de4b4feaa1d5d276323654
```

**To Reproduce** 
Refer to https://github.com/Azure/AKS/issues/3612

**Expected behavior**
Node has sufficient resources and should run these pods without the above issues.

**Configuration:**
 - Edition: Windows Server
- Base Image being used: Windows Server Core
 - Container engine: Containerd
 - Container Engine version: containerd://1.6.14+azure

**Additional context**

**Comment by fady-azmy-msft** [comment]
Routing this to the correct team (#44584622)

**Comment by fady-azmy-msft** [comment]
This looks like an Azure CNI issue @ShiqianTao. Please route this issue to https://github.com/Azure/azure-container-networking/issues

**Comment by ShiqianTao** [comment]
Thank you, @fady-azmy-msft . The issue may be caused by 3 factors, the main issue is
- https://github.com/Azure/AKS/issues/3612

There are different errors from different components, so I created 2 sub-issues:
  - https://github.com/microsoft/Windows-Containers/issues/351 (this one for Containers Runtime)
  - https://github.com/Azure/azure-container-networking/issues/1918 (another one for Azure CNI)

Some issues may need Containers Runtime's help, e.g., containers should only pull the same image once (a few seconds are enough), instead of all containers pulling their own images redundantly, which results in pulling images costing more than 10 minutes.
```
  Normal   Pulling                 27m                  kubelet            Pulling image "mcr.microsoft.com/dotnet/framework/samples:aspnetapp"
  Normal   Pulled                  13m                  kubelet            Successfully pulled image "mcr.microsoft.com/dotnet/framework/samples:aspnetapp" in 13m53.6124318s
```

**Comment by fady-azmy-msft** [comment]
Ah

**Comment by fady-azmy-msft** [comment]
I see. This looks like two different issues @ShiqianTao, is that right? If so, can you split this so we can deal with each separately? 

I've created an internal ticket for the containerd-related issue (#44710270).

**Comment by ShiqianTao** [comment]
Hi @fady-azmy-msft . Agree. I created another issue https://github.com/microsoft/Windows-Containers/issues/364, and updated this issue's description. Thank you.

**Comment by fady-azmy-msft** [comment]
@kiashok would you have thoughts on this?

**Comment by fady-azmy-msft** [comment]
Spoke with @sbangari and we believe this is an Azure CNI issue. Can you redirect this to the Azure CNI's github [Issues · Azure/azure-container-networking (github.com)](https://github.com/Azure/azure-container-networking/issues). The issues raised here are actively monitored by the Azure CNI team.

**Comment by ShiqianTao** [comment]
Thank you, @fady-azmy-msft . I have created https://github.com/Azure/azure-container-networking/issues/1918
