### ISSUE TITLE
Cannot run Windows container in process-isolated mode

### ISSUE THREAD

**Issue by Michelle-Shou** [microsoft/Windows-Containers#352]
I followed the [Microsoft document ](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container#create-container) and try to run a Windows contianer in process-isolated mode. I got errors below.  I can run container with **--isolation=hyperv**, but not **--isolation=process**. 

docker run -it **--isolation=process** mcr.microsoft.com/**windows:ltsc2019** cmd
> docker: Error response from daemon: hcsshim::CreateComputeSystem b54b8c03a1950f220bfa0402b8c87688fb0fb235676995fd216d33bb300dee7b: The container operating system does not match the host operating system.
 
 Does this error means I need to find the exact tag of base image with match my os on the post PC? 
 I use both Windows 10 on my host pc, which tag is right for me?

 Edition: Windows 10 Pro
 Version: 22H2
 OS build: 19045.2006
 Experience: Windows Feature Experience Pack 120.2212.4190.0

 
Best regards,
Miche

**Comment by akarshm** [comment]
The process isolation containers need to match the build number of the host. The compatibility matrix is available [here](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10).

The recommendation is to use Hyper-V isolation since the container image is WS2019 while the host is Windows 10 22H2 (Build 19045).

**Comment by Michelle-Shou** [comment]
> The recommendation is to use Hyper-V isolation since the container image is WS2019 while the host is Windows 10 22H2 (Build 19045).

Thanks for your comment. I see now I have to check the build number, but there is no 22H2 container image available. I tried process isolation because I am want to share USB devices with container. Can I share device with hyperv isolation container? Do you know there any plans of release new Windows base image?

**Comment by vrapolinario** [comment]
This would answer your question: https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/hardware-devices-in-containers

USB is not supported and device sharing is only supported with process isolation.

**Comment by Michelle-Shou** [comment]
Thanks for answering my question. It looks like windows container does not meet my requirement.
