### ISSUE TITLE
Windows container /system32/drivers/etc/hosts behavior

### ISSUE THREAD

**Issue by Antonytm** [microsoft/Windows-Containers#357]
**What is your question?**

I want to be able to use `host.docker.internal` inside Windows containers.

1. I have Docker compose file, which contains different Windows base images. 
1. After starting, I connect to them one by one and run the command: `ping host.docker.internal`
1. Results are different from container to container. 
1. It can be failure
```
C:\>ping host.docker.internal
Ping request could not find host host.docker.internal. Please check the name and try again.
```
5. Or it can be a success
```
C:\Identity>ping host.docker.internal

Pinging host.docker.internal [192.168.88.23] with 32 bytes of data:
Reply from 192.168.88.23: bytes=32 time<1ms TTL=127
Reply from 192.168.88.23: bytes=32 time<1ms TTL=127
Reply from 192.168.88.23: bytes=32 time<1ms TTL=127
Reply from 192.168.88.23: bytes=32 time<1ms TTL=127
```
6. I compared these containers. The difference is that containers that work have DNS records in the `hosts` file
```
192.168.88.23 host.docker.internal
192.168.88.23 gateway.docker.internal
```
7. Containers that fail to find `host.docker.internal` doesn't have anything in their `hosts` file

8. I am on the latest Docker Desktop version
9. Adding `*.docker.internal` names to `hosts` file is enabled:
![image](https://user-images.githubusercontent.com/647813/236627358-13b97801-e8c5-4725-9681-c671fb88d770.png)
10. I have no `extra_hosts` settings in my Docker compose files

**My questions:**
1. What is the expected behavior for Windows containers? Should Windows containers have DNS records?
2. Is this behavior different for different base images: NanoServer/ServerCore/WindowsServer/Windows?
3. Which part is responsible for updating `hosts` file? Is it on Docker side? Or is it backed into images?
4. How to troubleshoot and dig deeper to find, what causes this difference?

**Comment by fady-azmy-msft** [comment]
Since we don't own the experience for Docker / Docker Desktop, the best place to ask these questions would be on Windows Docker repo (https://github.com/docker/for-win). A few issues that might be relevant to this: 
1. [Hosts file not updated after upgrading to 4.18.0](https://github.com/docker/for-win/issues/13398)
2. [Update to 4.18.0 removed 127.0.0.1 host.docker.internal from hosts file on windows](https://github.com/docker/for-win/issues/13388)
