### ISSUE TITLE
addition and deletion of routes inside the container network namespace

### ISSUE THREAD

**Issue by rawahars** [microsoft/Windows-Containers#362]
## Summary
I am trying to add as well as delete routes inside a container network compartment without exec'ing into the container. Our networking setup is such that-
- We create an empty network compartment using docker
- We create an `L2Bridge` as defined in the blog post [here](https://techcommunity.microsoft.com/t5/networking-blog/l2bridge-container-networking/ba-p/1180923).
- We create an HNS Endpoint from the above `L2Bridge` and attach it to the earlier created network namespace

When we exec inside the container and check the routes, we see the default ones. We want to `add` as well as `delete` routes inside the container network compartment.

We have validated that if we do the following, we can accomplish the same-
- Use [SetCurrentThreadCompartmentId](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-setcurrentthreadcompartmentid) to set the compartment ID of the container namespace
- Run the Win32 APIs to add/remove routes. They would run in the container network namespace.
- Set the network compartment back to the host compartment using above API

While it works for us, the Microsoft documentation states `Reserved for future use. Do not use this function`. Also, there was some confusion about the usage of this method in https://github.com/microsoft/hcsshim/issues/937. However, we observed that this method  [is used in](https://github.com/moby/moby/blame/e8a79114b8c1782d5539421c9a6a1cd6fc5dfa65/libnetwork/network_windows.go#L20) `docker` code as well to modify the network namespace.

Can you please confirm if the usage of `SetCurrentThreadCompartmentId` to modify network namespace is supported?

**Comment by jterry75** [comment]
Any updates here?

**Comment by sbangari** [comment]
@rawahars The usage of SetCurrentThreadCompartmentId for modifying the routes in the compartment is supported.

**Comment by rawahars** [comment]
Thanks @sbangari for the confirmation.
