### ISSUE TITLE
Disabling management vNIC in host namespace for L2Bridge HNS network to prevent cross-interface traffic

### ISSUE THREAD

**Issue by rawahars** [microsoft/Windows-Containers#363]
## Summary
We are setting up container networking on a host VM similar to as suggested in documentation [here](https://techcommunity.microsoft.com/t5/networking-blog/l2bridge-container-networking/ba-p/1180923) such that-
- We have a network interface on host intended for the host traffic. There is another network interface on host which is intended for containers. Both the interfaces may or may not be in the same subnet.
- We create an L2Bridge which connects to the second interface in the upstream vSwitch port. The specified subnet for HNS network is same as the subnet of the second network interface.

The ask is that the traffic from host namespace goes through network interface 1 where as the traffic from containers goes through network interface 2 via L2Bridge.

Therefore, we disable the management vNIC from the host namespace for the L2Bridge. While functionally this seems to work properly, **we want the Microsoft guidance that using the L2Bridge in this configuration is supported**.

## Implementation commands
```
$network = New-HnsNetwork -Type L2Bridge -Name "winl2bridge" -AddressPrefix "10.0.3.0/24" -Gateway 10.0.3.1 -AdapterName "Ethernet 4" -DNSServer 10.0.0.2

$endpoint = New-HnsEndpoint -NetworkId $network.ID -Name "l2bridge-ep" -IPAddress "10.0.3.77"

$container = docker run -d --net none mcr.microsoft.com/windows/servercore:ltsc2019 ping -t localhost

Attach-HnsEndpoint -EndpointID $endpoint.ID -CompartmentID 2 -ContainerID $container

netsh interface set interface name="vEthernet (Ethernet 4)" admin=disabled
```
Note that the second interface on the VM has IP address `10.0.3.249`. L2Bridge is configured such that the gateway `10.0.3.1`, DNS server `10.0.0.2`, and the container IP `10.0.3.77` exists in the infrastructure.

## Additional details
**ipconfig in host namespace before creation of L2Bridge network**
```
PS C:\Users\Administrator> ipconfig

Windows IP Configuration


Ethernet adapter Ethernet 3:

   Connection-specific DNS Suffix  . : corp.rawahars.com
   Link-local IPv6 Address . . . . . : fe80::77e8:4489:3127:7948%4
   IPv4 Address. . . . . . . . . . . : 10.0.1.81
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.1.1

Ethernet adapter Ethernet 4:

   Connection-specific DNS Suffix  . : corp.rawahars.com
   Link-local IPv6 Address . . . . . : fe80::2aaa:56bd:abad:3b0d%18
   IPv4 Address. . . . . . . . . . . : 10.0.3.249
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.3.1

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7796:446e:a30e:e584%11
   IPv4 Address. . . . . . . . . . . : 172.26.112.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```

**ipconfig in host namespace after creation of L2Bridge network**
```
PS C:\Users\Administrator> ipconfig

Windows IP Configuration


Ethernet adapter Ethernet 3:

   Connection-specific DNS Suffix  . : corp.rawahars.com
   Link-local IPv6 Address . . . . . : fe80::77e8:4489:3127:7948%4
   IPv4 Address. . . . . . . . . . . : 10.0.1.81
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.1.1

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7796:446e:a30e:e584%11
   IPv4 Address. . . . . . . . . . . : 172.26.112.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```

**Output of hnsdiag list all**
```
PS C:\Users\Administrator> hnsdiag list all
Networks:
Name             ID
nat              517896AD-0E70-48A1-9923-8F7F15BA512E
winl2bridge      E01FCBE0-FA5F-4C02-8FA8-CCE24B7B72C7

Endpoints:
Name             ID                                   Virtual Network Name
l2bridge-ep      452fd775-643d-4d08-ada5-200d30f6047f winl2bridge

Namespaces:
ID                                   | Endpoint IDs

LoadBalancers:
ID                                   | Virtual IPs      | Direct IP IDs
```

**Comment by sbangari** [comment]
@rawahars Disabling the management vNic from the host namespace in L2Bridge network mode is not a supported configuration. This may lead to network connectivity drops or unpredictable network behavior.

**Comment by rawahars** [comment]
@sbangari Thanks for your response.

Since when using L2Bridge disabling management vNIC is not supported then how can we configure multiple physical interfaces on the VM? 

Essentially we need all the traffic from host to go through only network interface 1 in the host namespace. The major issue i feel with keeping the management vNICs in host namespace enabled is that the traffic from host (eg kubelet or other agents) can go through the secondary interfaces which might not have equivalent connectivity policies.

**Comment by rawahars** [comment]
@MikeZappa87 @daschott @sbangari Any update about this issue?

**Comment by sbangari** [comment]
@rawahars Can you try setting a lower metric (higher priority) on the InterfaceMetric and the RouteMetric for the default route on the preferred interface for the traffic and see if that addresses your scenario? This setting would prefer the specific interface for all the traffic from the host namespace.

Set-NetIPInterface -ifIndex 1 -InterfaceMetric 10
Set-NetRoute -ifIndex 1 -DestinationPrefix 0.0.0.0/0 -RouteMetric 10

**Comment by jterry75** [comment]
@sbangari - We cannot use RouteMetrics for weight. We have seen that in many cases even with a lower metric, Windows still selects the 2nd net interface. Each of the networking interfaces may have different security policies based on the containers that are attached to them. For example, maybe one of the nic's has a policy for access to a specific resource. That nic is attached to the vswitch for that specific container net namespace. We do not want any other processes with network access to be able to inadvertently use that nic and gain those privileges. Thus, we disable all nics associated to l2bridge or transparent networks from the host compartment, so now process other than container processes in the appropriate net namespaces can use those nics.

**Comment by rawahars** [comment]
@sbangari @MikeZappa87 Can you please help with this issue?

**Comment by jayanthAP** [comment]
@jterry75, @rawahars You mentioned "_in many cases even with a lower metric, Windows still selects the 2nd net interface_". This seems like unexpected behavior? Is this something you can reproduce? If yes, could you use the below commands to collect data-path logs and share them with us?

netsh trace start provider=Microsoft-Windows-TCPIP report=di cap=yes
netsh int  ipv4 delete dest
netsh int  ipv6 delete dest
_repro issue_
netsh trace stop

**Comment by fady-azmy-msft** [comment]
Closing issue because it's going stale.
