### ISSUE TITLE
Request for Input (from Microsoft) - Where do you get your Windows Containers news?

### ISSUE THREAD

**Issue by fady-azmy-msft** [microsoft/Windows-Containers#368]
We're exploring streamlining the Windows Container news and would like to get your input. 

Where do you get your Windows Container news (latest updates/enhancements/bug fixes)? And where would you normally expect to find this information?

**Comment by zhiweiv** [comment]
I am using Windows Container Blog RSS Feed to get news, https://techcommunity.microsoft.com/plugins/custom/microsoft/o365/custom-blog-rss?tid=5995606656199244418&board=Containers&label=&messages=&size=10.

But it is not easy to find a good RSS Feed reader, something like https://github.com/dotnet/announcements is a good way I prefer.

For bug fix updates, I subscribed interested issues in this repo.

**Comment by Sporesirius** [comment]
Mostly from this repo and https://techcommunity.microsoft.com/t5/containers/bg-p/Containers
I prefer GitHub.
