### ISSUE TITLE
Populating a volume using a container does not work in Docker on Windows #40771

### ISSUE THREAD

**Issue by windymindy** [microsoft/Windows-Containers#369]
Hello.
Could this possibly be in scope of this project?
https://github.com/moby/moby/issues/40771

When using Docker Desktop in the Windows Containers mode named volumes render directories empty.

I found it very confusing that named volumes prepopulating behaviour is Linux only.
And I did not seem to find it mentioned anywhere in the documentation.

Thank you.

**Comment by zylxjtu** [comment]
There is already a document link for this in the original thread?

https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes

**Comment by ntrappe-msft** [comment]
FYI @ritikaguptams

**Comment by ritikaguptams** [comment]
Hi @windymindy,
These links might be helpful: https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/persistent-storage#named-volumes and https://techcommunity.microsoft.com/t5/itops-talk-blog/containers-basics-providing-persistent-storage-to-containers/ba-p/1200050 . If that doesn't help, could you share the steps and expected vs actual behavior you are seeing?

**Comment by windymindy** [comment]
> Hi @windymindy, These links might be helpful: https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/persistent-storage#named-volumes and https://techcommunity.microsoft.com/t5/itops-talk-blog/containers-basics-providing-persistent-storage-to-containers/ba-p/1200050 . If that doesn't help, could you share the steps and expected vs actual behavior you are seeing?

Hey.
Ty for the links.

The steps are described in
moby/moby#40771
and
https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container

The idea, once again, is that one is able to pick out data from the container. Maybe, override some of it, for instance a configuration file, and put it back. This is how named docker volumes are mostly used on linux.

But as the note warns (thanks for finding it), the target inside the container should be empty.
https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes

The reason I made this ticket is that I was wondering if there is some major limitation that prevents from implementing the behaviour.
Or perphaps there is a place for a storage plugin, that would do exactly that akin the local-persist plugin.

**Comment by ntrappe-msft** [comment]
I've added "pre-populating named volumes" to our backlog of feature requests. If we have a chance in the future, we'll try to incorporate this ask into our plans. Since we don't have a current timeline to share, I'll close this Issue.

**Comment by ntrappe-msft** [comment]
To provide additional context to future viewers, you _can_ pre-populate volumes in both Linux and Windows Docker containers but you'll have to approach them in different ways.

## Linux Docker Containers
For Linux Docker containers, we can create a volume, use a temporary container to populate it, and hook it up to the container. That, or any other container, can have access to the contents of the volume. We do this through the following commands:

1. Create a volume.
```vim
docker volume create my-vol
```

2. Check that the volume exists and lives in `.../docker/volumes`.
```vim
docker volume ls
docker volume inspect my-vol
```
3. Create a file `a.txt` in the folder `foo/` on our Desktop.
```vim
cd foo
echo hi > a.txt
```
4. Populate the contents of the volume using a temporary container. Here, we're populating `my-vol` with the contents of `foo/`.
```vim
tar -C /Users/Desktop/foo -c -f- . | docker run --rm -i -v my-vol:/data alpine tar -C /data -xv -f-
```
> [!IMPORTANT]
> Make sure you specify `my-vol:/data` not `my-vol`. `my-vol` is the name of the volume that lives on the host. `:/data` is the mount point and where in the container's file system you want to access the data in `my-vol`.
5. Run the container with that volume. We're using the `alpine` image in this case.
```vim
docker run -v my-vol:/data -it --name bar alpine
```
> [!NOTE]
> Make sure Docker Desktop is set to "Use Linux Containers" and you've pulled the image `alpine`.
6. In the container, check the contents of `data/` and you should see `a.txt`. 
```vim
$> data ls

a.txt
```
> [!NOTE]
> If `data/` has no files, either you have not pre-populated the volume or you did not provide the correct mount point. On Docker Desktop, you can check the contents of `my-vol`. If it has `a.txt`, then check your container start up code. If it's empty, try populating the volume again.


## Windows Docker Containers
For Windows Docker containers, we can only create an **empty** volume and attach it to a container. The container can populate it but it does not start out pre-populated like Linux containers can do. There _is_ a way to emulate this behavior however.

1. Create a volume.
```vim
docker volume create my-vol
```

2. Check that the volume exists and lives in `...\\docker\\volumes`.
```vim
docker volume ls
docker volume inspect my-vol
```

3. Create a file `a.txt` in the folder `foo\` on our Desktop.
```vim
cd foo
echo hi > a.txt
```

4. Here is the magic. We'll use a temporary container to copy over the files from `foo\` into `my-vol`.
```vim
docker run --rm -v C:\Users\Desktop\foo:C:\foo -v my-vol:C:\data -it mcr.microsoft.com/windows/servercore:ltsc2022
```
> [!NOTE]
> `C:\Users\Desktop\foo` has all the files we want for our volume. We'll mount it to `C:\foo` in the temporary container. `my-vol` is the name of our volume and `C:\data` is the mount point.

5. Inside the container, check that `foo\` and `data\` exist.
```vim
$> dir

02/05/2024    02:26 PM      <DIR>      data
02/05/2024    01:51 PM      <DIR>      foo
... other folders
```

6. Now, copy all the contents of `foo\` into `data\`. You can then delete `foo\`.
```vim
$> Xcopy C:\foo C:\data /E /H /C /I

1 File(s) copied
```
7. Shut down the container.
```vim
$> exit
```
8. Now, run the container you wanted with the volume `my-vol`.
```vim
docker run -v my-vol:C:\data -it mcr.microsoft.com/windows/servercore:ltsc2022
```
9. Inside the container, you should see the folder `data\` with all the files we wanted.
```vim
$> dir

02/05/2024    02:26 PM      <DIR>      data

$> dir data

02/05/2024    02:23 PM                 a.txt
```
