### ISSUE TITLE
hcsshim::CreateScratchLayer - failed failed in Win32: The system cannot find the path specified. (0x3)

### ISSUE THREAD

**Issue by Hithesh0899** [microsoft/Windows-Containers#375]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
my base image FROM mcr.microsoft.com/windows/servercore:ltsc2019
Unable to build the image using the docker file with WORKDIR C:/app command 

**To Reproduce** 

**Expected behavior**
Image of sample application should be created without any bugs

**Configuration:**
 - Edition: Windows 10 Enterprise
- Base Image being used: mcr.microsoft.com/windows/servercore:ltsc2019
 - Container engine:
 - Container Engine version  20.10.17

**Additional context**
Step 1/14 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> 66a1a48cbc11
Step 2/14 : WORKDIR C:/dockers
hcsshim::CreateScratchLayer - failed failed in Win32: The system cannot find the path specified. (0x3)

`dockerfile: `

FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR C:/app

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# https://github.com/docker-library/python/pull/557
ENV PYTHONIOENCODING UTF-8

#PYTHON Dependency
ENV PYTHON_VERSION 3.11.3

RUN $url = ('https://www.python.org/ftp/python/{0}/python-{1}-amd64.exe' -f ($env:PYTHON_VERSION -replace '[a-z]+[0-9]*$', ''), $env:PYTHON_VERSION); \
	Write-Host ('Downloading {0} ...' -f $url); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile 'python.exe'; \
	\
	Write-Host 'Installing ...'; \
# https://docs.python.org/3/using/windows.html#installing-without-ui
	$exitCode = (Start-Process python.exe -Wait -NoNewWindow -PassThru \
		-ArgumentList @( \
			'/quiet', \
			'InstallAllUsers=1', \
			'TargetDir=C:\Python', \
			'PrependPath=1', \
			'Shortcuts=0', \
			'Include_doc=0', \
			'Include_pip=0', \
			'Include_test=0' \
		) \
	).ExitCode; \
	if ($exitCode -ne 0) { \
		Write-Host ('Running python installer failed with exit code: {0}' -f $exitCode); \
		Get-ChildItem $env:TEMP | Sort-Object -Descending -Property LastWriteTime | Select-Object -First 1 | Get-Content; \
		exit $exitCode; \
	} \
	\
# the installer updated PATH, so we should refresh our local value
	$env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine); \
	\
	Write-Host 'Verifying install ...'; \
	Write-Host '  python --version'; python --version; \
	\
	Write-Host 'Removing ...'; \
	Remove-Item python.exe -Force; \
	Remove-Item $env:TEMP/Python*.log -Force; \
	\
	Write-Host 'Complete.'
	
	
	# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 22.3.1
# https://github.com/docker-library/python/issues/365
ENV PYTHON_SETUPTOOLS_VERSION 65.5.1
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py
ENV PYTHON_GET_PIP_SHA256 96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207

RUN Write-Host ('Downloading get-pip.py ({0}) ...' -f $env:PYTHON_GET_PIP_URL); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $env:PYTHON_GET_PIP_URL -OutFile 'get-pip.py'; \
	Write-Host ('Verifying sha256 ({0}) ...' -f $env:PYTHON_GET_PIP_SHA256); \
	if ((Get-FileHash 'get-pip.py' -Algorithm sha256).Hash -ne $env:PYTHON_GET_PIP_SHA256) { \
		Write-Host 'FAILED!'; \
		exit 1; \
	}; \
	\
	$env:PYTHONDONTWRITEBYTECODE = '1'; \
	\
	Write-Host ('Installing pip=={0} ...' -f $env:PYTHON_PIP_VERSION); \
	python get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		--no-compile \
		('pip=={0}' -f $env:PYTHON_PIP_VERSION) \
		('setuptools=={0}' -f $env:PYTHON_SETUPTOOLS_VERSION) \
	; \
	Remove-Item get-pip.py -Force; \
	\
	Write-Host 'Verifying pip install ...'; \
	pip --version; \
	\
	Write-Host 'Complete.'
	

	
COPY . C:/app
COPY Execution_Logs.txt C:/

**Comment by Hithesh0899** [comment]
Please need an immediate assistance on the above issue

**Comment by zylxjtu** [comment]
Can you please try with workdir c:\\\\app (escape the backslash) as specified here? https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile#considerations-for-using-workdir-with-windows

**Comment by Hithesh0899** [comment]
Thanks, sure let me check and update

**Comment by Hithesh0899** [comment]
> Can you please try with workdir c:\\app (escape the backslash) as specified here? https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile#considerations-for-using-workdir-with-windows

I tried this too, but it is giving the same error. Please help me.

**Comment by ntrappe-msft** [comment]
Hi. I tried to reproduce your error but the build was successful for me. Could you provide us with some more info? 

**Task 1:** Check which version of the Windows Server Core 2019 image you're using.
- Get the image ID: `docker images mcr.microsoft.com/windows/servercore:ltsc2019`
- Paste the output of `docker inspect <image ID you just got>`

**Task 2:** Give us more information on your Docker system.
- Paste the output of `docker version`

**Task 3:** Check how much memory is available for Docker.
- Make sure Docker Desktop is open in the background and that docker is running
- In a PowerShell window, run `docker info --format '{{.MemTotal}}'`
- Paste whatever number (e.g. `8588828672`) you see
- Or, depending on your version of Docker Desktop, tell us what you see under memory: **`Docker Desktop`** > **`Settings`** > **`Resources`** > **`Memory`**

**Comment by Hithesh0899** [comment]
> ntrappe-msft

Thanks a lot for the steps you have shared, apology for the late reply. 
Issue got resolved, after i have selected an option - set to factory defaults. 

Root cause: I have unknowingly deleted some data in C:Programdata/docker/windowsfilter - caused this issue, 
after setting to factory defaults, it removed all the junk and old files from C drive and able to create image.

Thanks a lot for reply @ntrappe-msft

![image](https://github.com/microsoft/Windows-Containers/assets/86660424/bb139610-be5d-447e-9f9d-0235597e8d8c)

**Comment by Hithesh0899** [comment]
If anything i will reopen the issue.

**Comment by ntrappe-msft** [comment]
Ok! Thanks for letting us know and I'm happy your issue was resolved. I'll make a note of the error and root cause you identified to help us in the future.

**Comment by Hithesh0899** [comment]
This is new issue which i need to address in the same thread. @ntrappe-msft 
Docker for Windows: No permissions over folders inside `C:\ProgramData\Docker`
I dont have access inside this folder, even if I go into the folder again every file and folder needs to have admin access. 
Please need your help how disable the admin access to above path C:\ProgramData\Docker
Kindly need an solution

**Comment by ntrappe-msft** [comment]
Let's check what permissions you currently have for the files in the `Docker` folder. Can you give me the output of the following command?

(This is for **Command Prompt** but I can give you a **Powershell** equivalent too).
```ruby
icacls "C:\Program Files\Docker\*"
```

You should get something like:
```powershell
C:\Program Files\Docker\licenses.txt 
    NT AUTHORITY\SYSTEM:(I)(F)
    BUILTIN\Administrators:(I)(F)
    BUILTIN\Users:(I)(RX)
    APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
    APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(RX)
C:\Program Files\Docker\metadata.json 
. . . 
etc. 
```

**Comment by Hithesh0899** [comment]
As of now i am in company - but my admin is trying to give permissions. 
but we tried a lot it is not happening. 
Please need to understand the root cause.
currently the following is the status of folder permission: 

<img width="330" alt="image" src="https://github.com/microsoft/Windows-Containers/assets/86660424/9887f483-f3ee-482d-a9ad-23ab8232f573">

**Comment by ntrappe-msft** [comment]
Can you:
1. Open up File Explorer and navigate to the `C:\ProgramData` folder?
2. Write-click on the `Docker` folder to open up folder properties.
3. In the **`General`** tab make sure you have "Read-only" access checked.
4. Go to the **`Security`** tab and click `Advanced`.
5. Under **`Permissions`** click `Continue`.
6. What access do you see? Full control?

**Comment by Hithesh0899** [comment]
Sure, I will check this things and will update you on this - regarding monday. Apologies for delay.

**Comment by fady-azmy-msft** [comment]
Issue is going stale, closing this issue for now.

**Comment by ntrappe-msft** [comment]
This may not solve the specific issue you had _but_ it did resolve it when I encountered it.

For reference, I tried to start up a container from a Windows Server Core LTSC 2022 image.

```cmd
> docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 powershell
```

This failed and I received the error: `Error response from daemon: hcsshim::CreateScratchLayer failed in Win32: The system cannot find the path specified. (0x3).`

The image I was using was decently old; I'd pulled it 5 months ago and hadn't updated it or received any of the new security patches.

```cmd
> docker images

REPOSITORY                            TAG       IMAGE ID      CREATED
mcr.microsoft.com/windows/servercore  ltsc2022  29e69ab16e91  5 months ago
```

I pulled the newest image, ran the command to start up a container again, and everything succeeded.

```cmd
> docker pull mcr.microsoft.com/windows/servercore:ltsc2022
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:ltsc2022

> docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 powershell
```

Hope this helps anyone else!
