### ISSUE TITLE
File access times not visible and can't be enabled

### ISSUE THREAD

**Issue by Acohen-work** [microsoft/Windows-Containers#376]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
When querying a directory with /ta flag, file access times don't get updated.
There is also no way to enable this. Generally it is done via command line like:
fsutil behavior set disablelastaccess 0
However that requires an OS restart, which is impossible in a containerized environment.
I've tried including that step in a docker file after the FROM line, so the key gets modified, however the OS never gets to 'boot' with those settings.

**To Reproduce** 
run a ltsc2019 image. create a file like:
copy con a.txt
aaa (f6-enter)

dir /ta (you will see the current time)
then, more a.txt
(you will see 'aaa')
then, dir /ta.
you will see the same time (access time not updated).

**Expected behavior**
Access times get updated, either out of the box, or there is some way to do this.

**Configuration:**
 - Edition: W10
- Base Image being used: ltsc2019
 - Container engine: docker
 - Container Engine version 4.18.0

**Additional context**
I am open to other solutions besides just a registry key edit, but it must be actionable from within a container. File Access time is a critical attribute.

**Comment by jupan-msft** [comment]
Sharing some findings when repro this issue and one work around. Note that this issue is not limited to Windows container. Below repro can be done on a Windows 11 machine and I got the same result.

### Repro and work around
You can use Powershell and it always returns the correct value for Last Access time.
```
PS E:\> docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell.exe

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> fsutil behavior query disablelastaccess
DisableLastAccess = 3  (System Managed, Enabled)             <-- It is by default enabled.
PS C:\> Set-Content -Path "test.txt" "abcd"
PS C:\> dir .\test.txt|select FullName,LastAccessTime,LastWriteTime

FullName    LastAccessTime      LastWriteTime
--------    --------------      -------------
C:\test.txt 6/8/2023 2:04:43 PM 6/8/2023 2:04:43 PM


PS C:\> sleep 60
PS C:\> Get-Content .\test.txt
abcd
PS C:\> dir .\test.txt|select FullName,LastAccessTime,LastWriteTime

FullName    LastAccessTime      LastWriteTime
--------    --------------      -------------
C:\test.txt 6/8/2023 2:06:47 PM 6/8/2023 2:04:43 PM         <-- Correct value.


PS C:\> cmd
Microsoft Windows [Version 10.0.17763.4377]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>dir /TA test.txt
 Volume in drive C has no label.
 Volume Serial Number is A023-275E

 Directory of C:\

06/08/2023  02:04 PM                 6 test.txt                        <-- Wrong value.
               1 File(s)              6 bytes
               0 Dir(s)  136,085,008,384 bytes free
```

**Comment by jupan-msft** [comment]
Following up on this.

According to [this doc](https://learn.microsoft.com/en-us/windows/win32/sysinfo/file-times), The NTFS file system delays updates to the last access time for a file by up to 1 hour after the last access. If my repro experiment, if you wait one hour and read the file, dir /TA will display the updated LastAccessTime.

**Comment by ntrappe-msft** [comment]
We'll also update our documentation to reflect @jupan-msft's findings.

**Comment by ntrappe-msft** [comment]
@Acohen-work did that answer your question? Or do you need clarity on something else?

**Comment by Acohen-work** [comment]
This seems like a reasonable workaround
