### ISSUE TITLE
How to Register Com DLL(Which was developed long back) in windows Container wirh  .net framework 4.8  base image . and use that dll and expose that as a web application.

### ISSUE THREAD

**Issue by UdayaBhandaru** [microsoft/Windows-Containers#379]
How to Register Com DLL(Which was developed long back) in windows Container wirh .net framework 4.8 base image . and use that dll and expose that as a web application in IIS.
There is no documentation available explaining this scenario . It would be of great help if there is any documentation and guidance. 

I have tried using 

```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
WORKDIR /inetpub/wwwroot
COPY . .
RUN regsvr32.exe /s /i *****.dll
Expose 80
```

the dll is not getting registered for sure

Thanks,
Uday

**Comment by Cloudsq-Su** [comment]
Can you provide the dll that I can use to repro the issue?

Here are some troubleshooting ideas:

Confirm that this works on the host machine. Make sure no error dialogs appear.

Run process monitor on the container host and repro the full scenario above. Filter the output to focus on any registry modifications with the key name and share the output.

In a normal cmd window (not powershell) see if "echo %ERRORLEVEL%" shows an error code after the command has run.

**Comment by fady-azmy-msft** [comment]
Closing issue due to going stale.
