### ISSUE TITLE
Add support to HCN for setting Valid/PreferredLifetime for vEthernet IP Address

### ISSUE THREAD

**Issue by jterry75** [microsoft/Windows-Containers#385]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/microsoft/hcsshim/issues/1419 for historical context. Moving to Windows Containers repo.

We have discovered that in some cases, when setting a static IP on a vEthernet adapter in a container namespace that the Valid/PreferredLifetime of the IP address will be set to 60 minutes. After 60 minutes the IP address expires and because it is a static IP not from DHCP no address reallocated. At this point the container will drop all IP connectivity until the IP address is put back in the container namespace.

**Describe the solution you'd like**
We would like a way via the HCN API to set the Valid/PreferredLifetime of the IPAddress assigned to the vEthernet Endpoint created by the HCN. Something like

```
Set-NetIPAddress -ifIndex 39 -IPaddress <address> -ValidLifetime "00:30:00" -PreferredLifetime "00:30:00"
```
But we cannot do this via PowerShell because NanoServer containers do not have PowerShell by default. So we would like this to be done via HCN setup, rather than require an exec into the container namespace to accomplish this.

**Describe alternatives you've considered**
At the moment we are running a sidecar container in the container namespace that automatically does this operation, but it consumes host level resources to run this sidecar just to set the lifetime.

**Additional context**

**Comment by MikeZappa87** [comment]
That certainly sounds like undesirable behavior. Can you provide details on your set up and how you go about assigning the static ip address inside the network namespace? Are you assigning IPV4 or IPV6 addresses? For IPv4, these values are pretty much useless and should follow a 'forever' default as Linux does. Linux sets those fields as forever as well when statically assigned as well when its ipv6.

**Comment by jterry75** [comment]
Hey @mikezappa87, apologies for the delay in response.

We are assigning static ip's on the vNIC created by the HNS when we create the endpoint. These are IPv4 addresses. For Transparent networking, we take the IPv4 address / MAC of the host adapter and put it onto the HNS endpoint. We attach it to the transparent network and disable the physical net interface in the host compartment. Therefore all traffic to and from the interface in the container namespace appears directly as that host address (transparent networking design). It seems that what may be happening is that the IPv4 address inherits the lifetime of the address from the host NIC. When the lifetime expires, dhcp client cannot reset the lifetime because the nic is disabled in the host compartment. And so the IPv4 address expires. (This is just a hunch). If we could simply set the lifetime of the IPv4 address on the adapter via the HNS when creating to infinite, it would solve this issue.
