### ISSUE TITLE
PreStop Hook execute script

### ISSUE THREAD

**Issue by codeground123** [microsoft/Windows-Containers#388]
We are trying to configure a PreStop hook in a OpenShift Windows Container Platform.  In Prestop we want to execute a perl/powershell script which is not working.

```
**preStop:
              exec:
                command: 
                  - 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
                  - '-File'
                  - 'C:\pathtoscript\myscript.ps1'**
```

Also tired specifying more value to "terminationgraceperiod:1200", no luck

I want to run a script when pod is scaled down or terminated, 

Below is my powershell script which copies files to volume

```
$sourcePath ="C:/somefolder/logs"
$destinationPath = "C:/Data/appname/PROD "
# Get all .log files in the source folder
$files = Get-ChildItem -Path $sourcePath -Filter "*.log"
# Move each .log file to the destination folder
foreach ($file in $files) {
$destination = Join-Path -Path $destinationPath -ChildPath $file.Name
Move-Item -Path $file.FullName -Destination $destination
Write-Host "Moved file: $($file.Name)"
}
```

**Comment by jsturtevant** [comment]
We do have tests that run pre-stop exec hooks (https://testgrid.k8s.io/sig-windows-signal#capz-windows-master&include-filter-by-regex=Container%20Lifecycle%20Hook).  What type of container are you running the power shell command against (nano/servercore)?

**Comment by codeground123** [comment]
@jsturtevant 
The base image I am using is servercore/ltsc2022

From the POD terminal I can execute basic powershell command

**Comment by aravindhp** [comment]
@codeground123 please post the full `Deployment` spec. Or are you trying to use a `DeploymentConfig`?

**Comment by codeground123** [comment]
@aravindhp 

Please find the deployment yaml below. I have removed/renamed few variables to not show some private data

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  namespace: mfg-it
  uid: abcd
  resourceVersion: '34333333'
  generation: 14
  creationTimestamp: '2023-06-19T07:00:59Z'
  annotations:
    deployment.kubernetes.io/revision: '4'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycontainername
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asdfasdffsd
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: pull-secret-name
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 1200
      dnsConfig:
        nameservers:
          - 10.20.xx.xxx
          - 10.xx.xx.xxx
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 150m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 150Mi
          terminationMessagePath: /dev/termination-log
          lifecycle:
            **preStop:
              exec:
                command: 
                  - 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
                  - '-File'
                  - 'C:\pathtoscript\myscript.ps1'**
          name: somename
          command:
            - 'C:\pathtocommand\installer.cmd'
          env:
            - name: COMPUTERNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ntfs-logs
              mountPath: 'C:\\Data'
          terminationMessagePolicy: File
          image: 'artifactory/it-mfg/myapp:jun19'
      volumes:
        - name: ntfs-logs
          persistentVolumeClaim:
            claimName: ntfs-pvcname
      dnsPolicy: ClusterFirst
      tolerations:
        - key: os
          value: Windows
```


My Powershell script myscript.ps1  looks like below

```
$sourcePath ="C:/somefolder/logs"
$destinationPath = "C:/Data/appname/PROD "
# Get all .log files in the source folder
$files = Get-ChildItem -Path $sourcePath -Filter "*.log"
# Move each .log file to the destination folder
foreach ($file in $files) {
$destination = Join-Path -Path $destinationPath -ChildPath $file.Name
Move-Item -Path $file.FullName -Destination $destination
Write-Host "Moved file: $($file.Name)"
}
```

One Thing I observed is, the files are not getting moved but the folder is getting created and timestamp for the folder is getting updated

**Comment by codeground123** [comment]
@aravindhp @jsturtevant 

Observed that the copying of files to volume using a script in PreStop is not working. Any ideas or solutions ?

The service account for the Persistent Volume Claim has Full permissions

Not sure how to debug when PreStop is running. This is a windows container. Container Events do not show any logs related to prestop.

**Comment by codeground123** [comment]
Was able to fix this.

Observed that Move Item does not work during PreStop Executions

Replacing it with Copy-Item worked for me. Was able to move the files.

I think during PreStop Move item will not work, maybe windows will lock few files that are in use.

**Comment by codeground123** [comment]
Was able to fix this.

Observed that Move Item does not work during PreStop Executions

Replacing it with Copy-Item worked for me. Was able to move the files.

I think during PreStop Move item will not work, maybe windows will lock few files that are in use.

**Comment by ntrappe-msft** [comment]
Hi, thanks for finding a solution! We'll make a note of this for our PreStop engineers to explore why `Move` does not work but `Copy` does work.
