### ISSUE TITLE
Run on arm64?

### ISSUE THREAD

**Issue by steveiliop56** [microsoft/Windows-Containers#389]
**What is your question?**
Could the windows nano server image possibly run on arm64, specifically on a raspberry pi 4?

**Comment by michbern-ms** [comment]
We don't support running Windows containers on ARM64 at this time.  It is something we are considering, but I don't have a timeline I can share with you.  

Windows 10 IoT Core supports Raspberry Pi, in case that is useful to you:
https://learn.microsoft.com/en-us/windows/iot-core/tutorials/rpi
