### ISSUE TITLE
Signed Docker Images for Windows Images

### ISSUE THREAD

**Issue by alexander-webber** [microsoft/Windows-Containers#39]
Are there any plans to sign windows images so that we can take advantage of [ACR Content Trust](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-content-trust) / image signing in Azure? There was a [forum question](https://social.msdn.microsoft.com/Forums/azure/en-US/ceebf674-ffe2-4ba8-a213-15cc7c139a22/signed-docker-images-for-windows-images?forum=AzureContainerServices) over a year ago regarding this but it would appear this still hasn't happened.

**Comment by thecloudtaylor** [comment]
We are considering signing Windows base and derivative images as part of the [Notary V2]( https://github.com/notaryproject/requirements) effort. 

Additionally all of the binaries in the base windows images are catalog signed and the base images are always distributed from a Microsoft endpoint (referred to as a non-redistributable-artifacts or foreign layer).

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by SteveLasker** [comment]
Hi folks,
As @thecloudtaylor [mentioned](https://github.com/microsoft/Windows-Containers/issues/39#issuecomment-652688869), we will be providing SBOMs and signing all MCR content with Notary v2 signatures, enabling Artifact Reference Types. The work is underway. We plan to have ACR support early this fall, with mcr content support soon thereafter.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 90 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by jsturtevant** [comment]
this was announced https://techcommunity.microsoft.com/t5/containers/announcing-image-signing-for-windows-containers/ba-p/3792097
