### ISSUE TITLE
Visual Studio reports "Docker is not installed" after docker-ce installation on Windows Server 2019

### ISSUE THREAD

**Issue by iancward** [microsoft/Windows-Containers#393]
**What is your question?**

Hi there; I support some legacy .Net Framework applications and we had met with some degree of success putting them into containers and migrating them to the cloud. For our build environment, we have been leveraging Windows Server 2019 with Visual Studio 2019 Build Tools and Docker installed through the [OneGet MicrosoftDockerProvider](https://github.com/OneGet/MicrosoftDockerProvider) which is what the Microsoft documentation had a while back.

The OneGet provider has been deprecated since May, so we tried installing through the script provided in this repository for docker-ce; however, Visual Studio build tools complains that it can't locate Docker, even though it is, in fact, installed.

```
PS C:\Users\Administrator\git\myproject\Web> docker version
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false

PS C:\Users\Administrator\git\myproject\Web> msbuild.exe .\web.csproj /t:containerbuild /p:Configuration=Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/3/2023 8:26:49 PM.
Project "C:\Users\Administrator\git\myproject\Web\web.csproj" on node 1 (containerbuild target(s)).
ContainerVerifyDockerInstallation:
  'docker' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\Administrator\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.11.1\build\Container.tar
gets(97,5): error : Docker is not installed or is not in the current PATH. [C:\Users\Administrator\git\myproject\Web\
web.csproj]
Done Building Project "C:\Users\Administrator\git\myproject\Web\web.csproj" (containerbuild target(s)) -- FAILED.


Build FAILED.

"C:\Users\Administrator\git\myproject\Web\web.csproj" (containerbuild target) (1) ->
(ContainerVerifyDockerInstallation target) ->
  C:\Users\Administrator\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.11.1\build\Container.t
argets(97,5): error : Docker is not installed or is not in the current PATH. [C:\Users\Administrator\git\myproject\We
b\web.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.47
```

Is there something missing from the install script that Visual Studio is looking for? It looks like the container target is running `docker --version` which runs fine in the same PowerShell prompt.

```
PS C:\Users\Administrator\git\myproject\Web> docker --version
Docker version 24.0.2, build cb74dfc
```

`where.exe` also reports that `docker` is in `C:\Windows\System32`:

```
PS C:\Users\Administrator\git\myproject\Web> where.exe docker
C:\Windows\System32\docker.exe
```

**Comment by iancward** [comment]
It looks like Visual Studio, being a 32 bit application, is redirected to `C:\Windows\SysWow64` [instead](https://developercommunity.visualstudio.com/t/vs2019-v1654-unable-to-open-microsoft-files-in-env/998765). The old MicrosoftDockerProvider [updated the Path](https://github.com/OneGet/MicrosoftDockerProvider/blob/developer/DockerMsftProvider.psm1#L664) to add the docker installation directory, whereas the new installation script [merely copies](https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1#L619-L623) `docker.exe` and `docker.exe` to `C:\Windows\System32`. This means that it's not available to Visual Studio.

I imagine the new script should probably install the files to somewhere other than `C:\Windows\System32` add the docker installation directory to the PATH the same way that the old provider did.

**Comment by ntrappe-msft** [comment]
Hi, quick question: did you have Docker Desktop running while you built your solution in Visual Studio?

**Comment by ntrappe-msft** [comment]
Hi. Could you paste the output of `docker version` please?

**Comment by ntrappe-msft** [comment]
I could not repro the error you're getting from Visual Studio. However, I think that docker is installed in the correct location and that Visual Studio can access it. I was only able to get similar errors when Docker Desktop was not running and I was trying to start up a container or build in Visual Studio.

**Comment by iancward** [comment]
Hi @ntrappe-msft sorry for not writing back sooner. This is in a Windows Server environment, so I've installed Docker-CE via the helper script [in this repository](https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1), per the [Microsoft Documentation](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1), so Docker Desktop doesn't exist.

**Comment by ntrappe-msft** [comment]
Ah sorry for my confusion. I'd assumed you had installed Docker Desktop. I'll try to repro using only Docker-CE and see whether Visual Studio fails to find essential Docker scripts.

**Comment by ntrappe-msft** [comment]
I tried to repro a similar but simple setup:
- I installed Docker-CE using the script in this repo
- I installed Visual Studio
- I created a basic ASP.NET core app
- I enabled Docker for Windows when creating the new project
- In the Solution Explorer, I added Docker support which created a Dockerfile
- I built the Dockerfile and it successfully passed (meaning it found where I'd installed Docker)

Since I didn't hit the error you did, could you explain:
- [ ] what type of project/solution you created on Visual Studio?
- [ ] did you enable Docker support?
- [ ] did you add any Docker orchestration support?
- [ ] have you taken a look at this [guide for using Docker + Visual Studio](https://learn.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022)?

**Comment by ntrappe-msft** [comment]
Issue has gone stale. Closing for now.

**Comment by iancward** [comment]
HI @ntrappe-msft, sorry, I didn't notice that you had written back on this.
You used Visual Studio to build the application? Your fourth bullet indicates that Visual Studio installed docker, which means that it did not find the Docker for Windows installation from bullet one.

When you use Visual Studio, it installs Docker Desktop; as I mentioned in my example, I used Build Tools, which is a 32-bit application and it simply expects docker to already exist.

Try these steps to reproduce:

- Start with Fresh Windows Server 2019 instance
- Install Docker CE as per the script in this project
- Install Visual Studio 2019 build tools
- Bring Docker project created elsewhere onto server (e.g. file copy or repository clone)
- Run: `msbuild.exe .\<path_to_project_file> /t:containerbuild /p:Configuration=Release`

You should observe that msbuild is unable to locate docker. This is because the docker-ce installation script in this repository copies docker.exe directly to C:\Windows\System32. But, msbuild.exe is a 32-bit application and instead uses C:\Windows\SysWow64 and is therefore not able to find docker.exe.
