### ISSUE TITLE
New Installers Fail Under System Account - Which is Used by Azure Custom Script Extension for running instance scripts

### ISSUE THREAD

**Issue by DarwinJS** [microsoft/Windows-Containers#395]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
When run under the system account by the terraform provider azurerm_virtual_machine_extension, the script errors out when trying to add the scheduled task.

**To Reproduce** 

1. Use azurerm_virtual_machine_extension to run this script which simply uses the Azure Custom Script Extension.
1. Observe errors in file: C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\*\Status\0.status

**Expected behavior**
To be able to orchestrate the installation from the SYSTEM account.

The official docs for these scripts talk about the Azure Custom Script Extension as though it is supported: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=containerd#custom-script-extensions - but I'm wondering if it has been tested with this code because I'm not having success.

**Configuration:**
 - Edition: [e.g. Windows 11, Windows Server]
- Base Image being used: [e.g. Windows Server Core]
 - Container engine: [e.g. docker]
 - Container Engine version [e.g. 22]

**Additional context**

**Comment by DarwinJS** [comment]
FYI - in my scenario I did not need the hyper-v feature - maybe that could be controlled by a switch since it seems to be the reason for a mid-install reboot?

**Comment by ntrappe-msft** [comment]
Hi, thanks for bringing this issue to our attention! Would you mind attaching a file or pasting the errors you saw in file `C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension*\Status\0.status` so we can identify whether we encounter the same ones?

**Comment by DarwinJS** [comment]
I ended up using just the containers install and using chocolatey to install the docker cli.

The code was part of a blog for Microsoft and is here: https://gitlab.com/guided-explorations/microsoft/azure-aks/aks-windows/-/blob/master/gitlab-infra/aks-terraform/shell-runner-with-docker-install.ps1?ref_type=heads

**Comment by ntrappe-msft** [comment]
Ah interesting. I wonder if there was an Issue with not having Docker on the system or configured improperly. Just to make sure I understand, where you trying to set up a GitLab Runner on an Azure virtual machine using the Azure Custom Script Extension?

**Comment by ntrappe-msft** [comment]
I'll close this for now but please let us know if you encounter any other issues. Thanks.
