### ISSUE TITLE
Foreign layers not skipped during Docker push of mcr.microsoft.com/windows/servercore:ltsc2019 after 6/14

### ISSUE THREAD

**Issue by xiaoluo2017** [microsoft/Windows-Containers#398]
**Describe the bug**
After 6/14, foreign layers are no longer being skipped during the Docker push of mcr.microsoft.com/windows/servercore:ltsc2019, resulting in increased push times.

**To Reproduce** 
In Powershell:
```powershell
docker pull mcr.microsoft.com/windows/servercore:ltsc2019
docker tag mcr.microsoft.com/windows/servercore:ltsc2019-amd64 <your_registry>/<your_repository>:<your_tag>
docker push <your_registry>/<your_repository>:<your_tag>
```
Replace <your_registry>, <your_repository>, and <your_tag> with your own values.

**Expected behavior**
The output should show:
```
bf00aa7b5e3a: Skipped foreign layer
```
However, it actually takes 3 minutes to push the image.

**Configuration:**
 - Edition: Windows 11
 - Base Image being used: mcr.microsoft.com/windows/servercore:ltsc2019
 - Container engine: docker
 - Container Engine version: 24.0.2

**Additional context**
Since 6/14, the ‘Push Container Image’ time in the Azure build pipeline has increased from 4 seconds to several minutes.

Upon investigation, it appears that before 6/14, foreign layers were being skipped during the push process. However, after 6/14, no foreign layers were skipped.

Further investigation into the ‘Docker: Build’ task revealed that the main difference between the two builds is that for mcr.microsoft.com/windows/servercore:ltsc2019-amd64, a newer image was available after 6/14.

The RootFS layers of the image mcr.microsoft.com/windows/servercore:ltsc2019-amd64 are also different between the two builds. In the build before 6/14, there are two layers, both of which were skipped during the Docker push. In the build after 6/14, however, there is only one layer and it was not skipped.

**Comment by AbelHu** [comment]
I think that it is expected. https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833

**Comment by xiaoluo2017** [comment]
Thanks AbelHu, it makes sense.
