### ISSUE TITLE
The container operating system does not match the host operating system.

### ISSUE THREAD

**Issue by nkpun** [microsoft/Windows-Containers#399]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
We are using Azure AVD with Windows 10  for developer development. The command below fails:

**docker run --rm -it --entrypoint cmd.exe mcr.microsoft.com/windows/nanoserver:1809**
docker: Error response from daemon: hcs::CreateComputeSystem 377c5ba81cdccd9cf8217251aba4171ca3bd6a593f14db12c3ae6ead394530c3: The container operating system does not match the host operating system.

**To Reproduce** 
Run command below on AVD (Azure Virtual Desktop):
docker run --rm -it --entrypoint cmd.exe mcr.microsoft.com/windows/nanoserver:1809

**Expected behavior**
Able to run the nanoserver container.

**Configuration:**
 - Edition: Microsoft Windows [Version 10.0.19045.3086]
- Base Image being used: mcr.microsoft.com/windows/nanoserver:1809
 - Container engine: Server: Docker Desktop 4.21.1 (114176)
 - Container Engine version:Server: Docker Desktop 4.21.1 (114176)

**Additional context**
When I run the docker info, I get where **Default Isolation: process**
Server:
Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
Images: 43
Server Version: 24.0.2
Storage Driver: windowsfilter
  Windows:
Logging Driver: json-file
Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 19045 (19041.1.amd64fre.vb_release.191206-1406)
Operating System: Microsoft Windows Server Version 22H2 (OS Build 19045.3086)
OSType: windows
Architecture: x86_64
Docker Root Dir: C:\ProgramData\Docker
Debug Mode: false
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

Questions:
1. Why is Default Isolation: process instead of hyperv
2. Is this what's causing error above? If so, what's the step to set the process to hyperv.

**Comment by ntrappe-msft** [comment]
Hi. Could you paste the output of `docker version` please?

**Comment by ntrappe-msft** [comment]
Hi. Could you paste the output of `docker version` please?

**Comment by nkpun** [comment]
yep sure, pls see below

Client:
Cloud integration: v1.0.35
Version:           24.0.2
API version:       1.43
Go version:        go1.20.4
Git commit:        cb74dfc
Built:             Thu May 25 21:53:15 2023
OS/Arch:           windows/amd64
Context:           default

 

Server: Docker Desktop 4.21.1 (114176)
Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by nkpun** [comment]
I'm confident that AVD is Windows 10 but unsure how docker info is showing this:
**Operating System: Microsoft Windows Server Version 22H2 (OS Build 19045.3086)**

winver shows this:

![Capture](https://github.com/microsoft/Windows-Containers/assets/4523497/b89e504a-2978-4b9e-8f3c-d505ebdb8335)

**Comment by ntrappe-msft** [comment]
Did you try different variations of that command? I tend to run containers using this syntax (with the image first then the interactive terminal type given the `-it` flag).
```ruby
docker run -it mcr.microsoft.com/windows/nanoserver:1809 cmd
```

**Comment by nkpun** [comment]
Issue has been resolved.

Windows 10 OS on AVD runs within Windows Server. As a result, docker desktop engine detects the Product Type as 3 which means [VER_NT_SERVER](https://docs.docker.com/engine/reference/commandline/dockerd/#on-windows) (Windows Server). The default isolation is ‘Process’ for windows server, hence the docker throws the incompatible host OS.

What' the work around?

Set isolation type to hyerv.

{
"exec-opts": ["isolation=hyperv"],
"experimental": false
}

**Comment by GoingMyWay** [comment]
> Issue has been resolved.
> 
> Windows 10 OS on AVD runs within Windows Server. As a result, docker desktop engine detects the Product Type as 3 which means [VER_NT_SERVER](https://docs.docker.com/engine/reference/commandline/dockerd/#on-windows) (Windows Server). The default isolation is ‘Process’ for windows server, hence the docker throws the incompatible host OS.
> 
> What' the work around?
> 
> Set isolation type to hyerv.
> 
> { "exec-opts": ["isolation=hyperv"], "experimental": false }

@nkpun

Thanks. It actually resolved the issue.
