### ISSUE TITLE
Creating a Container with Nfs Client Support

### ISSUE THREAD

**Issue by pnookala-px** [microsoft/Windows-Containers#400]
Hi Team, I am trying to create a Windows Container that has a NFS Client  Enabled and my DockerFile reads:

FROM [mcr.microsoft.com/windows/server:ltsc2022](http://mcr.microsoft.com/windows/server:ltsc2022)
RUN powershell.exe Install-WindowsFeature NFS-Client;

Here the installation fails as the command expects the server to be restarted for the changes to take effect. Is there any workaround where we can install the feature without requiring a reboot?

**Comment by fady-azmy-msft** [comment]
Can you explain what you're trying to achieve with avoiding the reboot? @pnookala-px

**Comment by pnookala-px** [comment]
I am trying to a get a docker image with nfs feature enabled. If I reboot at this instance, the docker container that gets created doesn't have nfs enabled. I am all for reboot but the client for nfs should be on by default in the container that I want to use. Please suggest how I can reboot safely so that the feature is enabled.

**Comment by boxoky** [comment]
Hi @pnookala-px , have you fixed it? 

If not, it might help you, have you used SMB to Persistent Storage with Docker/containers in general?

**Comment by pnookala-px** [comment]
Hi, I used hostprocess container to mount the nfs file system. Smb also worked but we wanted to limit to nfs, used hpc. It works from k8s version 1.25 onwards.

**Comment by boxoky** [comment]
I'm happy to read it. Thanks to you I found this new feature in Kubernetes. Thank you!
