### ISSUE TITLE
Windows and Linux simultaneously for Windows Server 2016, 2019, and 2022

### ISSUE THREAD

**Issue by Cjewett** [microsoft/Windows-Containers#404]
We're in a position where we would like to install both Windows and Linux container functionality on the same machine without the need to swap between the two.  The current belief is that Windows Server 2016 does not support Linux containers and that the functionality for Linux containers is considered beta for all Windows Server versions. Due to that I was hoping to get some answers to questions which would help us understand the current state of the world.

- Based on [this discussion](https://github.com/microsoft/Windows-Containers/issues/318#issuecomment-1480332494) it looks like running Windows and Linux container functionality at the same time should work. Is that true for Windows Server 2016 and 2019? The blog revolves around Windows Server 2022.
- What does `WSL 2 is supported for development and testing purposes, not production`  mean exactly?

**Comment by Cjewett** [comment]
@vrapolinario Sorry to ping but any thoughts here? Saw you were the one who wrote the blog post

**Comment by jupan-msft** [comment]
I did find another blog that explains the steps to run Windows and Linux containers simultaneously with WSL on Windows. [Running Windows and Linux containers without Docker Desktop](https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/).

I don't think server 2016 could work, but you can try install WSL on server 2019 with instructions [here](https://learn.microsoft.com/en-us/windows/wsl/install-on-server#install-wsl-on-previous-versions-of-windows-server).

**Comment by fady-azmy-msft** [comment]
WSL 2 only supports WS22 ([no WSL 2 support for WS 2019](https://github.com/MicrosoftDocs/WSL/issues/678)) and we only recommend using WSL 2 for dev not production workloads.

Can you share your scenario behind wanting to use all Windows Server versions and Linux simultaneously?

**Comment by fady-azmy-msft** [comment]
Closing issue because it's going stale.
