### ISSUE TITLE
Question about how to skip foreign layer?

### ISSUE THREAD

**Issue by CHENXIXIXIXI718** [microsoft/Windows-Containers#407]
**Question about how to skip foreign layer or how to speed up docker push?**
Hi,
I see the announcement provided [Announcing Removal of Foreign Layers from Windows Container Images](https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833) in previous issue, which said about the foreign layer would be added. Actually as my own experience, this change is very unfriendly because  it made docker push very slow. In our case, the duration of docker push in worst case is ten times than before, and usually about five times than before. So my question is there any way to skip push the foreign layer? For example, does there exist command to skip push foreign layer during the docker push? Or do you have other idea and solutions?
Thanks for your time,
Chenxi

**Comment by jinweili1** [comment]
Hi team, any suggestions about it?

**Comment by CHENXIXIXIXI718** [comment]
Hi, maybe does anyone has any idea?

**Comment by NAWhitehead** [comment]
> **Question about how to skip foreign layer or how to speed up docker push?** Hi, I see the announcement provided [Announcing Removal of Foreign Layers from Windows Container Images](https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833) in previous issue, which said about the foreign layer would be added. Actually as my own experience, this change is very unfriendly because it made docker push very slow. In our case, the duration of docker push in worst case is ten times than before, and usually about five times than before. So my question is there any way to skip push the foreign layer? For example, does there exist command to skip push foreign layer during the docker push? Or do you have other idea and solutions? Thanks for your time, Chenxi

Hey, I have a few questions and items I want to clarify first. I just want to clarify that the foreign layer has been removed and no longer exists. 
What is the size that you are pushing? 
What is your internet speed?

**Comment by jinweili1** [comment]
Hi @NAWhitehead ,For your question, the size is 3.6GB, and because we are using azure resources that is the VM created by image with D8s sku.
The internet speed is not stable, sometime push all layers to azure cr takes 4mins, but the worst case takes 30mins, and for now the P80 of the pushing time is 8mins, but our build pipeline just 15mins without push image.

**Comment by NAWhitehead** [comment]
> Hi @NAWhitehead ,For your question, the size is 3.6GB, and because we are using azure resources that is the VM created by image with D8s sku. The internet speed is not stable, sometime push all layers to azure cr takes 4mins, but the worst case takes 30mins, and for now the P80 of the pushing time is 8mins, but our build pipeline just 15mins without push image.

Hello, when we decided to remove the foreign layer from the container images we knew that there would be an increased start-up cost for those that had unstable internet connect for the first image push. However, now that you have pushed to your container registry the next time the image will be cached in your repository and only the new added layers will need to be pushed going forward.

**Comment by NAWhitehead** [comment]
> Hi @NAWhitehead ,For your question, the size is 3.6GB, and because we are using azure resources that is the VM created by image with D8s sku. The internet speed is not stable, sometime push all layers to azure cr takes 4mins, but the worst case takes 30mins, and for now the P80 of the pushing time is 8mins, but our build pipeline just 15mins without push image.

Hello, when we decided to remove the foreign layer from the container images we knew that there would be an increased start-up cost for those that had unstable internet connect for the first image push. However, now that you have pushed to your container registry the next time the image will be cached in your repository and only the new added layers will need to be pushed going forward.

**Comment by jinweili1** [comment]
But now, we're facing a problem that is the push container image step is always push all layers, even if there already has same layer. Hi @NAWhitehead do you know what will cause it?

**Comment by NAWhitehead** [comment]
> 

Hey, we are going to try and replicate the issue and I will get back to you.

**Comment by NAWhitehead** [comment]
> But now, we're facing a problem that is the push container image step is always push all layers, even if there already has same layer. Hi @NAWhitehead do you know what will cause it?

Hey we are going to try and replicate this issue and I will get back to you.

**Comment by NAWhitehead** [comment]
> But now, we're facing a problem that is the push container image step is always push all layers, even if there already has same layer. Hi @NAWhitehead do you know what will cause it?

Hello @jinweili1 we have tried recreating this could you provide your steps so that we can follow what you are doing so that we can attempt to recreate this issue.

**Comment by fady-azmy-msft** [comment]
Closing issue because it's going stale.
