### ISSUE TITLE
No Matching Manifest

### ISSUE THREAD

**Issue by ntrappe-msft** [microsoft/Windows-Containers#410]
**Describe the bug**
When trying to pull a Windows Server Core LTSC 2022 image, it fails with the error message:
```ruby
no matching manifest for linux/amd64 in the manifest list entries
```

**To Reproduce** 
- Start up Docker Desktop. If you don't have it installed, download it [here](https://www.docker.com/products/docker-desktop/).
- In a PowerShell window, run the following command:
```ruby
docker pull mcr.microsoft.com/windows/servercore:ltsc2022
```
- You should see the error message after running the command.

**Expected behavior**
We would expect the pull to be successful and to start seeing Docker download the image. There should be no error message.

**Configuration:**
- Edition: Windows 11
- Base Image: Windows Server Core LTSC 2022
- Container Engine: Docker
- Container Engine Version: 24.0.2 (`cb74dfc`)

**Comment by ntrappe-msft** [comment]
**Background:**
This error occurs when there is a mismatch between the Container Image OS and the platform OS. We are trying to pull a _Windows_ image, however, it's saying it cannot find a "`manifest for linux/amd64`". This message arises when the Docker platform is set to "Linux containers" while trying to pull a Windows image.

**Solution:**
If Docker Desktop is running, switch the platform to use Windows containers by right-clicking the little docker icon (black whale) in the system tray. Click **`"Switch to Windows containers"`**. To confirm that you have switched (there can be a 30s delay), right-click again on the icon and if you see the option **`"Switch to Linux containers"`** you know that it's now using Windows containers. Try to pull the image again and it should succeed.

**Comment by mshakurov** [comment]
This is not a solution. When selecting any of the container platforms, Windows or Linux, the same error still occurs, even after restarting Docker Desktop services after switching.
And this applies not only to one version of LT SC 2022, it applies to any version. In general, no image can be downloaded, we get an error on any of the images:
docker: no matching manifest for linux/amd64 in the manifest list entries.
