### ISSUE TITLE
Does EFS encryption (cipher.exe) work?

### ISSUE THREAD

**Issue by tanzislam** [microsoft/Windows-Containers#414]
I ran `cipher /e License.txt`, and it is failing with a `The request is not supported` error. (`net start` shows that the `Encrypting File System (EFS)` service has already started.)

Tried under containers based on both `mcr.microsoft.com/windows:ltsc2019` and `mcr.microsoft.com/windows/servercore:ltsc2019` images, same result.

**Comment by fady-azmy-msft** [comment]
@tanzislam Can you provide your repro steps when you hit this issue?

**Comment by tanzislam** [comment]
Start the container on the base image:
`docker run -it --rm mcr.microsoft.com/windows/servercore:ltsc2019`

Then, in the cmd.exe prompt inside the container, run `net start` to ensure that the EFS service has come up. If necessary, wait a minute or start it yourself using `net start EFS`.

Afterwards, try using `cipher.exe` to apply EFS encryption on any file inside the container, for example the `C:\License.txt` file:
`cipher /e License.txt`

This fails with the error.

**Comment by fady-azmy-msft** [comment]
@tanzislam Can you also explain what you're trying to accomplish by encrypting files from within a container with EFS?

**Comment by tanzislam** [comment]
We have a production C# application (run as a service account) that applies EFS encryption on some secret files at startup. (It uses the [.NET Framework's `FileInfo.Encrypt()` API](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.encrypt?view=net-7.0) to do so.)

I'm trying to Dockerize it for development/testing purposes, and this is the feature gap I'm currently running into. For now I'm working around by commenting out the relevant code and rebuilding the app.

**Comment by fady-azmy-msft** [comment]
Got it. I believe this is by design and not a bug.

Since containers are designed to [be stateless](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/lift-shift-to-containers#what-cant-be-moved-to-windows-containers), if a file is encrypted with EFS inside a container using a user-specific key, it could become inaccessible when the container is terminated. Disabling EFS within containers helps prevent this potential issue.

You can use EFS encryption on the host and then mount the encrypted files or directories into the container as volumes. This way, the files remain encrypted on the host system, and the container can access the decrypted content as needed.

**Comment by tanzislam** [comment]
I understand that rationale in case of Dockerfile `RUN` statements and in the case of files in bind-mounts and volumes during `docker run` (where the files would outlive the container), but not in the case of files in the container's own filesystem (where the files are as ephemeral as the container). https://docs.docker.com/storage/

Is there a way to make the encryption operation return a success code within the container (so that existing code can behave the same way at the API level), even if the encryption operation is implemented as a no-op (in line with the stateless containers design principle)?

**Comment by ntrappe-msft** [comment]
Hi. Someone else may correct me but I do not believe that you can return a success code in the container for the encryption operation. Is there a reason why you'd need a success code (or any code)? We may be able to suggest some other mechanisms for you to use.

**Comment by tanzislam** [comment]
Ok thanks. I was looking for this so that I can get our production logic to work as-is, without introducing any Docker-specific logic to skip the EFS-encryption bit.

You can close this issue; I'll have to add a check of whether our program is running in Docker (based on [registry keys, running services, etc.](https://stackoverflow.com/questions/43002803)).

**Comment by ntrappe-msft** [comment]
Thanks for explaining your situation. We'll let you if anything changes in the future but, for now, I appreciate you finding a workaround.
