### ISSUE TITLE
ReFS support

### ISSUE THREAD

**Issue by mikenorgate** [microsoft/Windows-Containers#416]
I've been investigating the possibility of building a custom snapshotter for containerd that can make use of ReFS block cloning to help speed up container start times by reducing IO.

However I'm getting the following error

```
time="2023-08-31T14:01:19Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:e3ed4837ac41531c693a2a70929b7c50ce22997f81268031dabc470345139022: hcsshim::ProcessBaseLayer \\\\?\\D:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.refs\\snapshots\\1: Incorrect function.: unknown" key="extract-957600700-rp30 sha256:e3ed4837ac41531c693a2a70929b7c50ce22997f81268031dabc470345139022"
ctr: failed to extract layer sha256:e3ed4837ac41531c693a2a70929b7c50ce22997f81268031dabc470345139022: hcsshim::ProcessBaseLayer \\?\D:\ProgramData\containerd\root\io.containerd.snapshotter.v1.refs\snapshots\1: Incorrect function.: unknown
```

Is there a limitation in vmcompute `ProcessBaseImage` that means it's not able to work on an ReFS filesystem?

**Comment by Howard-Haiyang-Hao** [comment]
@mikenorgate Were you using docker or containerd? Could you please share your repro steps? I would also like to know the Container Host OS that you were using for your repro. Thanks

**Comment by Howard-Haiyang-Hao** [comment]
@mikenorgate, REFS volume is not currently supported by our container filter driver. Let me follow up with the team to see where we stand in terms of supporting REFS as the container data volume:

<img width="1017" alt="image" src="https://github.com/microsoft/Windows-Containers/assets/30302321/9f92e63e-721c-4c3c-b1b9-1e1cd4774226">

**Comment by Howard-Haiyang-Hao** [comment]
@mikenorgate,  Upon returning from the feature team, there is currently no plan to support REFS as the container layer volume. I will update this thread if there are any changes to the plan in the future.
