### ISSUE TITLE
windows firewall not working in windows containers

### ISSUE THREAD

**Issue by itsmurugappan** [microsoft/Windows-Containers#418]
This [page](https://learn.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-isolation-security) outlines about network isolation and mentions in isolation mode hyperv windows firewall is part of the container. I am not able to start windows firewall nor base filter engine to write custom rules. 

is [wfp](https://learn.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page) available in windows containers ?

OS: windows 11 pro
Docker version: 24.x
container image: tried in all windows images (server/server core/nano/windows)

**Comment by fady-azmy-msft** [comment]
Hey @itsmurugappan, let me look into this. In the meantime can you share what you're trying to do with the windows firewall / base filter engine?

**Comment by itsmurugappan** [comment]
Thank you. looking at running some windows containers in kubernetes. Would like to use wfp to write some network policies.

**Comment by kestratt** [comment]
@itsmurugappan,

1. Are the fw/bfe services running in your local environment? Running the following commands in powershell should return a status of running:
    Get-Service bfe
    Get-Service mpssvc

2. What networking mode are you planning to use for your Kubernetes cluster?

3. Would you be able to elaborate some more on the network policies are you trying to create in wfp?

**Comment by fady-azmy-msft** [comment]
Closing this issue because it's going stale.
