### ISSUE TITLE
Windows nanoserver container - Is it possible to install the aws cli?

### ISSUE THREAD

**Issue by psimms-r7** [microsoft/Windows-Containers#419]
**What is your question?**
A clear and concise description of what your question is. If you have bug/blocker, please open a 'Bug Report' issue instead.
Windows nanoserver container - Is it possible to install the aws cli?

I am creating a windows nanoserver container and looking to install the aws cli - but I can't seem to install it due to the lack of msi

Is there a way recommended way to install the aws cli on a nanoserver container?

**Comment by fady-azmy-msft** [comment]
Hey @psimms-r7, I'm not sure what the recommended way to install AWS CLI on nanoserver is. I'd recommend you ask the EKS team on https://github.com/aws/containers-roadmap/
