### ISSUE TITLE
Windows container monitoring events and logging improvement ask

### ISSUE THREAD

**Issue by keikhara** [microsoft/Windows-Containers#42]
Due to the nature of docker, all console logs are pushed out thru stdout and stderr. Since Windows application places their given windows format, customer as coming back asking how can they push their logs thru docker format but able to use to troubleshoot. Some of the customer responses we see are IIS logs. 

- length of the log should fit stdout/stderr
- log format should fit the common standard which is close to linux so vendors can consume

**Comment by jsturtevant** [comment]
would this help: https://github.com/microsoft/windows-container-tools?

**Comment by immuzz** [comment]
Adding to the backlog. It will be prioritized on the next planning cycle.

**Comment by vrapolinario** [comment]
The Log Monitoring tool above should provide the ability to extract logs from Windows Containers to Docker Logs. The IIS team is currently working on enabling the tool on their image. Their current Insider image has it enabled: https://hub.docker.com/_/microsoft-windows-servercore-iis-insider

We'll close this for now and reopen if there's a request to improve the tool.
