### ISSUE TITLE
Database connection dropped on long running jobs from Windows Container

### ISSUE THREAD

**Issue by ay-garg** [microsoft/Windows-Containers#423]
Is there any way we can increase the TCP idle timeout value for Windows Container? The pod running on Windows Node is connecting to a database external to the cluster but in the same network where sometimes the Database takes 20+ minutes to respond with results and the client closes the TCP connection i.e. Windows container.

I found the following documentation link:
--> https://learn.microsoft.com/en-us/azure/aks/windows-faq?tabs=azure-cli#what-is-the-default-tcp-timeout-in-windows-os

However, if the request is initiated directly from the Windows node then connection doesn't drop after 20+ minutes but from the pod it's dropping.

**Comment by fady-azmy-msft** [comment]
Unfortunately, there isn't a way to increase the idle timeout for Windows Containers, we do have an issue (#81 ) that we monitor the interest of if this is a priority for you. At the time we of the original issue though, we deemed this enhancement not a priority.

A possible workaround to this is to implement a keep-alive mechanism where you send periodic keep-alive messages to the external database to ensure that the TCP connection remains active.

CC @mikezappa87 for visibility.

**Comment by ay-garg** [comment]
Hey @fady-azmy-msft thanks for replying, I checked for adding tcp_keepalive in deployment for the pods but as per my understanding it will work fine for Linux container and not sure about Windows Container. Will you be able to confirm or share an example for Windows Container if possible for you?

**Comment by ay-garg** [comment]
@fady-azmy-msft any help on this please?

**Comment by MikeZappa87** [comment]
The container networking stack has different settings outside of the ip stack for the host. A few questions.
What database are you using? Does it have any way to send keep alives? 
Have you tried to optimize the database so that a query does not take 20+ minutes?

Keep in mind, increasing the timeout can impact performance in other ways since the socket is left open.

**Comment by fady-azmy-msft** [comment]
Closing this because it's going stale.
