### ISSUE TITLE
Running simple visual basic script for unzipping a zip file throws Unspecified Error

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [microsoft/Windows-Containers#424]
### Describe the Bug

I would like to run a visual basic script inside the docker container that places zipped content into a destination inside the docker container. It appears there may be something missing in the base image I am using: `mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019`, which is based on the image `mcr.microsoft.com/windows/servercore:ltsc2019-amd64`. My .vbs script ultimately yields an unspecified error when creating a NameSpace for my zip file. 

### To Reproduce

1. Clone https://github.com/christopher-watanabe-snkeos/dotnet-framework-docker-batch-file-issue
2. Create a `testZip.zip` with some dummy content inside. 
3. Build the docker container; e.g. `docker build . -t test-dotnet-batch-issue`
4. Run the docker container in interactive mode. e.g. `docker container run -it test-dotnet-batch-issue`
5. Try to run the .vbs script with `cscript ./test.vbs`

From these steps, I notice the following: 
- The zip folder and test.vbs are copied successfully to the docker container. 
- Running `cscript ./test.vbs` yields the following output: 
> destination: C:\
zipFilename: C:\testZip.zip
Creating Shell.Application Object
Creating objShell.NameSpace of testZip.zip
C:\test.vbs(12, 1) (null): Unspecified error

It seems the hangup is this line in the .vbs file: 
`set zipFiles=objShell.NameSpace(zipFilename).items`

### Expected Behavior

My .vbs script is able to unzip a .zip file to a destination in a windows docker container.

### Configuration

*Output of `docker version`*

> Client:
>  Version:           20.10.9
>  API version:       1.41
>  Go version:        go1.16.8
>  Git commit:        c2ea9bc
>  Built:             Mon Oct  4 16:11:10 2021
>  OS/Arch:           windows/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.9
>   API version:      1.41 (minimum version 1.24)
>   Go version:       go1.16.8
>   Git commit:       79ea9d3
>   Built:            Mon Oct  4 16:06:39 2021
>   OS/Arch:          windows/amd64
>   Experimental:     false

### Additional context

I know I can work around this by writing a powershell script that uses `Expand-Archive` instead, for example. Or I've seen other articles suggesting using third-party tool like 7zip. However, in the scope of another project, the unzipping is accomplished by a .vbs script, so I would like to understand more about why this is happening before using a workaround.

**Comment by ntrappe-msft** [comment]
Hi, thanks for asking a question and for acknowledging a work around. Could you tell us what version of Visual Basic you're using? It may be possible that Shell.App may not be supported in Windows Server Core just because, when we reduced that image, we had to pick and choose what to keep or what to remove. This may be one of the features that was removed to reduce the size. Could you see if this works for you on a full Windows Server image?

**Comment by christopher-watanabe-snkeos** [comment]
Hi @ntrappe-msft, thanks for the response! 

The image I would like to use is mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019. It looks like the framework ships with Visual Basic 2019.

I've tried to run the VB script on the image mcr.microsoft.com/windows:ltsc2019 on this [feature branch](
https://github.com/christopher-watanabe-snkeos/dotnet-framework-docker-batch-file-issue/tree/feature/test-windows-image) and it runs no problem. While I could use this image, I'm hesitant primarily because of the size. I use my image in the scope of automated testing: building the docker image and running on a git runner. The docker image provides a more controlled test env without pre-installed git runner software. GitHub nicely caches other windows images (both [ltsc2022 ](https://github.com/actions/runner-images/blob/win22/20230903.2/images/win/Windows2022-Readme.md#cached-docker-images) and [2019](https://github.com/actions/runner-images/blob/win22/20230903.2/images/win/Windows2019-Readme.md#cached-docker-images)) so the build takes only seconds, but the full server image is not among the cached images.

So it seems I have a couple options: 
- My mentioned workaround. 
- Use the full server image and run my automated tests only when absolutely necessary to prevent the download times on the git runner.
- Request the removed feature be re-added to the server core image.

**Comment by ntrappe-msft** [comment]
Did you try to run your VB script on a Server Core 2022 container? I'm curious about whether it's just an issue with 2019. I'm also waiting for a response from another team to confirm whether VB scripts are fully supported in 2019 containers. Thanks for your patience!

**Comment by christopher-watanabe-snkeos** [comment]
@ntrappe-msft : I tried to run both on 2019 and 2022 images, but both failed at the same point in the VB script. In the meantime I'm using my mentioned workaround, but I'm happy to hear that there's some discussion about it! Thanks!

**Comment by fady-azmy-msft** [comment]
Thank you for highlighting this to us @christopher-watanabe-snkeos, I'm not sure what's causing the error you hit, however I did speak with the team about this. 

Since VBScript was announced to be [deprecated soon](https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features#deprecated-features) and there are available workarounds, we are de-prioritizing investigating this potential bug so we can focus on addressing issues that have no workarounds/are blockers to important scenarios.
