### ISSUE TITLE
MSMQ-Multicast cannot be enabled in servercore container

### ISSUE THREAD

**Issue by mdekoster** [microsoft/Windows-Containers#425]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**

Wnen trying to enable MSMQ-Multicast in a windows servercore (ltsc2019 and ltsc2022) container the following error is reported.

```
Enable-WindowsOptionalFeature : One or several parent features are disabled so current feature can not be enabled.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Multicast -Al ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

The features MSMQ, MSMQ-Services and MSMQ-Server can be enabled in the Windows servercore container, but the MSMQ-Multicast feature cannot be enabled.

```
PS C:\> Get-WindowsOptionalFeature -Online -FeatureName MSMQ* | select FeatureName, State

FeatureName           State
-----------           -----
MSMQ                Enabled
MSMQ-Services       Enabled
MSMQ-DCOMProxy     Disabled
MSMQ-Server         Enabled
MSMQ-ADIntegration Disabled
MSMQ-HTTP          Disabled
MSMQ-Multicast     Disabled
MSMQ-Triggers      Disabled
MSMQ-RoutingServer Disabled
```

**To Reproduce** 

1. Start docker container with powershell:

`docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 powershell`

2. Enable the MSMQ-MUlticast feature

`Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Multicast -All`

**Expected behavior**

The MSMQ-Multicast feature is enabled in the container.

**Configuration:**
 - Host Edition: 
 ```
 Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎30-‎8-‎2022
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0
 ```
- Base Image being used: Windows Server Core (ltsc2019 and ltsc2022)
 - Container engine: docker
 - Container Engine version:
```
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:39 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by ntrappe-msft** [comment]
Hi, thanks for bringing this Issue to our attention. Have you tried to enable MSMQ-Multicast on the full Windows Server image? To pare down Windows Server Core, we had to remove some of the less used features. It's possible that MSMQ-Multicast was included in that list and may no longer be accessible on Windows Server Core. I'll double check whether or not MSMQ-Multicast is fully removed or disabled (_if it's disabled, there's a chance we could re-enable it_). But, for now, can you try to repro this on full Server?

**Comment by mdekoster** [comment]
On the full server image the following Error is reported:

```
PS C:\> Enable-WindowsOptionalFeature -FeatureName MSMQ-Multicast -All -Online
Enable-WindowsOptionalFeature : The requested operation failed. A system reboot is required to roll back changes made.
At line:1 char:1
+ Enable-WindowsOptionalFeature -FeatureName MSMQ-Multicast -All -Onlin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
```

**Comment by fady-azmy-msft** [comment]
We're still looking into this, in the meantime what are you trying to achieve with MSMQ? @mdekoster

**Comment by ntrappe-msft** [comment]
Repro'd successfully.

In a Windows Server Core LTSC 2022 container, the following command fails.

```cmd
> Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Multicast -All

Enable-WindowsOptionalFeature : One or several parent features 
are disabled so current feature can not be enabled.
```

I did enable MSMQ, MSMQ-Services, and MSMQ-Server individually and they were successful. _(These features are all necessary for MSMQ-Multicast to be enabled and should be automatically enabled when we run `... MSMQ-Multicast -All`)_. 

I've collected some logs so we'll go through that and see what's going wrong.

**Comment by ntrappe-msft** [comment]
Internal ADO ticket (46857879).

**Comment by mdekoster** [comment]
> We're still looking into this, in the meantime what are you trying to achieve with MSMQ? @mdekoster

We have an existing application/service which communicates with other application instances on other machines using MSMQ multicast.

**Comment by ntrappe-msft** [comment]
Currently, MSMQ-Multicast will not work on Windows Server 2022 or Windows Server Core 2022 (I haven't checked 2019 yet). The MSMQ-Multicast package has two parent packages: **Microsoft-Windows-Server-Shell** and **Microsoft-Windows-MSMQ-Server**. It looks like MSMQ-Server is available for all but Server-Shell is not for Windows Server Core. We're determining whether this is intentional (that MSMQ-Multicast does not work in a container) or if there truly is a bug.

**Comment by ntrappe-msft** [comment]
**MSMQ-Multicast should not work in Windows Server Core by design.** However, it should work in full Windows Server so I'm looking into this now.

**Comment by ntrappe-msft** [comment]
Looks like full Server doesn't have the `Microsoft-Windows-Server-Shell` package according to the log files. I'm going to talk to the team that owns full Server to confirm this. However, as of right now, it also looks like **MSMQ-Mutlicast will not work on full Windows Server**.
