### ISSUE TITLE
On windows server, how do i uninstall?

### ISSUE THREAD

**Issue by beckerben** [microsoft/Windows-Containers#433]
I didn't see any mention in the documentation if we installed using the install-docker-ce.ps1 on windows server how to actually perform an uninstallation?  We wanted to move the installation from C:\ to D:\ an wasn't sure how to properly do the uninstall.

**Comment by ntrappe-msft** [comment]
Hi! Great question. @brasmith-ms might know more about this than I but I can take a stab at it.

1. Make sure you kill any containers that are running or push any images you want to save to Docker Hub.
```ruby
# Check if any containers are still running
docker ps
```
2. Stop the Docker service so you can remove it. Run the following an Administrator PowerShell window:
```ruby
Stop-Service -Name docker
```
3. Unregister dockerd also in that PowerShell window:
```ruby
& dockerd --unregister-service
```
4. Remove docker from your `ProgramData` folder. (This path might be different for you depending on your configuration but it's under `C:/` for me).
```ruby
Remove-Item -Path C:\ProgramData\docker -Recurse
```
5. Check that the Docker service no longer exists:
```ruby
$service = Get-Service -Name "docker" -ErrorAction SilentlyContinue
$service -eq $null
# if it prints out True then docker is not installed (yay)
# if it prints out False then a previous command failed
```

**Comment by beckerben** [comment]
@ntrappe-msft looks easy enough, thanks.  

It probably makes sense to get a section added to the formal docs for reference as well.

**Comment by ntrappe-msft** [comment]
Totally agree, we'll write up something. Just re-open this if anything doesn't work.

**Comment by SanielDous** [comment]
I previously installed Containerd together with nerdctl. I want to switch to Moby/Docker CE and thereby uninstall containerd/nerdctl. I ran the commands from above and switched docker with containerd. But in step 4 when trying to remove the program data I get a lot of access violations (although I ran it in an elevated PS).

For example:
    
    Remove-Item : Cannot remove item C:\ProgramData\containerd\root\io.containerd.snapshotter.v1.windows\snapshots\9\Files\Windows\WaaS: Access to the path 'WaaS' is denied.

**Comment by beckerben** [comment]
We just got around to trying this process that @ntrappe-msft mentioned and ran into permission errors doing the delete from an elevated shell.  We found that in order to delete the "docker" folder we had to take ownership of it and then were able to perform the delete.

**Comment by beckerben** [comment]
I spoke too soon, the command looked like it was working but it ended up having issues removing the "C:\ProgramData\docker\windowsfilter".  We ended up having to use this: https://github.com/moby/docker-ci-zap

**Comment by ntrappe-msft** [comment]
Hmm I'll look into what's happening. Thanks for the heads up.

**Comment by ntrappe-msft** [comment]
Ah yep it's probably not a good idea to use the docker-ci-zap tool unless you never want to install docker again. It doesn't let you automatically delete the `docker/windowsfilter` folder because it's actually the storage driver Docker uses to save images and container metadata. I'll work on an uninstall script that can safely remove the driver and everything else.

**Comment by beckerben** [comment]
I see, we had no problems using the tool and then re-installing.  We were hoping to install to a different drive altogether but not sure that is possible from what we have seen so we ended up re-installing everything via the script and moved our data directory to another drive.

**Comment by flvinny** [comment]
> Hi! Great question. @brasmith-ms might know more about this than I but I can take a stab at it.
> 
> 1. Make sure you kill any containers that are running or push any images you want to save to Docker Hub.
> 
> ```ruby
> # Check if any containers are still running
> docker ps
> ```
> 
> 2. Stop the Docker service so you can remove it. Run the following an Administrator PowerShell window:
> 
> ```ruby
> Stop-Service -Name docker
> ```
> 
> 3. Unregister dockerd also in that PowerShell window:
> 
> ```ruby
> & dockerd --unregister-service
> ```
> 
> 4. Remove docker from your `ProgramData` folder. (This path might be different for you depending on your configuration but it's under `C:/` for me).
> 
> ```ruby
> Remove-Item -Path C:\ProgramData\docker -Recurse
> ```
> 
> 5. Check that the Docker service no longer exists:
> 
> ```ruby
> $service = Get-Service -Name "docker" -ErrorAction SilentlyContinue
> $service -eq $null
> # if it prints out True then docker is not installed (yay)
> # if it prints out False then a previous command failed
> ```

Thanks, these instructions worked just fine for uninstalling the Docker server in our case.
But, how would one go about uninstalling the the Docker _client_ after this? We're planning on installing Docker to a different machine instead, and we have no use on having the client still sitting there

**Comment by ntrappe-msft** [comment]
@CebolaBros64 Are you trying to remove the Docker CLI? Usually the Docker Client consists of that.

**Comment by flvinny** [comment]
@ntrappe-msft Yes, that's correct

**Comment by ntrappe-msft** [comment]
Did you try removing Docker Desktop? That's usually what adds/removes the Docker CLI.

**Comment by flvinny** [comment]
Docker Desktop isn't installed, as the machine is running Windows Server 2019 and isn't compatible. I was under the impression the `install-docker-ce.ps1` script was what added the CLI, is that not the case?

**Comment by ntrappe-msft** [comment]
Hi, you're right, the `install-docker-ce.ps1` script does install it. I just wanted to make sure that's what you were working with. We're going to release an official uninstall script soon but here are some steps you can take in the meantime:

1. Check which Docker files you have remaining.
```powershell
where.exe docker
```
2. You should see these two locations:
```powershell
C:\Program Files\Docker\Docker\resources\bin\docker
C:\Program Files\Docker\Docker\resources\bin\docker.exe
```
3. Remove those files and/or any others the command noted.
```powershell
Remove-Item -Path "C:\Program Files\Docker\Docker\resources\bin\docker" -ErrorAction SilentlyContinue
Remove-Item -Path "C:\Program Files\Docker\Docker\resources\bin\docker.exe" -ErrorAction SilentlyContinue
```
4. Check that the Docker CLI is gone. You should get an **error** like "The term 'docker' is not recognized".
```powershell
docker
```

**Comment by flvinny** [comment]
Thank you, that did the job :)
