### ISSUE TITLE
Are containers still supported on Windows Server 2016?

### ISSUE THREAD

**Issue by Trigve** [microsoft/Windows-Containers#438]
I'm trying to use containers on Windows server 2016 (DE) on VPS. I'm using docker 20.10.9 (the latest support on windows server 2016). When I try to pull windows server image, I've got the error `no matching manifest for windows/amd64 10.0.14393 in the manifest list entries`. As noted in the doc, 2016 host must match exactly the container version. But I couldn't find any image for windows server 2016. From what I've read, the 2016 images were removed some time ago. So how can I then run containers on windows server 2016 then? Is there some archive of older images?

**Comment by akarshm** [comment]
@Trigve, the container image lifecycle is documented [here](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle). We still publish [WS2016 Server Core image](https://mcr.microsoft.com/en-us/product/windows/servercore/about) (mcr.microsoft.com/windows/servercore:ltsc2016) which is in service until Jan 11, 2027. Please feel free to ask us if you need any further information.

**Comment by Trigve** [comment]
Thanks for the reply.
I was trying "windows server" (standard) image, which after reading the links you provided is supported only for 2022. But now as I'm thinking I think windows core should suffice.
