### ISSUE TITLE
GMSA with Windows Containers doesnt work with ContainerD

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#44]
When using the ContainerD runtime (Feature State: Kubernetes v1.19 [beta]) accessing restricted network shares via the GMSA domain identity fails. The container will receive the identity of and calls from `nltest.exe /query` will work. It is recommended to use the Docker EE runtime if access to network shares is required.

**Comment by immuzz** [comment]
We are working to fix this issue. Currently this affects Windows Server 2019, 1903, 1909 and 2004. We are planning to fix it in 2004 first and then backport to 2019, 1903 and 1909. Current rough ETA for backporting is 2-3 months

**Comment by immuzz** [comment]
This has been resolved and will be released for Windows Server 2004 in 11C Windows Patch

**Comment by vitaliy-leschenko** [comment]
Hi @immuzz, as I understand from your comments in 11C Windows Patch fix will be available only for WS2004. So we need to wait 2-3 months for patch for WS2019. Is it correct?

**Comment by jayunit100** [comment]
also wondering the same thing.... when will this be available in 2019?

**Comment by unacceptable** [comment]
@vitaliy-leschenko @jayunit100 I reckon when saying Windows Server 2004 they are referring to the Windows Server SAC releases for Server 2019.  Not 100% sure though since I am not a Windows guy.

**Comment by marosset** [comment]
I spoke with @immuzz and confirmed this will not be available for Windows Server 2019 until Feb 2021.

**Comment by immuzz** [comment]
Re-opening the issue as it will be available in Feb 2021 for Windows 2019. Will close it then

**Comment by immuzz** [comment]
Just to be clear. This fix is available today on Windows Server 2004 (SAC release)

**Comment by ericsmalling** [comment]
Just curious, @immuzz, is Win 2019 still on track for Feb 2021 release?

**Comment by immuzz** [comment]
Closing this issue as this should be part of Feb Patch Tuesday. Please let me know if someone is still running into issues and I will try to investigate.

**Comment by immuzz** [comment]
Befor re-opening i am waiting for gMSA team to confirm its the same issue

**Comment by marosset** [comment]
> Closing this issue as this should be part of Feb Patch Tuesday. Please let me know if someone is still running into issues and I will try to investigate.

@immuzz were these fixes in 2B or 2C?

**Comment by jsturtevant** [comment]
should be in 2c or 3b

**Comment by dcantah** [comment]
The fix is in, you just need to enable the registry key it's gated behind: `reg add "HKLM\SYSTEM\CurrentControlSet\Services\hns\State" /v EnableCompartmentNamespace /t REG_DWORD /d 1`. We'll work to get this documented publicly

**Comment by perithompson** [comment]
Great work to everyone involved!
