### ISSUE TITLE
Not able to download windows container images

### ISSUE THREAD

**Issue by chiragce17** [microsoft/Windows-Containers#447]
**Issue:**

PS C:\practicelab\DokcerFiles> docker pull mcr.microsoft.com/windows/nanoserver
Using default tag: latest
Error response from daemon: manifest for mcr.microsoft.com/windows/nanoserver:latest not found: manifest unknown: manifest tagged by "latest" is not found

I have tried to apply multiple tags and for other windows images I get the same error message.

**Comment by vrapolinario** [comment]
Please note Windows container images don't have a latest option. You should input the specific tag you'd like to pull, for example: mcr.microsoft.com/windows/nanoserver:ltsc2022. You can find all available tags for Windows images here: https://mcr.microsoft.com/en-us/product/windows/server/about.

**Comment by chiragce17** [comment]
> Please note Windows container images don't have a latest option. You should input the specific tag you'd like to pull, for example: mcr.microsoft.com/windows/nanoserver:ltsc2022. You can find all available tags for Windows images here: https://mcr.microsoft.com/en-us/product/windows/server/about.

Thank you. But it seems none of the tags are suitable for Windows 10 client OS version.

**Comment by vrapolinario** [comment]
You should be able to pull ltsc2019 on Windows 10. Please note these are supported on Windows 10 with Hyper-V isolation: https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10 (This is the default on Windows client anyway)
