### ISSUE TITLE
Docker in Docker with Windows Containers

### ISSUE THREAD

**Issue by t4eman** [microsoft/Windows-Containers#451]
Is it possible to run a Windows Container in a Windows Container? I’m trying to do a Docker in Docker configuration. But when I try `Enable-WindowsOptionalFeature -Online -FeatureName Containers` while inside the container, I get the error cannot find source.

**Comment by StefanScherer** [comment]
No, this doesn't work. I've tried that long time ago, but I don't think it has changed.

What you could use instead is bind mount the named pipe into a Windows Container.
On a Windows Server 2022 with Windows Docker engine running you can run a container that uses the Docker engine on the Windows host:

```
docker run -v //./pipe/docker_engine://./pipe/docker_engine docker:24.0.7-windowsservercore-ltsc2022 docker version
```

**Comment by t4eman** [comment]
Could you do something like 
`nerdctl run -v //./pipe/containerd_containerd://./pipe/docker_engine docker:24.0.7-windowsservercore-ltsc2022 docker version`?

**Comment by t4eman** [comment]
```shell
PS C:\Program Files\docker> .\dockerd.exe
time="2023-12-30T14:02:37.629123500-08:00" level=info msg="Starting up"
time="2023-12-30T14:02:37.641269100-08:00" level=info msg="Windows default isolation mode: process"
time="2023-12-30T14:02:37.686873100-08:00" level=info msg="[graphdriver] trying configured driver: windowsfilter"
time="2023-12-30T14:02:37.703061300-08:00" level=info msg="Loading containers: start."
time="2023-12-30T14:02:37.706999700-08:00" level=info msg="Restoring existing overlay networks from HNS into docker"
failed to start daemon: Error initializing network controller: failed during hnsCallRawResponse: hnsCall failed in Win32: Class not registered (0x80040154)
``` 
As far as I can get it. I manually added all the files and such. But I assume that I would have to extract the class it’s looking for and somehow register it. Or the error is a generic error.
