### ISSUE TITLE
pull image from PS command on Docker Desktop Window 10Ent

### ISSUE THREAD

**Issue by quangnx** [microsoft/Windows-Containers#452]
I try to pull image from PS command:
docker pull mcr.microsoft.com/windows/servercore:ltsc2022
Error response from daemon: no match for platform in manifest: not found

docker pull mcr.microsoft.com/windows/servercore:1909-amd64
1909-amd64: Pulling from windows/servercore
9038b92872bc: Download complete
b7676dab9a05: Download complete
failed to extract layer sha256:8a9ba5eb77c62b5f5d4990c8994147489654ef89f61a96fac2e2befd229d78e3: link /var/lib/containerd-stargz-grpc/snapshotter/snapshots/1539/fs/Files/Program Files/Common Files/Microsoft Shared/Ink/en-US/micaut.dll.mui /var/lib/containerd-stargz-grpc/snapshotter/snapshots/1539/fs/Files/Program Files (x86)/Common Files/Microsoft Shared/ink/en-US/micaut.dll.mui: no such file or directory: unknown

Can I pull from somewhere for image?

**Comment by ntrappe-msft** [comment]
Could you provide us with some more details? Usually when you hit a `no match for manifest` error there's a mismatch between the container image OS and the host OS. Please paste the output of `docker info`. Thanks!

**Comment by ankitgupta1988** [comment]
I am also facing the same issue.

PS C:\Work\Deploy\Docker> docker pull mcr.microsoft.com/windows/servercore:ltsc2019
ltsc2019: Pulling from windows/servercore
cb524f6f2215: Already exists
1581446d2913: Extracting [==================================================>]  409.3MB/409.3MB
failed to register layer: re-exec error: exit status 1: output: failed to find link target for 'Files\Program Files (x86)\common files\Microsoft Shared\ink\en-US\micaut.dll.mui' -> 'Files\Program Files\common files\Microsoft Shared\Ink\en-US\micaut.dll.mui'

Here is the docker info : 

Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19045 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Microsoft Windows Version 22H2 (OS Build 19045.3803)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 19.74GiB
 Name: IN-PF2ANR8H
 ID: 5972ee8b-70fd-40c1-8ce2-096023fec075
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

I am already on Switched to Windows container and also disabled WSL2 in setting as suggested by lot of people

**Comment by quangnx** [comment]
> Could you provide us with some more details? Usually when you hit a `no match for manifest` error there's a mismatch between the container image OS and the host OS. Please paste the output of `docker info`. Thanks!

Hi ntrappe,

The last detail are out of scope. I might try to send log include under Docker folder: C:\Users\Administrator\AppData\Local\Docker

My Environment ~ about: Window 10 enterprise/ install Docker Desktop latest at https://docs.docker.com/desktop/install/windows-install/
[settings.json](https://github.com/microsoft/Windows-Containers/files/13884527/settings.json)
[
[log.zip](https://github.com/microsoft/Windows-Containers/files/13884575/log.zip)
](url)

I saw some inside Environment that cause fewer expectation for a solution (~ 1 year have no up to date)

May difficult business logical.

Regards,

**Comment by ntrappe-msft** [comment]
@ankitgupta1988 Could you try removing the image and then trying to pull?

```powershell
$> docker rmi mcr.microsoft.com/windows/servercore:ltsc2019
$> docker pull mcr.microsoft.com/windows/servercore:ltsc2019
```

**Comment by quangnx** [comment]
I just quickly clean Docker and re-try with no success..
>> It might the Environment not clean. So I will re-create Window to try again.

thank much for a test case

**Comment by quangnx** [comment]
I tried with out success at all.
May be I am not official one in the business thread for logging-in

Regards,

**Comment by ankitgupta1988** [comment]
@ntrappe-msft  Do you think this is related to an operating system or anything with Antivirus/Zscaler Security ??

**Comment by ankitgupta1988** [comment]
![image](https://github.com/microsoft/Windows-Containers/assets/71297633/7250c210-783a-4aef-8065-ec5b6234fb1f)

I tried as you suggested but no success.

**Comment by quangnx** [comment]
> ![image](https://private-user-images.githubusercontent.com/71297633/299382639-7250c210-783a-4aef-8065-ec5b6234fb1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTkzMjUsIm5iZiI6MTcwNjE1OTAyNSwicGF0aCI6Ii83MTI5NzYzMy8yOTkzODI2MzktNzI1MGMyMTAtNzgzYS00YWVmLTgwNjUtZWM1YjYyMzRmYjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA1MDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZTc4MDczMjM0YzgyMzE3ZTA1ZTQ4YTkxMmY3MWEzNjZmOTgwZGExNTA1ZDdkMTdlZTkwYjhmNGI3NDhiMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndkmswyFC7eksaMfcoW8ukt1mA2ccHZLb4DAP6E_L50)
> 
> I tried as you suggested but no success.

Thank much for your info. I just re-try one more time for 2019

**Comment by ntrappe-msft** [comment]
@quangnx Are you using the [Stargz custom snapshotter](https://github.com/containerd/stargz-snapshotter)? And what's your container runtime?

**Comment by ntrappe-msft** [comment]
Also, Windows Server Core 2022 isn't compatible with Windows 10. You'd need to upgrade to Windows Server 2022 or Windows 11 to pull and run Server Core 2022. The error `Error response from daemon: no match for platform in manifest: not found` indicates that there was no match for the container OS type and the host OS type. This means that they aren't compatible.

You may want to try Windows Server Core 2019 instead as it should work fine with Windows 10.

```powershell
docker pull mcr.microsoft.com/windows/servercore:ltsc2019
```

**Comment by fady-azmy-msft** [comment]
For more information on the compatibility, you read this page on Azure docs: https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10

**Comment by ntrappe-msft** [comment]
@quangnx The issue you're encountering is likely a result of using the Stargz snapshotter. It's not compatible with Windows Containers and that's why it's throwing that error. I'm closing this Issue for now but reopen it if you still have problems. Thanks.
