### ISSUE TITLE
Plans for Windows 10/11 Containers in the Future

### ISSUE THREAD

**Issue by sikhness** [microsoft/Windows-Containers#454]
I understand that there are Windows Server based containers readily available and updated frequently that we can leverage, however there were also client based Windows 10 containers being offered that I found very useful for applications that require to be run on a Client OS rather than a Server OS (applications that seem to check for it explicitly).

Currently, I'm seeing only the LTSC2019 Windows containers being updated and no major updates have been released there since 20H2.  Are there any plans to continue development on full client Windows containers as well and adding features there for those who require a container that is the Client Windows OS?  Would love to be able to get some feature additions there as well such as process isolation and GPU capabilities and other devices passthrough.

**Comment by kilasuit** [comment]
This would be very useful for spinning up development environments which typically have required use of VM's to achieve the same result, with a much smaller footprint so would be useful for devices where there isn't a huge amount of storage available (thinking Surface Go type devices) and would also help further use of devcontainers in projects.

**Comment by fady-azmy-msft** [comment]
I'm not sure if this directly answers your question but it sounds like you're asking how to leverage server features on client?

The client container images are based on Windows Server, and we're not planning on building any client-specific images. If you want to run a newer container on client you'll generally need to use [hyper-v](https://learn.microsoft.com/en-us/windows-server/get-started/application-compatibility-windows-server-2022). 

We are looking to supporting new clients run older container images, as part of the portability work we're doing, with process isolation but don't have any timelines to communicate other than point to the next version of Windows Server. Specifically re: the GPU capabilities and device passthroughs, that relies on having process isolation.

@kilasuit , can you expand on the use cases you're referring to for expanding local dev scenarios?

**Comment by kilasuit** [comment]
@fady-azmy-msft  Sorry for the delayed reply, as have had some personal issues to deal with relating to my health and housing, so they took priority,
 
For example I can see huge benefit in adding a devcontainer configuration to projects that 

- Uses Windows Client OS'es
  - Optionally could be Domain Joined as to enable GPO's to be applied
- Installs Visual Studio Code or Visual Studio or other IDE tooling and other necessary tools which aren't meant to be installed on Server OS'es (like Microsoft Office for example)
- Enables RDP connection to the container
  - optionally this may even be RDP over SSH similar to [this blog post](https://www.saotn.org/tunnel-rdp-through-ssh/) 
- Is then published to an internal (or public) container repository feed so can be used for continued development of that project in an isolated environment

This is what many orgs do with VM's today and make use of Hyper-V on their Win10/11 Pro/Enterprise systems for local dev scenarios (like when off network or on client networks), by enabling the same experience with Win 10/11 containers this would help in those scenarios too whilst being able to teach about both containers and VM's and their uses and differences and would be good in future to have feature compatibility between VM's & Containers

Overall I can see this being incredibly beneficial for those that are training others in software development

**Comment by kilasuit** [comment]
For anyone coming to this apparently there is already (albeit not supported) way of utilising Windows Client OSes as a container image) [via this repo](https://github.com/dockur/windows)
