### ISSUE TITLE
Issues Installing Oracle Instant Client on Windows Container: Network Sharing Problem

### ISSUE THREAD

**Issue by subinbab** [microsoft/Windows-Containers#455]
Encountering challenges while attempting to install Oracle Instant Client on a Windows container has led to the discovery of a network sharing issue within the Windows container environment. Here are the key findings:

lanmanserver Service Status:

Not running, impacting network sharing capabilities.
Dependency Issues:

srvnet, a dependency of lanmanserver, is also not running.
msquisc (kernel-level driver), a dependency of srvnet, is running.
Error Message (PRKN-1040):

Failed to remove directory "\817484d0b0a7\C$\Users\ContainerAdministrator\AppData\Local\Temp\oraremservicev2" on node "817484d0b0a7".
The network location cannot be reached.
Error opening the pipe, os error = 1231.
Summary of Oracle Installation Log Error:

The error suggests a network location unreachability problem during directory removal.
Next Steps:

Ensure lanmanserver service and its dependencies are started.
Address network sharing configuration within the Windows container.
Investigate and resolve the issue preventing the removal of the specified directory during Oracle Instant Client installation.
Conclusion:

Resolving these network sharing issues is crucial for a successful Oracle Instant Client installation on Windows containers. By addressing service dependencies and network configuration, the installation process can proceed smoothly.

**Comment by fady-azmy-msft** [comment]
Hey @subinbab , I'm not familiar with the Oracle Instant Client so have some questions. 

What are you trying to accomplish with windows containers in the end? And would [host process containers](https://learn.microsoft.com/en-us/azure/aks/use-windows-hpc) fit this case?

Also what version of Windows Server container are you using?

**Comment by fady-azmy-msft** [comment]
Closing issue because it's gone stale.
