### ISSUE TITLE
MSIX installation support

### ISSUE THREAD

**Issue by JensNordenbro** [microsoft/Windows-Containers#462]
It expected to be able to install command line tools such as WinGet on Windows Containers. 

Today WinGet is packaged using misx and this technology although possible to install using command line seems to need some kind of user session mode not available in Windows Containers. Please make sure this work so that we can se WinGet to acquire tools/apps for our needs.

**Comment by ntrappe-msft** [comment]
Have you tried installing WinGet in Windows Server Core LTSC 2022 or Windows Server 2022? Could you explain your installation process?

**Comment by mthalman** [comment]
WinGet isn't currently supported on Windows Server (container or otherwise): https://github.com/microsoft/winget-cli/discussions/2361

**Comment by JensNordenbro** [comment]
ahh...and all Windows containers are windows **server** containers.
That explains it! 
Is it considered for support anytime soon?

**Comment by ntrappe-msft** [comment]
This feature request is under consideration by the product team. Thanks for highlighting your interest!
