### ISSUE TITLE
[MicrosoftDocs] gMSA Documentation

### ISSUE THREAD

**Issue by ntrappe-msft** [microsoft/Windows-Containers#464]
**What is your question?**
From the MicrosoftDocs/Virtualization-Documentation repo, we've seen a number of requests to improve the documentation or correct mistakes. These include:
- [gMSA and DNS Server settings](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1903)
- [gMSA on Kubernetes has gone GA](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1564)
- [host/PRINCIPAL to a gMSA MicrosoftDocs/Virtualization-Documentation#1791](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1791)
- [So you effectively replaced a Process ID with a Process ID plus gMSAs? MicrosoftDocs/Virtualization-Documentation-Private#1144](https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1144)
- [Update gMSA state MicrosoftDocs/Virtualization-Documentation#1477](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1477)
- [Need to "SetSPN" or servicePrincipalName on gMSA account. MicrosoftDocs/Virtualization-Documentation#1341](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1341)
- [Using secondary gMSAs MicrosoftDocs/Virtualization-Documentation-Private#1355](https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1355)
- [Typo in "Check the container", step 4 MicrosoftDocs/Virtualization-Documentation#1414](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1414#issue-629915344)
- [Elaborate more on Additional credential spec configuration for non-domain-joined container host use case MicrosoftDocs/Virtualization-Documentation#1680](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1680)

**Comment by vrapolinario** [comment]
Tracking this internally as Advocacy work on Docs.

**Comment by deedubb** [comment]
I agree these documentation items need to be improved

**Comment by avin3sh** [comment]
Can we please also introduce some documentation around `User Manager` as part of this. It feels like it is some kind of proxy for LSA operations. It also has some unexpected effects that users should be aware of - such as when trying negotiate between processes within same container, ~after having DisableLoopbackCheck disabled~ <sup>(edit: does not look like setting `DisableLoopbackCheck` to `1` is required even if you have two containers in same Pod, sharing the network namespaces)</sup>, the ticket is actually issued by `User Manager` and not the actual KDC the container/gMSA may be related to.

**Comment by vrapolinario** [comment]
I have taken action on most items above. Items still open that I will be following up on:

- https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1791
- https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1680
- https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1355

**Comment by ntrappe-msft** [comment]
@vrapolinario Amazing, thank you!

**Comment by vrapolinario** [comment]
I have updated two of the items, with just this one remaining: 
- https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1355
I'm currently investigating this internally to provide clarity on the issue raised by the customer.

**Comment by vrapolinario** [comment]
Apologies for not updating this thread. I'm working on updating some documentation and confirming some gMSA scenarios internally, no news for now.
