### ISSUE TITLE
Windows containers shutdown not working properly on docker (no SIGTERM?)

### ISSUE THREAD

**Issue by david-garcia-garcia** [microsoft/Windows-Containers#466]
**Describe the bug**

After thorough search and test, I don't seem to be able to figure out the proper way to do a graceful shutdown of a windows container using docker.

I have opened a dupe issue in the moby project:

https://github.com/moby/moby/issues/47416

**To Reproduce** 

https://github.com/david-garcia-garcia/dockernosigterm

Instructions and code to reproduce in the repository.

**Expected behavior**

There is a way to gracefully shutdown a container in docker, so that teardown logic can be implemented.

**Configuration:**

See https://github.com/moby/moby/issues/47416 for details on docker version and environment.

**Comment by tfenster** [comment]
This https://github.com/moby/moby/issues/25982 gives you an idea of where we are with graceful shutdowns on Windows containers. The very short version: It doesn't work

**Comment by david-garcia-garcia** [comment]
@tfenster thanks for the link to that issue, that was it.

**Comment by david-garcia-garcia** [comment]
"Fixed" in https://github.com/moby/moby/issues/25982, still, shutdown for windows containers is confusing and probably undocumented.

**Comment by ntrappe-msft** [comment]
Thanks for bringing this Issue up. I'll talk to the team about how we can provide sufficient documentation.
