### ISSUE TITLE
Registrykey "ProductName" returns "Windows Server 2016" from nano

### ISSUE THREAD

**Issue by Herr-Sepp** [microsoft/Windows-Containers#468]
**Describe the bug**

Registry-Key 
_"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName"_
has never updated inside Nano-Images.

It works correct for Server and Server-Core Images but not for Nano-Images

**To Reproduce** 

**nanoserver-ltsc2022**
docker run --rm --entrypoint pwsh mcr.microsoft.com/powershell:nanoserver-ltsc2022 "-Command" "Get-ItemProperty -Path \`"Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\\`" -Name ProductName"

\>\> ProductName: Windows Server 2016 Datacenter

Test with **windowsservercore-ltsc2022**
docker run --rm --entrypoint pwsh mcr.microsoft.com/powershell:windowsservercore-ltsc2022 "-Command" "Get-ItemProperty -Path \`"Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\\`" -Name ProductName"

\>\> ProductName: Windows Server 2022 Datacenter

**Expected behavior**
ProductName  : Windows Server 2022 Datacenter

**Configuration:**
 - Edition: Windows Server 2022
- Base Image being used: Nano
 - Container engine: Docker
 - Container Engine version 25.0.3

**Comment by ntrappe-msft** [comment]
Hi, thanks for bringing up this Issue. We plan to fix this in the upcoming release (Windows Server 2025).
