### ISSUE TITLE
Windows Admin Center v2 - Container Extension

### ISSUE THREAD

**Issue by ThePieMonster** [microsoft/Windows-Containers#477]
**What is your question?**

I just installed the v2 version of WAC. 

In the original I would see a list of extensions, one of which is called the container extension. 

![image](https://github.com/microsoft/Windows-Containers/assets/11359134/73d2f3ce-2e78-48a4-8caf-6e097e213118)

https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-admin-center

<br/>
I see here you can install extensions from custom feeds. Is there a feed for the container extension? 
<br/>

https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/using-extensions#installing-an-extension

**Comment by ritikaguptams** [comment]
Hi @ThePieMonster from my investigation internally I found out that we do not support WAC extension for containers. I have a PR out to update the documentation to reflect that as well. https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1985

Can I ask why are you trying to use WACs container extension?

**Comment by ThePieMonster** [comment]
Hi @ritikaguptams and thanks for the reply. 

I was looking for a Windows solution of Mini Kube / MicroK8S. 
Since WAC has K8S support (or it seems like it did), I figured I could run containers in some fashion.

**Comment by ntrappe-msft** [comment]
@ThePieMonster I'm going to close this Issue for now. If you have any other comments or concerns, feel free to re-open it.
