### ISSUE TITLE
Domain Join as computer account

### ISSUE THREAD

**Issue by agowa** [microsoft/Windows-Containers#48]
Allow containers to be domain joined even if the host is not or even joined to a different domain.
Containers are meant to be a stripped down userland that contains everything the application needs to run without interacting with "the world outside the container".
Therefore the current approach of integrating containers into a domain by using service accounts is not great.

If I'm maintaining e.g. a web app that has ldap auth, the container should be able to perform this without requiring anything from the host, so that the container can be moved to another host without needing preparation.
Also I consider the secret that is used to connect to the AD "state" of the container and therefore the container should be able to store it on a volume itself controls. There is just no need for the host to treat these kind of information special.

Also as a service provider I want to be able to have the hosts within my activedirectoy, so that my admins and my automation can log into it, but also to offer the applications to customers. Now if the application is an domain integrated one it would (currently) require the host to be joint to the customer domain and an gMSA to be configured. I'd like it to be split. The container should be able to be joined to the customer domain (appear with a normal computer account) and be treated indistinguishable from normal computers but with stripped down services and functionality.
Such a setup would allow to make a service cut between providing the application and managing the host server. The service provider could than have the application running within a k8s cluster and providing automated fault tolerance and uptime monitoring while requiring no change to the containerized application (even applications not compatible with gMSA will work).

**Comment by vrapolinario** [comment]
This issue is being evaluated as we plan for updates on gMSA. Given the nature of the Windows containers composition, we don't plan to provide support for domain-join. We do however want to solve for this: Allow containers to be domain joined even if the host is not. 

Assigning the appropriate people and providing the right tags.

**Comment by immuzz** [comment]
@mapalko Can you comment here on the plans for gMSA and if this would be accommodated?

**Comment by vrapolinario** [comment]
We recently released a blog post with some new information on gMSA updates. Please check: https://techcommunity.microsoft.com/t5/containers/what-s-new-for-windows-containers-on-windows-server-2022/ba-p/2167036

As part of the update, we will support gMSA on non-domain joined container hosts. I believe this satisfies the requirements from this issue. We'll close the issue for now.

**Comment by ohault** [comment]
There is a big confusion here. To bring a real answer to this question, the current single-tenant LSASS architecture should be reconsidered completely. As long as, a real kernel implementation of namespaces or sub-env will not be designed, all answers will be pseudo solutions. ReactOS could be a good starting point to illustrate how to implement it.
