### ISSUE TITLE
Push for stateless software design

### ISSUE THREAD

**Issue by agowa** [microsoft/Windows-Containers#49]
Currently stateless software is more the exception than the norm within the windows ecosystem. For windows containers this is quite a challenge to overcome, as containers are not designed for stateful software. They are basically a tool to package an application without it's data. Therefore by design the application needs to be stateless and being able to resume from just it's database/files. For an upgrade it needs to be able to work with the files of the previous version, as the old version is just terminated and the application in the newer version is pointed towards the old files and started.
If one tries this with most windows software currently it just fails to start.
Therefore more in terms of educating developers and shifting best practices towards stateless software design within the windows ecosystem needs to be done. Compared with linux where every application works (or can be made working using a shart startup script), windows has still to catch up.
As an example, a container with ubuntu can run a whole desktop environment, one is running xrdp and another a custom web application that allows users to spawn there container/desktop environment and finally another one is running guacamole for html5 based rdp. Now the customer has a full vdi infrastructure within 4 containers (working on e.g. 2gb of ram and 2 cpu cores on any cpu architecture) and is able to login either via html5 or native rdp. Where as Windows requires a hypervisor and much much much more resources in general. In the linux example the root filesystem within the container can be mounted read only with the actual /home of the user being persistent. Now if the base container updates everything still continues to work for the user. Where as in the windows world applications start to bail out because they *expect* being able to do the resource/configuration version update within the installer/updater and not upon startup.

Therefore I'd like to see the following design goals/principals to be pushed more by microsoft:
- Push the PackageManager WinGet more
- Push steless software design concepts more. Most developers on windows don't know about steless design it seams.
- This should be more popular among windows developers https://12factor.net
- Get rid of the pet design within the windows ecosystem. And drive towards much more cattles based workloads (And finally drop the last pets).

**Comment by vrapolinario** [comment]
Thanks for the inputs @agowa338. Most of the notes you made are not technical implementations on the platform, but design patterns that developers should be following. We have a bunch of documentation and developers tools to support that - although we can always improve on these.
From the above, the actionable item is the package Manager. This is something we're currently looking into but nothing to share at this stage as we're in early stages of investigation.
We'll keep this issue open for now and update once we have a more concrete plan of action.
Thanks for the inputs!

**Comment by vrapolinario** [comment]
Per my previous comment, we're looking into a solution such as common package manager for Windows Containers. However, we don't have a timeline at this moment.
I'll be closing this, but please rest assured that we're looking into this issue.
