### ISSUE TITLE
The referenced assembly could not be found. Error: 0x80073701

### ISSUE THREAD

**Issue by philipt99** [microsoft/Windows-Containers#495]
When running the script, I got an error. It went through Querying the status and Enabling feature but then I got the error. I ran it again in ISE to keep the errors up. Any thoughts on this?
![2024-05-16 13_40_15-Window](https://github.com/microsoft/Windows-Containers/assets/8651318/91e690c2-33a8-4a39-ac46-7db274a85268)

**Comment by ntrappe-msft** [comment]
@philipt99 Hi, what OS version are you using? And are you running this script in an elevated PowerShell window?

**Comment by philipt99** [comment]
@ntrappe-msft @ritikaguptams 
Sorry for not being more specific. This is on Windows Server 2019 Standard 1809 running as Administrator

**Comment by ntrappe-msft** [comment]
Could you check if you have the `Add-WindowsFeature` cmdlet installed? Just run the following and you should see that ServerManager is present (it owns `Add-WindowsFeature`).

```powershell
Get-Module -ListAvailable -Name ServerManager
```

**Comment by philipt99** [comment]
@ntrappe-msft 

Here is the output I got from the command
<img width="699" alt="Greenshot 2024-05-16 18 38 27" src="https://github.com/microsoft/Windows-Containers/assets/8651318/8e1f4443-9f87-478c-b47e-6489045cfff8">

Here is the full list:
<img width="655" alt="Commands 2" src="https://github.com/microsoft/Windows-Containers/assets/8651318/c1d97426-0807-4523-855a-c8bd3af8ede0">

**Comment by ntrappe-msft** [comment]
@philipt99 Hi, thanks for showing the output. I was hoping it was just the case that `Add-WindowsFeature` wasn't installed properly or available. Since that's not it, there may be a permissions error with your script trying to install something the system isn't allowing. I'm attending [Build](https://build.microsoft.com/) this week so I won't be able to investigate until next week. Thanks for your patience.

**Comment by philipt99** [comment]
I went ahead and upgraded to Windows Server 2022 and got it running under that.

**Comment by ntrappe-msft** [comment]
@philipt99 I'm glad it's working with Windows Server 2022. 2019 seems to have significant differences between the commands you can run or information you can query. I'll see if we plan to add 2019 support to the script. I'll close this for now but link it with any PRs we submit for 2019.
