### ISSUE TITLE
RUN --mount support in Windows BuildKit

### ISSUE THREAD

**Issue by dev-adi-github-nuitka** [microsoft/Windows-Containers#498]
The following comment written in the issue for adding Windows BuildKit support indicated that in the future, we might be able to expect support for caching `RUN` steps via the `--mount` option. However, I am still unable to use the `--mount` option for `RUN` commands in Windows. Is support for this planned?

---
> A very quick poke around suggests this failure is coming from hcsshim, which at that point does not appear to be ready to accept a windows-layer mount to a mount-point in the container

That is correct, currently Windows only supports mounting physical/virtual devices and named pipes/host folders via VSMB.  The default mount type on Linux when none is explicitly specified is `bind`. On Windows it's `windows-layer`. While bind mounts on Linux are common place and can be used in any number, on Windows, `windows-layer` have only ever been used as root filesystem mounts.

It may suffice to allow setting the mount type in `llb` state. But I have not looked too much into it. Will have a look soon. I suspect we'll hit this issue when enabling tests as well.

> For me, the next step (with no particular timeframe) was to run-up the BuildKit integration tests and see what works and what doesn't.

That is already being worked on by @profnandaa (see https://github.com/moby/buildkit/pull/4432) and there should be a number of PRs incoming that will at least hook up the test suite to the CI and lay the ground for enabling tests (some will already be enabled, some should run but require support - images, windows specific testing Dockerfiles, etc).

_Originally posted by @gabriel-samfira in https://github.com/microsoft/Windows-Containers/issues/34#issuecomment-1845181566_

**Comment by profnandaa** [comment]
Cross-linking https://github.com/moby/buildkit/issues/4837

**Comment by profnandaa** [comment]
Still on the backlog, will update when we have something working.

**Comment by profnandaa** [comment]
Still on the backlog.

**Comment by lucillex** [comment]
Closing this as it's being tracked in the buildkit repo: https://github.com/moby/buildkit/issues/4837
