### ISSUE TITLE
Smaller, compactor and dependable codebase

### ISSUE THREAD

**Issue by agowa** [microsoft/Windows-Containers#50]
Windows is currently a big blob of proprietary software that changes between version without any way of referencing that your application needs either at least some specific library version or specific feature to be enabled. Even though there are manifest files for programmers, there is no way to provide this in a comparable way like package managers do. And the lack of a good package manager is just ineligible for windows containers.

Ideally **only** the libraries actually needed by the application are present within the container and no unnecessary parts of windows. And for that to work also system components need to be served using the same package manager as the software is (not necessarily from the same repository though). Windows system components need to be additive and within a package manager. E.g. Start with nothing and add some features it's a nano server, add some more it's a core server and add a few libraries it's a "full" server.
But if you do not need one of the features e.g. dhcp client, cmd or notepad you do not need to install it.

As this feature is great by its own, what is the benefit for containers one might ask? Well, you just need to have a base container that has *only* a working package manager and nothing else. Than you ran e.g. `winget install PowerShell` to get a powershell and also all system libraries powershell needs to work.

This will provide:

- lower resource utilization
- faster container pull time
- less security vulnerabilities, something that does not exist cannot have a vulnerability.
- Much simpler to identify and troubleshoot applications (even if the bug is within a native library)
- Much simpler to identify applications that potentially break upon updates of os components (and rollback just that one component / library)
- Reduce the amount of system updates. Only installed components need to be updated and intermediate library versions can be skipped instead of all patches being applied sequentially and the same library being overwritten several times.
- (for the microsoft developers) allows to separate out the os components into separate projects, focus on the individual components. The base windows is currently too cluttered with features/stuff that on most machines will never be used (e.g. Modem libraries or Map provider on a file and database servers).
- (for the microsoft developers) will simplify writing patches as them themselves know which what things they touch depend on.
- (for the microsoft developers) allow them to better (and also automatically) test updates, estimate test coverage and identify libraries that do not have a maintainer (for some things in windows it looks like there is not a single developer taking care of it).
- (for the microsoft developers) Allows to move stuff out of the windows mono repository into separate projects. The announcement how big it is and that it is by far the biggest git repository was shocking.
- (for application developers) allow to identify breaking os patches much quicker, as only patches to used libraries need to be considered.
- (for application developers) allows to do automated testing with different patch levels and library versions quickly.
- (for system administrators) needing to install less updates and needing to care about less security vulnerabilities.
- (for system administrators) knowing exactly what runs on a system. No unnecessary background services.

**Comment by vrapolinario** [comment]
Apologies for not responding to this earlier.
Thank you for the detailed feedback here. As a group, we've been working to make the Windows container image smaller, but also taking care of app compatibility. Unfortunately, the composition of the Windows container image is not as simple as removing components to then have it restored at later point when needed. With that said, having a smaller image with a common package manager/installer is something we're looking into - however we can't provide a timeline for that at this moment.

I'll be closing this but wanted to ensure that we're looking into this issue.
