### ISSUE TITLE
Image 'LastUpdatedTime' date differs from DockerHub documentation

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [microsoft/Windows-Containers#501]
Hello,

I'm using `mcr.microsoft.com/windows/nanoserver` (`ltsc2022`, `1809`) as a base for some of my images. Looking at the [Microsoft/Nano Server](https://hub.docker.com/_/microsoft-windows-nanoserver) page on Dockerhub, the last update time for both of them is set to `03/12/2024`. 

Recently, I've noticed a size increase in my images built after `03/12/2024`.

Wihle investigating it, I've noticed the following changes in metadata:
**1. OS version**
* `1809` tag: `10.0.17763.5696` was changed to `10.0.17763.5820`;
* `ltsc2022` tag: `10.0.20348.2402` was changed to `10.0.20348.2461`;

**2. Image creation time** obtained via Docker CLI.
* `1809` tag: `03/12/2024` -> `05/10/2024`
* `ltsc2022` tag: `03/12/2024` -> `05/10/2024`

``` 
# 1. 1809
$ docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022  &&\
   docker image inspect mcr.microsoft.com/windows/nanoserver:ltsc2022 
... 
        "Created": "2024-05-10T20:16:48.9651239Z"

# 2. LTSC 2022
$ docker pull mcr.microsoft.com/windows/nanoserver:1809  && \
    docker image inspect mcr.microsoft.com/windows/nanoserver:1809     
… 
        "Id": "sha256:262f5153bde06a37d47731e0f7dede683ed5f72ab4b2f0e13c2c6a8a50b483a9", 
        "Created": "2024-05-10T20:21:42.0775987Z"
        … 
```

Could you, please, kindly suggest if [Nano Server](https://hub.docker.com/_/microsoft-windows-nanoserver) images have received any updates recently? This would greatly simplify tracking changes in images built on top of them.

Thank you!

**Comment by ntrappe-msft** [comment]
@deverouxmartin-msft Would you know the answer to the question about Nano Server images being recently updated?

**Comment by zylxjtu** [comment]
I believe what you get from the docker CLI is correct, the latest version for 2022 is 2461 and for 1809 is 5820. I think maybe the doc in here https://hub.docker.com/_/microsoft-windows-nanoserver will need to be updated

**Comment by ntrappe-msft** [comment]
@vrapolinario Would you be able to contact someone at Docker to get our docs updated?

**Comment by vrapolinario** [comment]
Let's discuss this internally.
For transparency with our customers: Microsoft is responsible for the description of Windows images on Docker Hub. The ownership of this has changed hands internally, so we need to fix this to ensure we have a proper process to keep the page updated.

**Comment by plooploops** [comment]
@AndreyKoltsov1997 

I did a check on the [nanoserver dockerhub page](https://hub.docker.com/r/microsoft/windows-nanoserver) and the image's documentation have been recently updated.

1. I'm including the relevant portion of the table for the tags you had mentioned:

| Tags | OsVersion | LastUpdatedTime |
| ----- | ----------- | ------------------- |
| 1809 | 10.0.17763.6189 | 08/13/2024 |
| ltsc2022 | 10.0.20348.2655 | 08/13/2024 |

2. For image creation time obtained via Docker cli:

```console
# 1. 1809
$ docker pull mcr.microsoft.com/windows/nanoserver:1809 && docker image inspect mcr.microsoft.com/windows/nanoserver:1809

...
        "Created": "2024-08-11T06:47:40.3781895Z",
...

# 2. ltsc2022
$ docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022 && docker image inspect mcr.microsoft.com/windows/nanoserver:ltsc2022
...
        "Created": "2024-08-10T19:28:00.5282956Z",
...
```

If there's any other questions, feel free to comment, otherwise feel free to close the issue.

**Comment by plooploops** [comment]
Marking as closed.  @AndreyKoltsov1997 if you have additional comments, please re-open or raise a new issue.
