### ISSUE TITLE
How to uninstall Docker CE on Windows Server

### ISSUE THREAD

**Issue by zhzy-to** [microsoft/Windows-Containers#508]
Currently the official documentation has a script for installing but not for uninstalling.
I uninstalled it step by step as someone else suggested earlier, but after installing it again and reimporting the image it gives me an error 
```
hcsshim::CreateLayer failed in Win32: Access is denied. (0x5)
```

**Comment by ntrappe-msft** [comment]
@zhzy-to Hi, please provide the following information so we can help you:
- What host are you using (e.g. Windows Server 2022)
- What image are you pulling (e.g., Windows Server Core 2022)
- How old is the image? (You can find out when it was created via `docker images` or `docker inspect <image id>`)

**Comment by ntrappe-msft** [comment]
^ Re-pinging thread.

**Comment by ntrappe-msft** [comment]
Issue is going stale. Closing for now.
