### ISSUE TITLE
Calico for Windows Open Source availability

### ISSUE THREAD

**Issue by mkostersitz** [microsoft/Windows-Containers#51]
With 3.16 Calico for Windows is now available in open source in line with the Linux version. This is now available for all customers deploying on premises. AKS integration will come soon.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@mkostersitz, please provide an update or close this issue.

**Comment by mkostersitz** [comment]
Calico for Windows is now available in open source at https://projectcalico.org
