### ISSUE TITLE
install-containerd-runtime.ps1 contains hardcoded old versions

### ISSUE THREAD

**Issue by ghost** [microsoft/Windows-Containers#512]
I think these values are hardcoded

param(
    [string]
    [ValidateNotNullOrEmpty()]
    $ContainerDVersion = "1.6.6",

    [string]
    [ValidateNotNullOrEmpty()]
    $NerdCTLVersion = "0.21.0",

    [string]
    [ValidateNotNullOrEmpty()]
    $WinCNIVersion = "0.3.0",

https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-ContainerdRuntime/install-containerd-runtime.ps1

**Comment by ritikaguptams** [comment]
Hi @codrutpopescu 
Thank you for reaching out to us. They are default values if nothing is passed. 
example usage if you pass parameters: 
`.\install-containerd-runtime.ps1 -ContainerDVersion "1.7.0" -NerdCTLVersion "0.22.0" -WinCNIVersion "0.4.0"
`

If nothing it passed i.e. script is invoked like it uses the default values: 
`.\install-containerd-runtime.ps1`
