### ISSUE TITLE
Install-docker-ce.ps1 script starts to fail in china

### ISSUE THREAD

**Issue by KlwntSingh** [microsoft/Windows-Containers#513]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
China seems to have blocked docker website and because of this [install-docker-ce.ps1](https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1) is failing to download and install docker with following error
```
Checking Docker versions
C:\Windows\system32\config\systemprofile\install-docker-ce.ps1 : Unable to connect to the remote server
At line:1 char:1
+ .\install-docker-ce.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,install-docker-ce.ps1
```

**To Reproduce** 
1. Launch Windows instance in china region
2. Execute the script [install-docker-ce.ps1](https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1)
3. This script will fail as docker is not reachable.

**Expected behavior**
This script should work in china region.

**Comment by ritikaguptams** [comment]
Hi Kulwant, 

I'd +1 on @jsturtevant's slack comment - https://kubernetes.slack.com/archives/C0SJ4AFB7/p1719428723493789?thread_ts=1719350084.192009&cid=C0SJ4AFB7

It looks like a docker issue, potentially you'd could download docker binaries and host them somewhere where your VMs from china can pull them. Just edit the curl to pull from your hosted location accessible in the country.
