### ISSUE TITLE
Nano Server SAC1809 Container Image Support now extended to Jan 2024

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#52]
Current support for Nano server 1809 ends on 11/10/2020. Whats the long term plan for support of Nano server Images for SAC and LTSC?

**Comment by weijuans-msft** [comment]
We appreciate the community's interest in Nano Server containers and generally Windows containers. Thanks:). For Nano Server container released with Windows Server version 1809, as Muzz called out, we are fully aware currently it goes out of support on 11/10/2020. We are aware of the need from the community to extend it and are actively working on that. The current rough ETA to have that approval is the end of this month. Will update the community once that happens.

We are also actively working on Nano Server container support in Windows Server vNext release. If you have any input here, please feel free to chime in. 

You can find out more about Windows Server vNext release and try out the Preview releases here:
https://blogs.windows.com/windows-insider/2020/08/26/announcing-windows-server-vnext-preview-build-20201/

Weijuan

**Comment by weijuans-msft** [comment]
I thought this will be great news to close the week:) -

We now have the approval to extend Nano Server container SAC1809 to be supported to Jan 2024, same as the Server Core container LTSC2019 mainstream support end date.

Woohoo~~

**Comment by weijuans-msft** [comment]
I should've added this: I have updated the Base OS image life cycle page with the change :).

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle.

**Comment by Josefczak** [comment]
We really need the windows:1809 image support also until 2024!

We spent a lot of time finding other solutions, but the best would just be to stay on the windows:1809 image on the 2019 server host.
