### ISSUE TITLE
The gMSA PowerShell module creates an improperly formatted key vault secret.

### ISSUE THREAD

**Issue by spowell-kcc** [microsoft/Windows-Containers#520]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
One of the Authors of this module asked me to report this bug here.

The [gMSA PowerShell module](https://www.powershellgallery.com/packages/AksGMSA/) function **New-GMSAAzureKeyVault** doesn't create a properly formatted key vault secret for the account used to manage the gMSA account. 

Using the secret created by the function results in the following errors when a gMSA credSpec container is launched:
 - Failed to setup the external credentials. 
 - The RPC server is unavailable. (0xC0020017) 

**To Reproduce** 
Call the New-GMSAAzureKeyVault function with the expected parameters.

A key vault secret will be created with the following value:
"value": "System.Security.SecureString"

**Expected behavior**
The key vault value should be created as one of these values:
 - "value": "<fqdn.com>\\\<username\>:System.Security.SecureString"
 - "value": "<fqdn.com>\\\<username>:\<password-in-plain-text>"

**Configuration:**
 - AKS version 1.27.9
- gMSA Module Version: 1.4.2 

**Additional context**  

Line 839 in the PowerShell module sets the secret value as this:
```
$secretValue = ConvertTo-SecureString -String "${GMSADomainUser}:$([System.Net.NetworkCredential]::new('', $GMSADomainUserPassword).Password)" -AsPlainText -Force
```
... fully encoding the domain, username and password.

The [key vault configuration section](https://learn.microsoft.com/en-us/azure/aks/use-group-managed-service-accounts#store-the-standard-domain-user-credentials-in-azure-key-vault) of the [Enable Group Managed Service Accounts (GMSA) for your Windows Server nodes on your AKS | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/use-group-managed-service-accounts) uses this example: 
```
az keyvault secret set --vault-name myGMSAVault --name "GMSADomainUserCred" --value "$Domain\\$DomainUsername:$DomainUserPassword"
```
... setting the password as plain text.  

Converting the secret string to encode only the password as a secure string, or to set the password as plain-text only, eliminates the errors and allows the AKS gMSA plugin to launch the containers using the desired gMSA user context.

**Comment by ntrappe-msft** [comment]
@vrapolinario + @thecloudtaylor for visibility.

**Comment by vrapolinario** [comment]
I have connected with @spowell-kcc offline and we discussed this. I have tested the PS module version 1.4.2 and can confirm that it currently sets up the secret in Azure Key Vault as the password-in-plain-text above.

@spowell-kcc did provide some good feedback on this, including adding the option to set this up as "<fqdn.com>\<username>:System.Security.SecureString" which is not supported currently in the module, but works for gMSA in case users want to do it manually.

**Comment by spowell-kcc** [comment]
⁠Vinicius,
This is a different, but similar, issue to what we discussed last week.
 When Mark and I originally installed GMSA we used the GMSA PS module function to create the keyvault and the secret. When using that function the entire credential (<fqdn.com>\<username>:<plaintextpassword>) gets set as a secure string in the vault, which did not work with the plug-in when launching pods.
The GMSA function created the keyvault credential value as this …
"System.Security.SecureString"
… instead of this …
"<fqdn.com><username>:System.Security.SecureString" or
"<fqdn.com><username>:<plaintextpassword> "
… both of which seem to work.




K-C Internal Only

**Comment by vrapolinario** [comment]
Hi Sean,
Can you confirm if you ran the command as in the documentation? https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/configure-gmsa-ps-module#create-the-azure-key-vault

```
# The Azure key vault will have a secret with the credentials of the standard
 # domain user authorized to fetch the gMSA.
 New-GMSAAzureKeyVault -ResourceGroupName $params["aks-cluster-rg-name"] -Location $params["azure-location"] -Name $params["akv-name"] -SecretName $params["akv-secret-name"] -GMSADomainUser "$($params["domain-fqdn"])\$($params["gmsa-domain-user-name"])" -GMSADomainUserPassword $params["gmsa-domain-user-password"]
```

I have tested this last Friday and can confirm the command above creates the secret as plain text password. If you ran the same command and ended up with a different output, we'll have to investigate why that is.

**Comment by spowell-kcc** [comment]
Hi Vinicius,

If you have verified that the current version works, go ahead and close the issue.

I opened this item 4-5 weeks ago, so I don’t have any of the code / examples I was using then. I only have the sample code I added to the ticket.




K-C Internal Only

**Comment by vrapolinario** [comment]
Thanks Sean, if you do see this happening again, please comment back here and we'll re-open the issue.
