### ISSUE TITLE
SmartCardReader class device ?

### ISSUE THREAD

**Issue by domignace** [microsoft/Windows-Containers#521]
**Is it planned to support SmartCardReader class device ?**

[Devices in containers on Windows](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/hardware-devices-in-containers#hyper-v-isolated-linux-container-support) indicates how to use supported devices in a Windows container. 

Is it planned/possible/requestable to support SmartCardReader class devices ?

**Comment by fady-azmy-msft** [comment]
Hey @domignace , can you share the scenario you have in mind for needing support to the SmartCardReader class? What are you trying to accomplish and what windows container set up do you have (K8s?)

**Comment by ntrappe-msft** [comment]
Pinging this thread.

**Comment by fady-azmy-msft** [comment]
Closing this thread due no response.

**Comment by domignace** [comment]
@fady-azmy-msft , @ntrappe-msft , sorry for the late answer.

I am thinking of 2 use cases :
- A docker image with our build chain and the ability to code sign. 
- Being able to automate tests for our PKCS#11 , CSP, KSP.

Regarding our setup, we are just starting looking at the possibility to use windows docker images to replace our physical / virtual machine slaves.

If you don't mind, I'll reopen the issue when restarting to work on this topic.

Regards,
  ++dom
