### ISSUE TITLE
I am unable to run process-isolated WS2022 containers through Docker Desktop and Windows 11

### ISSUE THREAD

**Issue by Uranusmiko** [microsoft/Windows-Containers#525]
Hi,

currently I met a problem when running WS2022 container under Windows 11 and process isolation mode.  Here is the error message:

PS C:\WINDOWS\system32> docker run --rm -it --isolation=process mcr.microsoft.com/windows/servercore:ltsc2022
docker: Error response from daemon: <container id> encountered an error during hcs::System::CreateProcess: c:\windows\system32\cmd.exe: failure in a Windows system call: The remote procedure call failed. (0x6be).

If I change to another image:  mcr.microsoft.com/windows/server:ltsc2022 (instead of servercore), I got a different error message:
PS C:\WINDOWS\system32> docker run --rm -it --isolation=process mcr.microsoft.com/windows/server:ltsc2022
docker: Error response from daemon: <container id> encountered an error during hcs::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).

All commands work fine under hyperv isolation mode.

I wonder whether I miss some configuration steps or there is some compatibility issue with process isolation mode when running under Windows 11.

Thank you very much!

**Comment by sabinamiezah-msft** [comment]
Hi, thank you for bringing this to our attention. Can I confirm if you are using docker desktop? If so, can you make sure you've switched to Windows Containers? (It should say "Switch to Linux Containers" if you have).

**Comment by Uranusmiko** [comment]
Thank you for your response. There is no choice of "Switch to Windows Containers" in the menu of docker desktop. I manually switch to Windows containers by running the following command:
 “C:\Program Files\Docker\Docker\DockerCli.exe” -SwitchDaemon

**Comment by sabinamiezah-msft** [comment]
Alright, could you paste the output of running `docker info`?

**Comment by Uranusmiko** [comment]
Here is the output of docker info:

Client:
 Version:    27.0.3
 Context:    desktop-windows
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.10.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 141
 Server Version: 27.0.3
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22631 (22621.1.amd64fre.ni_release.220506-1250)
 Operating System: Microsoft Windows Version 23H2 (OS Build 22631.4037)
 OSType: windows
 Architecture: x86_64
 CPUs: 14
 Total Memory: 31.46GiB
 Name: TestMachine3
 ID: 
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by ntrappe-msft** [comment]
Hi, just jumping in here quickly. It looks like @sabinamiezah-msft couldn't repro your error so we'll need to get some more info. Would you mind collecting some Docker Events and HCS Logs?

### Docker Events
```ruby
docker events
```

### HCS Logs
```rust
Get-WinEvent -ProviderName "Microsoft-Windows-Hyper-V-Compute"
```

We may need different events/logs later if these don't expose what's going wrong. Thanks!

**Comment by sabinamiezah-msft** [comment]
Hi, just getting back to you on your issue. Are you still facing the failure to create a servercore/fullserver container? Additionally, can we try to get some more info using the following commands:

`docker events`

`Get-WinEvent -ProviderName "Microsoft-Windows-Hyper-V-Compute"`

**Comment by sabinamiezah-msft** [comment]
Due to unresponsiveness, I'll be closing this discussion now.
