### ISSUE TITLE
Release notes for mcr.microsoft.com/windows:ltsc2019 base docker image

### ISSUE THREAD

**Issue by KiranMulawad** [microsoft/Windows-Containers#526]
I see that **_mcr.microsoft.com/windows:ltsc2019_** image has been updated as per the info provided on dockerhub, image mentioned was updated on 08/13/2024. By any chance is there a way to check what has been updated I mean release notes for the same. mentioning hot fixes applied in case any.
I wanted to make sure that is it necessary/better practice to update base images frequently(to accommodate new updates in base images) in order to be inline with the new updates/security patches on container host machines.

**Comment by avin3sh** [comment]
I use `{docker,podman} image history` for this purpose

```
PS C:\Users\Avinesh> docker image history mcr.microsoft.com/windows:ltsc2019
IMAGE          CREATED         CREATED BY                       SIZE      COMMENT
8c4498ace9e0   2 weeks ago     Install update 10.0.17763.6189   3.08GB
<missing>      14 months ago   Apply image 10.0.17763.4499      7.31GB
```

As you can see, the latest image is built from build `10.0.17763.6189` and its corresponding release notes are at https://support.microsoft.com/en-us/topic/august-13-2024-kb5041578-os-build-17763-6189-522a6305-63d2-40e3-8084-2ab8f9589bc6

However I do agree this should be standardized and there should be a process to release container-specific notes aside general CU release notes.

**Comment by ntrappe-msft** [comment]
@vrapolinario Do you have any thoughts on update/release notes?

**Comment by akarshm** [comment]
@KiranMulawad you can find the Windows Server container release notes [here](https://support.microsoft.com/en-us/topic/kb5042376-windows-server-containers-for-august-2024-1e8dde39-d203-4eb0-92cc-a0350b45f7ed).
