### ISSUE TITLE
Windows Server 2004 use docker-compose create multi NAT network HNS process is CPU high

### ISSUE THREAD

**Issue by kkbruce** [microsoft/Windows-Containers#53]
Hi Sir

I feedback Windows Server 2004 and Windows Container issue in https://github.com/docker/for-win/issues/8423

stephen-turner say:  Docker Enterprise for Windows Server, support is provided by Microsoft.

I don't know where can contact Microsoft with this issue. Could you confirm this issue or provide a contact address for me?

**Comment by mkostersitz** [comment]
We are going to route this issue to Docker Enterprise support.

**Comment by mkostersitz** [comment]
This should be resolved in next Windows Server Semi Anual Cycle release.
