### ISSUE TITLE
File permission changes with RunAsUserName

### ISSUE THREAD

**Issue by jingxu97** [microsoft/Windows-Containers#54]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-runasusername/, 
Here it introduced a feature to RunAsUseName in Kubernetes. So want to verify whether there is any file permission implications when using this feature. 

This is just a general right now for the record. I will try to test later about it.

**Comment by kevpar** [comment]
The `RunAsUserName` feature will change the underlying Windows user context that the container runs under. This user must be one that is present in the container image. Each file and directory has a set of ACLs that control which users have permissions to interact with it. You can view these permissions with the `icacls` command inside the container.

For the base images Microsoft provides (e.g. `mcr.microsoft.com/windows/servercore:2004`), I think there are only `ContainerUser` and `ContainerAdministrator` users. `ContainerUser` has a standard user's level of access to the container's files, whereas `ContainerAdministrator` has the level of access an administrator would normally have.

When creating a Windows image, it is possible to add new users and change filesystem permissions, using standard Windows tooling (e.g. the `net` and `icacls` commands).

**Comment by immuzz** [comment]
@jingxu97 I hope this answers your question. Feel free to re-open the issue if you have any more questions
