### ISSUE TITLE
Liveness/readiness probe for applications running on windows containers

### ISSUE THREAD

**Issue by keikhara** [microsoft/Windows-Containers#55]
We are seeing many customers running a lot of processes on windows container since the base image is too expensive. Due to this, monitoring is very weak since they need to monitor many processes. The k8s readiness/liveness probe will work for a simple process but when it comes to this, it is hard to monitor. Customers are asking as way to monitor all the processes inside. 

 It would be good if you can have way to expose these processes and make sure it is clear so customers do not need to track every logs from multiple applications in a single log file. (i.e. - stdout.out) 

When doing this, add some indication so you can filter with certain applications.

**Comment by vrapolinario** [comment]
This will be investigated as continue to plan on enhancements for Windows Containers. No timeline at this point.
