### ISSUE TITLE
Custom CA certificate disappears in Windows Container

### ISSUE THREAD

**Issue by zhiweiv** [microsoft/Windows-Containers#56]
We are trying to import CA certificate to Cert:/LocalMachine/AuthRoot during application start. The import is successful, however after 35mins~40mins, the certificate is gone from Cert:/LocalMachine/AuthRoot.

At the beginning there are 2 built-in certificates, after import there are 3. But after 35mins~40mins you will find only built-in certificates left, the custom CA certificate is gone.

The code to reproduce:
```
class Program
    {
        static void Main(string[] args)
        {
            ListCerts(); 
            var  cert = new X509Certificate2(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ca.crt"));
            using (var store = new X509Store(StoreName.AuthRoot, StoreLocation.LocalMachine))
            {
                store.Open(OpenFlags.ReadWrite);
                store.Add(cert);
            }
            while (true) 
            {
                ListCerts();
                Thread.Sleep(TimeSpan.FromSeconds(30));
            }
        }

        static void ListCerts()
        {
            using (var store = new X509Store(StoreName.AuthRoot, StoreLocation.LocalMachine))
            {
                store.Open(OpenFlags.ReadOnly);
                Console.WriteLine(DateTime.UtcNow.ToString());
                foreach (var item in store.Certificates) 
                {
                    Console.WriteLine("{0} {1}", item.Thumbprint, item.Subject);
                }
            }
        }
    }
```

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-20200714-windowsservercore-ltsc2019
COPY . /app/
ENTRYPOINT ["/app/certtest.exe"]
```
ca.crt:
[ca.zip](https://github.com/microsoft/Windows-Containers/files/5280114/ca.zip)

docker(Windows Server 2019):
docker run -it --rm certtest:v1

**Comment by vrapolinario** [comment]
Thanks for bringing this to our attention @zhiweiv.
We have created an internal bug and the team will investigate this issue.

**Comment by zhiweiv** [comment]
We raised Azure Support ticket 120092526001168, MS support reproduced same issue in his environment. Now he stated the case has been submit to PG team for further investigation.

The custom CA certificate was deleted by Windows, the event logs came from Windows container.
![ca](https://user-images.githubusercontent.com/22001089/97128709-0148e180-1778-11eb-849f-cc5012c6cb32.jpg)

**Comment by zhiweiv** [comment]
Can reproduce by PowerShell too:
cert.ps1
```
Import-Certificate -FilePath ca.crt -CertStoreLocation Cert:/LocalMachine/AuthRoot
cd Cert:/LocalMachine/AuthRoot; 
while($true) 
{ 
	Get-Date
	dir;
	Start-Sleep 60; 
}
```
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-20200908-windowsservercore-ltsc2019
WORKDIR /app
COPY . /app/
ENTRYPOINT ["Powershell", "-File", "cert.ps1"]
```

Command:
docker build -t certtest:v1 .
docker run -it --rm certtest:v1

**Comment by zhiweiv** [comment]
@vrapolinario
Any update from from your side?

**Comment by immuzz** [comment]
@weijuans-msft as @vrapolinario is on leave.

**Comment by vrapolinario** [comment]
Apologies for the delay in providing an updated on this one. We're still investigating it internally.

**Comment by zhiweiv** [comment]
@vrapolinario 
Any update? It is still a problem for us.

**Comment by vrapolinario** [comment]
Hi @zhiweiv, I'm so sorry for the delay.
The team did respond and noted that this is an expected behavior, since the recommendation is to not install on the AuthStore as that is managed by the auto root update mechanism. The recommendation is to install it on Cert:/LocalMachine/Root.

Can you please validate that for your application?

**Comment by zhiweiv** [comment]
Cert:/LocalMachine/Root works for me, thanks.
