### ISSUE TITLE
ServerCore base image with added features

### ISSUE THREAD

**Issue by Hvid** [microsoft/Windows-Containers#58]
Please either make it possible to add capabilities to containers:
Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0.0.1.0

Or provide a base image with the compatibility feature added.

Thanks

**Comment by vrapolinario** [comment]
Thanks for opening this issue @Hvid. Our team is currently evaluating an option for adding features/components/capabilities to the Windows base images. Can you please share more details on your request? What is the scenario you want to enable - from the example you provided, it seems like you're looking for the AppCompatibility feature - is that it?

**Comment by Hvid** [comment]
We're hosting legacy applications in Windows containers. These are applications out of our control, so we can't make code changes. These applications depend on old components like cdosys.dll, access 2000 databases and so on. They work with the Windows base image, but that isn't really optimal, as it's huge and seem to be the client OS. The AppCompatibility feature should be able to solve our issues, so we can keep them on servercore.

**Comment by biiiipy** [comment]
Not to hijack the thread but it would be great if MS created a smaller image that includes http.sys stuff, so Windows Authentication would work in a Nano-like image. Server Core works, but it's huge and we only really need Windows Authentication to work. Or make it possible to add features to base images or remove unneeded stuff from bigger images...

**Comment by vrapolinario** [comment]
Sorry for not answering to this earlier.
This is in our backlog and we don't have a timeframe to provide at this moment, but given the customer feedback on it, we'll be investigating it and providing an update when possible.

**Comment by Hvid** [comment]
How do i track this, if you're closing the issue?

**Comment by vrapolinario** [comment]
This will be kept in our backlog. We're closing as we don't have an update at this time neither a timeline to provide an update.
With that, I wanted to ensure this is still something we're looking at.
