### ISSUE TITLE
HNS Endpoint DNSSuffix not taking effect

### ISSUE THREAD

**Issue by hanlins** [microsoft/Windows-Containers#59]
Environment:
```
PS C:\> (Get-WmiObject Win32_OperatingSystem).Version
10.0.17763
```

My team is working on kubernetes CNI support for windows container, and we need to add a DNS suffix search list to container network. By passing the DNS search list to `DNSSuffix`, seems we configured the HNS endpoint correctly:
```
PS C:\Users\bosh_e6eb4f2e0bd3484> get-hnsendpoint


ActivityId                : 03C31E90-A258-4807-B41B-73DA844A4490
AdditionalParams          :
CreateProcessingStartTime : 132457439315722566
EncapOverhead             : 0
GatewayAddress            : 169.254.1.1
Health                    : @{LastErrorCode=0; LastUpdateTime=132457439315554069}
ID                        : 72A0776A-BB47-4F98-8953-2A738F4BAF4D
IPAddress                 : 169.254.1.0
MacAddress                : 00-50-56-96-00-0E
Name                      : agent0
Policies                  : {}
PrefixLength              : 30
Resources                 : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; Health=;
                            ID=03C31E90-A258-4807-B41B-73DA844A4490; PortOperationTime=0; State=1;
                            SwitchOperationTime=0; VfpOperationTime=0; parentId=7B252054-1D2D-40A7-941B-3030776A9E28}
SharedContainers          : {}
StartTime                 : 132457439328228959
State                     : 2
Type                      : Transparent
Version                   : 38654705667
VirtualNetwork            : a1ae87fc-5ecf-414a-b464-fd638455a075
VirtualNetworkName        : transit

ActivityId                : A5308748-62DA-4746-AA67-D65CFF1F3CE9
AdditionalParams          :
CreateProcessingStartTime : 132457502837743593
DNSServerList             : 10.220.0.2
DNSSuffix                 : svc.cluster.local,cluster.local
EncapOverhead             : 0
GatewayAddress            : 172.46.2.1
Health                    : @{LastErrorCode=0; LastUpdateTime=132457502837743593}
ID                        : CAE5A21C-B068-45F2-9446-72A9D307F5E2
IPAddress                 : 172.46.2.3
MacAddress                : 04-50-56-00-e8-3d
Name                      : 9a72f1aa15fa0bd06795406772d2bd090c3cf469be3e1df4a4106312106a8d3b_eth0
Policies                  : {}
PrefixLength              : 24
Resources                 : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; Health=;
                            ID=A5308748-62DA-4746-AA67-D65CFF1F3CE9; PortOperationTime=0; State=1;
                            SwitchOperationTime=0; VfpOperationTime=0; parentId=7B252054-1D2D-40A7-941B-3030776A9E28}
SharedContainers          : {9a72f1aa15fa0bd06795406772d2bd090c3cf469be3e1df4a4106312106a8d3b,
                            7a095a174a5b5ff47bf2cb8dd4bc7816edfee195bd578ef2d74f
...
```
As we can see above, `DNSSuffix` is set to `svc.cluster.local,cluster.local`. The in-cluster DNS service (`kube-dns` with virtual IP `10.220.0.2`) can resolve FQDN like `kubernetes.default.svc.cluster.local` as following:
```
PS C:\> nslookup kubernetes.default.svc.cluster.local
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.220.0.2

Name:    kubernetes.default.svc.cluster.local
Address:  10.220.0.1
```
We expect that we can perform DNS lookup for `kubernetes.default` within container. Unfortunately it didn't work as expected:
```
PS C:\> nslookup kubernetes.default
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.220.0.2

*** kube-dns.kube-system.svc.cluster.local can't find kubernetes.default: Non-existent dom
ain
```

From the error message, the windows container made attempt to directly resolve `kubernetes.default` where we expect it to also make attempts for resolving `kubernetes.default.svc.cluster.local`.

From the container, we also saw that `SearchList` property in registry key `HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters` is not configured:
```
PS C:\> Get-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name SearchList
Get-itemproperty : Property SearchList does not exist at path
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters.
At line:1 char:1
+ Get-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (SearchList:String) [Get-ItemProperty], PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.GetItem
   PropertyCommand
```
We manually ran following commands in the container powershell:
```
PS C:\> $arguments = @('nicconfig','call','SetDNSSuffixSearchOrder',"('default.svc.cluster.local','svc.cluster.local','
cluster.local')")
PS C:\> wmic $arguments
```
Which effectively set the registry value as mentioned above:
```
PS C:\> Get-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name SearchList
SearchList   : default.svc.cluster.local,svc.cluster.local,cluster.local
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Paramet
               ers
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip
PSChildName  : Parameters
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```
And then, we can resolve `kubernetes.default` as expected:
```
ubuntu@opsmgr-06-slot-50-pez-vmware-com:~$ kubectl exec test-win-64f858c7f9-zntbj -- nslookup kubernetes
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.220.0.2

Name:    kubernetes.default.svc.cluster.local
Address:  10.220.0.1
```

Our questions are:
1. Given the nature of k8s CNI design, we cannot perform intrusive modifications within windows containers. All what we can do is to pass configuration during the creation of HNS endpoint. Is `DNSSuffix` the parameter to pass the DNS search list or we have the wrong expectation?
2. Is the format (comma separated string) of `DNSSuffix` correct? From the [code](https://github.com/containernetworking/plugins/blob/v0.8.7/pkg/hns/endpoint_windows.go#L89) we're under impression that it should be a comma separated string.

Also please let us know if you got a confirmation that this is an implementation issue on HNS endpoint, thanks!

**Comment by michmike** [comment]
@daschott, can you please take a look at this issue
cc: @marosset

**Comment by mkostersitz** [comment]
@daschott is out of the office right now. I will take care of it.

**Comment by mkostersitz** [comment]
We are investigating the issue right now. Will update as soon as we have news

**Comment by daschott** [comment]
@hanlins 
DNS Resolver on Windows treats any domain name with a . in it as if it was FQDN:
https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations

This is a platform difference that may be possible to investigate. Can you elaborate more details explaining why resolution for `kubernetes.default` is needed?

As for setting domain, can you try setting "--cluster-domain" flag in kubelet? On top of this, depending on CNI plugin you'd need to add the suffices to the CNI configuration file as well (or pod spec if you are passing DNS information that way). By default it will only have "svc.cluster.local" inside it

E.g. in win-bridge or win-overlay you can add field "dns" in the CNI configuration:
"dns":  {
                                 "Nameservers":  [
                                                     "10.96.0.10"
                                                 ],
                                 "Search":  [
                                                "svc.cluster.local"
                                            ]
                             },
or if you enabled DNS in the CNI plugin by setting DNS capabilities:true, you should be able to pass DNS configuration via pod spec as well.

**Comment by hanlins** [comment]
Hi @daschott thanks for getting back! I see, that's interesting, we haven't checked the [windows specific doc](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations) you mentioned, so I think this issue is prevalent for all current CNI solutions. We found the issue in both our proprietary implementation as well as [Antrea](https://github.com/vmware-tanzu/antrea/) windows support that the clusters failed the sig-windows conformance tests because of this limitation. I can check with my team and let them provide the details on the failed tests. Also maybe @ydp can help on retrieving the detailed CNI spec we passed to the cluster.
Besides that, you mentioned there's a inconsistency between windows and linux that windows treats anything contains a '`.`' as a FQDN, is this intentional or this is something to be fixed? Is it possible to expose an option to change this behavior(so windows will also make attempts for appending the suffixes to FQDNs) during the creation of HNS endpoint?

**Comment by ydp** [comment]
Hi @daschott , I will try to setup a new env and get more info here. In the mean time, can you help explain that windows only have 1 DNS suffix with pod namespace? Does this suffix need we pass in or the container automatically find this suffix? Since from our tests for antrea, we already passed  `$namespace.svc.cluster.local` in, but the query never try to append any suffix at all, which is why our CNI plugin cannot pass conformance test.

**Comment by ydp** [comment]
Hi @daschott  here is what I got:

cni configuration:
```
PS C:\var\vcap\jobs\nsx-cni-windows\config> cat .\10-nsx.conf
{
    "cniVersion": "0.3.1",
    "name": "nsx-cni",
    "type": "nsx.bat",
    "dns": {
        "Nameservers": ["10.100.200.2"],
        "Search": ["svc.cluster.local", "cluster.local"]
    }
}
```
DNS Suffix in windows container:
```
win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : iis-site-windows-5769b547f5-6fwc2
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : cluster.local
                                       default.svc.cluster.local
                                       svc.cluster.local

Ethernet adapter vEthernet (2f2f5c0b3b48628e196f52aaf5e10362e666dabf40f197c33b8a6093ff38a305_eth0):

   Connection-specific DNS Suffix  . : cluster.local
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #4
   Physical Address. . . . . . . . . : 02-50-56-00-50-16
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::b53b:7c2a:1700:c5b4%25(Preferred)
   IPv4 Address. . . . . . . . . . . : 40.0.15.4(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 40.0.15.1
   DNS Servers . . . . . . . . . . . : 10.100.200.2
   NetBIOS over Tcpip. . . . . . . . : Disabled
   Connection-specific DNS Suffix Search List :
                                       cluster.local
                                       default.svc.cluster.local
                                       svc.cluster.local
```
You could see we have `default.svc.cluster.local` passed in.

Look up FQDN in container success:
```
win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- nslookup kubernetes.default.svc.cluster.local
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.100.200.2

Name:    kubernetes.default.svc.cluster.local
Address:  10.100.200.1

```

Look up PQDN in container failed:
```
win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- nslookup kubernetes
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.100.200.2

*** kube-dns.kube-system.svc.cluster.local can't find kubernetes: Non-existent domain
```
It's looking for `kubernetes`, not `kubernetes.default.svc.cluster.local`.

* Could you please help point where is wrong in our configuration?

* Do we need to set `Connection-specific DNS Suffix` or `Primary Dns Suffix` here?  Those fields confuses me.

And to your previous question, we do not need to resolve `kubernetes.default`, but we do need to resolve `kubernetes`, however, it seems not working either.

**Comment by daschott** [comment]
@ydp thanks for following up - have you tried using `resolve-dnsname` cmdlet?

The thing about nslookup is that it doesn’t use the Windows DNS client resolver. It should not be used for testing DNS connectivity on Windows.

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations

**Comment by ydp** [comment]
Hi @daschott  thanks for pointing out the cmdlet, I have tried, seems it works fine, but nslookup not as I present before. Here is my result:

```
kubo@jumper:~/win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- powershell.exe Resolve-DnsName -Name kubernetes

Name                                           Type   TTL   Section    IPAddres
                                                                       s
----                                           ----   ---   -------    --------
kubernetes.default.svc.cluster.local           A      5     Answer     10.100.2
                                                                       00.1


kubo@jumper:~/win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- powershell.exe Resolve-DnsName -Name kubernetes.default.svc.cluster.local

Name                                           Type   TTL   Section    IPAddres
                                                                       s
----                                           ----   ---   -------    --------
kubernetes.default.svc.cluster.local           A      5     Answer     10.100.2
                                                                       00.1


kubo@jumper:~/win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- powershell.exe Resolve-DnsName -Name my-nginx

Name                                           Type   TTL   Section    IPAddres
                                                                       s
----                                           ----   ---   -------    --------
my-nginx.default.svc.cluster.local             A      5     Answer     10.100.2
                                                                       00.30


kubo@jumper:~/win2$ kubectl exec iis-site-windows-5769b547f5-6fwc2 -- powershell.exe Resolve-DnsName -Name my-nginx.default.svc.cluster.local

Name                                           Type   TTL   Section    IPAddres
                                                                       s
----                                           ----   ---   -------    --------
my-nginx.default.svc.cluster.local             A      5     Answer     10.100.2
                                                                       00.30
```

@daschott   Could you please help share some insights about how to verify if other tools used Windows DNS client resolver? I have a test for ping, seems it works fine too.

**Comment by daschott** [comment]
`resolve-dnsname` is representative of DNS resolution used by vast majority of applications and other tools. Just don't use `nslookup` and you should see consistent results everywhere else, including Invoke-Webrequest, curl, .NET apps, IIS apps, resolve-dnsname, etc.

**Comment by mkostersitz** [comment]
As outlined by @daschott nslookup might fail where resolve-dnsname will succeed. I am closing this issue as there is a workaround.
