### ISSUE TITLE
[feature]Calico Network policy support for Windows Containers on AKS-HCI

### ISSUE THREAD

**Issue by msjingli** [microsoft/Windows-Containers#63]
Calico Network policy support for Windows Containers on AKS-HCI

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by msjingli** [comment]
This feature is completed. https://docs.microsoft.com/en-us/azure-stack/aks-hci/new-akshcicluster#-primarynetworkplugin.
