### ISSUE TITLE
Customer Issue: Missing Fonts on Server with reduce footprint (Nano and potentially Server Core)

### ISSUE THREAD

**Issue by alib-ms** [microsoft/Windows-Containers#64]
We received following email from a customer who is using containers with Windows Server Nano/Core which doesn’t have the system fonts built-in because these are Servers with reduce footprint.  e.g. the Nano Server only has the Lucida Console available. Would it be possible to provide a method to download font packages on these Windows Servers editions? 

Dear Basit, 

We are an ISV developing products which run OCR and extract data from documents. For our latest product (see description below) it seems that we will need to license the Microsoft system fonts in order to be able to provide the intended functionality. 
Normally our technology runs on a Windows machine and we use the system fonts for our purposes, however we will be using containers with Windows Server Nano/Core which doesn’t have the system fonts built-in.

As advised by the Microsoft website we contacted Monotype, however they told us that they do not have rights to licenses all Microsoft system fonts to us for the described purposes. 
Could you please advise what is the best way for us to proceed here?

Detailed explanation of product functionality related to fonts: 
Vantage is a product that is intended to extract data from documents, e.g. number, date and total amount from invoices. Vantage is provided to customers as SaaS and on-premises.

Vantage supports processing documents from different files formats, including PDF files, that may be scans or digitally born PFDs with text layer. Vantage uses fonts to produce an image from PDF file to perform OCR (optical character recognition) and to show document image to the user that will conduct manual review of OCR results. Not all digitally born PDF files have fonts embedded, that why Vantage requires fonts to be able to show the image of the file and OCR that image. Since typically PDF are created on Windows, we need fonts that Windows has by default. 

Once processed, the document, regardless the original file format, may be saved into PDF with text layer for long-term storing. Upon user request, Vantage may embed fonts inside PDF file, so later this file can be seen by the user at any computer.

Thank you very much in advance!
Kind regards,

**Comment by biiiipy** [comment]
We struggled with the same issue couple of weeks ago. We use Server Core image that also has only Lucida Console in it. We tried different hacks to add fonts to windows image, but that didn't work. Thankfully we were able to code around this issue. It would be great if there was a documented way how to add them properly to our images (we definitely don't want them built in by default, because fonts take up a lot of space).

**Comment by zhiweiv** [comment]
+1, We need fonts too.

**Comment by SlHris** [comment]
@weijuans-msft we do need a solution to this issue since we are about to announce a new version of the product described above by @alib-ms and this is a roadblock for us. Thank you!

**Comment by weijuans-msft** [comment]
Apologize for the delay. My bad.  It didn't occur to me until now that I haven't suggested this: Have you tried the 3rd image, https://hub.docker.com/_/microsoft-windows? This image has much broader API support and also have fonts. It is bigger on size though. If you haven't, please do give it a try and let us know how that works for you.

**Comment by weijuans-msft** [comment]
@alib-ms @biiiipy @zhiweiv ping. wanted to see if you have tried the 3rd windows container image.

**Comment by biiiipy** [comment]
We resolved the issue by making changes in our service to custom load fonts on the app end, so didn't try microsoft-windows image. In any case, that definitely would not be ideal as microsoft-windows is a huge image and we didn't want to introduce and support another base image. These kind of issues ideally should be solvable with a scriptable installation on docker build, so we could pick and choose what we need, but alas windows is not known for being flexible...

**Comment by weijuans-msft** [comment]
@biiiipy thanks for the update.   I have created an internal tracking item #32608605. We will evaluate and share the updates here when we make progress.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @judyliu-ms, please provide an update or close this issue.

**Comment by artisticcheese** [comment]
We have no issues adding custom fonts to images, example is below which adds times new roman font


```DOCKERFILE
#escape = ` 
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
RUN Invoke-WebRequest https://core360utilitystorage.blob.core.windows.net/public/times.ttf -outfile times.ttf; `
   copy-item times.ttf c:\windows\fonts\; `
   Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts' -name 'Times New Roman' -value 'times.ttf' -type STRING; `
   Remove-Item times.ttf;
```

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by vrapolinario** [comment]
We finally have a prescribed a d supported way to install fonts back to the Server Core image. 
When we removed the fonts, we also removed the feature that installs new fonts. I blogged here on how to get fonts back to Server Core images: https://techcommunity.microsoft.com/t5/itops-talk-blog/adding-optional-font-packages-to-windows-containers/ba-p/3559761

**Comment by tanukus** [comment]
Hello @vrapolinario - We have followed the steps documented in the prescribed way to install fonts back. We are getting an error "System.DllNotFoundException: Unable to load DLL 'T2Embed'" in our ASP.NET 4.8 web application running in a container.
The app uses Microsoft.ReportViewer to extract a PDF from a report, that is when this error occurs.

Base image: "mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019". 
The host VM: Windows Server 2019 Datacenter edition and T2Embed.dll is in the host System32 folder, however the container file system is missing the T2Embed.dll. How can this dll be obtained?

Any help or guidance is appreciated.

**Comment by vrapolinario** [comment]
Thanks for reporting this @tanukus. @weijuans-msft is the PM owner of this. She's currently OOF so it might take a while for her to respond. Adding @michbern-ms and @fjs4 for visibility.

**Comment by michbern-ms** [comment]
@tanukus Did the steps documented bring the fonts back as expected?   I think the T2Embed is a separate problem, and I think it is going to cause confusion if we try to tackle it in this issue.  Can I ask you to please open a new issue so that we can review this specifically?  Thanks!

**Comment by tanukus** [comment]
> @tanukus Did the steps documented bring the fonts back as expected? I think the T2Embed is a separate problem, and I think it is going to cause confusion if we try to tackle it in this issue. Can I ask you to please open a new issue so that we can review this specifically? Thanks!

Thank you for quick responses @vrapolinario @michbern-ms 
Yes, the steps ran fine, except for the below command, which failed to run on Windows Server Core 2019 DataCenter VM (host)
`dism /online /enable-feature /featurename:ServerCoreFonts-NonCritical-Fonts-UAPFonts /Source:O:\ /LimitAccess"`.

Opened https://github.com/microsoft/Windows-Containers/issues/266 for the T2EMBED.DLL issue, thanks.

**Comment by artisticcheese** [comment]
@tanukus Did you ever try my method? https://github.com/microsoft/Windows-Containers/issues/64#issuecomment-1059865508
This works very well for us and seems to be requiring much less hassle to implement

**Comment by tanukus** [comment]
> @tanukus Did you ever try my method? [#64 (comment)](https://github.com/microsoft/Windows-Containers/issues/64#issuecomment-1059865508) This works very well for us and seems to be requiring much less hassle to implement

@artisticcheese  The issue is with handling the "Embedded" Fonts in the documents (PDF) and not the type of font itself.

**Comment by artisticcheese** [comment]
> > @tanukus Did you ever try my method? [#64 (comment)](https://github.com/microsoft/Windows-Containers/issues/64#issuecomment-1059865508) This works very well for us and seems to be requiring much less hassle to implement
> 
> @artisticcheese The issue is with handling the "Embedded" Fonts in the documents (PDF) and not the type of font itself.

Are not those coming from OS fonts? We had the same issue and it was fixed with fonts being uploaded into OS.
