### ISSUE TITLE
[feature]gMSA v2 support on Windows AKS-HCI

### ISSUE THREAD

**Issue by msjingli** [microsoft/Windows-Containers#65]
Current version of gMSA will require the nodes to be in a domain. gMSAv2 is not required domain joined.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by msjingli** [comment]
This feature is completed. Public documentation is available at https://docs.microsoft.com/en-us/azure-stack/aks-hci/prepare-windows-nodes-gmsa.
