### ISSUE TITLE
Verify Privileged container access volumes/disks on host

### ISSUE THREAD

**Issue by jingxu97** [microsoft/Windows-Containers#67]
Can privileged container allows accessing volumes/disks on hosts from inside the container?
CSI storage driver need to run Get-Disk/Get-Volumes/Format-disk to perform storage related operations on host's disks/volumes etc.

**Comment by jingxu97** [comment]
cc @immuzz @marosset

**Comment by immuzz** [comment]
cc : @ambguo

**Comment by dcantah** [comment]
@jingxu97 Yes, anything a normal process on the host can do a privileged container will be able to do. If the host has powershell and access to these cmdlets then the answers yes.

**Comment by immuzz** [comment]
@jingxu97 I hope that answers your question. Let us know if you have any follow-up questions.
