### ISSUE TITLE
Envoy Proxy Support for Windows

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#71]
Expecting envoy proxy to work with Windows Containers

**Comment by daschott** [comment]
The alpha for this has been released:
https://docs.google.com/document/d/1-sj_LSX93MXPbZpbV8TYc_WgpdHhd4LvrceVx2vDrMg/edit#

See EnvoyCon 2020 presentation where this was presented: 
https://youtu.be/f3DezuydHr4
