### ISSUE TITLE
Telemetry fwding of Windows Events

### ISSUE THREAD

**Issue by Lukeout** [microsoft/Windows-Containers#74]
Geneva customers have been using a custom made shim to fwd events. We'd like to deprecate this shim to use native Windows container capabilities. These include, 

Forwarding of ETW formats to logs (eventsource, tracelogging, 1DS/IFx)
Direct forwarding of custom metrics from IFx\1DS
Forwarding of performance counters from in-container to agent (on host)

Please reach out to luki to discuss more.

**Comment by vrapolinario** [comment]
Have you looked into our Log Monitoring tool? https://techcommunity.microsoft.com/t5/containers/windows-containers-log-monitor-opensource-release/ba-p/973947

This is the current solution for this issue. Please let us know if the tool doesn't meet your requirements.
