### ISSUE TITLE
Support ipv6

### ISSUE THREAD

**Issue by Hvid** [microsoft/Windows-Containers#75]
Please add support for ipv6.

**Comment by mkostersitz** [comment]
IPv6 support for L2Bridge networks has been implemented in the latest Semi Annual Channel release and is backported to Windows Server 1809 as part of the October 10C release.

We are working Overlay network support in 2021 and will post progress here as part of the Roadmap work.
We are tracking this in issue: https://github.com/microsoft/Windows-Containers/issues/82

**Comment by Hvid** [comment]
What about nat networks?

**Comment by mkostersitz** [comment]
NAT networks will be tackled at a later point in time. The primary customer asks are around L2Bridge and Overlay network

**Comment by PraveenAnaparthi** [comment]
Any latest update on NAT networks?

**Comment by rawahars** [comment]
@mkostersitz @daschott  The [public documents](https://learn.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture#unsupported-features-and-network-options) state that Windows containers attached to L2Bridge on Windows Server 2022 onwards support IPv6 stack. 

However your comment on this thread mentions that the changes were backported into Windows Server 2019. Can you please confirm if IPv6 is supported in Windows Server 2019?
