### ISSUE TITLE
Provide a link to this repo from the Windows repositories on Docker Hub

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/Windows-Containers#76]
I would expect a link to this GH repo within the feedback section of the Windows repositories on Docker Hub (e.g. https://hub.docker.com/_/microsoft-windows-servercore).  This will provide users with another way to provide suggestions on improving the Windows container experience along with reporting issues, etc.

**Comment by 2212Emmanuel** [comment]
this needs to be closed

**Comment by MichaelSimons** [comment]
> this needs to be closed

@2212Emmanuel - Do you intend to fix this or simply close it?

**Comment by 2212Emmanuel** [comment]
> > this needs to be closed
> 
> @2212Emmanuel - Do you intend to fix this or simply close it?

It's been fixed

**Comment by MichaelSimons** [comment]
The `Feedback` section is confusing.  

> Feedback
> Please direct all feedback to our forum.
> 
> Suggestions on improving Windows Containers or issues can also be raised at the repo.

The first sentence says to direct all feedback to the forums yet the second sentence indicates suggestions and issues can be raised at a GH repo.  When I go to the forum there is a banner at the top indicating its closed - `This forum is closed. Thank you for your contributions.`

How about something like the following?

# Feedback
* [File an issue](https://github.com/microsoft/Windows-Containers/issues)
* [Contact Microsoft Support](https://support.microsoft.com/contactus/)

**Comment by mthalman** [comment]
Another thing to consider is enabling [discussions](https://docs.github.com/en/discussions/quickstart) for this repo to make it an appropriate destination for general questions (as opposed to issues).

**Comment by vrapolinario** [comment]
We added a link to this repo on the Docker Hub description for the Windows images.

**Comment by MichaelSimons** [comment]
@vrapolinario, did you see my previous response (https://github.com/microsoft/Windows-Containers/issues/76#issuecomment-805935948)?  Surely we can do better.

**Comment by vrapolinario** [comment]
Thanks for pointing it out and apologies for missing that response. I'll ask the team to update that as well.

**Comment by MichaelSimons** [comment]
From a public visibility perspective can this issue be re-opened or would you like me to log a new issue to correct this?

**Comment by vrapolinario** [comment]
Sure. Thanks for the note.
@2212Emmanuel is currently on point for this.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@2212Emmanuel, please provide an update or close this issue.

**Comment by cwilhit** [comment]
Closing as this has been addressed.
