### ISSUE TITLE
Windows Server Container - mcr.microsoft.com/windows should have been a Server OS Container

### ISSUE THREAD

**Issue by Josefczak** [microsoft/Windows-Containers#77]
Who needs container technology if not for server purpose?
As these base images run also on Windows 10 Hosts, the term Windows Server Container implies, that the container itself is Windows Server and not the host where it can run.

Please fix the mcr.microsoft.com/windows image to be and behave like a Windows Server!

https://docs.microsoft.com/en-us/virtualization/windowscontainers/images-eula
states, 

DEFINITIONS
Windows Server Container (without Hyper-V isolation) is a feature of Microsoft Windows Server software.

Windows Server Container with Hyper-V isolation. Section 2(k) of the Microsoft Windows Server license terms is hereby deleted in its entirety and replaced with the revised terms as shown in “UPDATED” below.

UPDATED: Windows Server Container with Hyper-V isolation (formerly known as Hyper-V Container) is a container technology in Windows Server which utilizes a virtual operating system environment to host one or more Windows Server Container(s). Each Hyper-V isolation instance used to host one or more Windows Server Container(s) is considered one virtual operating system environment.

**Comment by vrapolinario** [comment]
Thanks for opening this issue @Josefczak. Can you please clarify which functionality you think is missing? Is it related to #58 ?

**Comment by Josefczak** [comment]
> Thanks for opening this issue @Josefczak. Can you please clarify which functionality you think is missing? Is it related to #58 ?

It is related to limitations imposed on mcr.microsoft.com/windows because it is seen as Windows 10 OS, a Home Edition not to be used for server purposes. 
Like: #73 
If there is really someone in need of a Home Edition OS, you should introduce a new image, which is server and LTSC.
Proposal: mcr.microsoft.com/windows/server:2019ltsc

**Comment by vrapolinario** [comment]
Update: The specific issue with the customer has been solved with a workaround. We'll be closing this issue for now and will update the Windows Container community once a more definitive solution is achieved.
