### ISSUE TITLE
When enabling DSR mode in Kubernetes kube-proxy, policies end up in degraded state on cleanup

### ISSUE THREAD

**Issue by daschott** [microsoft/Windows-Containers#79]
There is an active issue such that when DSR load balancing is used and the network is deleted before load balancing policyList is deleted, the policies can end up in degraded state.

It is always recommended to clean up the policies first:
```
Stop kube-proxy
Get-HNSPolicyList | Remove-HNSPolicyList
Proceed to delete network
```
This issue will be resolved in a future cumulative update. The proposed fix is currently undergoing validation.

**Comment by daschott** [comment]
The fix for this issue is planned to ship with the May cumulative update.

**Comment by vrapolinario** [comment]
@daschott any updates on this?

**Comment by daschott** [comment]
We are waiting for May cumulative update

**Comment by daschott** [comment]
https://support.microsoft.com/en-us/topic/may-11-2021-kb5003171-os-build-17763-1935-3f03e74b-4759-4ca3-b9f1-4bc0d5ab5d27 has been released and includes the fix.
