### ISSUE TITLE
Allow VMswitch Apis to be install without the hypervisor

### ISSUE THREAD

**Issue by perithompson** [microsoft/Windows-Containers#80]
Windows containers running with Process isolation do not require the hypervisor to be installed in order to run however certain CNI plugins require vmswitch functionality.  The vmswitch also doesn't need the hypervisor for process isolated Containers but all the Windows Roles and Features that install vmswitch also install the hypervisor and the Containers feature does not install the vmswitch.  

Can we add the ability to install VMSwitch functionality either separately or as part of the containers feature?  This would allow windows containers to be installed on systems that don't support nested virtualisation.

**Comment by jsturtevant** [comment]
A long thread in sig-windows on the confusion and requirements here: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1607619445072100

**Comment by mkostersitz** [comment]
This currently under consideration for a future release. I am adding this to the backlog

**Comment by mkostersitz** [comment]
This is still under consideration for a future release. If you have a requirement/use case for this please DM me on GitHub or email me mikek (at) microsoft (dot) com

**Comment by daschott** [comment]
It seems like it might be possible to install the switch without the hypervisor today – you’d want to enable the Microsoft-Hyper-V-Services feature (all of Hyper-V except the hypervisor) on client editions (e.g. Windows 10): 
```
dism /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V-Services /FeatureName:Microsoft-Hyper-V-Management-PowerShell /FeatureName:Containers /All /NoRestart
dism /Online /Disable-Feature /FeatureName:Microsoft-Hyper-V-Hypervisor
```
or the Microsoft-Hyper-V-Offline feature (just enough Hyper-V to create offline VMs) on server editions:
```
dism /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V-Offline /FeatureName:Microsoft-Hyper-V-Management-PowerShell /FeatureName:Containers /All /NoRestart
dism /Online /Disable-Feature /FeatureName:Microsoft-Hyper-V-Online
```

The second command turns off a feature inadvertently turned on by the first command, and you need to run them both to make sure you don’t end up with the hypervisor enabled.
@perithompson does this help?

**Comment by perithompson** [comment]
Thanks, @daschott I think we found this before and started using it in image builder however when provisioning machines on environments where hypervisors are not supported it would be preferable to have an option to use the PowerShell cmdlets when only the containers feature is used, something like

``` Powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-VirtualSwitch
```
or something like that as it has much wider support for provisioning tools such as ansible to check whether various windows features are installed rather than handling dism commands.

**Comment by vrapolinario** [comment]
Is there an update on this?

**Comment by immuzz** [comment]
@daschott Do we have any plans for this?

**Comment by daschott** [comment]
This is not on our roadmap for Server 2022, but we are discussing available options with Hyper-V team and tracking this in backlog.

**Comment by daschott** [comment]
@perithompson have you tried checking installed features using:
`dism /online /Get-Features` 

We are not fully understanding the core issue here since it is possible to run such dism commands from within PowerShell. Can you describe in more detail why it is not possible to use `dism` from Ansible? Is this issue blocking your efforts?

**Comment by Keith-Mange** [comment]
Enable-WindowsOptionalFeature and Disable-WindowsOptionalFeature can be used instead of DISM.

**Comment by AbelHu** [comment]
@perithompson do you know which VMSwitch Apis are used? We tested it in AKS without installing hyper-v but do not see any issue.
