### ISSUE TITLE
[Networking] [Enhancement] Modify L2Bridge network mode idle timeout value

### ISSUE THREAD

**Issue by DeletorDev** [microsoft/Windows-Containers#81]
Currently, in 'L2Bridge' network mode for containers, the  4-minute idle timeout is the default value and is not configurable, these ephemeral ports are released back to the port pool after a 4-minute idle timeout.

**Situation:** We have an app with an open connection to Oracle and retrieve information every 3 minutes, the app connect to the DB, retrieve data and wait for 3 minutes to retrieve data again.

**Issue:** When the app try to retrieve the data from an Oracle DB in a third iteration the connection failed because was marked as dead.

**Log Trace:**
_"Start: 10/27/2020 7:48:42 PM

Create logging structure on share
Return Code: 0
Welcome

Create Connection
10/27/2020 19:48:45.427
Selecting ...
  leRetCd: 0
Returning SYIN_PARENT_INST: 1763705
Exec netstat ...

Active Connections
Proto  Local Address          Foreign Address        State
TCP    xx.xxx.xxx.xx:49178    xx.xx.xx.xxx:1521      ESTABLISHED
Going to sleep for 3 minutes ...
Exec netstat before re-select ...

Active Connections
Proto  Local Address          Foreign Address        State
TCP    xx.xxx.xxx.xx:49178    xx.xx.xx.xxx:1521      ESTABLISHED
Resetting Record ...
Selecting ...
  leRetCd: 0
Exec netstat after re-select ...

Active Connections
Proto  Local Address          Foreign Address        State
TCP    xx.xxx.xxx.xx:49178    xx.xx.xx.xxx:1521      ESTABLISHED
Resetting Record ...
Selecting ...
  leRetCd: 8
Connection OCInfo: 
Connection: 
Connection: ORA-03113: end-of-file on communication channel
Process ID: 9177
Session ID: 515 Serial number: 47455

Connection: SQLExecute() - Failed to execute OCIStmtExecute() successfully.
SqlApiErrMsg: SQLExec() - General Error Returned.
ConnectionErrMsg: SQLExecute() - Failed to execute OCIStmtExecute() successfully.
Exec netstat after re-select ...

Terminated with Exit Code = 8
End: 10/27/2020 7:58:34 PM
Total time: 00:09:52"_

This issue can be resolved just by increasing the idle timeout value for L2Bridge network mode, but in the current AKS Windows version that is not possible.

We want to be able to modify the value using a flag parameter as --idle-timeout-network-mode.

Cesar Sanchez Pacheco
cesanchezp@gmail.com

**Comment by DeletorDev** [comment]
Please add the “networking” and “enhancement” label to this issue.

**Comment by daschott** [comment]
We have been considering to provide Ttl as a configurable value, but that is work for future.
We have asked for additional information over e-mail.

**Comment by daschott** [comment]
@DeletorDev IIRC, this was confirmed as not urgently needed. We are still hoping to add this in the future and will update this issue accordingly. 

If anyone else needs this setting be configurable, please upvote this issue.

**Comment by vrapolinario** [comment]
Any updates on this. Otherwise we'll go ahead and close it.
