### ISSUE TITLE
IPv4/IPv6 Dual-stack support for Overlay Networking in Kubernetes

### ISSUE THREAD

**Issue by mkostersitz** [microsoft/Windows-Containers#82]
We have implemented IPv6 support for L2Bridge networks. This issue is to track the Overlay network support in the roadmap.

**Comment by mkostersitz** [comment]
Re-assigning to @daschott as I am not working on this anymore

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by daschott** [comment]
This is available on build 22410 and above.

[Windows Server Insider Preview 22518](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver) has been released and contains IPv6 support for overlay

**Comment by wenyingd** [comment]
@daschott @mkostersitz Does Windows HNS Transparent supporting IPv6?

**Comment by wenyingd** [comment]
@daschott I tried the latest Windows Server build 25075 with l2bridge driver for IPv6 network using hcsshim v0.8.24, but I got an error `The network does not have a subnet for this endpoint.` . Could you help give some samples on how to create HNS network with IPv6 subnets?

I also tried `transparent` driver with IPv6 subnet, and I could create network, but I failed to create HnsEndpoint with the same error. Could you help give some suggestions?

**Comment by daschott** [comment]
The title of this is misleading, as the feature which landed here was actually IPv4/IPv6 dual-stack support, not support for IPv6 only. Both IPv4 and IPv6 addresses need to be set to use this feature. 

I followed up with my team on samples to share, but am waiting to hear back.

**Comment by jterry75** [comment]
@daschott - Did you ever get the samples here? Would like to better understand how to do the dual-stack setup. To confirm you are saying this is supported for both l2bridge and transparent on 2019 and 2022 correct?

**Comment by gattytto** [comment]
hello I can't get a l2bridge with ipv6 only to work on windows server 2022, is there any update on this? I could use some HNS example
