### ISSUE TITLE
Fix disconnect between Microsoft and Mirantis about the right way to install Docker on Windows Server

### ISSUE THREAD

**Issue by tfenster** [microsoft/Windows-Containers#84]
While the Microsoft documentation ([Prep Windows operating system containers | Microsoft Docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server)) indicates that a OneGet PowerShell provider is the right way to install Docker on Windows Server, the Mirantis documentation ([Mirantis Documentation: Install Mirantis Container Runtime on Windows Servers](https://docs.mirantis.com/docker-enterprise/v3.1/dockeree-products/mcr/mcr-windows.html)) references their own scripts. When I tested this the last time, the OneGet provider gave me Docker EE 19.03.14 and the Mirantis Script did the same, but also installed containerd 1.3.9. The [previous iteration of the Mirantis documentation](https://docs.mirantis.com/docker-enterprise/v3.0/dockeree-products/mcr/windows.html) had the same description as in the current Microsoft documentation, so this seems to be a conscious change. What is the right way to install Docker on Windows Server?

**Comment by weijuans-msft** [comment]
Tobias - Thanks for bringing that up. This should be a non-issue. The Microsoft one is still the right PowerShell provider for Windows Server customers and should work fine. If it doesn't, please report issues to us.

**Comment by tfenster** [comment]
@weijuans-msft another symptom of the not ideal documentation around installing Docker on Windows Server: https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1191. There seem to be Microsoft links pointing to (dead) Mirantis pages. Even if it wasn't dead, that page would say something different from other Microsoft docs

**Comment by weijuans-msft** [comment]
I'll close this one. For MicrosoftDocs/Virtualization-Documentation-Private#1191, I did talk to our friends at Mirantis. I will check with them again and address on that thread.
