### ISSUE TITLE
Shared disks for Azure VMs can't be used from containers in hyperv isolation

### ISSUE THREAD

**Issue by tfenster** [microsoft/Windows-Containers#85]
We are trying to use shared disks for Azure VMs and followed the instructions here https://techcommunity.microsoft.com/t5/failover-clustering/container-storage-support-with-cluster-shared-volumes-csv/ba-p/372140 to set them up. When we use them from process isolated containers, it works fine, so this comes up correctly:

```
docker service create --mount type=bind,src=C:\ClusterStorage\Volume1\249715c31f85\,dst=C:\data mcr.microsoft.com/windows/nanoserver:1809 ping -t 127.0.0.1
```

If we try them same with hyperv isolation we get the following error:

```
docker service create --isolation=hyperv --mount type=bind,src=C:\ClusterStorage\Volume1\249715c31f85\,dst=C:\data mcr.microsoft.com/windows/nanoserver:1809 ping -t 127.0.0.1
...
hcsshim::CreateComputeSystem 0ac1262a583e97022b0fb02ad2ae473b4f4e7a6e8df88264e002d2249a7c336e: More data is available. (extra info: {"SystemType":"Container","Name":"0ac1262a583e97022b0fb02ad2ae473b4f4e7a6e8df88264e002d2249a7c336e","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"F:\\dockerdata\\windowsfilter\\0ac1262a583e97022b0fb02ad2ae473b4f4e7a6e8df88264e002d2249a7c336e","Layers":[{"ID":"fb75a699-7695-5c66-91e5-bdd716a033f3","Path":"F:\\dockerdata\\windowsfilter\\6a3862a401c067c8409c662acacedc1f4074691c7608bd0d112d39e9e17b38ab"}],"HostName":"0ac1262a583e","MappedDirectories":[{"HostPath":"C:\\ClusterStorage\\Volume1\\249715c31f85","ContainerPath":"C:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["FD122255-ED8D-4E46-A50D-2E29A094BF25"],"HvRuntime":{"ImagePath":"F:\\dockerdata\\windowsfilter\\6a3862a401c067c8409c662acacedc1f4074691c7608bd0d112d39e9e17b38ab\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
```

The result is the same on both Windows Server 2019 (1809) and Windows Server 2019 (2004). We also tried to set the permissions as open as possible for testing, but that didn't help

```
Invoke-Expression "icacls.exe $($driveLetter):\ /grant 'Everyone:(OI)(CI)(F)'"
```

**Comment by tfenster** [comment]
@vrapolinario Does this mean that this is accepted as bug?

**Comment by vrapolinario** [comment]
Apologies for not replying earlier when I trigged this issue.
I'm contacting the appropriate teams internally and checking with them. I'm not sure at this point if this is a bug or if this is just not a supported scenario. We'll update soon.

**Comment by vrapolinario** [comment]
Hi @tfenster, sorry for the delay on this. Can you please confirm this issue still repro with the latest update?
We had a similar bug fixed and wanted to ensure this is still happening before I go back to the devs on it.
Thanks!

**Comment by tfenster** [comment]
@lippertmarkus do you still have a repo?

**Comment by lippertmarkus** [comment]
@vrapolinario @tfenster tried again but now I can't even create a default container with process isolation and a volume on the shared disk. Tried to set the permissions for the shared disk/directory as open as possible but that didn't help:

```
PS C:\> docker run -v C:\ClusterStorage\Volume1\test1:C:\data  --rm -it --user ContainerAdministrator mcr.microsoft.com/windows/nanoserver:2004 ping -t 127.0.0.1
docker: Error response from daemon: hcsshim::CreateComputeSystem 81ca314552eebbc1f7b58137ffbe8af3eaa3f3f0c5f8678242046911b133da4b: The system cannot find the path specified.
(extra info: {"SystemType":"Container","Name":"81ca314552eebbc1f7b58137ffbe8af3eaa3f3f0c5f8678242046911b133da4b","Owner":"docker","VolumePath":"\\\\?\\Volume{f4e977ec-6ee4-4407-9da4-b5156b639f1f}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\81ca314552eebbc1f7b58137ffbe8af3eaa3f3f0c5f8678242046911b133da4b","Layers":[{"ID":"0a8544ea-fbd1-5c13-9a8f-cbd88af3449f","Path":"C:\\ProgramData\\docker\\windowsfilter\\ed2dbb96ecf730bd2e9b4974c907e287b185e516ee901382897d75a25c8e075f"}],"HostName":"81ca314552ee","MappedDirectories":[{"HostPath":"c:\\clusterstorage\\volume1\\test1","ContainerPath":"c:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["30bc6084-c113-4f7b-84a0-bde12f961aee"],"AllowUnqualifiedDNSQuery":true}).
```

**Comment by immuzz** [comment]
To confirm that this is indeed an issue with a drive letter, can you assign a drive letter to the CSV volume using mountvol and attempt to start container using that drive letter?

**Comment by lippertmarkus** [comment]
When assigning a drive letter to the CSV it works with process isolation but only partly with hyperv isolation:
```
PS C:\> mountvol "Z:" "\\?\Volume{33b99261-3cff-4e42-af84-7722c711a562}\"

# process - root path - works
PS C:\> docker run -v Z:\:C:\data  --rm -it --isolation process mcr.microsoft.com/windows/nanoserver:2004 ping -t 127.0.0.1

# process - subdir - works
PS C:\> docker run -v Z:\test1:C:\data  --rm -it --isolation process mcr.microsoft.com/windows/nanoserver:2004 ping -t 127.0.0.1

# hyperv - root path - works
PS C:\> docker run -v Z:\:C:\data  --rm -it --isolation hyperv mcr.microsoft.com/windows/nanoserver:2004 ping -t 127.0.0.1

# hyperv - subdir - doesn't work
PS C:\>  docker run -v Z:\test1:C:\data  --rm -it --isolation hyperv mcr.microsoft.com/windows/nanoserver:2004 ping -t 127.0.0.1      
docker: Error response from daemon: hcsshim::CreateComputeSystem 45aa6e2381ad6fec16b98631ec52a2168e0c76e4e579d7a2d259b5a04833318e: More data is available.      
 (extra info: {"SystemType":"Container","Name":"45aa6e2381ad6fec16b98631ec52a2168e0c76e4e579d7a2d259b5a04833318e","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\45aa6e2381ad6fec16b98631ec52a2168e0c76e4e579d7a2d259b5a04833318e","Layers":[{"ID":"0a8544ea-fbd1-5c13-9a8f-cbd88af3449f","Path":"C:\\ProgramData\\docker\\windowsfilter\\ed2dbb96ecf730bd2e9b4974c907e287b185e516ee901382897d75a25c8e075f"}],"HostName":"45aa6e2381ad","MappedDirectories":[{"HostPath":"z:\\test1","ContainerPath":"c:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["f6d4cb3a-535e-4f63-aec9-d927611dce59"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\ed2dbb96ecf730bd2e9b4974c907e287b185e516ee901382897d75a25c8e075f\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
```

**Comment by thecloudtaylor** [comment]
Cluster shared volumes are only supported for specific workload types, including Hyper-V virtual machines and Scale-Out File Servers [(Use Cluster Shared Volumes in a failover cluster | Microsoft Docs)](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs). While CSV may function for other applications including process isolated containers it is not a scenario we have designed for, regularly validate, or have integrated with container orchestrators/clustering – as such it is not recommended/supported for production environments at this time. I did submit a change to our documentation [(Clarifying support on cluster shared volumes (CSV))](https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1618) to better clarify this support.

We recommend customers use persistent volumes in Kubernetes for an orchestrated and fully supported experience (https://docs.microsoft.com/en-us/azure-stack/aks-hci/persistent-volume).

**Comment by tfenster** [comment]
@thecloudtaylor that means that there is no supported way to have shared storage across Windows hosts for process isolated workloads outside of AKS? Or am I missing an option?

**Comment by thecloudtaylor** [comment]
@tfenster - SMB would be an out of the box option (that's likely what I would use). You could also imagine doing something like what K8 block PVs do in mounting the storage to the node running the container but that would require some doing. If I recall swarm does have hooks for such things but it's been a while since I looked at that code.

**Comment by tfenster** [comment]
@thecloudtaylor thanks for the feedback. We indeed initially looked at SMB but as we want to run SQL databases on it, we had concerns about performance. Would you expect that to work?

**Comment by thecloudtaylor** [comment]
@tfenster - I think it would depend on the configuration and of course the load but the same could be said about managed disks... You might benefit from adding an additional NIC to the hosts for the storage path, this might also be good from a network isolation perspective.

**Comment by tfenster** [comment]
Interesting idea, will give that a try. Thanks!
