### ISSUE TITLE
I can not use a web app core with Windows container support. It works with Linux Container

### ISSUE THREAD

**Issue by RafaelLiendo2409** [microsoft/Windows-Containers#86]
I am trying to run a demo following the instructions from this page:
https://docs.microsoft.com/en-us/visualstudio/containers/hosting-web-apps-in-docker?view=vs-2019&viewFallbackFrom=aspnetcore-5.0

I ran the image in my local machine and worked fine, but when I am trying to publish it to Azure, I got:

Gravedad Código Descripción Proyecto Archivo Línea Estado suprimido
Error No se pudo ejecutar el comando de Docker. Código de salida: 1.
The command 'cmd /S /C dotnet restore "DockerAppPrueba/DockerAppPrueba.csproj"' returned a non-zero code: 1 DockerAppPrueba C:\Users\usuario\source\repos\DockerAppPrueba\DockerAppPrueba\Dockerfile 0

This is my docker file:

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["DockerAppPrueba/DockerAppPrueba.csproj", "DockerAppPrueba/"]
RUN dotnet restore "DockerAppPrueba/DockerAppPrueba.csproj"
COPY . .
WORKDIR "/src/DockerAppPrueba"
RUN dotnet build "DockerAppPrueba.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DockerAppPrueba.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DockerAppPrueba.dll"]

This is the publication:

![image](https://user-images.githubusercontent.com/44041077/104968631-ffc03b80-59ab-11eb-947a-dc9559178a12.png)

I am using this versión of Visual Studio 2019. I am create a new default web core app with Windows Container support

![image](https://user-images.githubusercontent.com/44041077/104968710-372ee800-59ac-11eb-9d0f-415d63b8557d.png)

**Comment by vrapolinario** [comment]
When using App Service, you need to use a Windows Server 2019 (or 2016) container image. Since you're using a SAC release (1903) this will fail. We'll close this for now as this is related to Azure App Service.
