### ISSUE TITLE
Question: Support for docker checkpoint on Windows?

### ISSUE THREAD

**Issue by tfenster** [microsoft/Windows-Containers#88]
With support for checkpoint / restore seemingly on the way for K8s (https://github.com/kubernetes/kubernetes/pull/97689 and https://github.com/kubernetes/kubernetes/issues/3949#issuecomment-749936235), I am wondering whether there is anything planned for Windows as well? As far as I can see, the work is restricted to Linux until now?

**Comment by vrapolinario** [comment]
Assigning it to Muzz to see if it makes sense from the Windows on K8s (Sig-Windows?) standpoint.

**Comment by immuzz** [comment]
@marosset @jsturtevant Do you guy know about this?

**Comment by marosset** [comment]
I'm not aware of anyone planning on this support for Windows (mostly due to lack of developer resources not because it isn't a good idea)

**Comment by immuzz** [comment]
@tfenster Could you please open this ticket under Kubernetes/Kubernetes https://github.com/kubernetes/kubernetes/issues and tag with SIG-Windows so we can review this with K8s community? I'm closing this here as this needs to happen in K8s repo

**Comment by tfenster** [comment]
@immuzz done
