### ISSUE TITLE
WAC-Make Windows Admin Center as a container

### ISSUE THREAD

**Issue by vrapolinario** [microsoft/Windows-Containers#9]
Request from user from User Voice: https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/32408029--deployment-container-containerize

Make Honolulu available as a container image. This would be helpful for creation on semi-annual servers.

**Comment by tbprince** [comment]
By the way, attempted to containerize WAC on a Windows Container. It mostly worked though the Powershell tool doesn't work at all. Not sure why.

https://www.theserverside.technology/2019/11/02/how-to-containerize-windows-admin-center/

**Comment by vrapolinario** [comment]
We are continuing to evaluate this request. We'd love to hear more details on what are the needs for WAC as a container.

**Comment by immuzz** [comment]
We are continuing to look into this.

**Comment by vrapolinario** [comment]
Sorry for not making any comments on this.
This is still planned and we're working currently working on prioritization.
More to come soon.

**Comment by noendscripting** [comment]
Using WAC as a container in a public clouds would allow relatively simple and and inexpensive way of securing access to VMs by removing the need for public Ip addresses and port open. Very helpful for Devtest labs where cost is a consideration.
You are also very likely to see increased usage in Azure as it would allow to work around limitations of the Azure bastion and likely to become a best-practice recommendation to deploy in a production hub\spoke subscription\vNET scenarios

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@vrapolinario, @immuzz, please provide an update or close this issue.

**Comment by vrapolinario** [comment]
This is still a scenario we're evaluating. However, we don't have an update or timeline at this point.
I'll close this for now, but please rest assured that we're looking into this issue.

**Comment by Sporesirius** [comment]
Do we have a status update on this?
It would be cool if MS could build first party images for MS tools/services.
