### ISSUE TITLE
Windows Server 2019 - Network issues

### ISSUE THREAD

**Issue by JoseIgnacioD** [microsoft/Windows-Containers#90]
I'm building a Windows image, and I'm trying to install chocolatey. However in the install step for Chocolatey I am getting a download timeout trying to run the command.
Here the Dockerfile, trying to install chocolatey with powershell.

**_FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-20210112-windowsservercore-ltsc2019
SHELL ["powershell", "-Command"]
RUN New-Item -ItemType directory -Path $Env:SOME_USER_HOME; \
    $ErrorActionPreference = 'Stop';
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Set-ExecutionPolicy Bypass -Scope Process -Force; \
    $env:chocolateyUseWindowsCompression = 'true'; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))_**

The error:
**_Exception calling "DownloadString" with "1" argument(s): "The operation has timed out" At line:1 char:179 + ... n = 'true'; iex((New-ObjectSystem.Net.WebClient).DownloadString('ht.._**

Then I tried to install chocolatey using Nuget CLI
_**RUN nuget install chocolatey**_

But I received a similiar error.
**_Unable to load the service index for source https://api.nuget.org/v3/index.json.
The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms._**

I did the following tests:
1) I can install chocolatey using both methods in the server, outside the container
2) I can ping chocolatey.org without issue within the Docker container.

**Comment by vrapolinario** [comment]
I'm not sure about the network timeout error message, but for Chocolatey, have you tried this:
PS C:\> Install-PackageProvider -Name Chocolatey -force

Name                           Version          Source           Summary
----                           -------          ------           -------
chocolatey                     2.8.5.130        https://onege... ChocolateyPrototype provider for the OneGet meta-package manager

PS C:\> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSaveMode, FilterOnTag, Contains, AllowPrerelea...
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, Confi...
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, ...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

Adding @mkostersitz to check on the timeout issue if he can help...

**Comment by vrapolinario** [comment]
I'll close this issue as we haven't heard back from the user. Will re-open if needed.
