### ISSUE TITLE
Windows Defender Performance issues with Containerd

### ISSUE THREAD

**Issue by perithompson** [microsoft/Windows-Containers#92]
### Observerd
When running Containerd on windows 2019, Windows defender massively decreases container extraction and during the first full of the base windows ltsc2019 image spikes CPU load to ~30-40% when extracting the image.

**With Windows defender**
![image](https://user-images.githubusercontent.com/11655452/106914939-69a34980-66fd-11eb-8181-1be35c1f4091.png)

**During the extraction of the image**
![image](https://user-images.githubusercontent.com/11655452/106914968-6f992a80-66fd-11eb-99f5-e0a12d47ef1d.png)

**After disabling windows defender realtime monitoring**
![image](https://user-images.githubusercontent.com/11655452/106914803-47a9c700-66fd-11eb-9d59-ec0a21d4bcb2.png)

### Version information
Windows Server 2019 LTSC
Containerd 1.4.3

### Server Info
4 CPU
8GB RAM

### Reproduction Steps
``` powershell
#On a fresh windows install
Measure-Command -Expression {ctr images pull mcr.microsoft.com/windows/servercore:ltsc2019}

# Disable windows defender realtime monitoring
Set-MpPreference -DisableRealtimeMonitoring $true

# Clear image
ctr images rm mcr.microsoft.com/windows/servercore:ltsc2019

# Re-pull image 
Measure-Command -Expression {ctr images pull mcr.microsoft.com/windows/servercore:ltsc2019}
```

**Comment by perithompson** [comment]
@immuzz this is the issue discussed in the SIG-Windows weekly call

**Comment by perithompson** [comment]
https://github.com/containerd/containerd/issues/4989 seems to be related to this issue

**Comment by immuzz** [comment]
Thank you @perithompson. Let me ask the Defender team to take a look so we can narrow down what is causing it and which layer it needs to get fixed.

**Comment by immuzz** [comment]
Following up with Defender Team as they were investigating this.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.

**Comment by immuzz** [comment]
@perithompson are you still able to reproduce this issue? Sorry about the delay on this one

**Comment by perithompson** [comment]
I havent tried as we add the exceptions now, the exceptions certainly work although I feel it would be better if we didn't have to exclude them from AV checks?

**Comment by jsturtevant** [comment]
The issue identified here was scanning done by Defender.  The performance is improved if you exclude the containerd process:

```
Add-MpPreference -ExclusionProcess "$Env:ProgramFiles\containerd\containerd.exe"
```

If anyone is still seeing issues after this exclusion, please add details to this issue.

**Comment by perithompson** [comment]
Im not having issues but i think there was someone else who said the pull performance wasn't as good as docker, though I haven't got any numbers on that and it certainly hasn't been out of bounds for me

**Comment by singholt** [comment]
Some numbers based on my testing:
Runtime | Image | Instance Type | Defender on | Exclusion Path (ProgramFiles\containerd and ProgramData\containerd) | Exclusion Process (containerd.exe, ctr.exe) | Exclusion Paths + Exclusion Process | Defender off
-- | -- | -- | -- | -- | -- | -- | --
containerd | Servercore(2.5GiB) | m5.xlarge | 13.2mins | 6.3mins | 3.55mins | 4.15mins | 3.08mins
docker | Servercore(2.5GiB) | m5.xlarge | 6.7mins | - | - | - | 5.02mins

Note: m5.xlarge instances on AWS EC2 have 4 vCPUs and 16 GiB Memory.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.

**Comment by jterry75** [comment]
I just opened #209 without realizing about this. This is for sure still an issue and is 100% repro if you don't exclude the process in defender. We should not have to do that for security reasons. The integrity files should be applied correctly right?

**Comment by cwilhit** [comment]
The Windows Defender team made some changes in Defender's built-in exclusion rules for this scenario. They’re available in signatures 1.361.979.0 and newer, which went out last night. To check what signature version you have, you can go to:

 `Windows Security app -> Virus and Threat Protection -> Virus and Threat Protection Updates -> Check for Updates`

And it will show you the signature version. The latest updates cause Defender to avoid scanning any file opened/modified by containerd.exe (from the standard location that’s ACL-ed for admin only (under programfiles)). If the process is tampered in memory (via code injection, etc) – the exclusion is automatically reverted, and Defender starts scanning everything touched by this process. 

I just tested this on a D2v3 VM (2 vCPUs, 8 GB) in Azure using the latest definitions and saw a pull time for server core container image of 8.8 minutes, which matches the results @perithompson got with the reg key workaround, without needing to set the exclusion manually. 

I am going to close this issue as resolved. @jterry75, the issue you opened (#209 ) is about a slightly different topic (scanning non-base layeres) so let's keep that one open and continue that conversation there.

**Comment by jterry75** [comment]
@cwilhit - Many thank you's!

**Comment by jterry75** [comment]
Hey @cwilhit - We are for sure still seeing this even after taking the latest Defender updates. How is Defender determining this is safe? Is it a certain signature on containerd.exe a path location? Etc. Do we have special requirements here?

**Comment by jterry75** [comment]
Actually I'm sorry this was due to another containerd bug and un related. Its not defender that is causing the delay in this case. There is a bug that was fixed on containerd latest that improves pull perf when activating multiple pods at the same time. So it was because containerd was applying 14 base images at once... Thanks Craig this does work as far as I can tell

**Comment by jterry75** [comment]
Without exclusions:
```
PS C:\Users\Administrator\Desktop> Measure-Command { ctr image pull mcr.microsoft.com/windows/servercore:ltsc2019 }


Days              : 0
Hours             : 0
Minutes           : 4
Seconds           : 19
Milliseconds      : 113
Ticks             : 2591131127
TotalDays         : 0.0029989943599537
TotalHours        : 0.0719758646388889
TotalMinutes      : 4.31855187833333
TotalSeconds      : 259.1131127
TotalMilliseconds : 259113.1127
```

And with exclusions:
```
PS C:\Users\Administrator\Desktop> Measure-Command { ctr image pull mcr.microsoft.com/windows/servercore:ltsc2019 }


Days              : 0
Hours             : 0
Minutes           : 4
Seconds           : 15
Milliseconds      : 180
Ticks             : 2551803761
TotalDays         : 0.00295347657523148
TotalHours        : 0.0708834378055555
TotalMinutes      : 4.25300626833333
TotalSeconds      : 255.1803761
TotalMilliseconds : 255180.3761
```

**Comment by cwilhit** [comment]
Glad to hear it!

**Comment by mloskot** [comment]
In https://github.com/microsoft/Windows-Containers/issues/92#issuecomment-1083591322 @cwilhit wrote:
> If the process is tampered in memory (via code injection, etc) – the exclusion is automatically reverted, and **Defender starts scanning everything touched by this process**.

Would it be possible to expand the "everything touched" part?
What exactly is scanned?
For example, are files within the container run by the containerd scanned too?
