### ISSUE TITLE
[Kubernetes][Feature Request] Windows nodes behind Loadbalancer going OutOfService when the no. of pods is 65 or more

### ISSUE THREAD

**Issue by lalwanin2020** [microsoft/Windows-Containers#93]
**What happened:**
When the number of windows pods in the Kubernetes cluster are scaled to a number of 65 or more, then the Windows nodes behind a classic loadbalancer service are going OutOfService. A kube-proxy error was reported in the logs which is as follows: "E1208 04:52:16.756196 4268 proxier.go:1212] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The parameter is incorrect. (0x57) {"Success":false,"Error":"The parameter is incorrect. Unable to initialize VFP LB rule: invalid number of destinations.","ErrorCode":2147942487}"

**What you expected to happen:**
We expected the windows pods to scale beyond 65 without the Windows nodes behind the loadbalancer reporting their status as OutOfService or nodes becoming unhealthy.

**How to reproduce the issue:**
1. Create an AWS EKS Cluster with Windows support.
2. Scale the number of nodes to a number that supports 66 pods or more.
3. Deploy a sample Windows application with 65 replicas. You will be able to see the issue in the LoadBalancer section.
4. Scaling the number of deployments back to 64 or less, will revert the status of EKS Windows nodes back to InService.

**Anything else we need to know?:**
1. Enabling DSR (Direct Server Return) mode on all the Windows nodes didn't solve the issue.
2. Enabling Jumbo frames on all the Windows nodes didn't solve the issue.

**Environment:**
Kubernetes version: "v1.18.0"
OS: Windows Server 2004 Core

Kubernetes Issue Reference: https://github.com/kubernetes/kubernetes/issues/98680

**Comment by daschott** [comment]
Thanks for raising this issue here. 

Can you outline more details of your use-cases here so we can prioritize accordingly? Is this an urgent blocker for you?

**Comment by lalwanin2020** [comment]
Hi 
It is not an urgent blocker for us or for our customers. We do have a workaround of using multiple load balancers to scale pods in the cluster but it will be nice to have feature for scaling pods of same deployment/application in a k8s cluster behind a single load balancer.

**Comment by mkostersitz** [comment]
@lalwanin2020 thanks for the update. I will add this to our backlog as an improvement.

**Comment by daschott** [comment]
@lalwanin2020 How many pods are you looking to scale up to? Are you looking to scale to 100 pods backing a single service, or a different magnitude? We'd like to understand what would be a better threshold that should be targeted.

**Comment by muro671** [comment]
Tamam anladım

18 Şub 2021 Per 02:12 tarihinde David Schott <notifications@github.com>
şunu yazdı:

**Comment by lalwanin2020** [comment]
Hi @daschott
Thank you for your reply. Our customers want to scale around 100 pod replicas behind a single load balancer service for their applications. So from that, I think 100 or 110 should be good threshold values that should be targeted. 

Also, we wanted to know why 64 is the limit? Can you provide any information surrounding that.

**Comment by nshampur** [comment]
following

**Comment by daschott** [comment]
@lalwanin2020 Thanks for this information. The reason why is embedded in the OS. On Windows, K8s service resource is represented by HNS load balancer object. This is backed by rules in VFP which have a limit of 64 backends.

**Comment by nshampur** [comment]
has the limit been increased in Server 2022? or roadmap to increase it?

**Comment by daschott** [comment]
This is not planned to land in Server 2022. @nshampur would you benefit from this feature? If you need this we would love to hear more feedback and a description of your use-case & scenario. Happy to pass your feedback along to the responsible teams and see if this can get a priority bump.

**Comment by nshampur** [comment]
@daschott - we do run several (mission critical, at scale) services that have over 64 Pods. (~100 Pods on avg.)

**Comment by daschott** [comment]
@nshampur thanks for confirming. I am still waiting to hear back internally at Microsoft to see when this would fit into our roadmap. I will also follow up with you if there are more details needed.

@sbangari @Keith-Mange

**Comment by daschott** [comment]
We have implemented the changes on internal Windows builds but have to do additional stress testing which will take some time. Will circle back once the changes have undergone testing and are available in a public Insider build.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by daschott** [comment]
The feature to increase the number of backend pods for given Kubernetes service from 64 to 1024 has been completed and should be available in [Insider build 22526](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver) and above.

The change is also being serviced to Windows Server 2022 and Windows Server 2019; rough (tentative) ETA to release we are targeting is March 15th cumulative update.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by cwilhit** [comment]
This change is contained in the [most recent Windows Server update](https://support.microsoft.com/en-us/topic/march-22-2022-kb5011551-os-build-17763-2746-preview-690a59cd-059e-40f4-87e8-e9139cc65de4) released yesterday, 3/22/22. Please deploy this new update to resolve this issue and please let us know if you are still having trouble.
