### ISSUE TITLE
Timeout on Input in VMware Guest

### ISSUE THREAD

**Issue by awbeale** [microsoft/Windows-Containers#94]
When Windows server 2019 standard, with Docker enabled, and the latest Mirantis Docker Enterprise Engine installed, within a VMware guest, and the container waits for input on STDIN, and no input is provided, the container will terminate after some number of hours with no indication as to why. This works correctly within HYPER-V VMs  and inside Docker containers executing directly on the host win2k19 Server locally.

When a container waits for an extended time on input from STDIN, and no input is provided (intentionally), eventually, the container fails. We have experienced this anywhere from 15 minutes of elapsed time to 20+ hours of elapsed time. We have duplicated in multiple VMs and have isolated the problem down to a very small test case that requires substantial setup to get all the pieces configured appropriately.

We have attempted to reproduce this on win2k19 Server standard with Docker configured and running the testcase directly from PowerShell and CMD on the Windows host. It does not fail. 

We have attempted to reproduce this on Win2k19 Server Standard, with Hyper-V enabled, running in a Win2k19 Server Standard guest, with nested virtualization enabled, and the guest configured to run docker containers. It does not fail.

Only when Win2k19 Server Standard, with Hyper-V enabled along with nested Virtualization, located within a VMware guest, does failure occur

1.	Inventory List –
VMware vSphere Environment
Win2k19 Standard in a guest VM with Hyper-V enabled and nested virtualization
Within win2k19:
	Symantec Endpoint Protection with Workaround enabled (unclear if contributing or not)
	Docker + Mirantis Enterprise Engine
	Docker Image built as supplied below

2.	Repro Steps -–
I am providing two methods to duplicate this issue. Here are the steps to do so:

1.	Install Windows 2019 Server Standard in a VMWare guest with nested virtualization enabled. 
2.	Enable Hyper-V, containers, and Docker. 
3.	Install the latest Mirantis Docker Enterprise Engine as found at Mirantis Documentation: Install Mirantis Container Runtime on Windows Servers 
4.	Apply all the latest Microsoft updates.
5.	Install Symantec Endpoint Protection and enable the docker workarounds as documented at https://knowledge.broadcom.com/external/article?legacyId=tech246815
Note that while the article is for Win2k16, it also applies to Win2k19.
Also note that I do not know if this contributes to the failure or not, but this software is a requirement for my test environment so uninstalling it is not an option.
6.	Once all installations are complete, set the PowerShell execution policy to AllSigned.

At this point there are two ways to encounter the problem, one  uses a PowerShell script inside a container, the other uses a cmd file inside a container. Both exhibit similar behavior.

For the PowerShell variant:
Build a docker image using the following dockerfile:
FROM mcr.microsoft.com/windows/servercore:1809
WORKDIR c:\\Startup
COPY main.ps1 .
CMD [ "powershell.exe", "-File", "c:\\Startup\\main.ps1"]

The contents of main.ps1 are:
[Console]::WriteLine("Press Enter to continue...")
$a = [Console]::ReadLine()
[Console]::WriteLine("Past Readline. Read $a")
Start-Sleep -Seconds 60

Start the image with the following command from a Powershell prompt:
Docker run -i <image id>
	Note the lack of the t for the terminal option. In our production environment, as we connect using pipes, the -t option is not viable, but the problem still reproduces. Once the message is emitted, DO NOT PRESS ENTER. Just let it sit there. After some amount of time, the container will terminate. 

For the CMD variant:
Build a docker image using the following dockerfile:
FROM mcr.microsoft.com/windows/servercore:1809
WORKDIR c:\\Startup
COPY main.cmd .
CMD [ "cmd", "/C", "c:\\Startup\\main.cmd"]

The contents of main.cmd are:
set /p choice= "Please enter a number"
echo '%choice%'
Once the message is emitted, DO NOT ENTER A NUMBER OR PRESS ENTER. Just let it sit there. After some amount of time, the container will terminate.

**Comment by vrapolinario** [comment]
Hi @awbeale have you contacted VMware support for this issue? As the error seems to happen when running only on the VMware platform, it seems to be the correct route to go to.

**Comment by awbeale** [comment]
I have not contacted VMware. I went to Microsoft support first and they indicated running containers in a VMware guest is not a supported configuration.  Note the following from [https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements] and the lack of using VMware as a hypervisor.

_Virtualized container hosts
If a Windows container host will be run from a Hyper-V virtual machine, and will also be hosting Hyper-V isolation, nested virtualization will need to be enabled. Nested virtualization has the following requirements:

At least 4 GB RAM available for the virtualized Hyper-V host.
Windows Server (Semi-Annual Channel), Windows Server 2019, Windows Server 2016, or Windows 10 on the host system; and Windows Server (Full or Server Core) in the virtual machine.
A processor with Intel VT-x (this feature is currently only available for Intel processors).
The container host VM will also need at least two virtual processors._

Given that Microsoft does not support this configuration, even if VMware does find and issue a fix for it, lack of support would mean we can't offer a solution in that configuration to our clients.  This is unfortunate as a large percentage of our client base are using VMware instead of Hyper-V for their private and public clouds. 

Do you have a different understanding?

**Comment by awbeale** [comment]
I did work with VMware on this issue. I updated the VMware tools to version 11297 (11.1.1), and much to my surprise, the issue appears to be fixed. I have run the failing testcase for days without issue, so I am closing this.
