### ISSUE TITLE
Python / VC redist failing to install on LTSC 2016

### ISSUE THREAD

**Issue by tianon** [microsoft/Windows-Containers#96]
Hi!

I'm not sure the exact details of what's going on here, but I'll lay out what I do know:

- all `ltsc2016` builds of https://github.com/docker-library/python were succeeding three days ago, and started failing yesterday

- https://github.com/docker-library/python/commit/ec67f96b61c55ba35acd6c553f21641c5bf0ccc5 was the only `Dockerfile` change in that period, which only affects one out of three `ltsc2016`-based builds

- digging into the installer logs got us https://github.com/docker-library/python/pull/586#issuecomment-789120070 ("`Error 0x80070005: Failed to get provider key bundle id.`"), which from searching seems to be something from the VC redistributable installer (which I can only assume is embedded inside the Python installer, and shouldn't have changed at all for Python 3.9 and 3.8 -- I verified checksums on the download page on Wayback Machine with https://www.python.org/downloads/release/python-392/ and that I get `efb20aa1b648a2baddd949c142d6eb06` when I MD5 https://www.python.org/ftp/python/3.9.2/python-3.9.2-amd64.exe)

- `mcr.microsoft.com/windows/servercore:ltsc2016` was last updated 4 weeks ago :grimacing:  
  (making me question whether this is even the right place to be debugging this, but hopefully y'all can help us figure that out :heart:)

(I was told to cc @immuzz :sweat_smile: :heart:)

**Comment by vrapolinario** [comment]
Can you please confirm this works on a regular WS2016 VM - that way we can start inspecting if this is a general OS compat issue or a container related issue.

FYI: We do have internal weekly validation with Python, but on the latest image.

**Comment by tianon** [comment]
Unfortunately, I don't have access to a regular WS2016 VM -- anything I can provide from the container perspective to help narrow it down?

**Comment by vrapolinario** [comment]
I think the problem here is that we have internal validation that says it works and the issue you're bringing needs to be investigated/triaged before we say it's a bug on our side. Can you please share the docker file you're using to build this and the steps to repro the issue?

**Comment by tianon** [comment]
Absolutely -- you can see the full source (and logs) in https://github.com/docker-library/python/pull/586, but all of 3.10.0a6, 3.9.2, and 3.8.8 are failing to build.  Here's the exact `Dockerfile` for 3.9.2 (with the adjustment from 586 to get more detail in the build logs):

<details>
<summary>Dockerfile:</summary>

```dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2016

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# https://github.com/docker-library/python/pull/557
ENV PYTHONIOENCODING UTF-8

ENV PYTHON_VERSION 3.9.2
ENV PYTHON_RELEASE 3.9.2

RUN $url = ('https://www.python.org/ftp/python/{0}/python-{1}-amd64.exe' -f $env:PYTHON_RELEASE, $env:PYTHON_VERSION); \
	Write-Host ('Downloading {0} ...' -f $url); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile 'python.exe'; \
	\
	Write-Host 'Installing ...'; \
# https://docs.python.org/3/using/windows.html#installing-without-ui
	$exitCode = (Start-Process python.exe -Wait -NoNewWindow -PassThru \
		-ArgumentList @( \
			'/quiet', \
			'InstallAllUsers=1', \
			'TargetDir=C:\Python', \
			'PrependPath=1', \
			'Shortcuts=0', \
			'Include_doc=0', \
			'Include_pip=0', \
			'Include_test=0' \
		) \
	).ExitCode; \
	if ($exitCode -ne 0) { \
		Write-Host ('Running python installer failed with exit code: {0}' -f $exitCode); \
		Get-ChildItem $env:TEMP | Sort-Object -Descending -Property LastWriteTime | Select-Object -First 1 | Get-Content; \
		exit $exitCode; \
	} \
	\
# the installer updated PATH, so we should refresh our local value
	$env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine); \
	\
	Write-Host 'Verifying install ...'; \
	Write-Host '  python --version'; python --version; \
	\
	Write-Host 'Removing ...'; \
	Remove-Item python.exe -Force; \
	Remove-Item $env:TEMP/Python*.log -Force; \
	\
	Write-Host 'Complete.'

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 21.0.1
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/29f37dbe6b3842ccd52d61816a3044173962ebeb/public/get-pip.py
ENV PYTHON_GET_PIP_SHA256 e03eb8a33d3b441ff484c56a436ff10680479d4bd14e59268e67977ed40904de

RUN Write-Host ('Downloading get-pip.py ({0}) ...' -f $env:PYTHON_GET_PIP_URL); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $env:PYTHON_GET_PIP_URL -OutFile 'get-pip.py'; \
	Write-Host ('Verifying sha256 ({0}) ...' -f $env:PYTHON_GET_PIP_SHA256); \
	if ((Get-FileHash 'get-pip.py' -Algorithm sha256).Hash -ne $env:PYTHON_GET_PIP_SHA256) { \
		Write-Host 'FAILED!'; \
		exit 1; \
	}; \
	\
	Write-Host ('Installing pip=={0} ...' -f $env:PYTHON_PIP_VERSION); \
	python get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		('pip=={0}' -f $env:PYTHON_PIP_VERSION) \
	; \
	Remove-Item get-pip.py -Force; \
	\
	Write-Host 'Verifying pip install ...'; \
	pip --version; \
	\
	Write-Host 'Complete.'

CMD ["python"]
```

</details>

It's pretty vanilla. :sweat_smile:

**Comment by tianon** [comment]
Aha, more information -- I've just tried a build locally on a Windows 10 system using Hyper-V isolation, and it builds just fine.  However, the builds on GitHub Actions, which are failing, are happening on Server 2016 using process isolation.  Perhaps that's somehow related/relevant?

**Comment by StefanScherer** [comment]
The `windows-2016` GitHub actions runners were updated recently to

```
Client: Mirantis Container Runtime
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        6ee42dc
 Built:             03/11/2021 13:24:56
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       1e08f21e79
  Built:            03/11/2021 13:23:32
  OS/Arch:          windows/amd64
  Experimental:     false
```

https://github.com/actions/virtual-environments/pull/3059/files

That was about three days ago, looks suspicious 😅

I've pasted the Dockerfile from above into a small GH actions workflow and the `windows-2016` runner could build the image https://github.com/StefanScherer/githubactionstest/runs/2252651116 🤔

**Comment by yosifkit** [comment]
Thanks @StefanScherer, I restarted the builds on https://github.com/docker-library/python/pull/586 and they are working now. So the changes in https://github.com/actions/virtual-environments/pull/3059 do fix it (merged 10 hours ago, and your test was 7 hours ago).

So going by the dates of when we started to see errors (fine 3 days before March 2) and the history of `virtual-environments/images/win/Windows2016-Readme.md`, then it was definitely erroring in both https://github.com/actions/virtual-environments/pull/2769 and https://github.com/actions/virtual-environments/pull/2909.

**Comment by tianon** [comment]
Interesting -- well, I'm satisfied, but if someone wants to dig deeper into what was going on here, there's the references.  :smile:

Thanks folks! :+1:
