### ISSUE TITLE
os.Stat() return error for socket file in 20H2 Windows image & does not work for symlink points to a dir (in all Windows version)

### ISSUE THREAD

**Issue by jingxu97** [microsoft/Windows-Containers#97]
While testing the new 20H2 windows image, we discovered that golang function os.Stat() always return error when checking a socket file. See the error message

```
os.Stat error CreateFile C:\var\lib\kubelet\plugins_registry\pd.csi.storage.gke.io-reg.sock: The file cannot be accessed by the system
```

**Comment by jingxu97** [comment]
Another discovery is os.Stat() does not work (no matter which version of Windows) on symlink that points to a dir.
The error is "Access is denied"

**Comment by neolit123** [comment]
looks like there are a number of issues related to the stdlib os.Stat:
https://github.com/golang/go/issues/39183
https://github.com/golang/go/issues/34900

if `Lstat` works you can continue using that but it would not follow links.

alternatively, you can write your own local wrapper that imports and uses e.g. `CreateFile()` (or use the imported one in https://github.com/golang/sys/blob/94ec62e081691fed0145b707594111cee9cb360a/windows/syscall_windows.go)

the `CreateFile()` link following semantics are here:
https://docs.microsoft.com/en-us/windows/win32/fileio/symbolic-link-effects-on-file-systems-functions#createfile-and-createfiletransacted

**Comment by marosset** [comment]
@immuzz @vrapolinario Any updates here?
It seems like this is a new regression and Windows Server 2019 and/or 1909 are not impacted.

**Comment by vrapolinario** [comment]
Starting internal investigation on this.

**Comment by jingxu97** [comment]
os.Stat() seems ok for symlink on ltsc 2019 I just tested. (will confirm 20H2 later).

But for Windows container, if it checks symlink point to a different disk partition, it will not work. I put details in this doc https://docs.google.com/document/d/1hMn2LwFjXDbIzn3ZK_xiw4eNYnAajTIIyRXyQKaKa20/

**Comment by vrapolinario** [comment]
Quick update that we're still investigating this issue internally.

**Comment by vrapolinario** [comment]
For internal MS folks: Bug filled: Bug 32905775

**Comment by vrapolinario** [comment]
Sorry for the delay on this. Here's the result from the internal investigation:

The os.Stat() implementation never should have worked.  Windows had a short-term regression during which the os.Stat() implementation worked OK with socket files on some versions (Server 2019), accidentally.  Current versions (20H2 and forward) of Windows function correctly.  We strongly recommend that os.Stat() should handle the error case STATUS_IO_REPARSE_TAG_NOT_HANDLED and respond by opening the file with the FILE_OPEN_REPARSE_POINT flag specified.

                Which is approximately what this Go patch implements: os: fallback to open symlinks (Ib919e5ce) · Gerrit Code Review (googlesource.com): https://go-review.googlesource.com/c/go/+/265037
                That patch retries with FILE_OPEN_REPARSE_POINT in case of any error aside from ERROR_CANT_ACCESS_FILE – which is overly inclusive, but should solve the problem.
