### ISSUE TITLE
Remove EOL versions from the Full Tag Listing section on Docker Hub

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/Windows-Containers#98]
The `Full Tag Listing` on Docker Hub currently includes EOL OS versions.  The standard practice is for the `Full Tag Listing` to only list supported tags.  The end of this section includes a link to all available tags for scenarios in which users need to find this information.

Example Windows Server Core Docker Hub - https://hub.docker.com/_/microsoft-windows-servercore

![image](https://user-images.githubusercontent.com/8290530/110550525-78648e00-80f9-11eb-84f5-85d705d56ca7.png)

**Comment by vrapolinario** [comment]
@2212Emmanuel can you please fix the table in the Docker Hub?
@mamezgeb and @weijuans-msft for visibility.

**Comment by 2212Emmanuel** [comment]
fixed
